label Day19_Keisuke:
    window hide
    scene May31 with fade
    play sound "music/windchimes.ogg"
    show blossoms movie
    $ renpy.pause(5.5)
    play music "music/crowd01.ogg" fadein 5.0
    scene SGate
    window show
    $ date = "day19"
    "Walking around the school courtyard, I'm surprised by just how many people are out and about instead of being indoors."
    "The sun has been, quite frankly, ridiculously hot for the past hour or so and just stepping into the sunlight has me feel like I could start smoking any second now."
    "Although I guess those with shorter fur don't have as much of an issue..."
    "Still, if I want to walk to one of the other buildings I just have to do it don't I..."
    "?" "\"Please come see our performance tomorrow night!\""
    "I hear a female voice shouting from nearby."
    "The voice sounds so familiar to me that I decide to check it out, turning left and walking in that direction instead."
    show i 1 c smile at fdis, five with dissolve
    "I see a familiar calico cat, cheerfully calling passer-bys and handing them flyers."
    i "\"Please come see our performance tomorrow night, our ba-{nw}"
    show i 1 c smile at jumping
    extend " Oh, [povLastName]-kun, hiya!\""
    mc 1 c talk "\"Minazuki, you're in charge of distributing flyers?\""
    "She smiles brightly, nodding with a quick hop of her feet to show her enthusiasm."
    "Her voice sounded a little hoarser than usual but I'll just chalk it up to being shouting in the sun for God knows how long."
    i "\"I wanted to help in any way I can. I don't really understand anything about instruments and I can't do much about organizing them so I decided to handle the flyers.\""
    mc 1 c considerate "\"No offense but shouldn't that be a job for your manager?\""
    "Not that I want to dump more work on Kei-kun's shoulders but..."
    "Minazuki shakes her head in negative."
    i "\"He already has way too much on his plate, what with helping his class' display and with organizing the show. I don't wanna give him more stuff to do. Besides, passing flyers is no trouble.\""
    mc 1 c "\"How much work has he been doing for you guys? I haven't talked to him at all since the start of the festival so I assume he's been kept busy.\""
    i "\"Oh, he comes by to help out whenever he's not working on his class' project. I don't think he's taken any personal time off during the festival.\""
    mc 1 c wince "\"Sheesh. Sounds like he's overworking himself.\""
    i "\"I wouldn't doubt that. He can be pretty irresponsibly responsible sometimes.\""
    mc 1 c considerate "\"Irresponsibly responsible? Is that even a thing?\""
    i "\"I choose to believe it is.\""
    "Minazuki giggles, hugging her stack of flyers close to her chest, her voice reminiscent of a sweet purr."
    i "\"Oh, by the way, have a flyer too!\""
    "She hands a cute little flyer with details on the time and place of the performance."
    "Gotta admit, this thing is pretty minimalistic. I half expected a bunch of drawings of guitars, skulls, flames and whatnot."
    "... I might not have the most correct mental image of musicians."
    i "\"Here, everything you need to know when to show. I hope you'll come watch.\""
    mc 1 c happy "\"Of course. I wouldn't miss it. Cute flyer by the way.\""
    i "\"Kei-chan designed it. I told you he's been working around the clock to help us.\""
    "God, he's sounding like Shoichi when he does nothing but work."
    "Although I suppose I should be glad that he's working on something he really likes but..."
    "I don't know... part of me is worried that he's not taking good care of himself."
    "To be honest... I've more or less avoided trying to talk to him since I heard from Saya that he's confessing to the person he likes during the festival."
    "I... don't want to talk to him and then hear about how he's dating now or something like that."
    "In fact, a part of me kinda wishes he'd be rejected."
    "... I'm a horrible friend. And possibly person too."
    i "\"Hello? Earth to [povLastName]-kun. Are you still there?\""
    mc 1 c shock "\"Oh, uhm, what? Sorry, did you say something?\""
    "Minazuki pouts, putting a hand on her waist and giving me an annoyed look."
    i "\"Jeez, did you ignore everything I just said?\""
    mc 1 c considerate "\"Erm... no?\""
    i "\"Then what did I say?\""
    mc 1 c fsmile "\"T-that you were looking forward to the performance because it would be you guys' first time?\""
    i "\"... Oh, I guess you were paying attention after all. Sorry for doubting you, hahaha.\""
    "I WAS RIGHT?!" with hpunch
    mc 1 c considerate "\"S-see? And you said I wasn't paying attention. Haha... ha... ha.\""
    i "\"Alright, I'm gonna get going now. I need to make sure this stack of flyers is gone before lunch.\""
    mc 1 c smile "\"Sure. Have a nice day, Minazuki.\""
    i "\"Thanks. Hopefully I will. Just need to get through all these flyers before I have a heat stroke.\""
    mc 1 c considerate "\"Yeah, that would be really bad wouldn't it?\""
    "Minazuki giggles, nodding cheerfully."
    i "\"But I've been going at a good pace so I think I should be done before lunch!\""
    mc 1 c smile "\"Good luck, Minazuki.\""
    i "\"I'll see you later, [povLastName]-kun. I have no doubt Kei-chan will find a way to smuggle you backstage before the show anyways.\""
    mc 1 c shockb "\"Wha-\""
    show i 1 c smile at fdis, offscreenleft with moveoledis
    "Before I have any time to properly react to her sudden words, Minazuki winks at me and walks away, turning her back from me."
    "Wha- what did she mean by that?"
    "There's no way he'd do that!"
    "Why would Kei-kun sneak {i}me{/i} backstage? I'm sure he would rather bring whatever girl he's going to be confessing to anyway."
    "Yeah, show her all the cool stuff he gets to work on, that will probably be one hell of a way to show his charms..."
    play sound "music/disappointment.ogg"
    "Ugh, I'm pathetic. Why the hell am I obsessing so much over this?"
    "This is ridiculous, whether Kei-kun does or doesn't start dating someone is none of my business."
    "Hahaha, can you imagine that {i}I'd{/i} be jealous over that?!"
    "There's no way, no. No, not possible, nuh-uh, never, can't happen!"
    "A-and if anything, I'm just upset because he's gonna do something that's clearly so important and he didn't choose to tell me."
    "Yeah, that's it! After we've gotten so close recently, he doesn't even think of telling me that he's got a girl he likes? Or that he's gonna confess to her?!"
    "You hold a fellow in your arms while he freaks out from fear and yet you're somehow not close enough to hear about the things that are important to him?! The gall!"
    "And it was Saya of all people that he told?! I mean, I know they're close and all but come on, Saya?! She can't keep a secret to save her life!"
    "Yeah, there's no way I'm jealous. Nuh-uh. This is nothing. I've got absolutely no reason to be thinking about this right now. None!"
    "{cps=5}...{/cps}"
    play sound "music/disappointment.ogg"
    "I NEED HELP!" with hpunch
    "Preferably of the psychiatric variety because I've clearly lost my mind."
    "... Man, I can think some really offensive things sometimes, huh? What's wrong with me."
    play sound "music/disappointment.ogg"
    "Erm... no, better not go there..."
    "... *sigh*"
    "But despite all that, if Kei-kun is overworking himself nearly as much as Minazuki seems to think he is, I should probably offer him a hand."
    "I hate how despite all this, all I care about is making sure that he's doing okay."
    "Ugh, I'm a total doormat sometimes..."
    "There's no way I could be falling for him... right?"
    scene SCorridor with fade
    "By the time I get to the second floor corridor, I see a small line forming outside Keisuke's classroom, with a single student standing in front of it, wearing a black trench coat with suspicious-looking red stains on it."
    "The otter's coat is a little torn at the hem, he has half of an old, torn, formerly white bandana on his head and carries a clear plastic clipboard in his hand."
    "From the looks of it, he's signing all the students in, a big smile on his face as he does so."
    "I walk up to him. Once it becomes clear that I'm basically cutting the line to talk to him, I get a few annoyed glares from the people in line."
    "I choose to ignore them."
    mc 1 c "\"Hey, is Keisuke here?\""
    "Otter" "\"Keisuke who? We have three Keisuke's working in class. Not to mention that possibility that some of the people going through the attraction right now might also be called that.\""
    mc 1 c sigh3 "\"Urushihara. You know, white hare, plays tennis, always has a sour look on his face?\""
    "The otter mouths an \"Oh\" and nods."
    "Otter" "\"Yeah, Urushihara left a few minutes ago to grab some supplies we needed. I'm manning the front entrance in his absence. He should be back in a few minutes.\""
    mc 1 c smile "\"Thanks. I'll wait around for him to show up.\""
    "Otter" "\"Why don't you sign up for the haunted class while you wait? I'm sure the spooks will be a great way to pass time.\""
    "He grins at me, probably thinking of how he could stand to make extra money if I did what he wants."
    mc 1 c sigh3 "\"I'll pass for now. Maybe later.\""
    "Otter" "\"Awww. Fine, have it your way. Just don't hold up the line for actual paying customers.\""
    "... Wow, rude."
    "I shake my head and step away, leaning against the opposite wall and deciding to wait around in front of the classroom until Kei-kun arrives."
    "I hope he doesn't take long. I feel my resolve to face him withering the more time passes..."
    "Ugh, stop being so whiny, [povFirstName]-kun. Man up already!"
    "I wait around for what feels like an eternity, although I don't really trust my feelings on this matter since I tend to lose track of time pretty easily."
    "The line in front of Kei-kun's class never really does much thinning out. Despite all the people going in and out, the size of the line seems to stay about the same."
    "They seem to be wildly successful with their little haunted house. It's kinda surprising because I always found these a bit lame."
    "Just how much horror can you create inside a regular classroom lined with black polyethylene?"
    "?" "\"[povFirstName]-san?\""
    play music2 "music/BGM/Summer Day.ogg" fadein 5.0
    show k 1 u at fdis, five with dissolve
    "A voice snaps me out of my thoughts and when I look up, I see Kei-kun stopped in front of his class, looking at me."
    "He's carrying a heavy looking box that partially covers his chin, and yet from his body language it looks like it doesn't bother him much."
    mc 1 c fsmile "\"O-oh, Kei-kun, h-hi.\""
    k 1 u worried "\"What's with the stuttering? Are you alright?\""
    "Jesus, I've barely said two words and I already managed to sound like an idiot?"
    mc 1 c considerate "\"Yeah yeah, sorry, I was a bit distracted and you caught me by surprise.\""
    k 1 u "\"You were distracted? And when is that not the case?\""
    mc 1 c pout "\"Hey, rude!\""
    k 1 u smile "\"Nah, just the truth. Is there something I can help you with?\""
    mc 1 c shock "\"H-help me?\""
    k 1 u "\"Well, you did show up to my class unannounced. Since you're not waiting in line I doubt you want to go inside. I assumed you were looking for me since you don't know anyone else in here.\""
    mc 1 c considerate "\"Oh. Right, right. Yeah, that's about right.\""
    k "\"Alright. Just give me a second, I have to deliver these and then we can talk.\""
    mc 1 c worried "\"Erm... I can wait until you can go on break. I don't want to distract you from work.\""
    k 1 u smile "\"It's alright. My break starts as soon as I deliver this. It was just a last minute errand I had to run before I could do so.\""
    mc 1 c happy "\"O-oh. Alright!\""
    "Jeez, why am I so happy over something so silly?"
    "I press my ass against the wall so I can pin my tail and keep it from wagging."
    scene SCorridor
    show k 1 u smile at fdis, five
    with fade
    show minutes with dissolve
    $ renpy.pause (1.0)
    hide minutes with dissolve
    "Kei-kun walks back out of his classroom, nodding to the otter standing by the wall before he walks up to me."
    k "\"Alright, I'm here. What do you need?\""
    mc 1 c worried "\"... Do I need to need something to come talk to you?\""
    k 1 u "\"Huh? No, I suppose not. Still, you usually don't just drop in without a word so I was wondering. Are you okay?\""
    "Ugh, that came out weirder than it should have."
    "Come on, I have to pull myself together."
    mc 1 c happy "\"N-no, not at all. I just wanted to come check up on you, that's all.\""
    k "\"Check up on me? What for?\""
    mc 1 c smile "\"I ran into Minazuki earlier today. She was handing out flyers for the band's performance. She told me you'd been overworking yourself lately and I got worried.\""
    k 1 u sigh "\"Really? {i}I'm{/i} overworking myself? She's the one that's barely been getting any sleep lately with all the work she's been doing.\""
    mc 1 c "\"Wait, what? She said she's barely done anything since she doesn't know how to... erm... fiddle with the instruments or whatever it was that she says. I don't really remember all that well.\""
    k 1 u avoid "\"True, she doesn't really mess with that stuff. But she's been going around campus during festival hours giving out flyers and inviting people over. And once the festival ends she goes to the station.\""
    k 1 u sigh "\"All this on top of practicing until her voice gets hoarse. She really needs to give herself a break...\""
    mc 1 c wince "\"O-oh... that's... not ideal.\""
    k 1 u avoid "\"You tell me. She's gonna drop if she keeps going at this pace.{nw}"
    show k 1 u sigh at fdis
    extend " And to think she has the gall to worry about {i}me{/i} after that...\""
    mc 1 c worried "\"You guys are really gung-ho about your work, huh?\""
    k 2 u sigh "\"The worst part is, I can't even blame her for it. She formed this band over a year ago and this is their first chance to actually perform. I'm sure Kagaho and her are probably really stressed about it.\""
    "... Somehow I can't imagine the raven being stressed over anything."
    "Which probably just means he's really good at hiding it."
    mc 1 c wince "\"Is there anything I can do to help?\""
    k 1 u "\"Unless you're willing to grab her by the waist and drag her home kicking and screaming, I doubt it.\""
    mc 1 c sigh2 "\"... I'd get arrested if I did that. Justifiably so.\""
    k 1 u smile "\"I know. You're such a great friend to offer something so noble.\""
    mc 1 c shock "\"What? But I didn't- You said- But I don't-\""
    k 2 u gentle "\"Settle down, I'm only messing with you.\""
    k 1 u smile "\"You don't need to take everything so seriously. Loosen up and have fun will you?\""
    "{size=+4}I don't need to hear that from you!{/size}" with hpunch
    k 1 u "\"Man, you don't look so hot. Is something on your mind?\""
    mc 1 c wince "\"Huh? Why do you ask?\""
    k 1 u worried "\"You're pretty listless and sluggish. It's like you're barely even registering what I say. Usually you're a lot more... energetic.\""
    mc 1 c sigh3 "\"It takes a lot of energy to be energetic all the time.\""
    k 1 u smile "\"Yes, I know. But you're usually always so annoyingly positive. It's one of the few good things about you.\""
    mc 1 c sigh "\"Hey!\""
    k 2 u gentle "\"I'm kidding, I'm kidding. We both know you have a lot of positives.\""
    mc 1 c sigh3 "\"I have \"a lot of positives\"? I'm a person, don't weigh my \"positives\" around like I'm some kind of business decision.\""
    k 1 u smile "\"I'm doing no such thing.\""
    mc 1 c sigh "\"Really? Cause you sound like you like keeping me around cause I'm the boring salad that's good for you.\""
    k 1 u uncomfortable "\"W-what's with that weird analogy?\""
    "It's a perfectly good analogy, excuse you."
    k 1 u worried "\"[povFirstName]-san, are you sure you're okay? Should I be worried about you or something?\""
    mc 1 c considerate "\"No no, you're fine. I'm just... in a weird, funky mood today. I guess I'm a tad oversensitive.\""
    k "\"That's not good...{nw}"
    show k 1 u smile at fdis
    extend " Well, I have thirty minutes on my break. It might not be much but we can go around and have fun for a bit. See if I can't distract you from whatever funk it is you're in.\""
    mc 1 c wince "\"I thought you'd be too busy working to go out with me.\""
    k 1 u "\"Usually, yes. I've been using all my breaks as time to do more work on organizing the show but you take priority over that.\""
    play sound "music/heartbeat.ogg"
    mc 1 c avoidb "\"I-I see...\""
    "Shit... why does it make me happy to hear that?"
    k 1 u smile "\"Oh my God, are you blushing?!\""
    mc 1 c shockb "\"W-what? N-no way!\""
    k 2 u gentle "\"Oh wow, you're totally blushing!\""
    "Kei-kun laughs heartily, a big stupid smile on his face as his voice echoes loudly down the hall."
    "The people around us even turn to stare which only magnifies my embarrassment."
    mc 1 c pout "\"Kei-kun, you're being too loud!\""
    k 1 u smile "\"Who cares? This is a festival, we're just having fun. Let people stare.\""
    "... Did I really just hear those words? From the prim and proper Kei-kun of all people?"
    mc 1 c wince "\"You're not usually one to say that sort of thing.\""
    "He shrugs, his smile widening until I can see a hint of teeth."
    k 2 u gentle "\"Hmm... Maybe I've just been a bit infected by you. I find myself caring less and less about other people's opinions. Is that bad?\""
    mc 1 c considerate "\"It's certainly unexpected. I've never taken you for that type of person.\""
    "Hell, {i}I'm{/i} not that type of person so I don't see how you could have learned it from me."
    "I am very much self-conscious of how the people around me see me you know..."
    k 1 u smile "\"Come on, is there anything you want to do? Let me help put a smile back on your face. I will not have it be said that I just ignored you when you were down.\""
    mc 1 c considerate "\"Hmmm... if you're sure it won't get in the way of your work.\""
    k 1 u smile "\"I'm absolutely sure. You'll just have to hurry up with your decision cause my break isn't very long.\""
    mc 1 c think "\"Hmmm... let's think.\""
    play sound "music/disappointment.ogg"
    "I'm not very good at making on the spot decisions, you should know that by now..."
    "Hmm... what is something that we can do together really quickly?"
    "!"
    mc 1 c laugh "\"Oh, I know!\""
    k "\"Yeah? What is it?\""
    mc 1 c smile "\"Let's go for the haunted house.\""
    show k 1 u uncomfortable at fdis, jumping
    "Kei-kun's entire body twitches as soon as the words exit my mouth."
    k "\"The... the haunted house? W-why the haunted house of all things?\""
    mc 1 c smile "\"Well, we're standing right in front of it so we already know it's accessible. Plus, you've been working hard on it with your class so I want to see the fruits of your labor.\""
    k 1 u avoid "\"B-but... s-see how big the line is? It would take us too long to get i-\""
    show k 1 u shock at fdis, jumping
    "Otter" "\"Oh, don't let that be a problem.\""
    "A voice echoes from behind Kei-kun, making the hare jump forward and away from it."
    "Kei-kun's classmate, the otter, had been standing in front of the class and behind us this whole time so it stands to reason he could probably hear us talk."
    "He flashes Kei-kun a haughty grin and I immediately see the color drain from the hare's face."
    "Otter" "\"Urushihara-kun, don't forget the class members get priority on the waiting list~\""
    show k 1 u avoidb at fdis
    "The words coming out of his mouth are teasing in tone and make Keisuke's whole face go red."
    k "\"N-no, t-there's really no need, Hazakura...\""
    "The otter laughs again, grabbing his pen and writing something down on his clipboard."
    "Otter" "\"Alright, we'll have Urushihara and... I'm sorry, what was your name again?\""
    "He looks up at me with a smile."
    mc 1 c shock "\"Uhm... [povName].\""
    "Otter" "\"Okay. [povLastName] and Urushihara will be joining the next group! It should be you guys' turn in three minutes or so.\""
    k "\"W-wait...\""
    "Otter" "\"This will be your chance to see what our project ended up like, Urushihara! After all, you didn't put anything together.\""
    mc 1 c shock "\"Wait, you didn't?\""
    k "\"Hazakura!\""
    "Kei-kun whimpers in protest but that only makes the otter's grin go wider."
    "Otter" "\"Nope. He helped with getting materials, organizing the working hours, all that boring administrative stuff but he wasn't hands on with the assembly so he has absolutely no idea what the place is like inside.\""
    k 1 u sigh "\"... Hazakura, I'm so going to kill you for this.\""
    "Otter" "\"Enjooooy~\""
    "The otter doesn't seem at all affected by Keisuke's threat of extreme violence."
    "He's my kind of people!"
    mc 1 c "\"What's wrong with going inside? Why don't you want to check it out?\""
    k 1 u avoid "\"I... I mean... It's... It's not a big d-\""
    "Otter" "\"Hey, Urushihara, if you don't want to tell him then should I?\""
    k 1 u doom "\"Shut up already you overgrown mustelid!\""
    "The otter, Hazakura, raises his hands to the air and waves them unenthusiastically."
    "Otter" "\"Oh wow, I'm so scared. The spry rabbit is going to kick my ass.\""
    k 1 u sigh "\"... No one takes me seriously here.\""
    "Otter" "\"Hard to take you seriously when you're too chicken-shit to go inside the haunted house you yourself put together.\""
    show k 1 u avoidb at fdis, jumping
    k 1 u avoidb "\"Hazakura!\""
    mc 1 c shock "\"Wait wait wait, back up a bit. You don't want to go because you're too {i}scared{/i}?\""
    k "\"I mean, I...\""
    "Otter" "\"Yeah, he-{nw}\""
    k 1 u annoyed "\"Be quiet! I'll tell him myself.\""
    "Hazakura laughs at Kei-kun's apparent discomfort."
    k 1 u avoidb "\"I... don't really... do well with horror stuff.\""
    mc 1 c talk "\"Really? I never knew that.\""
    k 1 u sigh "\"I... Am very easily frightened, I guess.\""
    "Otter" "\"And you're also afraid of the supernatural so you can't even stand being in the same room as the mannequ-\""
    k 1 u avoidb "\"{size=+4}For the love of God, Hazakura, shut up!{/size}\"" with hpunch
    mc 1 c talk "\"You're afraid... of the supernatural?\""
    k 1 u wince "\"M-maybe...\""
    mc 1 c confused "\"So... ghosts and demons and stuff?\""
    k 1 u sigh "\"Kinda...\""
    show k 1 u worried at fdis
    "..."
    mc 1 c "\"...\""
    k "\"...\""
    mc 1 c laugh "\"Oh my God, that is so cute hahahaha!\""
    show k 1 u angryb at fdis, jumping
    k "\"Shut up shut up shut up shut up shut up shut up!\""
    "Otter" "\"You're welcome!\""
    k "\"I'm going to kill you, Hazakura!\""
    "Otter" "\"Yeah, sure. All I have to do is go inside the haunted house and you'll be too chicken to follow.\""
    k 1 u sigh "\"...\""
    mc 1 c smile "\"It's okay, Kei-kun. I'll keep you safe.\""
    k 1 u angryb "\"Don't you start mocking me either!\""
    mc 1 c laugh "\"Hahahaha.\""
    k 1 u sigh "\"Why do I even bother with you?\""
    mc 1 c smile "\"Aww come on, you know it comes from a place of love.\""
    k "\"{size=-6}If this is your way of showing love then I'm screwed...{/size}\""
    mc 1 c "\"What did you say?\""
    k 1 u avoid "\"Nothing.\""
    mc 1 c talk "\"Come on, what was it?\""
    k 1 u sigh "\"I already said it was nothing, stop prying.\""
    "What? First you mutter and now you won't even clarify yourself?"
    "Jesus, you're such a pain in the ass sometimes."
    mc 1 c smile "\"So?\""
    k 1 u "\"So what?\""
    mc 1 c happy "\"Can we go in the haunted house?\""
    k 1 u sigh "\"... You're actually serious about that?\""
    mc 1 c smile "\"Yes, I would very much like to go.\""
    k 1 u worried "\"Do we really have to?\""
    mc 1 c laugh "\"Pretty please? I really want to!\""
    k 1 u sigh "\"What are you, a child?\""
    mc 1 c smile "\"Nah, I just know what I want.\""
    k 1 u avoid "\"Alright, alright. Fine.\""
    mc 1 c happy "\"Great!\""
    "Otter" "\"I mean, there was no doubt you were going to go. Your name was already on the list.\""
    k "\"Stop butting into our conversation, Hazakura. That's rude.\""
    "Otter" "\"Then stop having your conversation loudly in public. You're the one dragging people into it.\""
    show k 1 u shock at fdis
    "To that, a few of the people in line mutter in agreement, leaving Kei-kun horrified."
    k 1 u avoidb "\"God, I'm sorry.\""
    mc 1 c smile "\"Oh? What happened to what you said earlier about not caring so much what people think anymore?\""
    k 2 u sigh "\"E-erm... D-did I say that?\""
    mc 1 c smile "\"Yes you did. Quite clearly too.\""
    "Otter" "\"It's true, you really said that.\""
    k 1 u avoid "\"Alright, just shut up already...\""
    play sound "music/slidingdoor.ogg"
    "Just then, the door is opened and a group exits the room, all chattering excitedly among each other."
    "Otter" "\"Oh, looks like it's your turn already!\""
    k 1 u worried "\"Oh no... I do not look forward to this...\""
    mc 1 c smile "\"Come on, Kei-kun, it'll be fun.\""
    k 1 u sigh "\"Your definition of fun does not compute for me.\""
    stop music2 fadeout 2.5
    scene HauntedHouse
    show k 1 u worried at fdis, five
    with fade
    "Once we go inside, we see a separate room built inside the classroom itself using fabrics and plastics."
    "Keisuke and I are ushered inside along 3 other people to form a group."
    "The whole thing looked very basic from the outside but as soon as we were ushered in and the door was closed behind us, it suddenly looked a lot more elaborate."
    "There were decapitated mannequin heads inside, fake blood stains, chains dangling from the ceiling, fake daggers and other bladed weapons."
    mc 1 c talk "\"Oh wow, this is really well made.\""
    k 1 u wince "\"I... I wasn't expecting it to be like this...\""
    mc 1 c smile "\"Yeah? Were you expecting it to be really crappy and not at all scary?\""
    k 1 u worried "\"... Kinda.\""
    play sound "music/scaryscream.ogg"
    show k 1 u shock at fdis, jumping
    "A blood-curdling scream echoes causing half of our group, Keisuke included, to jump."
    k "\"W-w-w-what was that?!\""
    mc 1 c smile "\"Oh wow, they have pretty decent sound effe-\""
    play music "music/creepybackground.ogg" fadein 5.0
    show k 1 u uncomfortable at fdis
    "Just then, a very ominous sound starts echoing loudly for all of us to hear."
    "Even I felt a slight chill run down my spine when I heard this thing."
    "It's not super loud, definitely no way we could hear it from outside, especially with the noise of the crowds walking through campus."
    "But damn, it's really eerie to listen to it now."
    k "\"I-I didn't know they had that either.\""
    mc 1 c "\"Looks like there was a lot you didn't know about them planning. You really should have paid more attention.\""
    k "\"S-shut up.\""
    "We keep walking forward since the whole haunted house is kind of a path we have to follow."
    "Somehow, I end up leading the way for the entire group."
    "Everyone else is either smiling dumbly at the whole thing or quivering in fear."
    "Kei-kun being the one with the most pronounced shaking, clutches the hem of my shirt as he follows right behind."
    "I have to admit, it's kinda cute."
    mc 1 c talk "\"Did you seriously know nothing about what they were setting up here? I find that a little hard to believe.\""
    k "\"I-I-I d-distanced myself from it for a reason. I-I hate this kind of o-occult stuff...\""
    mc 1 c considerate "\"{size=-4}That's kinda silly.{/size}\""
    play sound "music/scarysiren.ogg"
    "I hear the sound of slight footsteps followed by a sharp noise that I can't quite identify."
    "I have no idea what this is, I just know it sounds like a horror movie's sound effect."
    "And I have to admit, it is way cool."
    k "\"T-this was a terrible idea...\""
    mc 1 c smile "\"I don't know what you're talking about, I'm having a blast.\""
    "Mostly watching you freak out but still a blast either way."
    show k 1 u uncomfortable at fdis, jumping
    play sound "music/spookychains.ogg"
    "Every time something echoes, I hear Kei-kun whimpering and jumping behind me."
    "I have to admit, it's pretty funny."
    "Entertainment for the whole family!"
    k "\"C-c-can we leave?\""
    mc 1 c happy "\"We both know they close the entrance from the outside. You'd have to rip the walls to get out and they'd probably get really mad at you for that.\""
    "The scaredy hare whimpers again, obviously dissatisfied with my answer."
    "God, I really feel like bullying him right now."
    "... I will refrain from letting my sadistic side show."
    show k 1 u scared at fdis, jumping
    play sound "music/scaryscream.ogg"
    "The screaming echoes once more, this time even louder than before."
    "It seems like Keisuke is just about to go catatonic because he's shaking like a leaf and the color is slowly draining from his face."
    mc 1 c talk "\"Whoa, you don't look so hot. Are you okay there?\""
    "He doesn't answer me, merely continuing to clutch the hem of my shirt and shake."
    "This is starting to remind me of a certain tiger that I know and the mental image amuses me quite a bit."
    "Keisuke better be prepared because I'm gonna tease him so much over this."
    play sound "music/creakingdoor.ogg"
    "A creak echoes inside the room."
    "At this point I figure we're probably almost at the end of attraction."
    "We saw mannequins of witches, demon heads, ghosts hanging from the ceiling."
    "I have to admit, for a place with no animatronics to use and having to rely completely on a student budget, this is pretty darn well done."
    "Even I feel a bit tense in here and that's not something easily achieved."
    "Kei-kun on the other hand has gone totally unresponsive."
    "I almost feel a tinge of pity for him, thinking of how terrified he must be since he's apparently not good with horror."
    "I mean, I already knew he was a bit frightful after the whole thing with the thunderstorm at my house, but..."
    "This is just hilarious. And I don't have to feel bad about finding it funny either because it's not a phobia!"
    "... I might be a tad mean-spirited."
    play sound "music/spookychains.ogg"
    "The sound of chains being dragged starts creeping closer to us and I feel a chill running down my spine."
    "Male Member" "\"W-wait, is it getting closer to us? Are those footsteps?\""
    mc 1 c "\"Sounds like it.\""
    "Female Member" "\"There, I can see some light. I think that's the exit.\""
    mc 1 c smile "\"Oh, you're right. See that, Kei-kun? We're already at the end.\""
    "The hare nods meekly, barely even acknowledging my words."
    "I almost feel bad... almost."
    play sound "music/scarysiren.ogg"
    "???" "\"{size=+8}AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA!{/size}\"" with vpunch
    "Suddenly, a figure dressed in all black jumps out from behind us and screams, beginning to run in our direction."
    mc 1 c dismay "\"Waaah!\""
    "Everyone immediately bolts and runs out the door, running from the sudden assailant."
    "Even though in the back of my mind I knew it was fake, my flight instincts kicked in and made me run as fast as I could."
    stop music fadeout 2.5
    scene SCorridor
    show k 1 u fear at fdis, five
    with fade
    "Everyone immediately runs out of the classroom by the back door, huffing and panting as we try to piece ourselves back together."
    mc 1 c sigh3 "\"Oh wow... I wasn't expecting that...\""
    play sound "music/heartbeat2.ogg"
    "I can feel my heart beating super fast inside my chest and I take deep breaths to try and calm myself down."
    mc 1 c considerate "\"That was pretty good though. You and your classmates did a really good job, Kei-kun.\""
    "When I look to my side, I see Kei-kun sitting on the floor with his face buried on his knees and leaning his back against the wall."
    mc 1 c worried "\"H-hey, are you alright?\""
    k "\"I-I'm fine. J-j-just give me a minute.\""
    "I crouch down next to the hare, rubbing his back encouragingly and trying to help him calm down."
    mc 1 c considerate "\"It's okay, Kei-kun, you don't have to worry so much about it. It's just a fake haunted house.\""
    k "\"I-I know that. I-I just need time to recompose myself.\""
    "That's fair. I did ask him to do something I knew he hated. It'd be unreasonable of me to tell him to snap out of it."
    "... Even if seeing him freak out like that was probably some of the funniest ten minutes of my life."
    "I'm seeing all these new sides of Kei-kun lately and it's pretty fun."
    "Seeing someone who used to be so guarded and distant in all these new ways is definitely an experience."
    k 1 u worried "\"... Man, that sucked.\""
    mc 1 c worried "\"Really? I thought you'd have fun. I didn't think you'd hate it, let alone this much.\""
    k "\"It's... it's fine. I just really hate this kind of thing. I'm not good at all with horror...\""
    "That's an understatement."
    "... Probably not something I should say out loud though."
    mc 1 c talk "\"We still have around ten minutes left in your break. Do you wanna go do something real quick to get your mind off it?\""
    k 1 u sigh "\"No, it's alright. Besides, we wouldn't really have time to do anything. It's best if I hang around nearby anyway so I don't take too long to come back.\""
    mc 1 c considerate "\"No one is going to mind if you're a few minutes late.\""
    k 1 u avoid "\"No, I absolutely refuse to do that.\""
    "Jeez, even when you're all freaked out like this you're still fussy about being timely?"
    play sound "music/disappointment.ogg"
    "Get your priorities straight..."
    play sound "music/fabric.ogg"
    show k 1 u sigh at fdis
    "Kei-kun gets back up and readjusts his clothes, sighing."
    k "\"There, I've managed to calm down...\""
    mc 1 c wince "\"You sure? You can take more time if you need.\""
    k 1 u avoid "\"No thank you. The whole experience was already embarrassing enough. I don't need to be sulking on the ground for ten minutes after. {size=-4}There are a lot of people around us after all.{/size}\""
    mc 1 c smile "\"I thought you said you didn't care about that anymore.\""
    k 1 u sigh "\"And I thought I told you to shut up the last time you brought it up.\""
    mc 1 c happy "\"Roger that, sir.\""
    k 1 u avoid "\"Don't make me punch you.\""
    mc 1 c smile "\"Pfft, as if you'd do something like th-{nw}"
    play sound "music/punch.ogg"
    show k 1 u sigh at fdis
    show mc 1 c dismay at fdis, offscreenleft
    extend " {size=+4}Ow!{/size}\"" with hpunch
    "Kei-kun's fist lands squarely on my shoulder, pushing me back a few steps and making me yelp."
    mc 1 c wince "\"Y-you really punched me!\""
    k "\"Oh please, it was barely a tap. It's not like I really wanted to hurt you. Besides, I did warn you.\""
    mc 1 c wince "\"Alright, fair enough. I guess I was asking for it.\""
    "Saya is becoming a really bad influence on you if you're resorting to violence now..."
    k 1 u avoid "\"... Thanks.\""
    mc 1 c curious "\"Huh? For what?\""
    "That was out of nowhere."
    k 1 u sigh "\"... I guess... even if I hated it, it was still a fun experience... mostly because I went through it with you...{nw}"
    show k 1 u avoid at fdis
    extend " So yeah... thanks.\""
    "..."
    mc 1 c happy "\"Aww, you really don't know how to be honest do you?\""
    k 1 u sigh "\"Shut up or I'm gonna slug you again.\""
    mc 1 c dismay "\"R-roger that!\""
    k 1 u "\"...\""
    mc 1 c "\"Is something wrong? Why are you looking at me like that?\""
    k 1 u worried "\"... By the way, [povFirstName]-san...\""
    mc 1 c talk "\"Yeah? What's with the sudden coyness?\""
    k 1 u wince "\"Well... this might be a weird thing to ask but... you're coming to the show tomorrow, right?\""
    mc 1 c "\"Of course I am. Why wouldn't I?\""
    k 1 u considerate "\"I... just wanted to make sure.{nw}"
    show k 1 u smile at fdis
    extend " I'll call you tomorrow so we can meet up. Is that okay?\""
    mc 1 c curious "\"Sure, but is it really necessary?\""
    k 1 u considerate "\"I have to admit that...  I'm a bit nervous. I've been helping the guys prepare for this for a while and I have to admit... even though I'm not gonna be the one up there on the stage it still feels like that.\""
    mc 1 c smile "\"Aww, so you want some moral support? Want me to be your private cheerleader?\""
    k 1 u sigh "\"Ugh, please don't put it that way.\""
    mc 1 c happy "\"Fine fine. Besides, you didn't need to ask. I was planning go anyway.\""
    k 1 u wince "\"I had to make sure. I don't want to just assume. That's just setting myself up for disappointment.\""
    mc 1 c smile "\"Fine. I'll be there for sure. Does that make you feel better?\""
    k 2 u gentleb "\"Yes... quite a bit.\""
    play sound "music/heartbeat.ogg"
    "..."
    "I feel my cheeks growing hot and look away, trying to find a way to change the subject."
    mc 1 c avoidb "\"Well... I'm sure everything will be alright. You guys have been working really hard to prepare after all.\""
    k 1 u smile "\"You're right. I have no doubt they're all going to do great.\""
    mc 1 c smile "\"You're pretty passionate over your job aren't you, Mr. Manager?\""
    k 1 u considerate "\"I am. It's nice being able to work on something I really like.\""
    mc 1 c smile "\"You know, you've been a lot happier lately since you joined the band. You smile a lot more often.\""
    k 1 u wince "\"Really?\""
    mc 1 c happy "\"Yeah, it's really nice to see you so cheerful. Maybe music really is your passion after all!\""
    k 1 u worried "\"... I see.\""
    "What's with the unenthused reaction? I thought you'd be happy about this."
    mc 1 c talk "\"Are... Is everything okay?\""
    k 1 u "\"Yeah, I'm fine. I just hadn't noticed that before. I guess I don't pay all that much attention to myself.\""
    k 1 u smile "\"Anyway, thank you for spending time with me but if you'll excuse me, I have to start getting ready to return to my shift.\""
    mc 1 c wince "\"But we still have a few minutes.\""
    k 1 u considerate "\"True, but it doesn't hurt to be dilligent.{nw}"
    show k 1 u smile at fdis
    extend " I'll talk to you later, [povFirstName]-san.\""
    show k 1 u smile at fdis, offscreenleft with moveoledis
    "Kei-kun quickly scurries away from me and goes back inside his classroom without a further word."
    "It... almost feels like he was running away."
    "... Did I do something wrong?"
    $ date = None
    jump Day20_Keisuke
