label Day16_Keisuke:
    window hide
    scene May24 with fade
    play sound "music/windchimes.ogg"
    show blossoms movie
    $ renpy.pause(5.5)
    play music "music/rain.ogg"
    scene LivingRoomN with fade
    window show
    $ date = "day16"
    "I sit around in front of the window, idly twiddling my thumbs around as I look at the sky."
    "From the moment we woke up today, there was a pretty bad storm going on outside."
    "The clouds are so dense that there's barely any light shining through."
    "It still feels like we're in the middle of the night..."
    "Aki and I should have left for school a good fifteen minutes ago but we didn't have the courage to brave the weather, even with an umbrella."
    a 1 u sigh "\"Hey, Aniki, the weather forecast says it's supposed to be like this all day.\""
    show a 1 u sigh at fdis, fiveh with dissolve
    "Aki emerges from behind me, looking down at his phone with a frown."
    mc 1 u "\"Well, the clouds don't look like they're about to let up any time soon so I suppose you must be right.\""
    a 1 u "\"It's not me that's right, it's the weather app.\""
    "He wiggles his phone in front of my face for effect."
    mc 1 u smile "\"Whatever. You can call that weird thingamajig on your hand anything you want.\""
    a 1 u sigh2 "\"You're not technology illiterate. Stop acting like an idiot.\""
    mc 1 u happy "\"Oh come on, brighten up. If the sky is cloudy then the sunshine must come from within us!\""
    a 1 u sigh "\"That is quite possibly the dumbest thing I have ever heard in my life.\""
    play sound "music/stab.ogg"
    "T-that's a little harsh!" with hpunch
    "Also, what's with that way of talking? You're twelve, you haven't even lived long enough to say that!"
    mc 1 u wince "\"Alright, fine, I'll stop joking around.\""
    show a 1 u happy at fdis
    a "\"Oh, you were joking? Sorry, I couldn't tell.\""
    mc 1 u sigh "\"Yeah, keep talking like that, smart guy. Just remember I'm the one who cooks your food.\""
    show a 1 u sigh at fdis
    a "\"Fine, fine, you win...\""
    mc 1 u happy "\"Aww, don't be so upset. This sort of outcome was already to be expected. You can't best your awesome big bro after all.\""
    a 1 u worried "\"Keep that up and I'll kick you on the shin.\""
    mc 1 u sigh3 "\"... Got it.\""
    "I swear, no sense of humor at all..."
    a 1 u "\"What are we supposed to do about school? Should we call a cab?\""
    mc 1 u "\"Can you imagine how expensive a cab would be under these conditions. Those guys will probably be charging ridiculous premiums to go out in this rain.\""
    a 1 u avoid "\"That's true... so are we just going to have to miss class today?\""
    mc 1 u smile "\"Unless you want to go outside in this rain then yeah. If you do decide to do it, let me know beforehand so I can have popcorn at the ready.\""
    a 1 u smile "\"Don't worry, I'd toss you outside to see if it's safe first.\""
    mc 1 u sigh "\"Hey!\""
    "Aki chuckles, walking up to and throwing himself on the living room couch, opening his bag and grabbing a textbook from inside."
    mc 1 u confused "\"What are you doing?\""
    a 1 u "\"Studying. If I can't go to school then I should at least study the material I already have at home.\""
    mc 1 u sigh3 "\"Seriously? Don't you know how to enjoy your free time? You should just take this chance to relax.\""
    a "\"No thanks. I don't need to end up like my useless older brother.\""
    mc 1 u sigh "\"{size=+2}Hey!{/size}\""
    a 1 u smile "\"I still love you though.\""
    mc 1 u avoidb "\"I... that's... erm...\""
    "Goddamnit, you're lucky you're really cute..."
    mc 1 u "\"... Do you need any help with your studies?\""
    a 1 u "\"From you? Hardly.\""
    mc 1 u sigh "\"Hey, I'll have you know that I'm still at the top of my class. I can handle a Junior High curriculum.\""
    a 1 u sigh "\"I still don't need any help. I'm doing fine by myself.\""
    mc 1 u sigh3 "\"You could stand to be a little more friendly you know.\""
    a 1 u "\"I'm plenty friendly enough.\""
    "Seriously, decide what kind of personality you want to have already."
    "Just yesterday you were cuddling up to me on the couch to watch a movie. Now you're ignoring me?"
    "Go back to being cute already!"
    a 1 u worried2 "\"By the way, do you think Mom will have to go to work with this rain?\""
    mc 1 u "\"Wait, she's not at work yet?\""
    "Aki shakes his head sideways."
    a 1 u "\"She said she was given the morning off, remember? She even asked us not to wake her up when we left for class since she only has to be in the office in the afternoon.\""
    mc 1 u think "\"Oh, right. I forgot about that.\""
    mc 1 u smile "\"Well, if the rain keeps up like this then I don't think she'll go either. She doesn't have a car to begin with.\""
    a 1 u sigh "\"I guess you're right.\""
    mc 1 u happy "\"I'm always right!\""
    a 1 u "\"Let's not exaggerate.\""
    play sound "music/knock.ogg"
    show a 1 u avoid at fdis, jumping
    a "\"Huh?\""
    "The sound of a knock on the front door makes both of us jump."
    "Just the fact that someone is knocking in the middle of this heavy rain is already shocking enough."
    "But with how loud the rain is... just how hard did they have to knock?"
    "And who would be knocking on someone's door in the middle of a storm?"
    mc 1 u confused "\"I'll go check the door.\""
    scene HouseEntrance with fade
    play sound "music/angryknock.ogg"
    "The knocking gets more intense as I get close to the door."
    mc 1 u sigh2 "\"I'm coming!\""
    play sound "music/slidingdoor.ogg"
    show k 1 u worried at fdis, five with dissolve
    "Once I open the door, a white hare immediately jumps inside the house brandishing a wet umbrella."
    mc 1 u dismay "\"Wah!\"" with hpunch
    "The sudden movement catches me by surprise and I cry out."
    k "\"Calm down, [povFirstName]-san. It's just me.\""
    mc 1 u shock "\"Wha- Kei-kun?!\""
    k 1 u sigh "\"Jeez, do you have any idea how bad the weather is outside? Why did you take so long to let me in?\""
    mc 1 u sigh "\"What are you even doing here?! I mean, of course it would take me a while, how would I expect that someone would knock on my door under these conditions?\""
    k 1 u worried "\"Oh... I guess that's true.\""
    "While he seems to have remained mostly dry despite the storm outside, I see a few wet spots on the hem of his pants and on his shoulders."
    mc 1 u worried "\"Damn, you're really irresponsible for coming all the way over here in this rain... Here, come inside.\""
    k 1 u calm "\"It wasn't that bad. My driver brought me here.\""
    scene LivingRoomN
    show a 1 u at fdis, three
    show k 1 u smile at fdis, seven
    with fade
    "The two of us walk back to the living room."
    "Aki quickly walks up to the two of us and hands Keisuke a towel."
    a "\"Here. I figured whoever was outside would be pretty wet so I went to get a towel.\""
    mc 1 u smile "\"Oh, nice thinking there, Aki.\""
    k 2 u gentle "\"Thank you, Akiyoshi-kun.\""
    a 1 u smile "\"It was nothing. Make yourself comfortable, Keisuke-san.\""
    "Aki walks back to the couch and plops himself down, picking up his book once more and continuing to read it."
    k 1 u smile "\"Oh, so you're studying despite the rain?\""
    a 1 u "\"Yeah. Since I'm a student, the least I can do is study. Especially when I'm supposed to be in school.\""
    mc 1 u considerate "\"You see how he is, Kei-kun? Isn't it ridiculous?\""
    k "\"Not at all. That's very responsible of you, Akiyoshi-kun. Maybe your older brother could stand to learn a little something from you.\""
    mc 1 u shock "\"What?!\""
    a 1 u smile "\"See? I told you!\""
    mc 1 u pout "\"Kei-kun, don't you turn back against me too!\""
    k 1 u sigh "\"I'm not turning against anyone. You really could stand to study a little more.\""
    mc 1 u sigh3 "\"Give me a break. I'm already in the top five of my class. I don't need to study any more than that.\""
    k 1 u smile "\"If you can do that well despite studying so little then shouldn't you try to aim a little higher?\""
    mc 1 u sigh "\"What are you, my mother?\""
    k 1 u sigh "\"No. Just someone who worries about you and your legendary levels of laziness.\""
    a 1 u "\"Good luck getting through to him. He already ignores me, Mom, Shoichi-nii and Saya-nee.\""
    k 1 u sigh2 "\"Seriously? How many people do you already have on your case over this?\""
    mc 1 u sigh3 "\"I don't want to talk about it...\""
    k 1 u sigh "\"Good grief, you're impossible.\""
    "Keisuke shakes his head with a sigh as he towels himself."
    "Upon looking a little closer, I notice that he was actually a lot more drenched than I initially thought."
    "The undershirt he wore underneath his jacket was clinging tightly to his chest, making the muscle definition below very visible."
    "Despite his somewhat frail looking constitution, Kei-kun's body was very well built from all his years as a tennis player."
    "He might not have as much muscle as Shoichi or me but he still had a very good looking body."
    k 1 u "\"Hmm? Is something the matter, [povFirstName]?\""
    "Kei-kun seems to catch me staring, something even I hadn't realized I was doing."
    "Once my attention was called to it, I immediately looked away, my face feeling oddly flushed all of a sudden."
    mc 1 u flustered "\"It's... it's nothing.\""
    k "\"If you say so.{nw}"
    show k 1 u smile at fdis
    extend " Thank you for the towel, Akiyoshi-kun. It was very helpful.\""
    "Aki lifts his arm, flashing the hare a thumbs up and making Keisuke chuckle."
    mc 1 u "\"By the way, I asked this right after you came in but you didn't really respond to me. What {i}are{/i} you doing here, Kei-kun? Shouldn't you be at school?\""
    k "\"That's... actually why I'm here. I know most of you guys walk to school. Saya-san and Urata both tend to go quite early just like I do so they had already arrived before the rain started, but...\""
    k 1 u worried "\"I started thinking about you and how you usually leave for class around this time. I realized you and Akiyoshi-kun might be stuck here so I decided to call for my driver and come by.\""
    mc 1 u confused "\"So... wait, you came over to pick us up for school?\""
    k 2 u gentle "\"Exactly! Aren't I a genius?\""
    "... Once again, what are you, my mother?"
    show k 1 u at fdis
    a 1 u sigh "\"Erm... Mr. Genius, I think we're going to have a problem.\""
    "Aki chimes in from the couch. The two of us look over at his direction and see him looking down at his phone with a frown."
    a 1 u "\"The weather report just got updated. The storm has been classified as a weather hazard. Classes are being canceled and people are being advised to take shelter in whatever building they are.\""
    k 1 u shock "\"W-what?! No way!\""
    a 1 u worried2 "\"It's true. Sorry you came all the way here for nothing but even if you'd stayed on school grounds you wouldn't have had class. It says it's a storm with strong winds and chances of thunder and lightning.\""
    k 1 u worried "\"W-wait. D-did you just say... thunder and lightning?\""
    a 1 u "\"Yeah. See here?\""
    "Aki walks up to us and shows us the screen of his phone where we can plainly see the weather forecast."
    show k 1 u nervous at fdis
    mc 1 u talk "\"Waah, it's true. Damn, it did look like the storm was getting worse but I didn't think it was getting that bad. Good thing you got here before things got too ugly out there right, Kei-kun?\""
    "I see some fidgeting from the corner of my eye and my attention is immediately drawn away from the screen."
    mc 1 u curious "\"Kei-kun?\""
    "When I turn to look at him, Kei-kun is hugging his arms really close to his body, biting his lip."
    mc 1 u shock "\"Hey, are you alright?\""
    k "\"Y-yeah. I'm... I'm fine...\""
    a 1 u worried2 "\"Are you sure? You don't look fine.\""
    mc 1 u confused "\"Wait... could it be that... you're afraid of thunder?\""
    k "\"W-what? N-no, there's no w-\""
    play sound "music/thunder.ogg"
    show a 1 u at fdis
    show k 1 u shock at fdis, jumping
    k "\"Eeeep!\""
    "Kei-kun jumps, his whole body trembling at the sound of thunder."
    show k 1 u nervous at fdis
    a "\"Oh wow, that was a big one too.\""
    "Aki stares at the ceiling, bewildered."
    mc 1 u worried "\"Damn. The weather is taking a turn for the worst pretty bad.\""
    a "\"Should we wake up Mom?\""
    mc 1 u "\"Nah. I'd say that if she can sleep through this then she should be allowed to sleep.\""
    "Right now I'm more worried about someone else..."
    mc 1 u worried "\"Kei-kun, are you seriously afraid of thunder?\""
    k "\"S-so what? I-it's not a big d-\""
    play sound "music/thunder.ogg"
    show k 1 u shock at fdis, jumping
    "Almost as if on cue, thunder strikes once more to shut him up mid sentence."
    show k 1 u wince at fdis, fidget
    k "\"...\""
    "Kei-kun continues to fidget where he stands, now visibly trembling to the sound of the thunder outside."
    mc 1 u "\"Aki, can I borrow your headphones?\""
    show a 1 u at fdis, offscreenleft
    show k 1 u wince at fdis, five
    with move
    "He nods, quickly going up the stairs to his room."
    mc 1 u smile "\"Come on, let's sit down for a bit. It's best if we try  to make you comfortable.\""
    show k 1 u worried at fdis
    "Kei-kun nods meekly."
    "Once I grab him by his wrist, I can feel him entire body trembling against my hand."
    show a 1 u at fdis, offscreenright
    "I try my best to pretend like the whole thing isn't a big deal as that might give me a better chance of calming him down."
    "The two of us walk around the couch where I push Aki's stuff out of the way so we can both take a seat."
    mc 1 u "\"Here, isn't it better like this?\""
    k "\"I-I guess it i-{nw}"
    play sound "music/thunder.ogg"
    show k 1 u fear at fdis, jumping
    extend " Wah!\""
    "Kei-kun jumps again, his hands clutching the sides of his arms so tightly that I'm afraid his jacket might rip."
    play sound "music/tap.ogg"
    "I put a hand on his shoulder in an attempt to be comforting."
    mc 1 u worried "\"Hey, come on, everything will be ok-\""
    play sound "music/fabric.ogg"
    show k 1 u fear at fdis:
        ease .2 zoom 1.5 xoffset -30 yoffset 200
    mc 1 u shockb "\"Wha- Kei-kun?\""
    "As soon as I touched him, he practically jumped on me, burying his face on my chest and clinging to me in a panic."
    play sound "music/heartbeat.ogg"
    "!"
    "When I look down, I see Keisuke's face really close to mine, his breathing rapid and little teardrops forming on the corners of his eyes."
    "For some reason, I immediately feel the need to avert my gaze as my face begins to grow hot."
    "I put my left hand on top of his head, stroking it slowly in an attempt to be reassuring."
    mc 1 u avoidb "\"Everything's alright. See? There's no need to panic.\""
    "He makes no sound, merely wrapping his arms around me and holding me even tighter."
    mc 1 u worried "\"Kei-kun...\""
    "It's like he's not even listening to me right now."
    a 1 u sigh "\"Is this why you asked me to go get my headphones?\""
    show k 1 u fear at fdis, three:
        ease .2 zoom 1.0 xoffset 0 yoffset 0
    show a 1 u at fdis, seven
    with move
    "Aki then comes back downstairs, putting both his arms on top of the sofa back and leaning his chest forward, looking at us."
    mc 1 u avoidb "\"Shut up...\""
    "He shrugs, handing me a pair of surprisingly bulky earbuds."
    mc 1 u confused "\"Wait, why are these so huge? They're, like, twice the size of regular earbuds.\""
    a "\"I bought these about two years ago when you started bringing girlfriends home all the time. They're noise canceling. Haven't had to use them in a while though.\""
    mc 1 u flustered "\"W-what?!\""
    "Oh... oh God. The implications of that are..."
    mc 1 u avoidb "\"S-sorry...\""
    "He shrugs once more."
    a "\"It's cool. I just needed some peace and quiet, that's all.\""
    "Alternatively, you could have just mentioned it and I'd have..."
    "Err... actually, never mind. I wish I had never learned of this in the first place."
    "I plug the headphones onto my phone and start playing some music. Then I slip them into Keisuke's ears."
    show k 1 u avoidb at fdis
    "Immediately, the shivering begins to subside a bit."
    "I imagine that since he can't hear the sound of the rain, he's beginning to calm down a bit."
    k "\"[povFirstName]-san?\""
    mc 1 u considerate "\"Hey there. You feeling any better?\""
    "He nods meekly, his face rubbing against my chest as he does so."
    k "\"I can barely hear you...\""
    a 1 u smile "\"That means the headphones are working.\""
    "Kei-kun turns to look at Aki."
    "I half expect him to jump away from me when he notices Aki here but Keisuke stays put where he is."
    k "\"Thanks...\""
    mc 1 u worried "\"Are you alright? You seem really out of it.\""
    k 1 u worried "\"I... don't like thunderstorms...\""
    "He nuzzles my chest once again, continuing to cling onto me tightly despite knowing Aki is here."
    mc 1 u considerate "\"You're lucky you came here before the thunder started then. People would really tease you at school if they saw this.\""
    "I make an attempt at humor to try and alleviate the situation..."
    a 1 u "\"I think you'd be the one most likely to tease him in the first place.\""
    "... and it gets promptly shut down."
    a "\"If you don't mind me asking, how do you even deal with this at other times, Keisuke-san?\""
    play sound "music/thunder.ogg"
    "The sound of thunder echoes once more but Kei-kun doesn't seem to have any reaction to it this time."
    k "\"I tend to lock myself into my room and just listen to music until it passes...\""
    "Aki mouths a silent \'oh\', looking down at the hare's meek figure with worry."
    a 1 u worried2 "\"What about when you're in public? You can't shut yourself out in public, can you?\""
    k "\"I... use bathrooms...\""
    "Just then, the image of a scared Keisuke attempting to silently sob while locked inside a bathroom stall comes to mind."
    "And it breaks my heart..."
    "I wrap both my arms around him, hugging the still shivering hare closer to my body."
    "He reacts with a meek yelp before hugging me tighter too."
    show a 1 u at fdis
    k "\"Thanks...\""
    "Aki stares at the two of us like that for a few seconds before stepping back from the couch."
    a "\"Well, I'm gonna gather my things and go up to my room to study if you don't mind.\""
    mc 1 u "\"Sure. If you're already done by then, how about we all have lunch together?\""
    a "\"Alright.\""
    show a 1 u at fdis, offscreenright
    show k 1 u at fdis, five
    with move
    "Aki quickly picks up his books and bag and carries them back upstairs, disappearing from my sight without another word."
    "I focus my attention once more on the white hare I have in my arms."
    mc 1 u wry "\"You alright there?\""
    "He nods, not bothering to look up or say a word."
    "At least he's not shaking nearly as much as he was before."
    "Still... afraid of thunder, huh?"
    "Even though I can see it right now, I still have trouble conciliating that idea with the image I have of Kei-kun in my head."
    mc 1 u talk "\"By the way, I don't want to be a bother, but... didn't you say your driver brought you here to pick us up?\""
    "He nods once again."
    mc 1 u considerate "\"... Wouldn't that mean he's still waiting for us outside?\""
    k 1 u shock "\"Ah...\""
    show k 1 u worried at fdis
    "He pulls the headphones out of his ear and fishes his phone out of his pocket."
    "I can see a few idle twitches here and there as he starts hearing the sound of the rain again but he remains more or less composed."
    "Maybe holding onto me is calming him down a bit? I certainly would like it if that were the case."
    play sound "music/phonebeep.ogg"
    k "\"Hello, Isogai? I just found out that classes are being canceled for the day due to the storm but it's been declared dangerous to go outside. You should probably come in too.\""
    k 1 u sigh "\"What? No, I'm not going back to the estate in the middle of this storm.\""
    k 1 u worried "\"B-because it's unsafe...\""
    k 1 u sigh "\"No, it wouldn't be a bother if you came ins-\""
    k 1 u worried "\"Fine, fine. Just seek shelter, okay? Don't wait around for me outside. I'll call you to pick me up once the storm's gone.\""
    show k 1 u sigh at fdis
    play sound "music/phonebeep.ogg"
    "He turns off the call and drops his phone on the coffee table next to us, sighing."
    "Keisuke hesitates for a few seconds before putting the earbuds back in his ears."
    mc 1 u talk "\"Is everything okay?\""
    k "\"Yes, he's just a stubborn old fool. He insisted it would be inappropriate for him to come inside your house and said he would drive back to the estate.\""
    k 1 u worried "\"I hope he doesn't get in an accident...\""
    mc 1 u smile "\"If he's that confident that he can drive through the rain then I'm sure nothing is gonna happen, really.\""
    k 1 u sigh "\"Let's hope for that...\""
    show k 1 u avoid at fdis
    play sound "music/fabric.ogg"
    "He finally pulls away from me, sitting on the opposite end of the couch and adjusting himself."
    mc 1 u talk "\"Oh. Are you feeling better now?\""
    k "\"Y-yeah. Having something else to focus on helps... Sorry to have... erm... you know... {size=-4}Also, can you speak a little louder? It's a bit hard to hear now that I'm farther away.{/size}\""
    "I clear my throat, nodding."
    mc 1 u worried "\"If you don't mind me asking, what was that about? I've never seen you act like that.\""
    k 1 u sigh "\"I... I don't like thunder.\""
    "I stop myself before I can utter a sarcastic \'No way!\'."
    mc 1 u curious "\"But... how come I never heard about this before?\""
    k "\"It's... not something I can freely advertise.{nw}"
    show k 1 u avoid at fdis
    extend " Imagine how much I'd be made fun of about this. Besides, my family already gets on my case enough as it is about \"showing weakness\". I don't need one more thing to add to the list.\""
    mc 1 u worried "\"I... guess that's fair.{nw}"
    show mc 1 u considerate at offscreenleft, fdis
    extend " I just hope I was able to help any.\""
    k 1 u avoidb "\"You were... I just... sorry to have clung to you like that... {size=-4}God, that was mortifying...{/size}\""
    mc 1 u smile "\"It's fine. You don't have to worry about it, it's not a big deal anyway. I was just surprised to see you like that. You're usually always so composed.\""
    k 1 u sigh "\"Well, it doesn't always affect me like that either. I usually keep an eye on the weather forecast and have time to prepare for it so it doesn't get to me nearly as much.\""
    k 1 u avoidb "\"It's just... the rain today already came out of nowhere. No weather report mentioned it, and then came the thunder...\""
    mc 1 u worried "\"I can imagine.\""
    "For what it's worth, he already looks so much better."
    "He doesn't dare take the earbuds off but he's now sitting and talking to me much more normally than before."
    mc 1 u laugh "\"I didn't expect you to be the kind to want to cuddle for comfort though. Hahaha.\""
    k 1 u avoidb "\"... I told you, I just wasn't prepared for it.\""
    "I have an urge to point out how cute he is right now but I'm pretty sure he'd murder me if I did."
    mc 1 u smile "\"Yeah. It's no big deal, right?\""
    k 1 u worried "\"R-right...\""
    "Even if it was unexpected, I have to admit that I kinda liked seeing this more vulnerable side of him."
    "Kei-kun can be really cute sometimes."
    mc 1 u talk "\"How long have you had this problem?\""
    k 1 u avoid "\"... Ever since I was a little boy. Not many people know about it though.\""
    mc 1 u considerate "\"Sorry we ended up finding out.\""
    k 1 u worried "\"It's... fine... if it's you then I don't mind it much, I guess.\""
    mc 1 u happy "\"Aww, I feel flattered.\""
    k 1 u sigh "\"Yeah yeah, whatever. {size=-2}I wish Akiyoshi-kun hadn't seen me like that though.{/size}\""
    mc 1 u smile "\"Don't worry, Aki's not the type to tease you about it or tell others.\""
    k "\"I know that but it's still embarrassing to know he knows.\""
    mc 1 u happy "\"You worry too much.\""
    k "\"And you worry too little...\""
    show k 1 u avoid at fdis
    mc 1 u talk "\"And what are you going to do now? Hang out here until the rain passes?\""
    k "\"Probably... sorry for the intrusion by the way.\""
    "You're saying that now? After you already barged into my house without saying anything?"
    "You have a really weird sense of timing, Kei-kun."
    mc 1 u smile "\"It's no bother. I like having the chance to spend more time with you anyway.\""
    k 1 u wry "\"Thank you. I'm... happy to hear.\""
    mc 1 u talk "\"Is there something you want to do? I have a few games we could play.\""
    k 1 u sigh "\"I really don't recommend using devices plugged to the wall in the middle of a thunderstorm.\""
    mc 1 u think "\"Oh yeah, that's a fair point...\""
    "In fact, now that I think about it, I should probably start unplugging stuff from the wall until the storm passes."
    "If anything expensive were to get fried we'd be screwed."
    mc 1 u considerate "\"It might be a bit of a bother when you're like this but can you help with unplugging stuff from the wall? It won't take as long if it's the two of us.\""
    k 1 u smile "\"Sure. So long as I can keep these earbuds on I'm fine. You don't need to worry.{nw}"
    show k 1 u worried at fdis
    extend " Although you might have to speak a little louder if we're far apart cause I'm barely hearing you as is.\""
    play music2 "music/BGM/In That Mood - Narr.ogg" fadein 5.0
    scene LivingRoomN
    show k 1 u at fdis, five
    with fade
    "Almost an hour later, the two of us sit in silence, staring at the ceiling with nothing to really distract ourselves from our boredom."
    "Not only that, the continuous sound of rain outside is starting to make me drowsy."
    "I'm already sleepy enough at this time of day without adding rain to the equation..."
    "At least I eventually got my phone back from Kei-kun and had him plug his own to listen to music."
    mc 1 u sigh3 "\"Man, I'm bored...\""
    k "\"Why don't you use your phone?\""
    mc 1 u sigh "\"What am I supposed to do with my phone? We shut off the wifi modem, remember?\""
    k "\"Then just use your data plan.\""
    mc 1 u sigh3 "\"I don't have a data plan. If I did, don't you think I'd already be using it?\""
    k 1 u worried "\"Oh. That's fair. Do you want me to make a hotspot for you with my phone?\""
    mc 1 u considerate "\"Nah, it's okay. You don't have to waste your data on me...\""
    k 1 u smile "\"I have unlimited data. That's not going to be an issue.\""
    mc 1 u shock "\"Wow, seriously? Aren't those plans really expensive for a highschool student?\""
    k 1 u "\"...\""
    "The hare merely stares at me without a word, suddenly making me feel really stupid for what I just said."
    mc 1 u wince "\"O-oh... right... I forgot.\""
    k 2 u gentle "\"Pfft... it's alright, [povFirstName]-san.{nw}"
    play sound "music/phonebeep.ogg"
    show k 1 u smile at fdis
    extend " So, do you want me to make a connection for you?\""
    mc 1 u considerate "\"Pass. While the idea is tempting, if you're sitting right next to me I'd rather us do something together.\""
    k 1 u "\"Then why don't we?\""
    mc 1 u sigh "\"What exactly are we gonna do with everything shut off? Cuddle in front of a fire and watch a romantic movie?\""
    k 1 u avoidb "\"W-why would you mention something like that in the first place?\""
    mc 1 u suggestive "\"You {i}were{/i} clinging to me really tightly a while ago, maybe you'd li-{nw}"
    show mc 1 u wince at fdis, offscreenleft
    play sound "music/punch.ogg"
    extend " Ow!\""
    "I get promptly punched in the shoulder before I have the chance to complete my sentence."
    mc 1 u wince "\"Jeez, Saya-chan is being a really bad influence on you if you're doing this kind of thing now.\""
    k "\"This is what you get for saying really embarrassing things like that.\""
    mc 1 u sigh3 "\"It was just a joke, you didn't have to take it so seriously.\""
    k "\"...\""
    "Oh-oh, now he's going silent on me."
    mc 1 u considerate "\"Hey, come on, I didn't mean to mock you or anything like that. I really didn't mind it much. It was kinda pleasant even.\""
    k "\"P-pleasant?\""
    mc 1 u smile "\"Yeah. You're pretty soft so it felt nice.\""
    show k 1 u avoidb at jumping
    k "\"S-soft?\""
    mc 1 u "\"What's wrong? Why are you acting so weird?\""
    k "\"I-I'm not acting weird...\""
    "Yes you are, your voice has gotten so high and squeaky that you almost sound like a dog whistle."
    "Weirdo."
    k 1 u worried "\"D-do you think the rain is gonna pass any time soon?\""
    mc 1 u "\"Doesn't seem like it. It's still coming down pretty hard.\""
    k "\"Yeah. It really sucks."
    show k 1 u wince at fdis
    extend " I should probably follow Akiyoshi-kun's example and study right now...\""
    mc 1 u sigh "\"Ew. There are better ways to use your time off.\""
    k 1 u "\"It's not time off though. Not really. We were supposed to be in school today. It's just the weather that got in the way.\""
    mc 1 u sigh3 "\"Come on, man. You can't be that uptight about things. Live a little for god's sake.\""
    k 1 u annoyed "\"I really don't need to be hearing that from you. You barely ever study in the first place.\""
    mc 1 u smile "\"And yet I still place really high on my exams.\""
    k 1 u avoid "\"{size=-6}That's one thing that annoys me to no end.{/size}\""
    mc 1 u "\"What was that?\""
    k 1 u sigh "\"Nothing. I agreed with you.\""
    show k 1 u at fdis
    "I blink a few times, staring dumbly at the hare's face."
    "Every now and again I catch him doing this exact same thing, mumbling incoherently to himself when people say things to him."
    "I can never quite get what he's saying but I always get the feeling it's not exactly very... kind things."
    mc 1 u considerate "\"So you're actually gonna waste your time off and try to study?\""
    k "\"Do you have to frame it as if it was a bad thing? I feel judged.\""
    mc 1 u smile "\"I do. And I {i}am{/i} totally judging you.\""
    k 1 u sigh "\"Whatever. Can I use the desk in your room to study for a bit?\""
    mc 1 u smile "\"Sure. I can help you.\""
    k 1 u shock "\"Wha- Help me?! I thought you didn't want any part in it.\""
    mc 1 u "\"I mean, don't take me wrong, I still find the idea super boring.{nw}"
    show mc 1 u smile at fdis
    extend " But at the same time, I have nothing better to do and I feel it might be at least a little fun if I help you study.\""
    "I mean... I've been tutoring Jun lately and it's pretty funny to see him getting worked up over stuff."
    "Especially math. Man, he's really terrible at math."
    "I wonder if I'll be able to see another cute side of Kei-kun by doing this."
    k 1 u worried "\"No, I don't need you to help me.\""
    mc 1 u laugh "\"Come on, I might be a lazy bum but I'm at least decent at this. Besides, I'm your senior, I've seen all the things you're studying already.\""
    k 1 u wince "\"That's not the issue here. I-\""
    mc 1 u laugh "\"Nope, I don't care. Come on, I'm gonna help you study!\""
    k 1 u shock "\"Wha- [povFirstName]-san?!\""
    "I grab the stubborn hare by his wrist dragging him up the stairs kicking and screaming towards my room."
    play sound "music/door.ogg"
    scene BedroomN
    show k 1 u annoyed at fdis, five
    with fade
    "Once we're inside, I turn on the lights, pulling up a seat for Kei-kun on my desk."
    mc 1 u smile "\"Come on, stop pouting. It's no big deal.\""
    k "\"I'm not pouting, I'm huffing. There's a difference.\""
    mc 1 u happy "\"To be honest, I don't really care either way.\""
    k 1 u avoid "\"You're such a pain sometimes.\""
    mc 1 u happy "\"Yup, but I'm also your friend so you should indulge me sometimes.\""
    k 1 u sigh "\"Indulge you, huh...\""
    mc 1 u smile "\"Come on, pull out your books already. Show me what you're having trouble with.\""
    show k 1 u avoid at fdis
    "Kei-kun clutches his bag a bit tighter, looking away from me."
    k "\"I... already told you there's no need. I'm fine studying by myself.\""
    mc 1 u sigh3 "\"Jeez, Kei-kun, will you stop being such a stubborn mule and show me your books already? We don't have all day.\""
    k 1 u worried "\"S-stubborn mule? {size=-4}Why do I get the feeling that I'm being insulted here?{/size}\""
    mc 1 u smile "\"Not important. Just whip out your books already.\""
    k 1 u sigh "\"Goddamnit, you're really insistent aren't you? Fine... just don't say I didn't warn you.\""
    mc 1 u confused "\"Huh?\""
    "The hare sighs deeply, as if the whole thing is a big annoyance to him."
    "He pulls out a couple of standard issue school notebooks, some pretty familiar textbooks and..."
    mc 1 u talk "\"Wait, what are these? I've never seen these books before.\""
    "I grab a few hardback books that look totally unfamiliar to me."
    "I rifle around a few pages, trying to see what they are about and-"
    mc 1 u shock "\"Wait, what the hell is this stuff? I've never seen it before.\""
    show k 1 u avoid at fdis
    "There's math I've never seen before and... is this another language?"
    k "\"I told you I didn't need help. I'm doing just fine with my general studies. I was gonna focus on more... advanced stuff.\""
    mc 1 u sigh "\"Seriously, what on Earth is this? College grade math?\""
    k 1 u "\"It's mecatronics, actually. While I don't like the idea of inheriting the company, it is still a possibility if I fail to make it as a tennis player. In that case, I refuse to do it halfheartedly.\""
    mc 1 u sigh "\"So... you're studying up on something you don't even like in case you're forced to do something you don't even want to do?\""
    k 1 u "\"Well, to be perfectly honest, I find the subject to be fascinating. I just don't want to have to study it in the circumstances that I'm studying it.\""
    k 1 u eyesc "\"But if I do happen to end up working for the company and then becoming the CEO after graduation, I want to be sure I'm prepared to be the best job possible.\""
    mc 1 u talk "\"Wow. I'm surprised you can go through so much work trying to prepare for that when it's something you're actively trying to avoid doing.\""
    k 1 u avoid "\"Just because I don't want to do it doesn't mean I get a pass to do a crappy job at it. If I have to do it then I should do my best to do it well.\""
    mc 1 u considerate "\"Heh... that's really like you. You know, I always envied that about you.\""
    k 1 u "\"{i}That{/i}? What do you mean?\""
    mc 1 u smile "\"Your work ethic. No matter what it is, you always try your best at everything you do.\""
    mc 1 u considerate "\"I... just can't bring myself to be that serious about everything. Just looking at you go sometimes is really exhausting. Still, I really admire that about you.\""
    k 1 u worried "\"[povFirstName]-san...\""
    "Kei-kun shifts a few times on his seat, looking away from me."
    "Oh no, have I accidentally made the mood a bit awkward here?"
    mc 1 u happy "\"Erm... hey, why don't you explain a bit of this mecatatronics thing to me?\""
    k 1 u "\"It's {i}mecatronics{/i}. And since when do you have an interest in this kind of stuff?\""
    mc 1 u smile "\"I don't. Not really. But you must be pretty knowledgeable about it, right? I want to hear you sounding smart. It's pretty fun to see.\""
    k 1 u worried "\"Are... are you making fun of me?\""
    mc 1 u happy "\"Nope. I'm being one hundred percent honest.\""
    k 1 u sigh "\"In that case then you're really weird.\""
    mc 1 u smile "\"That sounds about right. Anyway, explain it to me, please.\""
    k 1 u smile "\"Alright. Just don't complain if it bores you out of your mind.\""
    mc 1 u happy "\"No way that's gonna happen. You have my full, undivided attention!\""
    k 2 u gentle "\"We'll see about that.\""
    stop music2 fadeout 2.5
    scene BedroomN with fade
    "I wake up to the sound of rain outside."
    "My eyes feel very heavy at first and even though I can feel the fog of grogginess lifting from my mind, I still choose to keep them closed for a few minutes."
    "Then, as my body begins to regain further consciousness, I blink a few times."
    "Turning my head on whatever hard surface I seem to have fallen asleep on, I see a figure sitting next to me."
    "I see a mound of white fur wearing a school jacket, thoroughly immersed on a really difficult looking book... at least judging from the fact that I can't read a single word that is on the cover."
    show k 1 u at fdis, five with dissolve
    "Then, as I move my head a little further, he seems to finally notice me moving."
    k "\"Ah, [povFirstName]-san, you're awake.\""
    "Still holding up his book, he looks at me from the corner of his eyes without really turning his head away from his book."
    mc 1 u wince "\"Awake? Did I... when did I fall asleep?\""
    show k 1 u smile at fdis
    "The hare smiles warmly, looking down at me with a hint of amusement on his face."
    k "\"After about fifteen minutes of me explaining mechatronics to you. I have to say, while I expected you to get bored I didn't think you'd totally conk out.\""
    mc 1 u wince "\"S-sorry...\""
    k 1 u calm "\"Don't be, I didn't mind. You looked really peaceful sleeping and listening to your breathing helped me to relax too.\""
    "I notice that he's no longer wearing the earbuds as before."
    "That's odd, I can still hear the rain going outside just as much as it was before."
    mc 1 u worried "\"What about your headphones?\""
    k 1 u smile "\"It's alright. There hasn't been any thunder in a while. I took them out so I could hear you breathe. Like I said, it was really relaxing.\""
    mc 1 u sigh3 "\"No offense but... that's kind of a creepy thing to say.\""
    k 1 u worried "\"I-it is? S-sorry...\""
    "Haha, you care about the weirdest things, Kei-kun."
    k "\"Y-you're laughing? Did I say something amusing?\""
    mc 1 u happy "\"No, it's just that... only Kei-kun can be so much like Kei-kun.\""
    k "\"What's that supposed to mean?\""
    mc 1 u smile "\"That I like the way you are. You're pretty easy to get along with once people get to know you.\""
    k "\"I don't know if that's supposed to be a good thing.\""
    mc 1 u happy "\"Of course it is. You don't have to try and analyze every little thing that I say for implications.\""
    "Although I know you'll do it nonetheless because that's just the kind of thing you'd do."
    k "\"I see...\""
    show k 1 u at fdis
    mc 1 u smile "\"What are you up to now? That's a different book from before isn't it?\""
    k "\"Yeah, I finished with that subject a while ago. I'm studying a bit about foreign economies. The book is in Spanish so you might have a hard time reading it.\""
    mc 1 u talk "\"You can speak Spanish? I don't remember that being in the list of languages you told us about a while ago. That's pretty awesome.\""
    k 1 u smile "\"Hardly. I've been trying to pick it up but I'm still pretty slow at it. Like I said, the only ones I have any confidence in are English and French. With everything else I just know basics\""
    k "\"I've been studying this particular book for a little over two weeks and I haven't even gotten halfway through it yet.\""
    mc 1 u "\"Isn't that really boring and difficult?\""
    k 2 u gentle "\"Difficult maybe. Definitely not boring though.{nw}"
    show k 1 u smile at fdis
    extend " Is it weird that I enjoy reading up on this stuff? Languages, I mean. I find it really fun to learn how to communicate with new people.\""
    mc 1 u smile "\"This coming from the guy who barely speaks to anyone outside of our group.\""
    k 1 u "\"The same can be said about you, you know.\""
    mc 1 u happy "\"I know, but at the same time I don't talk about how incredible it is to \"learn to communicate\".\""
    k 1 u sigh "\"... It's just like you to make fun of me for the things I like.\""
    mc 1 u smile "\"Hey, I might tease you every now and again but it comes from a place of love.\""
    k 1 u "\"Oh really? So you love me now?\""
    mc 1 u happy "\"Of course I do. Isn't that obvious?\""
    show k 1 u shock at fdis
    $ renpy.pause(1.0)
    show k 1 u avoidb at fdis
    k "\"I... erm... didn't expect you to answer like that.\""
    mc 1 u smile "\"There's nothing wrong with admitting you love your friends.\""
    k 1 u sigh "\"{size=-6}Right, it's that kind of love...{/size}\""
    mc 1 u "\"Did you say something?\""
    k 1 u "\"Just muttering to myself about this book. You should probably go back to sleep. You seem tired.\""
    mc 1 u smile "\"Nah, I didn't plan on sleeping in the first place. Plus, it's impolite to do it with guests over.\""
    k 1 u sigh "\"I just showed up out of nowhere and stuck around, you don't have to fuss over me too much.\""
    mc 1 u smile "\"I don't {i}have{/i} to but I choose to.\""
    k 1 u calm "\"Heh... thanks.\""
    mc 1 u "\"By the way, how long was I out for?\""
    k 1 u "\"About an hour and a half.\""
    mc 1 u shock "\"Seriously? That long?!\""
    k 1 u smile "\"Yup, it really surprised me. I was wondering a few minutes ago just how long you'd be able to sleep.\""
    mc 1 u wince "\"Ugh... that's kinda embarrassing.\""
    k 2 u gentle "\"Oh yeah, you should definitely be embarrassed.\""
    mc 1 u sigh3 "\"You're teasing me now?\""
    k 1 u smile "\"Yup. It's one of my favorite hobbies lately.\""
    mc 1 u smile "\"Tch. You're a little shit, you know that?\""
    k 2 u gentle "\"Hehehe.\""
    show k 1 u smile at fdis
    "Kei-kun closes the book he's been reading, putting it down on the table and getting up from his seat."
    "The hare stretches a few times, grunting."
    "I see his shirt lifting up slightly and get a good glimpse of the well-toned muscle underneath."
    mc 1 u talk "\"Oh, not gonna read anymore?\""
    k 1 u smile "\"Nah. I've gotten enough studying done for now. I'd rather us do something together that doesn't cause you to pass out.\""
    mc 1 u considerate "\"I want to say that that's unnecessary but... you're probably right.\""
    k "\"Perhaps Akiyoshi-kun is already done with his homework? The three of us could do something together, couldn't we?\""
    mc 1 u think "\"Hmm... knowing Aki, I doubt he'd be. We can still check anyway.\""
    "It's not even 10AM yet so he's probably going to be holed up in his room for a while more."
    "How someone that's my flesh and blood could be so damn different from me I still can't understand."
    k "\"Well, whatever. Let's just go downstairs before you fall asleep again.\""
    mc 1 u happy "\"Hehe, probably for the best.\""
    scene LivingRoomN
    show a 1 c at fdis, three
    show k 1 u smile at fdis, seven
    with fade
    "We walk down the stairs, stopping to knock on Aki's door and getting no response."
    "When we go back to the living room, the two of us see him sitting on the couch with his phone on hand."
    mc 1 u "\"Oh, Aki. We thought you'd still be studying.\""
    "Without lifting his eyes from the tiny screen, my little brother responds in a monotone."
    a 1 c "\"I was until a few minutes ago but people started messaging me on my phone and I gave up.\""
    mc 1 u smile "\"Oh really? Who are you talking to right now? One of your classmates?\""
    a 1 c smile "\"Hitoka-chan.\""
    mc 1 u "\"Hitoka? What's she doing talking to you?\""
    a 1 c "\"We talk every day you know. You're not the only one who's friends with those two.\""
    "Hmm... fair enough."
    k 1 u worried "\"I know I've only met her once but that girl scares me.\""
    "That's when Aki looks up from his phone, looking at the hare with a frown."
    "He looks almost... offended."
    a 1 c sigh "\"Hitoka-chan isn't scary.\""
    k "\"N-no, I don't mean that she's literally scary, just... she kinda reminds me of a younger Mizoguchi-san. She's also kinda mean spirited.\""
    a 1 c annoyed "\"Hitoka-chan isn't mean spirited. She's wonderful!\""
    "Oh boy, Aki is getting more and more intense and even making Kei-kun shrink where he stands."
    mc 1 u considerate "\"Okay okay, Aki, calm down. We get it, you have a major crush on Hitoka.\""
    a 1 c avoidb "\"W-what? I-I don't-\""
    k 1 u wince "\"[povFirstName]-san, that's kinda going too far with teasing.\""
    mc 1 u laugh "\"What? I'm just joking, I didn't mean anything by it.\""
    k 1 u sigh "\"{size=-4}Teasing people over who they like is a bit...{/size}\""
    show k 1 u at fdis
    mc 1 u smile "\"Tell Hitoka-chan I said hi, okay?\""
    show a 1 c annoyed at fdis
    "Aki shoots me an unfriendly glare before typing something away on his phone."
    a "\"Done. Anything else you want?\""
    mc 1 u laugh "\"Nah, I'm fine!{nw}"
    show a 1 c at fdis
    show mc 1 u smile at fdis, offscreenleft
    extend " Hey, since we're gonna be home today anyway, how about I make lunch for us? We can leave our lunchboxes for school tomorrow.\""
    a "\"Sure. Knock yourself out.\""
    mc 1 u smile "\"Wanna help me out?\""
    a "\"Nope.\""
    "Aki ignores me, continuing to type away on his phone."
    mc 1 u sigh "\"Come on, Aki. You have to learn to cook at some point. You're gonna be a teen soon.\""
    a "\"I don't see you getting on Shoichi-nii's case about not knowing how to cook.\""
    mc 1 u sigh3 "\"Well, Shoichi is an exception. I wouldn't want to be the one trying to teach him cook since I'd likely end up dead.\""
    a 1 c sigh2 "\"I want to say that's a cruel thing to say but it's probably true. Still, I'm not interested.\""
    mc 1 u sigh "\"Kei-kun, help me out here. Tell him he should learn how to cook.\""
    k 1 u worried "\"Oh, erm... yeah... you should probably do that...\""
    mc 1 u sigh3 "\"What's with the unenthusiastic response?\""
    k 1 u wince "\"You can't just ask me to do something out of the blue and expect me to do it a certain way.\""
    mc 1 u sigh3 "\"Lame.\""
    a 1 c "\"Yeah, I think I'm gonna stick to my phone thank you very much. Have fun making lunch.\""
    "Sometimes I regret doting on him so much. Little shit barely has any respect for me at this point..."
    mc 1 u smile "\"Well, Kei-kun, I think it's gonna be just you and me.\""
    k 1 u wince "\"Doing what?\""
    mc 1 u laugh "\"Making lunch of course.\""
    k "\"W-what? I have to help out?\""
    mc 1 u smile "\"It'd be faster that way.\""
    k 1 u worried "\"It's still not even 10AM. Why do you need lunch this early?\""
    mc 1 u happy "\"Don't overthink it!\""
    k "\"Wha- but...\""
    a "\"Keisuke-san, you should just go along with him, otherwise he's gonna bug you until you do what he wants.\""
    mc 1 u sigh "\"This coming from the one who never does what I ask him to do.\""
    a "\"I do too. Just not this time.\""
    mc 1 u sigh3 "\"Mhm, sure.\""
    k 1 u wince "\"I don't know about this.\""
    mc 1 u happy "\"Come on, cooking is fun. It'll be a nice way to spend time!\""
    k 1 u sigh "\"{size=-4}I have my doubts about that...{/size}\""
    "You don't have to seem so unenthusiastic about it you know."
    "How come people never seem to go along with what I want?"
    "So annoying..."
    mc 1 u happy "\"Pretty please?\""
    "I take a step closer to the hare, trying to give him my best puppy dog eyes."
    k 1 u avoidb "\"Alright alright, you don't have to look at me like that...\""
    "!"
    "Wow, that worked better than I expected!"
    mc 1 u happy "\"Great!\""
    show k 1 u shock at fdis, five
    show a 1 c at fdis, offscreenleft
    with move
    play sound "music/tap.ogg"
    "I grab Kei-kun by the wrist and drag him with me to the kitchen."
    k "\"Wha- not this again!\""
    show KitchenN
    show k 1 u shock at fdis, five
    with fade
    mc 1 u laugh "\"Come on, Kei-kun, you have to learn to let loose sometimes.\""
    k 1 u wince "\"I would hardly refer to cooking as \"letting loose\".\""
    mc 1 u happy "\"Close enough.\""
    "I open our fridge, peering at the things we have inside."
    "Since I'm the one in charge of keeping our groceries stocked, I already have a pretty good idea of what we have available."
    "Still, I prefer to confirm I have everything I need before I get started."
    "It can lead to pretty annoying moments later when you realize you're missing one key ingredient you need to make your meal."
    $ keilove = 0
    menu:
        "Let's see, with what I have I can make..."
        "Beef stew":
            $ kei16food = "stew"
            "Hmm... I'll try some traditional western beef stew."
            "We have pretty good quality meat on the fridge and it's a good way to make use of the vegetables that have already been here for a while."
            "Can't let anything go to waste."
            mc 1 u smile "\"Alright, I've decided on what I'm gonna make.\""
            k 1 u "\"What's that?\""
            mc 1 u smile "\"Beef stew. It feels like it'd be a nice meal for a day like today.\""
            k 1 u smile "\"I'm not going to disagree with you there.\""
            mc 1 u think "\"Now, let me think of something you can do to help...\""
            "I should probably avoid giving him anything that involves handling sharp objects."
            "He might be doing fine now but I don't need a hare jumping around the kitchen with a knife if there's thunder again..."
            "..."
            play sound "music/disappointment.ogg"
            "Come to think of it, there's not much he can do that wouldn't be dangerous in that kind of scenario..."
            mc 1 u considerate "\"{size=-4}Guess I'll just try my luck...{/size}\""
            mc 1 u smile "\"Hey, Kei-kun, can I ask you to dice the onion and garlic and then suér them?\""
            k 1 u worried "\"O-okay...\""
            "I take the ingredients I need out of the fridge and hand them to Kei-kun along with the knife."
            "The recipe I use for stew is pretty simple so it doesn't take long to have everything prepared."
            play sound "music/chopping.ogg"
            "I use very big, cubed cuts of meat so it doesn't take me two minutes to do that."
            "And I prefer not to add too many vegetables to my stew so that gets done really fast too."
            "Then..."
            mc 1 u shock "\"W-what are you doing?!\""
            "I realize that I can smell a really strong smell wafting from the stove and, when I go and look, I see browned and burnt pieces of roughly chopped onions and garlic."
            k 1 u worried "\"What you asked me to do.\""
            mc 1 u sigh "\"No you're not! I asked you to suér them. The heat is way too high for that {i}and{/i} you haven't been stirring so they're not cooked evenly. See here? This part is burnt.\""
            k "\"O-oh... I was supposed to go on low heat? Why didn't you tell me that before?\""
            "What?! I asked you to suér the damn thing. Low heat is already implied!"
            mc 1 u sigh3 "\"... Just trade places with me, okay? I'll handle this part, okay. Just... just make a marinade for the meat. The spices and everything are already set aside.\""
            k "\"Marinade, gotcha...\""
            "There's no way I can salvage this stuff..."
            play sound "music/chopping.ogg"
            "I start from zero and begin dicing more onions and garlic."
            "Even if it's incredibly tedious, this is something that goes by really quick."
            "I also make sure to finish it as fast as I can so I can keep an eye on Kei-kun's progress."
            "I turn towards him to look and-"
            mc 1 u blank "\"...\""
            k "\"...\""
            "I notice that the hare is just standing still looking down at the meat and the other ingredients."
            mc 1 u sigh3 "\"Kei-kun... why aren't you doing what I asked you?\""
            k "\"Erm... I'm just trying to remember...\""
            mc 1 u "\"Remember what?\""
            k "\"... What was a marinade again?\""
            "..."
        "Curry":
            $ keilove += 1
            $ kei16food = "curry"
            "Hmm... I think curry would be a good choice."
            "I remember Kei-kun mentioning a while ago that he really liked it."
            "Since he's staying over until the rain passes I might as well do something nice for him."
            mc 1 u smile "\"Alright, I've decided on what I'm gonna make.\""
            k 1 u "\"What's that?\""
            mc 1 u happy "\"Curry!\""
            k 1 u worried "\"C-curry?\""
            mc 1 u smile "\"Yeah. I remember you mentioning you loved curry a while ago. Don't remember when though.\""
            k "\"Y-you don't have to go through that trouble just to make something for me.\""
            mc 1 u smile "\"It's not any trouble. Besides, everyone in the house likes curry too so it's not like it'll be a problem. Besides, even if you're doing better I know you're still anxious about the rain. Let me pamper you a bit.\""
            k 2 u gentleb "\"... Thanks.\""
            show k 1 u smile at fdis
            mc 1 u think "\"Now, let me think of something you can do to help...\""
            "I should probably avoid giving him anything that involves handling sharp objects."
            "He might be doing fine now but I don't need a hare jumping around the kitchen with a knife if there's thunder again..."
            "..."
            play sound "music/disappointment.ogg"
            "Come to think of it, there's not much he can do that wouldn't be dangerous in that kind of scenario..."
            mc 1 u considerate "\"{size=-4}Guess I'll just try my luck...{/size}\""
            mc 1 u smile "\"Hey, Kei-kun, I'm gonna ask you to chop the vegetables while I work on the meat, okay?\""
            k 1 u worried "\"O-okay...\""
            "I take the ingredients I need out of the fridge and hand them to Kei-kun along with the knife."
            play sound "music/chopping.ogg"
            "I set aside the spices I'm gonna use on the meat once I've finished cubing it."
            "It doesn't exactly take long but I try to make sure all my cuts are evenly sized so things can cook uniformly."
            "Then..."
            mc 1 u shock "\"W-what are you doing?!\""
            "I turn around to see incredibly mismatched pieces of vegetables being cut and tossed into a bowl."
            "They hadn't been washed beforehand... or peeled."
            "In fact, I see a few pieces of carrots that still have bumps on their outside because they hadn't even been touched."
            k 1 u worried "\"I'm slicing the vegetables like you asked...\""
            mc 1 u sigh "\"Wha- You just went right into slicing? What about washing? Or peeling? And why are they all different sizes?\""
            k "\"I-I mean, the vegetables themselves are all different sizes too so what's the problem?\""
            "I can't believe I actually just heard those words coming out of his mouth."
            mc 1 u sigh3 "\"... Just trade places with me, okay? I'll handle the vegetables, you can work on sautéing the meat. I already set the spices aside too.\""
            k "\"S-sautéing? O-okay...\""
            play sound "music/chopping.ogg"
            "I try to salvage what I can from Kei-kun's hack job at prepping the vegetables."
            "I guess he has no knife skills to speak of, huh..."
            "As I'm focusing on my work washing, peeling and dicing all the veggies, making sure to keep them uniform in size, a strange smell hits my nose."
            "That's when I realize I hear popping, followed by a squeal."
            "I turn to look just in time to shut off the fire on the stove as salt was flying everywhere."
            mc 1 u shock "\"What the- Why is there a mountain of salt covering the meat?\""
            k "\"I-I was doing like you asked me. I was sautéing.\""
            mc 1 u sigh "\"What the hell do you think sautéing means?!\""
            k "\"I-It comes from the English word \"salt\"... right?\""
        "Katsudon":
            $ kei16food = "katsudon"
            "This is one of Aki's favorites."
            "For all I the flak I give myself about pampering him, here I am cooking something just because I know he likes it again."
            "Well, guess it couldn't hurt..."
            mc 1 u smile "\"Alright, I've decided on what I'm gonna make.\""
            k 1 u "\"What's that?\""
            mc 1 u smile "\"I'll make some katsudon. Aki loves it.\""
            k 1 u smile "\"That sounds good.\""
            mc 1 u think "\"Now, let me think of something you can do to help...\""
            "I should probably avoid giving him anything that involves handling sharp objects."
            "He might be doing fine now but I don't need a hare jumping around the kitchen with a knife if there's thunder again..."
            "..."
            play sound "music/disappointment.ogg"
            "Come to think of it, there's not much he can do that wouldn't be dangerous in that kind of scenario..."
            mc 1 u considerate "\"{size=-4}Guess I'll just try my luck...{/size}\""
            mc 1 u smile "\"Could you cut slits on the pork while I prepare the breading and the sauce?\""
            k 1 u worried "\"O-okay...\""
            "I take the ingredients I need out of the fridge and hand them to Kei-kun along with the knife."
            "I start preparing the seasonings and the sauce first since I need to have that stuff on the ready once I start cooking."
            "Afterwards, I set aside three bowls to put my panko flour, my eggs and my breaded slices of pork."
            "Then..."
            mc 1 u shock "\"W-what are you doing?!\""
            "I turn around to ask something else of Kei-kun and see most of the pork steaks being cut up into tiny pieces."
            k "\"I'm cutting it like you asked.\""
            mc 1 u sigh "\"That's not what I asked you to do. I asked you to make the slits on the pork.\""
            k "\"Isn't that what I'm doing?\""
            mc 1 u sigh2 "\"What? Of course it's not. Do those look like slits to you?\""
            k "\"Then... what am I supposed to be doing?\""
            mc 1 u sigh3 "\"... Never mind. I'll handle this part. Can you prepare the breading station for me?\""
            k "\"O-okay...\""
            "Kei-kun and I trade places."
            "I put aside the slices of pork he's already ruined so I can do something else with them later."
            "I cut a few shallow slits at multiple points on the pork."
            "These will keep the meat from curling up on itself once I fry it, giving me perfectly flat pork cutlets."
            "I get into a good groove with it. It's not like I need to prepare many in the first place."
            "One for me, one for Aki, one for Kei-kun and one for Mom... whenever she wakes up."
            mc 1 u talk "\"Alright, I'm done. Now help with the bre-\""
            "I turn to look at the hare and I see him mixing a... dough?"
            "My jaw nearly hit the floor once I realize he took all the eggs I laid out and cracked them on top of the panko flour inside of a bowl."
            "The result of it was a scraggly, dry looking dough-thingy that wasn't in any way shape or form what a person needs to do to bread meat."
    mc 1 u blank "\"Kei-kun?\""
    k "\"Y-yeah?\""
    mc 1 u blank "\"You have no idea how to cook, do you?\""
    k "\"... No.\""
    mc 1 u sigh2 "\"...\""
    k "\"S-sorry...\""
    "In retrospect, I should have seen that coming."
    "The guy was raised in a giant house with servants doing everything for him. Of course he wouldn't know how to do household chores."
    mc 1 u sigh3 "\"It's fine. It's my fault for just assuming you could...\""
    "Although you could have just said you didn't know how in the first place."
    "Who are you, Shoichi?"
    mc 1 u wry "\"I'll just... do this myself. You don't have to worry about it.\""
    k 1 u wince "\"But... but I want to be useful.\""
    mc 1 u sigh3 "\"You don't have to do something you have no interest in. It's fine.\""
    k "\"I... I never said I had no interest in it. I just... never learned how. Can't you teach me?\""
    mc 1 u blank "\"...\""
    k 1 u worried "\"W-what's with that look?\""
    mc 1 u "\"Fine, I'll teach you. But if you don't know how to do something you better tell me. If I see you screwing up cause you didn't want to say anything I'm gonna be pissed.\""
    k 1 u wince "\"G-got it.\""
    scene KitchenN
    show k 1 u wince at fdis, five
    with fade
    "While I wouldn't go so far as to say that things have been going smoothly, Kei-kun is much better at following directions than I thought he'd be."
    "I thought for sure that I was going to end up with another Shoichi in my hands but he seems to possess the better part of common sense."
    "... For the most part, at least."
    k 1 u worried "\"This stuff is really tiring to do...\""
    mc 1 u smile "\"But isn't it fun?\""
    k 1 u wince "\"I'm... not sure.\""
    "I'm glad we started cooking really early because I easily took twice the time I normally would trying to teach him how to cook."
    "Even if the recipe was pretty simple, it still took quite a bit for me to teach him how to do basic things."
    "But then again, for someone that has no experience cooking and was used to being served his whole life, Kei-kun is actually surprisingly competent."
    "We're just adding finishing touches by this point so there's not much more room for error here."
    if kei16food == "curry":
        mc 1 u smile "\"By the way, how spicy do you like your curry? I'm not super fond of spicy foods so we usually have it mild but I can add a bit of pepper to it if you'd like.\""
        k 1 u considerate "\"N-no, it's fine. Don't let me trouble you any further.\""
        mc 1 u "\"Any further? How exactly are you troubling me?\""
        k 1 u worried "\"You're already cooking for me and then I messed a bunch of stuff up and you had to teach me how to cook...\""
        mc 1 u smile "\"I call that fun, not trouble.\""
        k "\"Seriously?\""
        mc 1 u happy "\"Yup. I had fun teaching you.\""
        "Besides, seeing you be so inept at something was kinda cute."
        "Most of the time I only see you doing things that you're really good at so it's hard to remember that you're also a person with flaws."
        "... So far I just thought most of them were personality flaws though."
    mc 1 u smile "\"Well, food should be ready now. Why don't you set the table while I call Aki? I trust you know how to set a table, right?\""
    show a 1 c at offscreenleft
    k 1 u sigh "\"Of course I know how to set a table. I'm not {i}that{/i} stupid.\""
    if kei16food == "katsudon":
        mc 1 u happy "\"This coming from the guy who apparently tried to make bread when I asked him to prepare the breading.\""
        k 1 u avoidb "\"... Shut up.\""
        mc 1 u happy "\"Hehehe...\""
    show LivingRoomN
    show a 1 c at fdis, fiveh
    with fade
    "Aki is still sitting on the couch, lazily tapping away at his phone."
    "Probably still talking to Hitoka after all this time too."
    mc 1 u smile "\"Lunch is ready. You still chatting with Hitoka-chan?\""
    a 1 c "\"Yeah. She's really bored at school since most of her friends didn't get there before the storm hit and they're not being allowed to go out.\""
    "Hmm... maybe I should message Saya-chan and Shoichi to make sure they're okay."
    "... I can't imagine Jun having gotten there before the storm hit but I should probably message him just to be safe."
    mc 1 u "\"Can you go wake up Mom while I finish getting things ready downstairs.\""
    a "\"Sure. I'm surprised she hasn't woken up sooner with this storm going on outside.\""
    mc 1 u considerate "\"She works really hard. I'm not surprised she'd just pass out once she went to bed.\""
    a "\"True.\""
    show a 1 c at fdis, offscreenleft with move
    "Aki walks off to go check up on her, leaving me alone in the living room."
    "I look over at the kitchen and see Kei-kun setting the table without any issues so I decide to pull out my phone for a bit."
    play sound "music/phonebeep.ogg"
    "I decide to send messages to my other friends to make sure everything is okay."
    "Well, at least if they're all trapped in the school during the storm, they'll have each other for company."
    play sound "music/message.ogg"
    "Oh wow, I'm already getting messages from all three of them!"
    "Shoichi: \"Things are pretty okay over here. A lot of the student council members arrived early so we decided to run to the adjacent building after the storm hit to work a bit. I only fell once but I'm fine!\""
    "Seriously? Even in the middle of a storm? Do these guys have no sense of self preservation at all?"
    "What are you, a lemming?"
    "Saya: \"Jun-kun and I are hanging out together. He was really lucky, the storm started coming down hard just a few minutes before he arrived. He was all wet!\""
    "Oh, ouch. That's gotta suck."
    "Jun: \"[povFirstName]-saaaaaaan, my clothes are all still wet. It's really cold! I don't like the feeling of wet underwear clinging to me.\""
    "..."
    "That's a mental picture I wish I didn't have in my mind..."
    "Still, I'm glad to see they're all okay."
    "Erm... despite a few mishaps."
    k 1 u "\"[povFirstName]-san, I've finished setting the table.\""
    mc 1 u smile "\"Oh, thanks. Aki should be down in a bit. Let's just wait until him and my mom arrive so we can start eating.\""
    k 1 u smile "\"Sure.\""
    scene SkyN with fade
    "Almost twelve hours later, the rain finally dies down."
    "Luckily there weren't any other issues with thunder or anything of the like."
    "It turned out that the thunderstorm had somehow turned into a typhoon halfway through so that explained the lack of thunder and lightning."
    "Still, we didn't have much to do to pass time for that time."
    "Aki, Kei-kun and I ended up playing card games the whole day."
    "While I wouldn't call that a boring thing to do, it doesn't exactly rank up in my list of desired activities."
    "Mom was so tired that she just took a plate with her upstairs."
    "She barely even noticed Kei-kun either."
    "It was pretty funny to see him all shocked because she didn't even register his presence."
    "It was already late at night when Kei-kun called a driver to take him back home."
    "Still... overall, I can say that I really enjoyed this day."
    $ date = None
    stop music fadeout 2.5
    stop music2 fadeout 2.5
    jump Day17_Keisuke
