label Day18_Shoichi:
    window hide
    scene May28 with fade
    play sound "music/windchimes.ogg"
    show blossoms movie
    $ renpy.pause(5.5)
    play music "music/crowd01.ogg" fadein 5.0
    scene StadiumStands
    show sa 1 c at fdis, oneh
    show k 1 c at fdis, fiveh
    show a 1 c at fdis, nine
    with fade
    window show
    $ date = "day18"
    "The match is about to start."
    "The mood today is totally unlike yesterday's."
    "We can't bring ourselves to play and joke around like we did then."
    "This is it. Minamikawa vs Shiroyama."
    "Shoichi has never been able to beat Shiroyama before. They're basically his arch rivals."
    "And the fact that they're a team similar to his only stings him further."
    "They're both teams that forsake individual strength in favor of unity."
    "Shoichi is, without a doubt, the best individual player in that court."
    "But even that doesn't mean anything."
    "You can't play by yourself in volleyball. That also means you can't win {i}or{/i} lose by yourself either."
    sa 1 c bored "\"You think they can do it this time?\""
    a 1 c smile "\"I really hope so. Shoichi-nii was really excited that that wolf was going to be playing this time. Maybe the guy will make a difference after all?\""
    mc 1 c "\"He certainly had a lot of praise to give him.\""
    "Even if all that praise was blanketed under annoyance over Haruki's personality."
    sa 1 c bored "\"Ugh... they haven't even started yet and my chest already hurts.\""
    k 1 c worried "\"That's because we know how much is riding on this. If Urata loses here, that is the end of his high school volleyball career.\""
    a 1 c worried "\"{size=-4}Shoichi-nii, please win...{/size}\""
    "Every one of us is feeling on edge right now."
    "Even I am... my chest feels so incredibly tight."
    "Shoichi might act like he doesn't care about volleyball all that much, but..."
    "I don't want to imagine how he might be if he lost today, on what's supposed to be his last chance."
    "God, if you exist, please help Shoichi..."
    show sa 1 c shock at fdis, jumping
    sa "\"They're starting!\""
    "Just like Saya says, the players have finished their warm-up routines and the captains are now flipping a coin to decide who will serve first."
    k "\"Last year Shiroyama had two players who could do jump serves. You think they've gotten any better at that this time around?\""
    sa 1 c bored "\"Wasn't one of those players a senior? That would mean he's graduated by now, right? Then there should only be one left.\""
    mc 1 c "\"Yeah, but that was months ago. Other players could have learned how to do it by then. Plus, you always have to account any arriving freshmen.\""
    a 1 c "\"According to the brochure, they only have one freshman as a regular.\""
    mc 1 c curious "\"Which one is it?\""
    a "\"Number 15. That really tall middle blocker.\""
    mc 1 c worried "\"Yikes, that guy's built like a truck. He's almost as tall as Shoichi too.\""
    a "\"Other than that, their team is built mostly of juniors and seniors.\""
    sa 1 c "\"Our school doesn't have any freshmen in the starting players.\""
    a 1 c worried "\"Yeah...\""
    "The other team won the coin toss. Their captain is the first one to serve."
    "He gets in position for a jump serve."
    show a 1 c at fdis
    sa 1 c bored "\"Ugh, I remember that guy from last year. His serves were a pain in the ass then too.\""
    stop music fadeout 2.5
    play music2 "music/BGM/Straight.ogg" fadein 5.0
    "Yeah, I recognize that deer. He was the only one in Shiroyama that could match Shoichi's serves."
    "But then again, considering how much of an upgrade Shoichi has gone through, I really don't think this guy could keep up in that area."
    "He tosses the ball into the air and jumps after it."
    play sound "music/spike.ogg"
    "?!"
    "The hit ball goes much slower than expected, swerving erratically in the air."
    "I faintly hear one of the players barking an order and jumping after the ball."
    "He attempts to get the ball with an underhand receive but it swerves at the last second and hits him in the forearm instead, bouncing out of the court."
    sa 1 c shock "\"Wha-\""
    mc 1 c worried "\"That guy can do a jump float now? That is so annoying.\""
    show sa 1 c bored at fdis
    show k 1 c at fdis
    "Shoichi gives the player that missed the ball a pat on the back."
    "Play resumes with the deer once again tossing the ball into the air."
    "Will it be a floater again?"
    play sound "music/spike.ogg"
    "This time the ball is hit with tons of momentum, making a loud sound that echoes through the court."
    "It flies like a bullet towards the other side."
    "At least one good thing can be said of Shoichi's ridiculous training routines... he's practiced his jump serve so many times against his teammates that they've grown used to fast balls."
    "In an instant, a player dashes towards the ball, making clean contact with it and sending the ball to the setter position."
    sa 1 c shock "\"Nice!\""
    "Shoichi jumps to make faster contact with that ball."
    "His form is so clean that I can't tell at all where he's going to send it."
    "He tosses the ball behind him, to the spiker directly next to him."
    play sound "music/spike.ogg"
    "The spiked ball collides against the tip of the opposing blocker's fingers. It flies into the opponent's court."
    "Because of the decrease in momentum, they are able to receive it clearly, continuing the rally."
    "Their setter isn't as impressive as Shoichi. His tosses aren't as accurate and I think he either doesn't like to or doesn't know how to do jump tosses consistently."
    "He definitely doesn't call as much attention as Shoichi does."
    play sound "music/spike.ogg"
    "Both teams continue to connect the ball and keep the rally going."
    "So far, it seems they're neck and neck."
    "Shoichi organizes better attacks so our team's offensive power is higher, but Shiroyama has better blockers and are capable of keeping us from scoring the point."
    "Right from the start of the match, the game is close."
    play sound "music/spike.ogg"
    "Another ball is received cleanly and sent right for Shoichi."
    "So far he's been doing a good job of distributing the ball. Back attacks, quick attacks, he's used every single one of his spikers at one point or another and made a good job giving them good passes."
    "Then, to our surprise, instead of tossing the ball, Shoichi's hands meet it just above the net and he lightly pushes it into the other team's side."
    "Caught by surprise, the ball falls behind the blockers and their defenders cannot save it."
    sa 1 c shock "\"Wow. Shoichi isn't usually the type to do dump attacks.\""
    mc 1 c smile "\"After the loss last year, he said something about increasing his offensive skill set. I guess this was what he meant by it.\""
    k 1 c sigh "\"Because the serve that blows your arms off clearly wasn't enough, right?\""
    show k 1 c at fdis
    show sa 1 c think at fdis
    a "\"Haruki-san hasn't really done much so far.\""
    sa "\"Oh yeah, that's true. Shoichi hasn't tossed to him much yet even though the guy's at the net.\""
    mc 1 c smile "\"Shoichi isn't the kind that trusts in his instincts. He tends to avoid making plays that he hasn't practiced tons of times before. He's probably avoiding Haruki since he doesn't have much experience with him.\""
    play sound "music/spike.ogg"
    "Just then, a ball is tossed to Haruki and the wolf leaps, spiking it at an insane inner angle to allows the ball to fly right past the blockers."
    show k 1 c smile at fdis
    sa 1 c shock "\"W-whoa. What a crazy spike!\""
    k "\"Either that was a fluke or that guy really is crazy good.\""
    mc 1 c considerate "\"Right now I think it's both.\""
    scene StadiumStands
    show sa 1 c at fdis, oneh
    show k 1 c at fdis, fiveh
    show a 1 c at fdis, nine
    with fade
    "The match continues at a high-pace the whole time."
    "Even though last year our team got almost completely shafted, this time they're managing to hold on much better."
    "A lot of it comes down to our offense. With our team constantly hammering away at them, it takes everything they've got just to hold on."
    "They're having a hard time mounting an offensive because of it."
    "Still, the score is incredibly close."
    "Shiroyama is leading by 18-16."
    sa 1 c bored "\"Man... our team is doing well but they can't seem to pull ahead.\""
    k 1 c "\"Shiroyama's well known for having one of the best defenses in the country, with strong receivers and blockers. Getting past that is no easy feat.\""
    sa 1 c sigh "\"But that makes the match drag on forever. It's so annoying to watch. How do they even have the stamina to play a full match like that.\""
    mc 1 c "\"Just because they specialize in defense doesn't mean they don't have good offense. My guess is that they always aim to end matches quickly by shutting out the other team's spikers.\""
    mc 1 c talk "\"Since they're not being able to do that here, all they can do is get a lot of one-touches and receives. The match ends up dragging because of it.\""
    k 1 c "\"So you're saying that they aren't the ones making the match drag. We are.\""
    mc 1 c "\"Pretty much. They {i}want{/i} to shut us out and score points with their blocks. It's because we're not letting them that the match is dragging.\""
    mc 1 c worried "\"Our team's offense is good enough to avoid the wall shut-out but not good enough to consistently score points on top of it.\""
    k 1 c sigh "\"Sounds like a headache.\""
    play sound "music/spike.ogg"
    "Even Shoichi's serve that was scoring tons of points just yesterday is getting received consistently without many issues this time around."
    "Shiroyama might lack really strong players but their foundation is really strong."
    "They're not the kind of team that relies on a single player which also means they're not the kind of team that you can shut down just by putting the pressure on one person."
    "Our team also tries to be that, but because of the huge disparity between Shoichi's skill and that of the others, they could never really achieve that.\""
    "When you think about it, Shiroyama is a team with lots of strong players that are all balanced among each other. No one stands out."
    "But our team is naturally incredibly unbalanced. And with Haruki in this match, the balance tips over even further."
    "Once the other team has clear targets to focus on, it becomes easier for them to shut them out."
    a 1 c sigh "\"They've been trying to make Shoichi-nii get a lot of the first touches...\""
    mc 1 c "\"If Shoichi can't toss then our team loses most of its attack potential.\""
    a "\"That's really annoying.\""
    "Aki clutches his fist around his arm, quivering."
    "I can see how frustrated he is watching the match."
    "The score is really close. The match really looks even."
    "But despite that, I feel like they're slowly being strangled."
    "Their blockers are zoning onto Haruki faster and faster. A lot of the early points on our team came from his spikes, but now they're getting lots of one-touches."
    "Eventually I feel like they're going to start shutting him off completely and then he'll be out of options."
    "The amount of pressure on those two must feel tremendous right now."
    "Hang in there..."
    play sound "music/spike.ogg"
    a 1 c happy "\"A block out!\""
    "Shoichi made a feint pretending to toss the ball to Haruki before sending a quick toss to the backline spiker."
    "The ball hit the tip of the blocker's fingers as they were falling to the ground and flew out of the court."
    "21-20... Whoever takes this first set will define the pace for the match."
    show a 1 c at fdis
    "Losing the first set here would be a huge blow to their morale, especially considering the fact that at the pace this match is going, having to play all 5-sets would probably exhaust them."
    play sound "music/spike.ogg"
    "This is one thing I never understood about volleyball... how can they jump around so much?"
    "Just watching them do it over and over I already feel like my legs are on fire."
    play sound "music/spike.ogg"
    a "\"That's interesting... Shoichi's using Haruki-san more and more. You think he's getting used to him?\""
    mc 1 c "\"I think it's something like that. Different spikers have different preferences on how they want their tosses and on the timing of their attacks. Shoichi's the type to always watch his team so maybe he's figuring things out as he goes.\""
    sa 1 c bored "\"Although it can feel kinda creepy to be playing with someone that pays so much attention to you...\""
    mc 1 c smile "\"I have Urushihara as my practice partner. I can 100\% confirm that.\""
    k 1 c avoid "\"Hey! That was uncalled for...\""
    mc 1 c happy "\"Hahaha, sorry.\""
    play sound "music/spike.ogg"
    a 1 c laugh "\"Wow, Haruki-san is doing really well.\""
    show a 1 c smile at fdis
    mc 1 c smile "\"Yeah, he is. I was afraid he'd crumble once they started putting pressure on him but he's dealing with it just fine.\""
    k 1 c worried "\"My only concern is that he doesn't mingle with the team at all during time-outs. He just sits at a corner sipping on water.\""
    mc 1 c considerate "\"Well... Rome wasn't built in a day. Let's just be happy that he's not starting any fights.\""
    sa 1 c bored "\"He looks super pissed off though.\""
    a "\"I talked to him for a bit before the match. It looks like his brother is here to watch him today so he said he's going to be on his best behaviour.\""
    show k 1 c at fdis
    show sa 1 c at fdis
    mc 1 c shock "\"Wait, when did you talk to him?\""
    show a 1 c at fdis
    "Aki shrugs."
    a "\"When you guys were talking to Shoichi-san outside their locker room. I saw Haruki-san going inside and talked to him for a bit.\""
    mc 1 c sigh "\"I'm not sure how I feel about that.\""
    a 1 c happy "\"I just thought that I could remind him again about just how excited I am for this match and how I hope he'll be able to work well with his team!\""
    "Aki imitates a high, squeaky, super excited voice."
    k 1 c worried "\"You two scare me with how few qualms you have about manipulating people.\""
    show a 1 c smile at fdis
    "[povFirstName] and Akiyoshi" "\"It's nothing much.\""
    sa 1 c bored "\"Creepy...\""
    play sound "music/spike.ogg"
    show a 1 c at fdis
    "Just then, Haruki spiked another ball. Every time he does so, the sound that echoes through the court is deafeningly loud."
    "But for the first time in the match, he gets completely blocked."
    "Our team's libero tries to save the ball but it smashes against the floor."
    "25-23..."
    k 1 c worried "\"D-damn... they took the first set...\""
    a 1 c worried2 "\"And by blocking Haruki-san too... I hope he handles it w-\""
    show sa 1 c shock at fdis
    show k 1 c shock at fdis
    play sound "music/crash.ogg"
    h 1 v "\"Shit!\""
    "Just as Aki was saying these words, Haruki runs up to a nearby chair and kicks it over, startling everyone."
    "His teammates run up to try and calm him down but he seems to prefer just sulking on a corner."
    show sa 1 c sigh at fdis
    k 1 c worried "\"That's not good...\""
    sa 1 c sigh "\"That guy has a really nasty temper. My God.\""
    mc 1 c sigh3 "\"No kidding. I guess hoping everything went smoothly was a bit too optimistic...\""
    "Come on, man. Keep that temper in check for just this match..."
    sa 1 c bored "\"I don't like how this match is going. I don't feel like Shiroyama is just going to run away with it but I'm afraid that if it drags too long, our team might lose their gas first.\""
    k 1 c worried "\"It's not just that. Extreme exhaustion takes a really big toll on a person's mental condition. Our team isn't nearly as united as theirs. I'm afraid they would start fraying...\""
    mc 1 c sigh "\"Can we please stop saying such pessimistic things. I don't want to be thinking about all this crap right now.\""
    k "\"Sorry...\""
    stop music2 fadeout 2.5
    scene StadiumStands
    show sa 1 c bored at fdis, oneh
    show k 1 c worried at fdis, fiveh
    show a 1 c worried2 at fdis, nine
    with fade
    play sound "music/spike.ogg"
    "Haruki's spike flies towards the high blocking wall and is immediately sent back to the ground."
    "Even though the team was able to drag the match into the 5th set, it's becoming more and more apparent that they're struggling to keep up."
    "Not only that, this is the fifth time Haruki gets blocked just during this set."
    "It's plain to see that his play is deteriorating due to stress."
    k "\"11-8... Do you think they can recover from this?\""
    sa "\"T-they have to, right? They already managed to get all the way into the 5th set. They just need to reach 15 points first.\""
    "... That's easier said than done."
    play music2 "music/BGM/Sighs.ogg" fadein 5.0
    "During the whole match, I've been watching Shoichi intently."
    "I don't know why but I feel like his spirit is breaking little by little."
    "The accuracy of his tosses and the power of his serves hasn't diminished, but... I feel like he's not making as many bold attacks anymore."
    "The more cornered he feels, the more defensive he gets."
    "And since their strong attacks were the only thing keeping Shiroyama from going all-out on their own offense, it's also making it harder and harder for them to defend."
    mc 1 c worried "\"Shoichi...\""
    play sound "music/spike.ogg"
    "It's painful."
    play sound "music/spike.ogg"
    "Watching this match is starting to get painful."
    play sound "music/spike.ogg"
    "Even though they were trying so hard..."
    play sound "music/spike.ogg"
    "Even though they were doing so well..."
    play sound "music/spike.ogg"
    k 1 c sad "\"They're on match point...\""
    sa 1 c bored "\"Sho-chan...\""
    mc 1 c worried "\"...\""
    "14-10."
    "No matter how much I try, that is not a lead I can imagine them recovering from."
    play sound "music/spike.ogg"
    "The other team's captain serves."
    "He goes for a jump float again."
    "?!"
    "The ball is short, falling as soon as it passes the net."
    "It goes for Shoichi?!"
    "Was he targeting the setter position?"
    show k 1 c shock at fdis
    sa 1 c shock "\"Sho-chan!\""
    "Shoichi lifts his arms to do an overhand receive."
    "At the last second, the ball curves again."
    "Shoichi's attempt to receive the ball makes it fly right into the net in front of him."
    "Haruki, who was standing right next to Shoichi, lunges at the ball in an attempt to save it."
    "... But it hits the floor before the wolf can reach."
    "They all stare at the ball as it rolls away. Silently. In shock."
    play sound "music/crowdcheer3.ogg"
    "The crowd erupts in cheers."
    "Of course, for them this was nothing more than a really close, exciting match."
    "They don't feel the same way as we do."
    "... And I can't imagine we can feel the same way as the players do."
    "The players all line up in silence."
    "Team" "\"Thank you all for your support!\"" with hpunch
    "The team walks up to the bleachers, shouting their gratitudes to those of us who came to watch."
    "But just sounds wrong."
    "Hearing them say these things with such sad looks on their faces..."
    "I can't take it."
    sa 1 c bored "\"Let's go to the locker room. We should talk to Shoichi as soon as he gets out of his post-match meeting.\""
    k 1 c wince "\"Good idea.\""
    "Shoichi..."
    stop music2 fadeout 2.5
    scene StadiumLobby
    show sa 1 c bored at fdis, oneh
    show k 1 c worried at fdis, fiveh
    show a 1 c worried at fdis, nine
    with fade
    "We wait around for quite a few minutes, hoping that Shoichi will eventually show up."
    "We're not allowed inside the locker room area because we're not competitors so we have to wait by the lobby."
    "Once we see his teammates are starting to appear, we start looking for Shoichi."
    a "\"Haruki-san!\""
    show sa 1 c at fdis, one
    show k 1 c worried at fdis, fourh
    show a 1 c worried at fdis, seven
    with move
    show h 1 v at fdis, ten with moveiridis
    "We see Haruki walking side by side with a boy."
    "A white wolf just like him, except he has bright blue eyes and a smile on his face."
    "When Haruki notices us, he lets go of the boy's hand and gets down on his knee, giving the boy a bill."
    h 1 v smile "\"Taro, why don't you go to the vending machine and get yourself a snack, okay? Big bro has to talk to a few friends.\""
    "Taro" "\"Tch, Nii-chan, you don't have to treat me like a baby.\""
    "The boy looks at us for a few seconds and his eyes land on Aki."
    "Taro" "\"It's nice to meet you. Thank you for taking such good care of my brother. I'm sorry that he's so much trouble all the time.\""
    "The boy makes a reverence to us before turning to smile at Aki."
    show h 1 v at fdis
    h "\"Taro.\""
    "Haruki calls him again, this time more sternly."
    "The boy shows his brother his tongue before running away towards the vending machine."
    h "\"Ugh... he's such a brat...\""
    "The wolf sighs, tired."
    "For the first time, I actually feel like I can relate to him as a person."
    h "\"So, what do you want? Came to rub salt on the wound?\""
    a 1 c considerate "\"Uhm... you played really well, Haruki-san.\""
    "Aki smiles mournfully at the wolf, trying to sound sympathetic."
    h 1 v smile "\"Thanks. Man, you're such a well-mannered kid. Wish my brother could be more like you. He's a real brat.\""
    show a 1 c at fdis
    "Yeah... little brothers always tend to be brats to their older brothers. Believe me, it wouldn't change a thing."
    sa 1 c "\"Did you see Shoichi? We were looking for him.\""
    h 1 v "\"Hmm? He left a little before we did. Stayed around all smiles helping console the other members, he looked like he didn't even care at all. Then he said he was going to the bathroom. I didn't see him after that.\""
    sa 1 c shock "\"Huh? So you don't know where he is?\""
    "Haruki furrows his eyebrow."
    h 1 v "\"I thought he was with you people. Did the fucker just come up with an excuse to ditch us? I knew he didn't really want to deal with all that sobbing...\""
    "He sighs, rubbing his forehead."
    "He seems to be so tired that he can't even get properly mad."
    k 1 c sigh "\"Great. Urata's gone MIA...\""
    sa 1 c sigh "\"So we just sit around until he gets back, huh?\""
    "..."
    mc 1 c considerate "\"Will you guys wait around for me? I'll be back in a bit.\""
    show k 1 c shock at fdis
    sa 1 c shock "\"Wha- Where are you going?\""
    mc 1 c considerate "\"To the bathroom. Erm... for real. I've been wanting to go for a while now and I can't hold it in anymore.\""
    show k 1 c at fdis
    sa 1 c sigh "\"Seriously? Gross.\""
    mc 1 c sigh "\"What? You pee too. Chill.\""
    k "\"Try not to take too long, okay? We don't know when Urata will get back.\""
    mc 1 c considerate "\"Yeah, I know. I'll be quick.\""
    scene StadiumCloset with fade
    play sound "music/door2.ogg"
    "For some reason, I've had a feeling in my stomach that I should come here."
    "As soon as Haruki said something about Shoichi being cheerful... I knew there was something wrong."
    show s 1 v sad at fdis, five with dissolve
    s "\"... [povPetName]?\""
    "Just as I thought I would, I find Shoichi sitting alone on the floor and hugging his knees, his eyes red and wet."
    "Despite the lack of space, I sit next to him, silent."
    s "\"...\""
    "Once Shoichi realizes that I'm not going to say a word, he goes back to quietly sniffling."
    "I thought I'd bear witness to full-blown sobbing but he seems to be controlling himself now that I'm here."
    "Idiot."
    s 1 v blush "\"Why... are you here?\""
    mc 1 c wry "\"We met with Haruki. He told us you left a while ago... to go to the bathroom of all places.\""
    mc 1 c considerate "\"He said you were smiling and encouraging your teammates. He said it looked like you didn't care.\""
    mc 1 c wry "\"I knew that couldn't be further from the truth so... I came here to look for you.\""
    s 1 v wryt "\"I see... Sorry to cause you so much trouble... I just wanted to be alone... so no one could see me looking so pitiful... I especially didn't want you to see me like this...\""
    "I wrap my arms around him, pulling his head towards me and nestling it against my shoulder."
    mc 1 c worried "\"Don't be stupid, Sho... I'm... I'm your boyfriend now. I'm here for you whenever you need me.\""
    "Then, the dam breaks."
    play music2 "music/BGM/Watershine.ogg" fadein 5.0
    s 1 v cry "\"[povPetName]... I... I really wanted to win...\""
    mc 1 c worried "\"I know...\""
    s 1 v cry "\"I... I should have done better! I should have sent them better tosses. I should have scored more points with my serve. I... I... I should have been able to receive that last ball...\""
    mc 1 c worried "\"I'm sorry, Shoichi... You did the best you could. You can't blame yourself.\""
    s 1 v cry "\"But I let them all down! They were counting on me and I... I made so many mistakes. And now I'll never get to play with them again.\""
    mc 1 c worried "\"You didn't let anyone down. Stop saying that. You inspired everyone to keep going until the end. How can you say you let them down?\""
    s 1 v cry "\"But... I...\""
    play sound "music/chu.ogg"
    show s 1 v shock at fdis
    "I gently lift his chin with my fingers, planting a gentle kiss on his lips."
    s 1 v avoidb "\"[povPetName]?\""
    mc 1 c wry "\"I don't want to see you talking about yourself like that. I can't stand seeing you like that, Sho. You did the best you could. You did incredibly well. Surely you must know that.\""
    s 1 v avoidb "\"But... we lost...\""
    mc 1 c worried "\"You can't blame that on yourself. Weren't you the one who always said... volleyball is a team sport. You can't win or lose by yourself?\""
    s 1 v sadb "\"...\""
    mc 1 c wry "\"Sho... please, don't treat yourself like this. None of your teammates think that way of you at all. You all fought to the end with everything you had. Can't you at least be satisfied with that?\""
    s 1 v avoidb "\"... No. I wanted to win with them. I wanted to keep playing with them... Keep playing volleyball...\""
    mc 1 c considerate "\"Then why don't you?\""
    s 1 v blush "\"I can't...\""
    mc 1 c wry "\"Yes you can. You should do what you want, Shoichi. Stop worrying so much about what other people want you to do.\""
    s 1 v blush "\"I... I'm sorry, I... I ca-\""
    show s 1 v shock at fdis
    play sound "music/chu.ogg"
    "I kiss him once again, stroking his damp cheeks with my fingers."
    s 1 v avoidb "\"...\""
    mc 1 c happyb "\"I'm gonna keep doing this until you stop with this self-blame and denial.\""
    s 1 v wry "\"Are you trying to encourage me into continuing to do that?\""
    mc 1 c considerate "\"Hehe...\""
    s 1 v avoidb "\"... I don't want to quit, [povPetName]... but I have to. I promised my father I would stop after the Interhigh. I have to study for the college entrance exams.\""
    mc 1 c worried "\"Sho, you should stop doing everything he wants you to do. You're your own person. You should do what you love. What does it matter if he doesn't approve of it?\""
    s 1 v considerate "\"I...\""
    mc 1 c wry "\"You're not gonna try to look me in the eye and say you don't love volleyball, are you? I'm gonna smack you if you keep doing that.\""
    s 1 v avoidb "\"... I love volleyball. I never want to stop playing it.\""
    mc 1 c considerate "\"There we go.\""
    s 1 v wryt "\"But... But I can't go against what he wants, [povPetName].\""
    mc 1 c worried "\"Sho-\""
    s 1 v wry "\"Thank you... really. Thank you for being here for me. But it's not that easy.\""
    s 1 v considerate "\"And by the way... \"Sho\"... I really like hearing you call me that. Please, do that more.\""
    "Shoichi cups my cheek in his hand, nuzzling his forehead against mine."
    mc 1 c blush "\"Sho...\""
    "I do as he's asked me, prompting him to smile."
    s 1 v wryt "\"At least I have you here with me right now. That's enough for me... I love you, [povPetName].\""
    play sound "music/heartbeat.ogg"
    "..."
    play sound "music/chu.ogg"
    scene Black at fdis
    "We continue to kiss for a few more minutes with no more words said between us."
    "I... I wish I could do more."
    "Isn't there something I could do to help him?"
    "Unable to come up with an answer, we silently walk out to join the others."
    stop music2 fadeout 2.5
    stop music3 fadeout 2.5
    scene SkyE with fade
    "Once I found myself home, I kept looking out the window, thinking about what I can do for him."
    "Shoichi... you've done so much for me over the years."
    "I want to do something for you too."
    mc 1 c worried "\"Warm...\""
    "I touch the tip of my fingers to my lips, remembering the feeling of Shoichi's kisses."
    "For some reason, I find myself missing it."
    "Shoichi... I want to go see you right now..."
    "Why won't my chest stop hurting?"
    scene BedroomN with fade
    play sound "music/phonebeep.ogg"
    "Trying to get my mind to stop racing, I lie in bed and attempt to distract myself with my phone."
    "No answer from Shoichi yet..."
    "He was so silent all the way home..."
    "Even if he says I've helped him, it's obvious he's still sad and hurting."
    "... Just remembering the look on his face when he broke down into tears, I feel like crying myself too."
    "Crap... what's going on with me?"
    "Shoichi..."
    "I want this day to end already..."
    $ date = None
    $ schoolfestival = "shoichi"
    jump SchoolFestival
