label Day19_Jun:
    window hide
    scene June1 with fade
    play sound "music/windchimes.ogg"
    show blossoms movie
    $ renpy.pause(5.5)
    play music "music/crowd01.ogg" fadein 5.0
    scene SCorridor with fade
    window show
    $ date = "day19"
    "Once again, I am standing outside of my own classroom waiting around for a certain tiger to appear."
    "And once again, as is usual, he is late."
    "... Please tell me he didn't cause another accident today."
    play sound "music/slidingdoor.ogg"
    play music2 "music/BGM/Goraku Iinkai.ogg" fadein 5.0
    show j 1 ch sigh at fdis, five with dissolve
    "My attention is immediately snapped back to reality when Jun's rotund figure appears by the door."
    "He shuts it behind his back before leaning back onto it and sighing deeply."
    mc 1 c "\"Is everything okay?\""
    show j 1 ch wry at fdis
    "The little tiger looks up at me with a weary expression, not even at all fazed by my appearance."
    j "\"Hey, [povFirstName]-san. Yeah, I'm fine.\""
    mc 1 c worried "\"You sure? You don't look fine.\""
    show j 1 ch considerate at fdis
    "He lifts his hand up to chest height, waving it dismissively."
    j "\"Yeah, I'm just tired, that's all. Doing this stuff for four days kinda takes it out of you.\""
    mc 1 c "\"How come you were late again today? You didn't get into another accident did you?\""
    j 1 ch wry "\"No. My replacement was late so I had to stick around until he arrived cause I couldn't leave the place short-staffed.\""
    "Come to think of it, I did see one of our classmates walking into the restaurant with the waiter uniform."
    "I guess that explains that."
    mc 1 c "\"Do you want to take some time to just breath and relax before we set out?\""
    j 1 ch considerate "\"Could we? That'd be great...\""
    "Yeah, if he's actually agreeing with my idea of resting then I know he's {i}really{/i} exhausted."
    mc 1 c worried "\"Jun, don't push yourself so hard okay?\""
    j "\"Hehehe...\""
    "Knowing him, I can almost guarantee he will eventually."
    "Honestly, he's more stubborn than the proverbial mule."
    "It really makes me want to give him a good, firm kick to the ass sometimes."
    j 1 ch wry "\"By the way, [povFirstName]-san, do you have any idea what you want us to do today?\""
    mc 1 c smile "\"Yep. I have a few things planned out that I think you'll like.\""
    j 1 ch watch "\"Like what?\""
    mc 1 c talk "\"Well, we already agreed that we wanted to see that play the second years are putting on. I passed by there yesterday and got a brochure with the times and explaining the play itself.\""
    j 1 ch shock "\"Ooh, that's interesting.\""
    mc 1 c considerate "\"I didn't even tell you what it's about yet, how are you already thinking it's interesting?\""
    j 1 ch happy "\"I'm sure I'll find it interesting anyway.\""
    "..."
    mc 1 c "\"Anyway, I also checked and saw that the videogame club set up an arcade so we can go check that out.\""
    j 1 ch shock "\"An arcade?! How did they even manage to do that?!\""
    mc 1 c considerate "\"I have no idea. Maybe they rented a few machines for the day?{nw}"
    show mc 1 c smile at fdis, offscreenleft
    extend " All I know is that people have been saying they have quite a few good games so we can go try that.\""
    j 1 ch happy "\"Yeah, it sounds really fun.\""
    show j 1 ch shockb at fdis
    "Before I noticed it, I had put my hand on top of Jun's head and began calmly petting like that was the most normal thing in the world."
    mc 1 c talk "\"Oh, sorry.\""
    j 1 ch happyb "\"N-no, it's okay!\""
    mc 1 c smile "\"Heh. You look like you've perked up quite a bit already.\""
    j 1 ch happy "\"I have! How about we go to the arcade?\""
    mc 1 c happy "\"All this cause you want to play games?\""
    j 1 ch think "\"Well, the brochure you gave me says the play won't start until a few hours from now so it's not like we have anything else to do.\""
    mc 1 c smile "\"I suppose that's a good point. Alright, follow me and try not to get swept up by this sea of people on the floors below. If you think it's packed here wait till you see downstairs.\""
    j 1 ch considerate "\"I suppose it's too much to hope that there won't be many people at the arcade?\""
    mc 1 c considerate "\"Yup. It most certainly is.\""
    j 1 ch avoid "\"Aww...\""
    play sound "music/slidingdoor.ogg"
    stop music2 fadeout 2.5
    play music3 "music/BGM/The Arcade.ogg" fadein 5.0
    scene Arcade
    show j 1 ch smile at fdis, five
    with fade
    "The two of us walk into the dimly lit room, immediately we see a multitude of colorful flashing lights coming from the myriad of machines spread around the place in neat lines."
    show j 1 ch cshock at fdis
    "The place is far more packed than I thought it'd be, with barely any room to maneuver by the entrance."
    "I guess that's because there is only one very narrow door to function as both an entrance and an exit."
    "And they even have the single cash register right next to the door, with a small-ish looking stoat standing in front of it, frantically doing many tasks all at once to service the ever growing line of customers."
    "Considering her height, I'd guess the girl is a middle schooler but since I know such a thing is pretty impossible... maybe she's a freshman?"
    mc 1 c talk "\"Come on, Jun, let's get in li-{nw}\""
    play sound "music/tap.ogg"
    show j 1 ch cshock at fdis, shake
    "I feel a tight squeeze around my arm and without even having to turn to look, I already groan in exasperation."
    mc 1 c sigh3 "\"Can't you try to hold it together for just a little bit? The entrance might be packed but the place looks okay by the machines. We'll be out of the mob's hair in just a few.\""
    "Nope, no response at all."
    "Yeah, his brain has shut off pretty good again."
    "It's been a while since he's done this too."
    "I guess hoping his experience with the festival had made him improve at dealing with crowds was just a pipe dream."
    "I try to ignore the shivering tourniquet I have wrapped like a vice around my arm as I stand in line."
    "Soon I can feel some slight tingling that continues to grow more and more as time goes by."
    "Yep, it's official, I can't feel my arm."
    "And I might need a crowbar to pry this tiger away from me when we're finished."
    "The sad part is, this kind of stuff doesn't even faze me anymore."
    "Just another day in my life as I deal with Jun."
    "Clerk" "\"Good afternoon, how may I help you?\""
    "The stoat girl looks up at us with an uneasy smile once our turn finally rolls around."
    "I can barely make out her features very well considering the darkness in this room but I have a feeling that her eyes are a deep amber."
    mc 1 c "\"Hm, hi, me and my friend want to buy a few tokens for games.\""
    "Clerk" "\"Oh, we don't actually use tokens. We use cards.\""
    "She opens a drawer underneath her register and pulls out a credit card looking plastic thingy that has a magnetic bar on the back, gesturing to it with a smile."
    "Clerk" "\"See? We load credits into the cards and every machine has a card reader that debits them when swiped.\""
    mc 1 c confused "\"How the hell did you guys manage to get all this set-up? My class barely even managed to clear enough of a budget to get gas burners for their restaurant.\""
    "The girl's smile becomes a little more open at my question."
    "She adjusts herself where she stands and clears her throat."
    "Clerk" "\"You see, the videogame club is one of the most popular in school. Every year we make a lot of different highly profitable displays and use the funds from those to bolster our budgets for the next year.\""
    "Clerk" "\"That way our members can always have the best experiences possible during the festival and everyone gets to have fun. Isn't it great?\""
    mc 1 c "\"Huh. I don't even remember seeing the videogame club's events for the past two years. Guess I wasn't paying much attention.\""
    "Her shoulders sag at my apparent lack of enthusiasm as she stares up at me with a furrowed eyebrow."
    "Clerk" "\"I... I see...\""
    mc 1 c smile "\"Anyway, how much is a session in each of the machines?\""
    "However quickly her disappointment came, she put herself back together just as quickly and was back to her professional demeanor in no time, straightening her back and clearing her throat once more."
    "Clerk" "\"Each play session ranges from 150 to 400 yen but it depends on what machine you're looking to use.\""
    mc 1 c "\"That's a little pricier than a regular arcade... but then again, I imagine it couldn't have been cheap to rent all these machines for the duration of the festival.\""
    "She smiles and nods, not saying another word to my statement."
    mc 1 c smile "\"Okay, I'll take a card for me and one for my friend. Load them up with about ¥2000 each. That should be enough.\""
    "Clerk" "\"Let me just warn you that if you don't finish spending all the money before you leave, you'll still be asked to return the card and it'll be wiped clear of any funds.\""
    mc 1 c smile "\"Sure, that's fine.\""
    "Could you please hurry up? I really can't feel my left arm anymore."
    mc 1 c considerate "\"Uhm... hang on, let me just... try to get my wallet here.\""
    "I awkwardly attempt to finish my wallet out of my pocket using my right hand."
    "The girl, who seemed to have not noticed Jun this entire time, finally lays eyes on the shaking tiger and gasps."
    "Clerk" "\"I-Is he okay?!\""
    mc 1 c considerate "\"That's... debatable. He always gets like this in the middle of big crowds.{nw}"
    show mc 1 c wry at fdis, offscreenleft
    extend " Hey, Earth to Jun, can you let go of my arm? I kinda need it right now.\""
    "Nope, no response. Oh man, this is much more troublesome than I thought it would be."
    "Why do I always end up having to be the victim of Jun's panic attacks?"
    "Even when we're hanging out as a group, it's always my arm that ends up being attacked."
    "At this rate, I'm going to end up traumatized."
    mc 1 c sigh "\"Hey, Jun, I really don't want to be rough with you but I'm having a really hard time getting to my wallet {i}and{/i} I can't feel any blood circulation to my arm anymore.\""
    "No dice. He continues to cling to my arm, shaking like one of those vibrating back massagers you can buy for a few bucks on a random street vendor."
    mc 1 c sigh3 "\"Alright... Just for the record, I didn't want to have to resort to this.\""
    "Clerk" "\"Resort to wha-{nw}\""
    "With my free hand, I pinch Jun's nose."
    "Since his mouth is acting as if it were welded shut, he won't be able to breath if I do this."
    "Clerk" "\"W-wait, isn't that a bit-\""
    show j 1 ch cshock at fdis, jumping
    j "\"*GASP*\""
    "Jun lunges away from me and to the side, taking a deep breath as he comes back to his senses."
    j 1 ch wince "\"W-what are you doing, [povFirstName]-san?! Are you trying to kill me?\""
    mc 1 c sigh "\"I'm trying to wake you. Just go stand by the machines before you shut down again.\""
    j "\"B-but...\""
    mc 1 c sigh3 "\"Just do what I'm telling you. I already can't feel my arm, I don't need you latching to me again.\""
    j 1 ch avoid "\"S-sorry...\""
    show j 1 ch avoid at fdis, offscreenright with move
    "He walks away dragging his feet, looking incredibly crestfallen."
    "By how dramatic he's being, a random bystander might think I just called him some of the most horrible insults known to man."
    "Clerk" "\"That was... surreal.\""
    "The girl looks between the two of us with wide open eyes, clearly not used to seeing this degree of craziness in her everyday life."
    mc 1 c considerate "\"No... the sad part is that it really, really wasn't.\""
    "Sorry, hun, but I already deal with this in a daily basis. This sort of thing doesn't get to me anymore."
    "I clumsily manage to scoop my wallet out of my pocket, given that my arm's range of movement is severely impaired."
    "It's tingling so much right now. Such a weird feeling..."
    mc 1 c considerate "\"Here you go. Sorry about the trouble.\""
    "She nods politely, hesitantly taking the money I hand to her."
    "She scans two cards by her machine and quickly hands them back to me with another measured smile."
    "Clerk" "\"Thank you, I hope you'll enjoy your stay.\""
    "I nod and flash her a smile, walking off towards the rows of machines and looking for Jun."
    show j 1 ch shockb at fdis, five with move
    "I finally spot him watching another person playing an old 16-bit."
    "The machine had a second control station, probably so it could allow for two players."
    "In the game, an oddly skimpily dressed soldier would walk through a side-scrolling map while shooting a horde of weird looking alien things and picking power-ups for his weapons."
    "The guy playing the game seemed to be pretty good at it because the amount of projectiles flying at him was nothing short of insane and yet he would dodge all of them."
    "Ducking, jumping, sliding. All sorts of gravity-defying maneuvers were executed to allow him to dodge the barrage of bullets."
    "But eventually, one bullet just {i}slightly{/i} grazed him and that caused his character to immediately {i}explode{/i} into a 16-bit gorefest."
    mc 1 c wince "\"Yikes...\""
    j 1 ch watch "\"Ah, [povFirstName]-san!\""
    "Jun finally seemed to notice my presence. He was probably too engrossed in the game to care before."
    "The boy playing got up from the machine without another word and walked off, stomping on his way out, clearly frustrated."
    mc 1 c "\"This one's got your attention?\""
    j 1 ch happy "\"Yeah, I've played it before. Although it was the console version which isn't all that great in my opinion.\""
    mc 1 c "\"Really? Why not?\""
    j 1 ch considerate "\"It doesn't allow for two players, it's pretty laggy, it sometimes has trouble rendering all the bullets on screen meaning you get hit by invisible ones.\""
    mc 1 c worried "\"Oh... that does sound pretty terrible.\""
    j 1 ch think "\"Yeah. It's kind of a mess.\""
    j 1 ch smile "\"I've never played the arcade version of it. Can we give it a try? It allows for two players.\""
    mc 1 c smile "\"Sure. What's this game called anyway?\""
    j 1 ch happy "\"The name is Dune Wulf.{nw}"
    show j 1 ch smile at fdis
    extend " You play as a duo of veteran soldiers in the middle of a war somewhere in a place with a deep jungle before the Earth gets invaded by aliens and you have to fight back.\""
    mc 1 c considerate "\"That... doesn't really make much sense.\""
    j 1 ch think "\"The game is from the 80s so you shouldn't expect a marvel of storytelling from it.\""
    mc 1 c smile "\"I'm surprised you can say that with a straight face when you love games so much.\""
    j 1 ch considerate "\"Just because I love them doesn't mean I can't be realistic about their issues. Games a few years back really sucked in terms of story.\""
    j 1 ch think "\"Hell, I've once played an RPG where the only line of dialogue in the whole game was in the very opening sequence where the king just said \"Oh no, the princess was taken. Please save her.\" and that was it.\""
    mc 1 c wince "\"That's... not very good, yeah.\""
    j "\"To say the least.\""
    j 1 ch smile "\"The soundtrack was pretty good though considering it was an 8-bit game.\""
    mc 1 c smile "\"You always have comments on game soundtracks don't you?\""
    j 1 ch happy "\"Yeah. It's my favorite thing to pay attention to.\""
    mc 1 c smile "\"Do you have any idea what kind of company you'd work for once you got a job as a composer?\""
    j 1 ch considerate "\"I don't even know if I'd get one. It's not a sure thing by any definition of the word.\""
    mc 1 c happy "\"Oh come on, you've got so much talent. Sure you will.\""
    j 1 ch wry "\"Even if that is true, just having talent isn't enough. You need a lot of luck to make do in a highly competitive environment. Sometimes the most talented people get passed over.\""
    mc 1 c worried "\"That's... a really pessimistic view on things, Jun.\""
    j 1 ch considerate "\"I'm just being realistic. Sometimes even if you have a lot of talent, you might lack in interpersonal skills or you might not have many connections.\""
    j 1 ch wry "\"It takes a lot of luck to be successful. Just being talented won't be enough.\""
    menu:
        "Agree":
            $ junlove -= 1
            mc 1 c worried "\"I... I guess... you're probably right.\""
            j "\"It's not something I enjoy thinking about but it is what it is.\""
            "I don't want to agree with it but..."
            "... at the same time, I can't come up with any kind of logical response to it."
            "It stands to reason that not everyone will be able to make it."
            "What Jun said is true. No matter how talented you are, that isn't a guarantee of anything."
            "If things were that simple, there wouldn't be so many athletes in my own field running around and trying to get sponsors."
            "There's only so much a single person can do on their own. I know that."
            "It's just... I hate to have to agree with that."
            "To this day I have refused any and all sponsorship deals that were offered to me because I wanted to prove to myself that someone can make it on effort alone."
            "So this whole thing just... doesn't sit well with me."
            "It goes against all my personal feelings on the matter."
            "... But nevertheless, I can't think of a single argument to it."
            j 1 ch considerate "\"[povFirstName]-san, you're making a really pained expression right now.\""
            mc 1 c wry "\"O-oh... sorry.\""
            j 1 ch wry "\"You don't have to worry about it so much. All someone can do is try their best and hope for the best. There's no point in worrying about it.\""
            "..."
            "I don't like this."
            "I don't like this one bit."
        "Disagree":
            mc 1 c worried "\"Hmm...\""
            j 1 ch watch "\"What's wrong? You're making a weird face.\""
            mc 1 c considerate "\"Oh, you could tell huh?\""
            "Jun cocks his head to the side, eyeing me with suspicion."
            mc 1 c wry "\"It's just... I can't bring myself to agree with you there.\""
            j 1 ch considerate "\"[povFirstName]-san, I-{nw}\""
            mc 1 c considerate "\"Just hear me out, okay?\""
            mc 1 c worried "\"If we're speaking logically then... maybe you might be right. But... I just don't like that thought process, you know?\""
            mc 1 c considerate "\"To me it just sounds like admitting defeat even before it happens. It sounds like you're preparing yourself to lose even before you do so as to soften the blow.\""
            mc 1 c worried "\"That way when things finally go wrong you can say \"Oh well, there was nothing I could do about that\". I don't like it. You're convincing yourself it's okay to fail instead of trying your hardest.\""
            j 1 ch avoid "\"[povFirstName]-san...\""
            mc 1 c considerate "\"Of course, you probably don't need to hear this from me. No one knows your future career better than you do so I'm probably just an idiot who knows nothing and is disagreeing out of principle...\""
            j 1 ch considerate "\"Not at all. I really appreciate it.\""
            mc 1 c shock "\"You do?\""
            j 1 ch wry "\"Yeah. It makes me happy to know you care so much about it.{nw}"
            show j 1 ch happy at fdis
            extend " This might be silly but it kinda gives me a confidence boost. Hehe.\""
            "Without saying a word, I reach for the top of his head again, petting the tiger and scritching his chin leisurely."
            show j 1 ch happyb at fdis
            "I feel a pleasant vibration on his neck as I continue to do it, which just makes me want to keep going."
            "Crap, I really shouldn't be doing things like this in public."
    j 1 ch think "\"By the way, did you get the tokens so we can play?\""
    mc 1 c wince "\"O-oh, right!\""
    "Jun snaps me back to reality and I dig into my pockets for the two plastic cards I was given."
    mc 1 c smile "\"Here you go. I've loaded ¥2000 in each of these so we should be able to play for a while.\""
    j 1 ch shock "\"Oooh, I've never been to a place that used cards before.\""
    mc 1 c smile "\"They're pretty common in commercial arcades nowadays but I didn't think they'd use them in this one.\""
    j 1 ch considerate "\"I guess you can tell I haven't been to an arcade in a few years, huh?\""
    mc 1 c happy "\"Just a little.\""
    "We both swipe our cards into the Player 1 and 2 slots."
    "The screen exits its little demo video and immediately blinks into a game start screen."
    play sound "music/blaster2.ogg"
    "The two of us are immediately dropped into a thick jungle and there are already multiple pea sized bullets being shot at us by a group of soldiers hiding under bushes."
    mc 1 c talk "\"Wow, this game is wasting no time in trying to kill us huh?\""
    j 1 ch happy "\"Oh yeah, I forgot to tell you. This was considered one of the most difficult games of the 80s. It gobbled coins like no one's business.\""
    mc 1 c shock "\"What?!\""
    play sound "music/explosion.ogg"
    "Almost as if on cue, as soon as Jun says those words, an enemy shoots a mortar at the two of us."
    "Jun expertly jumps to the edge of the screen, narrowly dodging it by a few pixels."
    "As for me, I get immediately blown up to bits."
    "Literally to bits since this a 16-bit game."
    "Clever joke, I know."
    mc 1 c shock "\"What the hell?!\""
    j 1 ch wince "\"Careful, [povFirstName]-san. You only have three lives per player. If you lose all of them you'll have to pay more.\""
    "I look down at the little display on the card reader where it says \"¥300 per session\"."
    mc 1 c shock "\"This thing is freaking expensive for a game that can kill you just like that.\""
    j "\"[povFirstName]-san, pay attention to the game!\""
    mc 1 c wince "\"Ah!\""
    play sound "music/blaster2.ogg"
    "I narrowly dodge another barrage of bullets shot at me."
    "Jun's character is darting around the screen, dodging everything that is thrown at him and massacring the enemy forces."
    "Since this game is a sidescroller, we can only move forward if I'm with him."
    "I can quickly tell that I'm slowing him down."
    "Jun can somehow make progress really fast in this thing, killing most of the enemies with expert precision."
    "Meanwhile, it takes every bit of my well-trained reflexes to just avoid enemy fire."
    mc 1 c wince "\"How are you doing all this?\""
    j 1 ch happy "\"I played this game so much when I was little that I memorized a lot of the enemy placements.\""
    mc 1 c sigh "\"You're kidding me!\""
    j 1 ch think "\"Careful, on the next screen there will be an enemy helicopter flying overhead and dropping lots of bombs. You have to shoot up to destroy it and dodge all the normal enemy units at the same time.\""
    show j 1 ch watch at fdis
    "As soon as we cross some sort of invisible finish line, a sequence plays out where a giant helicopter that fills all the horizontal space of the screen appears, just like Jun said."
    "A character with a cartoonishly big head sits at the cockpit. He looks down at us and laughs before bombs begin to drops."
    "Immediately, Jun is rolling and jumping around, dodging every single one of those and firing at the chopper."
    "As for me..."
    play sound "music/explosion.ogg"
    mc 1 c dismay "\"Waah!\"" with hpunch
    "I get blown up for the second time in less than three minutes."
    j 1 ch think "\"Be careful, you only have one life left. This boss tends to be really good at sucking credits out of new players.\""
    mc 1 c wince "\"Y-you don't say...\""
    "God, I feel absolutely useless."
    "As soon as I respawn, I begin trying to mimic Jun's movements, trying desperately just to stay alive."
    "Which, by the way, is much easier said than done."
    "I think I counted less than forty seconds before I was blown up again."
    j 1 ch wince "\"Ah, [povFirstName]-san...\""
    mc 1 c considerate "\"Sorry. I guess I kinda suck at this...\""
    "Man, I don't think I've ever sucked so bad at a game before."
    j 1 ch considerate "\"I'll just let him kill me and we can go play something else.\""
    mc 1 c wry "\"No no, you don't need to do that. Just have fun playing the game. I'll watch.\""
    j 1 ch watch "\"You sure?\""
    "Even though he keeps looking between me and the game, he continues to expertly dodge and fire at the same time."
    "It's like this is super easy for him."
    "Man, I know Jun is good at games but this is kinda ridiculous."
    mc 1 c considerate "\"Just how often did you play this thing?\""
    j 1 ch think "\"Hmm... I think this was the only game I owned for over a year when I was small so I played it every day.\""
    "..."
    "I don't know whether I should be sad or impressed."
    "Eventually, Jun's efforts pay off as the helicopter begins to systematically explode."
    "The pixelly pilot turns to look at the screen with a look of terror before the whole thing finishes blowing up, taking him with it."
    mc 1 c considerate "\"This game definitely isn't ashamed about its own violence, huh?\""
    j 1 ch happy "\"That's what makes it fun. It's just silly, fast-paced gaming.\""
    "I'm not sure if I'd call it {i}fun{/i}."
    "Stressful? Sure. Not fun."
    mc 1 c smile "\"Let's see how long you can last on your own.\""
    "I continue to stand behind him, watching him massacre waves of enemies all by himself through multiple stages."
    "I don't even know how much time I spent watching him, although I'm somewhat dimly aware of the fact that he hasn't even died once yet."
    mc 1 c sigh "\"... Seriously, how are you doing this? Your dodges are all pixel perfect. That's ridiculous.\""
    j 1 ch happy "\"I had a lot of practice after all.\""
    mc 1 c "\"How many levels does this thing even have?\""
    "As Jun continued to play, I had noticed that each level got more and more bizarre."
    "From a thick, densely packed jungle to a forward enemy base in a clearing to a boat level to a marine base."
    "Then the aliens hit, the water turned purple, the skies darkened, hordes of... weird flying things began to attack from above."
    "I kind of lost count of how many weird new enemy types kept appearing but Jun apparently had all of them memorized."
    j 1 ch think "\"I'm on level 6 right now. This game has 10 levels. It probably won't last that much longer.\""
    mc 1 c sigh "\"You played over half the game without dying once? Are you kidding me?\""
    j 1 ch happy "\"Hehehe. I'm pretty good at it, aren't I?\""
    "You are... and definitely not humble about it either."
    "Although after seeing just how easily this game kicked my ass, I guess he's entitled to feel proud of himself for it."
    "The guy that had been playing before us seemed to be quite a few levels behind where Jun is now too."
    show j 1 ch shock at fdis, jumping
    j "\"Ah!\""
    "Then it happens."
    "A single bullet barely grazes the foot of Jun's character mid-jump and that causes him to explode."
    j 1 ch wince "\"Damn it... that's one.\""
    mc 1 c "\"I'm surprised it's only been just one.\""
    "There are so many bullets flying by the screen right now that I can't even keep track of where they're coming from."
    "He must have some really good hand-eye coordination."
    "During the next level, Jun is suddenly sucked into what I assume is the alien mothership."
    "He fights a bunch of frog-like things with cannons strapped to their backs."
    "They jump around in weird patterns and spray bullets in circles that fly all over the screen."
    "Just watching all of them on-screen is already starting to make me feel sick."
    "Jun dies for the second time there."
    "Just like before, he gets barely grazed by a bullet and that causes his character to die."
    "I have to say, for a veteran soldier, this character doesn't seem to be very resistant to... anything, really."
    "Like... a bullet just hit your toe, dude. You don't need to explode because of that."
    "Jun somehow manages to get past this level."
    "There were many times where I thought he was a goner but he clung to that last life."
    show j 1 ch judge at fdis
    j "\"Ahh... level 9! Just a bit more...\""
    "His face was scrunched up in a look of frustration as he continued to mash the buttons on the machine."
    "Jun was leaning so far forward on his chair that he was almost touching the screen with his forehead."
    mc 1 c considerate "\"Careful. You're gonna hurt your eyes like that.\""
    j "\"Shhh. Not now!\""
    "He, of course, brushed me aside completely."
    show j 1 ch shock at fdis, shake1
    play sound "music/blaster.ogg"
    j "\"Ah!\""
    "Jun jumps back on his seat as his character is hit for the third time."
    "Once he explodes again, the entire screen is tinted red, the words \"Gume Uver\" flashing brightly on the display in English."
    "... My guess is that whoever translated this wasn't doing a very good job."
    "But then again, games back then had a ton of translation issues so I guess I'll let that slide."
    j 1 ch wince "\"Aww... I was so close this time.\""
    mc 1 c considerate "\"Sorry you didn't make it.\""
    j 1 ch pout "\"Booo. Let me try again.\""
    "I stop him before he can swipe the card on the machine."
    show j 1 ch wince at fdis, shake1
    j "\"H-hey!\""
    mc 1 c considerate "\"How about we try some of the other games instead?\""
    j 1 ch pout "\"Booo!\""
    mc 1 c sigh "\"Booing me isn't going to change anything. I didn't come here just to watch you play.\""
    j 1 ch avoid "\"... Fine.\""
    show j 1 ch watch at fdis
    "Reluctantly, Jun steps away from the machine."
    "We take a few rounds around the room, looking at any interesting games we might find."
    mc 1 c confused "\"What's this thing? \"aidoruM@ker\"? What kind of game is this?\""
    j "\"Oh, that's a musical game. You pick girls to make an idol group and then you choose their training routines, their songs, their costumes, stuff like that.\""
    mc 1 c sigh "\"... Who would play this kind of thing?\""
    j 1 ch considerate "\"The songs are really nice though.\""
    mc 1 c sigh3 "\"Yeah, no, not my thing.\""
    show j 1 ch watch at fdis
    mc 1 c "\"Most of the games here seem to be pretty old. I wonder why that is.\""
    j 1 ch happy "\"They're all very popular, vintage machines.{nw}"
    show j 1 ch smile at fdis
    extend " If you take a close look, you'll see that they're the machines with the players. People are lining up for a few of them.\""
    mc 1 c talk "\"Sheesh, so much excitement just for a bunch of old games?\""
    j 1 ch pout "\"Some people really like the classics, okay!\""
    mc 1 c fsmile "\"A-alright, calm down, no need to blow a gasket over this.\""
    j 1 ch sigh "\"[povFirstName]-san, you can be so insensitive with other people's interest sometimes.\""
    mc 1 c sigh "\"Hey! That is absolutely not true. Name one t-{nw}\""
    j 1 ch shockb "\"Ooooh, I used to play this game as a kid too!\""
    "He cuts me off mid-sentence, hopping towards a nearby machine and examining it with great enthusiasm."
    mc 1 c sigh3 "\"Why do I even bother...\""
    scene Arcade
    show j 1 ch happy at fdis, five
    with fade
    "We do a few round across the the place, blowing most of our credits on a multitude of games."
    "Outside of a light gun game called \"Time Fortune\" that was... pretty fine."
    "I can tell it was a game from the early 90s just by seeing how bad the 3d graphics were but it was still pretty fun."
    mc 1 c "\"We should still have enough credits for one more game, I suppose.\""
    j 1 ch smile "\"Do you see any that you want to play?{nw}"
    show j 1 ch considerate at fdis
    extend " I kinda just dragged us around everywhere and forced you to watch me play a bunch.\""
    mc 1 c smile "\"I still had fun anyway.\""
    j 1 ch wry "\"Maybe, but it would still make me feel better if you could pick something this time.\""
    mc 1 c smile "\"Alright, sure. I saw a few I think we could play together. I'll just choose one of them.\""
    j 1 ch smile "\"Sure. Which one?\""
    "I think over my options for a second, trying to decide which one to play."
    play sound "music/disappointment.ogg"
    "... If I were going by names alone I wouldn't pick either of these, they're so bad."
    "But the gameplay of them seemed pretty interesting and according to Jun they are all cult classics so I guess I should give one of them a try."
    "Still... what is it about 80s and 90s games that makes most of them have terrible titles?"
    "It's like someone mistranslated them so badly and no one had the heart to correct them."
    "Well, no point overthinking this..."
    menu:
        "The game I'll pick is..."
        "Abode of the No Longer Living":
            "I'll go with this one."
            "It's also a light gun shooter but this one is against zombies and monsters instead of soldiers armed to their teeth."
            "... Instead, it's a bunch of things armed {i}with{/i} teeth."
            "I walk up to the machine and grab one of the guns that is connected to it by a thick metallic cable."
            j 1 ch happy "\"Oh, this one? That's a pretty good job. This game used to be super popular way back when.\""
            mc 1 c smile "\"How about we give this a try?\""
            j 1 ch smile "\"Sure. It should be fun.\""
            "Once I load up the last of our credits into the machine, it springs to life."
            "It shows us a quick screen asking us to aim at multitude of reticles."
            "Probably automatic calibration of the gun sensors to make sure no one gets screwed over by a bad gun."
            "Once we're done with that, we're immediately popped into a really badly rendered 3D graveyard."
            "Cries echo from the distance and the camera pans."
            "We see hellish creatures rising from their graves and rushing at us."
            j 1 ch shock "\"C-careful!\""
            "Jun definitely loses his cool on this one, firing wildly at anything that moves as he panics."
            mc 1 c shock "\"J-Jun, that was a hostage we were supposed to save!\""
            show j 1 ch shock at fdis, jumping
            j "\"Oh no!\""
            "Rest in peace, purple 3D lady. You shall be remembe-"
            mc 1 c shock "\"N-no! Jun, you shot another hostage!\""
            show j 1 ch cshock at fdis, shake
            j "\"Nuuuuu... [povFirstName]-san, I'm scared!\""
        "Boot of the Southern Celestial Body":
            "This one seems interesting."
            "It's a licensed game based on a popular anime from the 80s."
            "I remember watching re-runs of this... although I can remember of it is that a lot of people kept dying in it."
            "I'm honestly surprised Mom let me watch this as a kind haha."
            mc 1 c happy "\"How about this? It brings back a few childhood memories.\""
            j 1 ch shock "\"Ooooh, that one is pretty cool.\""
            mc 1 c smile "\"I've never played it before but from the demo videos on the screen it looks like a reskinned generic beat-em up.\""
            j 1 ch happy "\"Pretty much. It's still really fun though.\""
            mc 1 c smile "\"Yeah? Have you played it before?\""
            j 1 ch smile "\"The console version of it, yeah.\""
            mc 1 c "\"This has a console version?\""
            j 1 ch considerate "\"Yeah. The framerate is worse but... they fixed a lot of translation issues.\""
            mc 1 c confused "\"Translation issues? Is it that bad?\""
            j 1 ch think "\"Well...\""
            "Jun takes a card from my hand and swipes it on the machine."
            "Immediately it begins to play an intro scene, complete with many drawings of the characters talking."
            "The protagonist, Jugemu, stares at his opponent who stands on a pile of garbage."
            "The man points down at the imposing lead and his dialogue appears on the screen."
            "\"All your base are belongs to us, Jugemu!\""
            show j 1 ch considerate at fdis
            "..."
            mc 1 c sigh "\"The very first line of the game is mistranslated...\""
            j "\"Yeeeah... it gets worse.\""
            "Oh boy... this is gonna be awful isn't it?"
        "Buildings & People: Underground Structure of Blessing":
            "This seems pretty fun."
            "It's a beat-em up with magic and wizards and... a lot of underground structures."
            "I guess the name describes it pretty well after all?"
            j 1 ch think "\"Oh, this one? I think it's based on a popular tabletop RPG series but I've never played any of it.\""
            "Jun notices me staring intently at the machine and pipes up with some commentary."
            mc 1 c "\"Tabletop RPG? What's that?\""
            j 1 ch watch "\"They're basically RPGs you play with just your imagination. You write down your character, describe what you do and roll dice.\""
            mc 1 c sigh "\"That doesn't sound very fun.\""
            j 1 ch considerate "\"I've never played it so I wouldn't know. Still, it's pretty popular and this one was a success in arcades too.\""
            mc 1 c smile "\"I guess we can give this a try.\""
            "Oh, it has a character select screen even."
            "Let's see... I'll pick this witch girl dressed in green. It says here her magic stat is pretty high."
            "Actually... what are all these characters? They look like a bunch of furless monkeys."
            "It creeps me out..."
            "Jun picks some guy whose description says he's a Barbarian but he's wearing... suit and tie?"
            "What the hell?"
            mc 1 c talk "\"Erm... how do you use magic on this thing? Every button I press just makes her either jump or do a baton twil.\""
            j 1 ch think "\"Hmm... Oh, I forgot to mention. From what I read, this game is supposed to be set in a parody version of the real world so there is no magic in it.\""
            mc 1 c shock "\"What? Then what do I do with a magic caster character that can't use magic?\""
            j 1 ch smile "\"You better get really good at twirling that baton.\""
            mc 1 c sigh "\"Then why is my character even dressed like this?\""
            j 1 ch watch "\"She's a cosplayer suffering from chuunibyou.\""
            mc 1 c sigh "\"... I want to play a different game.\""
            j 1 ch considerate "\"We've already spent our last credits on this one.\""
            "... I'm considering recharging the cards just so I can pick something different."
            "But when I look back, the line is still pretty big."
            "Ugh... it would take me too long to do that."
            "... Guess I'll just have to play this thing."
            "Without spells, I can't do anything other than do cute little spins and twirls with her stupid wand/baton thing."
            "... Am I gymnast?"
    stop music3 fadeout 2.5
    play music2 "music/BGM/Dog Days.ogg" fadein 5.0
    scene SCorridor
    show j 1 ch happy at fdis, five
    with fade
    show sometime with dissolve
    $ renpy.pause(1.0)
    hide sometime with dissolve
    "Jun is humming the melody from one of the games he played, cheerfully making gestures with his fingers as he bops along to it."
    "He's probably in his best mood since the start of the day."
    "And considering how tired he was when we first met, that really makes me glad."
    play sound "music/phonebeep.ogg"
    mc 1 c talk "\"Oh, we need to hurry if we wanna catch that play. It starts in twenty minutes.\""
    j 1 ch smile "\"Okay.\""
    "Despite what I just said, he doesn't show the last bit of rush in getting there."
    "He keeps walking at a leisurely pace, slowly making his way through the sea of people populating the hallway."
    "At least he's not freaking out on me but I wish he had some sense of urgency."
    mc 1 c considerate "\"Uhm... Jun, we really need to hurry.\""
    j 1 ch happy "\"Gotcha.\""
    "The tiger continues to hum, walking at a snail's pace."
    "Did he... did he get {i}slower{/i}?!"
    mc 1 c sigh "\"... Jun, we're gonna miss the play.\""
    j "\"Understood.\""
    "..."
    "There is no break in his humming."
    "He continues to cheerfully and without a care in the world sing away as if he had infinite time at his disposal."
    "Walking slowly to match his speed is starting to get on my nerves because I don't want to end up missing the damn thing because of this."
    mc 1 c sigh "\"... Jun?\""
    j 1 ch smile "\"Yeah?\""
    show j 1 ch cshock at fdis, jumping
    mc 1 c sigh2 "\"{size=+2}Walk faster!{/size}\""
    "I lean onto his ear and shout loudly onto it, causing him to jump back in surprise and stare at me with super wide open eyes."
    "He nearly knocked someone down doing it too."
    "I have to admit, it's kinda funny."
    j "\"Awawawawawawawawa. What's the big idea?\""
    mc 1 c sigh "\"I'm telling you to walk faster! We'll miss the play if you keep walking at this snail's pace.\""
    j 1 ch avoid "\"B-but...\""
    mc 1 c sigh3 "\"But what? Is something the matter?\""
    j "\"... My feet kinda hurt.\""
    mc 1 c blank "\"...\""
    j "\"...\""
    mc 1 c sigh "\"... Come on, let's find someplace to sit down. We don't need to watch the play.\""
    j 1 ch wince "\"N-no, I want to watch it. I just don't want to have to run there.\""
    mc 1 c "\"How much do your feet hurt?\""
    j 1 ch considerate "\"I've been running around quite a bit these past few days so... kind of a lot.\""
    "Well, you {i}are{/i} out of shape. This kind of thing is to be expected."
    "But I'm not heartless enough to tell him that to his face."
    mc 1 c "\"What do you want to do? If we keep going at this pace there's no way we'll be able to get to the other building in time.\""
    j 1 ch considerate "\"I-I can make it. I just have to suck it up a little bit.\""
    menu:
        "What should I do?"
        "Rest and miss the play":
            $ junlove += 1
            mc 1 c considerate "\"Come on, let's look for a quiet place for us to sit down on.\""
            j 1 ch shock "\"What?! But what about the play?\""
            mc 1 c sigh "\"I'm not gonna make you run around campus when you're in pain.\""
            j 1 ch wince "\"I-I'm fine. I can deal with it. Come on, didn't you want to watch the play?\""
            mc 1 c smile "\"Honestly, I just want to spend time with you. I don't really care if we miss it or not.\""
            j 1 ch shockb "\"Ah...\""
            show j 1 ch blush at fdis
            "Jun looks away from me, his face suddenly turning quite a bit red."
            "Heh, I don't quite know why but I do really dig this reaction."
            "He looks pretty cute when he's blushing."
            j 1 ch wince "\"W-where do you want to go?\""
            mc 1 c happy "\"I have an idea. Follow me.\""
            show j 1 ch shockb at fdis
            "I grab him by the arm and lead him away with me."
            play sound "music/metaldoor.ogg"
            scene SRooftopE
            show j 1 ch shock at fdis, five
            with fade
            play music "music/breeze.ogg" fadein 5.0
            "It takes me a few tries but I finally manage to get through the doorlock."
            "This is probably one of the stupidest things I ever did but I have to admit I like the rush from it."
            j "\"How did you do that?! You just picked the lock!\""
            mc 1 c smile "\"Yup. It wasn't as hard as I thought it'd be. Kinda fun even.\""
            j 1 ch wince "\"A-aren't you going to get you trouble because of it?\""
            mc 1 c "\"It's not like they have cameras here. They won't even know we were here.\""
            j "\"Are you sure? It can't be that easy.\""
            mc 1 c happy "\"Oh but it is, little one.\""
            j 1 ch pout "\"I'm not little!\""
            mc 1 c smile "\"I dunno, you're kinda little.\""
            "Jun walks up close to me, standing on tip-toe to try and look at me face to face."
            j "\"Nuh-uh. Look, I'm almost as tall as you are.\""
            mc 1 c laugh "\"Hahaha, sure you are.\""
            show j 1 ch shockb at fdis
            "I begin to pet him again."
            "For some reason it kinda relaxes me."
            show j 1 ch happyb at fdis
            play sound "music/purr.ogg"
            "Jun immediately melts onto my hand, purring."
            "His face is so red and yet he doesn't seem to care one bit."
            "Hahaha, it's really cute."
            mc 1 c happyb "\"Hahaha, you liking that?\""
            j "\"Mhhhhm~ Please don't ever stop.\""
            mc 1 c smile "\"That's gonna be hard. I'll need bathroom breaks and food.\""
            j "\"Hmmmm~ That can be arranged.\""
            "His knees start shaking a little which is when I know it's time to stop."
            j 1 ch blush2 "\"Aww, why did you stop?\""
            mc 1 c smile "\"Cause I didn't want you to fall to the floor when your knees buckled.\""
            j "\"That wasn't going to happen...\""
            mc 1 c happy "\"Sure. No way it was.\""
            j 1 ch happyb "\"Come on, [povFirstName]-san, please pet me more!\""
            mc 1 c laugh "\"Oh my God, you're being so needy and demanding right now.\""
            j "\"Mhm. I don't mind it if it's with you.\""
            mc 1 c smile "\"Alright, fine, but at least sit first. I don't want your knees to just give away.\""
            j "\"Okay!\""
            play sound "music/fabric.ogg"
            "Jun quickly lies down on the floor."
            "Guess he decided to go a bit further than what I asked."
            "Not that I'll complain since I do nap up here quite often anyway."
            "I lie down on my side next to him, being able to see his face quite clearly."
            "He still has his eyes closed but as soon as my hand touches him, he moves his head towards my hand."
            "It's all very cute and relaxing."
            play sound "music/purr.ogg"
            "Soon he's purring again."
            "He's so easy to please. If this is all he needs to be happy and content then I guess he would be very a very low-maintenance boyfriend."
            "... Erm... to someone."
            "I don't know why I just thought of that... erm..."
            "Jun continues to nuzzle against my hand."
            "I have to admit, walking around for the past few days has left me a bit more tired than I thought."
            "I'm so comfortable right now that... I'm starting to feel drowsy."
            "I try to will myself into staying awake but the sound of the wind and Jun's purring slowly erodes at my wakefulness."
            "My eyes start to blink a little slower with each passing second..."
            stop music fadeout 2.5
            stop music2 fadeout 2.5
            scene SkyN with fade
            "I shift around a few times, feeling a cold, hard floor under me."
            "When my eyes open, I immediately see the night sky."
            "I lie still for a few seconds, absorbing the view and trying to remember where I am."
            "Then as a jolt of realization runs through me, I sit up with a jump."
            scene SRooftopN
            show j 1 ch shock at fdis, five
            with fade
            "When I look to the side, I see Jun eyeing me with a bit of surprise."
            "Probably because of the sudden movement."
            j 1 ch watch "\"Oh, [povFirstName]-san, you're awake.\""
            mc 1 c wince "\"W-when did I fall asleep?\""
            j 1 ch smile "\"A few minutes after we got here. I've just been enjoying some quiet time while I waited for you to wake up.\""
            mc 1 c wince "\"Ugh... you should have woken me up instead!\""
            j 1 ch happy "\"I didn't want to. You looked like you really needed your sleep.\""
            "Whether I did or not is irrelevant, you still should have woken me up!"
        "Hurry so we won't miss it":
            mc 1 c "\"Are you sure you can do it?\""
            j 1 ch considerate "\"Yeah. It just hurts a little. If there's no other way around it then I'll have to deal with it.\""
            mc 1 c sigh3 "\"Do tell me if it starts being too much, okay?\""
            j 1 ch wry "\"Okay.\""
            scene MusicRoom
            show j 1 ch wince at fdis, five
            with fade
            show minutes with dissolve
            $ renpy.pause(1.0)
            hide minutes with dissolve
            j 1 ch wince "\"Ha... ha...\""
            "Jun is huffing and puffing right next to me."
            "We managed to make it in the nick of time and he's barely had a chance to catch his breath."
            mc 1 c worried "\"Look, they're already starting. Let's go get our seats.\""
            j 1 ch avoid "\"Are there any seats free?\""
            mc 1 c "\"Erm... here, there are two next to each other.\""
            "The two of us try to reach the seats without disturbing any of the other people in the room."
            show j 1 ch watch at fdis
            "The lighting is dimmed and a boy walks up to the center stage."
            "They've improvised a stage of sorts in the room, removing all the tables from the classroom and setting up a small elevated wooden stage in front of the blackboard."
            "There are maybe twenty chairs arranged for viewers here and it seems they have a little closed off area to the side of the stage."
            "Probably where the actors can stay out of sight until their scenes roll along."
            "A light shines on the boy."
            "Wait, they don't have any spotlights here, how are they doing this?"
            "Male Lead" "\"Someone please tell me... why must fate hurt us so. With naught but suffering and ungratefulness in life, not even love to provide us succor...\""
            "The script is, as I expected, very cheesy."
            "According to the brochure I got, the play is about two teenagers who fall in love despite being from two families that swore a blood feud on each other."
            "The whole thing reeks of bootleg Romeo and Juliet but it's supposed to have a happy ending somehow."
            "The lead monologues on the stage for a few minutes before breaking into song."
            "His singing voice isn't anything to write home about but it's entertaining enough."
            "After he finishes his lamento, a girl dressed in a weird white outfit walks up to the stage with him."
            show j 1 ch shock at fdis
            "It turns out that she's some kind of nature sprite... fairy... whatever magical thingy."
            "She offers to grant him one wish if he fulfills a task for her."
            "The next twenty minutes of the play have him trying to find some kind of rare mystical fruit in the woods to finish the fairy's quest."
            "Somehow, the female lead hasn't appeared a single time yet."
            "He nearly gets killed a few times by wild animals and breaks into song two more times."
            "In the meantime, the play skips to the point of view of his family where they talk about finally having a special weapon to defeat the other family."
            "The whole thing has been making less and less sense as time passes."
            show j 1 ch watch at fdis
            "The scene cuts back to the boy. He got his mystical fruit... somehow."
            "The whole thing apparently happened off-screen."
            "Maybe they couldn't come up with an explanation for it?"
            "He brings the fruit back to the fairy-sprite thingy."
            "The girl is incredibly happy with it and asks what his wish is."
            "He then, in a twist I didn't see coming, asks the sprite to marry him."
            "Apparently he had fallen in love with her during his quest... somehow?"
            "What about the first girl he talked about in the opening monologue?"
            "What the hell is happening with this play?!"
            "The two of them get married and then it just... ends."
            "There is no resolution to the entire earlier conversation about how the two families were about to go to war for the last time."
            "It's just... the end?"
            play sound "music/clapping.ogg"
            play music "music/crowd01.ogg"
            "The crowd claps enthusiastically... for some reason?"
            "The whole thing felt very mediocre to me, if even that."
            "Yet somehow it's a hit?"
            "Maybe... maybe I'm just not much of a theater person?"
            mc 1 c wince "\"What... what was that?\""
            j 1 ch flustert "\"It... it was beautiful!\""
            mc 1 c shock "\"What?!\""
            j "\"Don't you love a good happy ending?\""
            "Happy ending?! The whole thing made no sense!"
            "What about the first girl?! She didn't show up even once"
            "What the hell happened to her?!"
            mc 1 c considerate "\"I'm... glad you liked it?\""
            j 1 ch avoid "\"Didn't you?!\""
            mc 1 c considerate "\"Erm... sure. Yeah, sure, I did.\""
            j "\"You don't sound very pleased with it.\""
            "Try not to be too critical. Try not to be too critical. Try not to be too critical."
            mc 1 c worried "\"Well... it's just that... the whole thing... it kinda... sucked.\""
            "..."
            "Good job, me."
            j 1 ch wince "\"Y-you think so? I really liked it.\""
            mc 1 c considerate "\"S-sorry, I think I went too far with my criticism...\""
            "Well... no, I really didn't."
            "But I'm comfortable if he chooses to believe I did."
            j 1 ch think "\"How long was that anyway? I lost track of time.\""
            "Lucky bastard."
            play sound "music/phonebeep.ogg"
            mc 1 c talk "\"Hmm... Oh wow, it's already 7:45.\""
            j 1 ch shock "\"What?! So it's already dark outside?!\""
            "The entire room's windows were blocked up with some dark drapes so no sunlight was coming through."
            "Guess the play itself was deceptively long. The whole thing was almost an hour and a half."
            "I'd call it impressive if I hadn't been so bored for most of the time."
            j 1 ch wince "\"W-what time is the fireworks display?\""
            mc 1 c smile "\"The bonfire is gonna be lit in about twenty minutes. Fireworks come after the dance.\""
            j 1 ch sigh "\"Oh, so we'll have time to get to the roof.\""
            mc 1 c happy "\"You don't want to join the bonfire dance?\""
            j 1 ch considerate "\"Nah, I'll pass. I'm not a huge fan of the idea of dancing around a giant blazing fire. {size=-2}I already nearly set myself on fire once. That's enough for a week.{/size}\""
            "Hehehe, fair enough."
            mc 1 c happy "\"Alright then, come on.\""
            j 1 ch shockb "\"Wha- [povFirstName]-san?!\""
            "I grab Jun by the hand and lead him out of the room, rushing along the waves of people so we can quickly get to our destination."
            stop music2 fadeout 2.5
            stop music fadeout 2.5
            scene SRooftopN
            show j 1 ch shock at fdis, five
            with fade
            "It took us a while to finally get here, what with having to walk to a different building across hordes of people."
            "It takes me a few tries but I finally manage to get through the doorlock."
            "This is probably one of the stupidest things I ever did but I have to admit I like the rush from it."
            j "\"How did you do that?! You just picked the lock!\""
            mc 1 c smile "\"Yup. It wasn't as hard as I thought it'd be. Kinda fun even.\""
            j 1 ch wince "\"A-aren't you going to get you trouble because of it?\""
            mc 1 c "\"It's not like they have cameras here. They won't even know we were here.\""
            j 1 ch shock "\"W-wow. It's so dark up here.\""
            mc 1 c happy "\"It is the middle of the night after all. But the stars are out today so it should be fine.\""
            "Jun takes a few steps forward, his eyes glued to the sky above."
            "I can't say I blame him, from up here you can see the stars a little bit better than you would from the station or our houses."
            "I take a seat on the ground next to where he's standing and the tiger follows suit, still mesmerized by the view."
    j 1 ch watch "\"Isn't it beautiful?\""
    "I follow his gaze and take in the view of the sky myself."
    mc 1 c smile "\"It sure is.\""
    j 1 ch smile "\"I'm glad you managed to get us here.{nw}"
    show j 1 ch considerate at fdis
    extend " Erm... even if you did have to pick the lock.\""
    mc 1 c happy "\"It's one more experience that I can say I had in the future.\""
    j "\"I probably wouldn't tell people about this... who knows, you might be arrested.\""
    mc 1 c laugh "\"Hahaha, I doubt someone would immediately call the cops on me because I told them I picked a lock back in high school.\""
    j 1 ch happy "\"Fair enough.\""
    show cg7_1 with dissolve
    "Jun leans back on the ground, his eyes sparkling with the light of the stars."
    "For some reason, I seem to be more interested in watching him than I do the sky."
    "I... never really stopped to think this before but... Jun is a pretty handsome guy."
    "I know I call him cute all the time but... this feels... somehow different."
    "It's weird. I'm not really sure why that is."
    "I'm confused over my own thoughts and that's not something I like."
    j 1 ch zero "\"By the way, what time is it, [povFirstName]-san?\""
    mc 1 c "\"Let me check.\""
    play sound "music/phonebeep.ogg"
    mc 1 c talk "\"Oh. The fireworks should be starting any time now.\""
    j 1 ch zero "\"Good. That means we were right on time.\""
    mc 1 c smile "\"Yeah it does.\""
    play music "music/breeze.ogg" fadein 5.0
    "The two of us stare at the sky in silence."
    "The distant cheerful voices of the other students and guests attending the festival can be heard down by the courtyard."
    "But up here, the one sound that is most distinguishable is that of wind."
    "I always found it a bit weird how there always seems to be a breeze up here."
    "Pleasant... but still weird."
    "I'd never come up here in the middle of the night before so the wind is a tad more chilly than I thought it would be."
    mc 1 c considerate "\"Man, I wish I had worn something a little warmer.\""
    j 1 ch zero "\"Probably shouldn't go out in nothing but a tank top.\""
    mc 1 c smile "\"I look good in a tank top though.\""
    "Jun chuckles, his voice carrying softly along with the wind."
    j 1 ch zero "\"Yeah, I guess you do. Although to be honest, you look good regardless of what you're wearing anyway.\""
    play sound "music/heartbeat.ogg"
    "..."
    "Jun isn't even looking at me right now."
    "That's a good thing because I wouldn't want him to see my cheeks searing hot from that compliment."
    "Damn, what's the matter with me?"
    j 1 ch zero "\"This actually reminds me, [povFirstName]-{nw}\""
    play sound "music/fireworks.ogg"
    play music2 "music/BGM/Reminiscing - Piano.ogg" fadein 10.0
    show cg7_2 with Dissolve(1.0)
    "Just then, Jun's voice is cut off by the pop of a firework."
    "Our eyes are immediately dragged upwards and we see the first one appear in the sky."
    "A neon green explosion that fills our view with a beautiful stroke of color."
    "Then, more and more fireworks begin to pop, one after the other."
    "Soon, the sky turns into a giant canvas on which all these vibrant colors are displayed."
    "They appear, they shine brightly and then they disappear, never to be seen again."
    mc 1 c shockb "\"Wow...\""
    "I'd never watched a fireworks display from this high up before."
    "It's truly mesmerizing."
    mc 1 c happyb "\"What do you think, J-{nw}\""
    show cg7_pan with Dissolve(1.0):
        subpixel True
        yalign 1.0
        linear 0.7
        linear 12.0 yalign 0.05
    "I turn to look at Jun, only to see the light of the fireworks reflecting on his eyes."
    "For some reason, my breath is taken away."
    "I stare at his figure slack-jawed."
    "The fireworks that are shooting and illuminating the sky all around us provide a beautiful scenery on the background... as well as shine a beautiful line on him."
    "For what I think it's the first time ever, my chest suddenly feels so tight."
    "I feel like words won't come to me."
    show cg7_4 with Dissolve(1.0)
    "Jun turns to look at me, those beautiful brown eyes sparkling so full of colors."
    j 1 ch zero "\"Did you say something?\""
    "He sounds so much more peaceful and subdued than I'm used to seeing him."
    "He's so... calm."
    hide cg7_1
    "I force myself to close my mouth, swallowing a few times before shaking my head in negative."
    "I don't know how much time has already passed as I completely lost track of it."
    "I continue to stare into Jun's eyes, not wanting to look away."
    "I feel so... warm."
    "I don't get it."
    show cg7_3 with dissolve
    "The fireworks subside, leaving only Jun's careful gaze pointed right at me."
    mc 1 c avoidb "\"I-I was gonna mention how... how the fireworks were beautiful.\""
    "Jun nodded, his face maddeningly blank for someone usually so energetic."
    "In fact... his gaze almost looked... distant."
    "Like he was here but at the same time... not."
    j 1 ch zero "\"Yeah... You looked beautiful with the fireworks shining on you too, [povFirstName].\""
    play sound "music/heartbeat.ogg"
    "!"
    "The words he said just now..."
    "They are incredibly close to the ones I myself was thinking just a while ago."
    mc 1 c considerate "\"W-what? M-me? You shouldn't be saying that, Jun, I'm a gu-{nw}\""
    j 1 ch zero "\"[povFirstName]... I like you.\""
    mc 1 c flustered "\"W-well, o-of course I like you t-\""
    "He slowly shakes his head sideways."
    j 1 ch zero "\"Not as a friend. As a man. Romantically.\""
    play sound "music/heartbeat2.ogg"
    "That's it."
    "The thin line that was still keeping my mind sane and capable of functioning completely snaps."
    "My mouth opens wide and I just... stare."
    "In shock... without saying a word."
    "Jun looks at me like that for a few moments... carefully... studying me."
    "..."
    "Say something..."
    hide cg7_3
    hide cg7_2
    hide cg7_pan
    hide cg7_4
    show j 1 ch blank at fdis, five
    with Dissolve(1.0)
    play sound "music/fabric.ogg"
    stop music2 fadeout 2.5
    "Jun slowly stands up, looking down at me with a now empty expression."
    j "\"...\""
    mc 1 c worried "\"...\""
    "Please... anything."
    "Move..."
    j 1 ch considerate "\"Yeah... this is about what I expected anyway...\""
    "I feel as if I were watching my own body from far away."
    "As if I were looking at the person right in front of me from someone else's eyes."
    "No matter how much I try to will myself, my body absolutely refuses to respond."
    "It just stands there... frozen in shock... uselessly."
    j 1 ch wry "\"... Please forget I ever said anything, okay?\""
    "No..."
    "Asking me to forget is a little..."
    "Impossible."
    show j 1 ch wry at fdis, offscreenright with moveoridis
    "Jun slowly walks away."
    "Inside my mind I scream at myself to do something. Anything."
    "But my body remains completely still."
    "I... I don't even know what I want to do..."
    "What should I even say?"
    "That... that's too much..."
    "So out of the blue, it's too much..."
    "I can't... I don't understand..."
    play sound "music/metaldoor.ogg"
    "I hear the sound of a door closing from far away but I still don't turn to look."
    "What do I..."
    "How do I respond?"
    "Is it too late to respond?"
    "... What am I doing?"
    "Why am I feeling so conflicted?"
    "Why don't I know what I want?"
    stop music
    scene Black with fade
    "At some point, I become aware that my mind has completely shut down."
    play sound "music/footsteps concrete.ogg"
    "I can hear the sound of steps..."
    "Somehow I know they're mine but I'm not even aware of when I started to walk."
    "My body just began moving on its own at some point."
    play sound "music/door.ogg"
    scene BedroomN with fade
    "By the time I realize it, I'm back in my room."
    "When did I get here?"
    "And why?"
    play sound "music/phonebeep.ogg"
    "Once I notice lucidity has come back to me, I grab my phone and immediately type up a message to Jun."
    "I... I don't even know what I want to say."
    "Do I... feel the same?"
    "How can he just expect me to come up with an answer to something like that on the spot?!"
    "Don't just... don't just drop something like this on me suddenly you idiot!"
    play sound "music/tableknock.ogg"
    "The sound of metal and glass cracking echoes across the air."
    "I didn't even notice it at first."
    "My phone is lying on the floor on the other side of the room, burst open at the center and with the glass cracked into a million pieces."
    "I... did I throw it?"
    "... Why?"
    play sound "music/fabric.ogg"
    "I sit down at the bed, staring at my own hands in a daze."
    "My mind isn't working right..."
    "I don't even know why I'm so annoyed, I just know that I am."
    "... I need to talk to Jun, but..."
    "I probably shouldn't drop by his house right now."
    "... And tomorrow we don't have class either."
    "I'll try to drop by his house tomorrow morning anyway."
    "Not like I can message him now with the mangled mess on the corner..."
    "I grab a pillow, falling back onto my bed and burying my face in it, groaning in frustration."
    "Why am I such an indecisive idiot?!"
    "... I need to think things over."
    "That was... that was definitely a confession..."
    "I need time to figure out how I feel about it."
    "Part of me definitely wants to say yes, but..."
    "There's this little part of my brain that keeps screaming at me."
    "It tells me that if I do, I'll just end up hurting Jun the same way I hurt the girls I dated."
    "... I don't want that."
    "I... I don't want to hurt him."
    "If I had to see him sad or crying, I don't think my heart would be able to take it..."
    "Instead, I roll over on the bed. As my body begins to relax being someplace familiar, my mind begins to settle down."
    "And I crash..."
    $ date = None
    jump Day20_Jun
