label Day20_Shoichi:
    window hide
    scene May31 with fade
    play sound "music/windchimes.ogg"
    show blossoms movie
    $ renpy.pause(5.5)
    play music "music/crowd01.ogg" fadein 5.0
    scene SCorridor with fade
    window show
    $ date = "day20"
    "Clerk" "\"Come back again!\""
    play sound "music/slidingdoor.ogg"
    play music2 "music/BGM/Bright Wish.ogg" fadein 5.0
    "One of the students in class 1-A waves at me as I leave their attraction, a big goofy smile on his face."
    "I have to admit, there are quite a few interesting displays set up this year."
    "Class 1-A set up a dramatized retelling of the legend of the old gods Izanagi and Izanami."
    "The story itself is a pretty well-known myth but the acting and the lighting effects were very good, I was drawn to it the whole time."
    "Certainly beats the weird version of Romeo and Juliet that I watched yesterday, that's for sure."
    "Still... I look down at my phone, part of me is pleading for the day to end already."
    "Even though I've been trying to distract myself, I've had something gnawing on me since the weekend."
    "Shoichi and I barely spoke at all since then."
    "He hasn't had any free time since Monday which means I've been worrying about him without having any chance to check up on him."
    "And... well... I also kinda miss him."
    "I keep thinking about him whenever I'm alone and idle."
    "It's... kind of annoying to be honest. Now I keep worrying about him all the time, thinking about how his day went and wondering if he's doing well despite us barely talking."
    "Is this what falling for someone is like? It's never happened to me before so I don't know."
    "Besides, I'm just being silly. It's not like we don't talk at all."
    "We still message each other every day in the morning and right before bed, just like we used to before."
    "\"Good morning! Hope your day today is great. I'm gonna be a bit busy so I probably won't be able to hang out with you. Please have fun without me!\""
    "That was the text he sent me yesterday."
    "Yep. Not much has changed. Except for maybe..."
    "\"Good night, [povPetName], have sweet dreams. I love you <3\""
    "My cheeks feel a bit hot just reading this stuff again."
    "Shoichi, you dork, why do you have to be so sweet and dreamy all the time?!"
    "Ugh... it scares me just how quickly I'm getting attached to him in a whole different way than I was before."
    "The more time I have to adjust to these new feelings, the more strongly they come up."
    "If anything, now that I know they're there and what they are, it feels like they're resonating even stronger inside of me."
    "God, I sound so stupid and mushy even to myself."
    "I really need a distraction right now."
    mc "\"Hmm?\""
    "A figure at the corner of my eye catches my attention. I turn around to look and-"
    show h 1 c at fdis, five with dissolve
    mc 1 c "\"Haruki-kun?\""
    "I see the wolf's ears twitch when I call out his name and he turns around to face me."
    "Why did I even call him? His name just came out of my lips before I noticed it."
    h "\"Oh, it's you. What's with that look on your face? You lost or something?\""
    mc 1 c confused "\"...\""
    "Haruki raises an eyebrow, looking at me with just as much confusion as I'm feeling right now."
    h "\"What? Is there something on my face?\""
    "He... hasn't noticed it? Or maybe I'm just mistaken."
    "I think this is the first time he ever managed to greet me without insulting me."
    mc 1 c considerate "\"Nah, it's nothing. Sorry, I'm a bit out of it.\""
    "The change is so slight that I barely even notice it, but Haruki's body immediately shifts when I say so."
    "His shoulders quiver and slump a little bit, his eyebrows lie just a bit flatter and his tail lowers itself, almost going under his legs."
    h "\"Is everything okay?\""
    "Is he... concerned for me?"
    mc 1 c considerate "\"Yeah, I'm fine. I just have a lot on my mind. How are you doing?\""
    "The wolf shrugs, looking out the windows of the hallway and staring out at the masses in the courtyard down below."
    h "\"I'm alright, I guess. The entire volleyball team was pretty down after the match this weekend and with the 3rd years all retiring, the mood has gotten a bit weird. It doesn't help we can't use our courts either.\""
    mc 1 c worried "\"Yeah...\""
    "His eyes focus on me again. Once he sees the expression on my face, he mutters a curse word to himself."
    h "\"Erm, sorry, I shouldn't have brought that up. Is everything okay with the dog?\""
    mc 1 c worried "\"Beats me.\""
    h "\"Beats you? Aren't you his b-\""
    play sound "music/tap.ogg"
    show h 1 c at jumping, fdis
    "Before he can finish his sentence, I wrap my hands around his muzzle, forcing them shut."
    "I can hear a stifled yelp and the wolf jumps away from me."
    stop music fadeout 2.5
    h "\"Ow ow ow, what's the big idea?!\""
    "A little tear forms around the corner of his left eye and he pokes his tongue a few times, wincing in pain."
    mc 1 c talk "\"Are you okay?\""
    h "\"No I'm not okay, you just closed my teeth on my tongue!\""
    mc 1 c considerate "\"Hehe, sorry. It's just... we're in public.\""
    "The wolf freezes."
    "After a few seconds frozen still, he turns around mechanically to see quite a few people stopped on the hallway with their eyes stuck on him."
    h "\"Ah... Sorry.\""
    "He mutters a quick apology to the crowd that stares at us and then turns away from them again."
    mc 1 c smile "\"Heh. Aren't you well behaved today?\""
    h "\"Shut up, dork.\""
    "Oh, ouch. Careful, you might end up cutting someone with all this sharp wit."
    h "\"To get back to what I was asking. Is everything alright with the dog? I haven't seen him since Sunday. He usually doesn't leave me alone for this long.\""
    mc 1 c talk "\"I didn't know you guys used to hang out.\""
    h "\"We didn't. I mean he's always hounding me to go to practice and to be nicer to our teammates and blah blah blah. Also, you're trying to dodge my question.\""
    mc 1 c considerate "\"Oh. You noticed, huh?\""
    h "\"I might not be the brightest guy out there but I'm not stupid either.\""
    mc 1 c worried "\"... To be honest, I'm not too sure. Shoichi and I hung out with the others for a bit on Monday but it was just a little while. We haven't really talked at all outside of that.\""
    h "\"Oh. You think he's trying to avoid you cause he doesn't want to worry you?\""
    mc 1 c sigh "\"... I do now!\""
    h "\"Oh... sorry.\""
    "He lifts a hand in the air as he apologizes, although his face remains completely neutral and unfazed."
    mc 1 c sigh3 "\"I think I liked it better when you were insulting me instead of trying to be helpful...\""
    h "\"Huh? What do you mean?\""
    mc 1 c sigh3 "\"Never mind.\""
    "Yup, totally unaware."
    mc 1 c worried "\"What about you? Are you okay considering the loss on Sunday?\""
    "Haruki shrugs, looking none the worse for wear all things considering."
    h "\"It doesn't hurt me as bad since I've barely even become part of this team. Besides, this isn't my last year and I never really played with the seniors so them leaving doesn't affect me much.\""
    mc 1 c considerate "\"I guess that's true.\""
    h "\"But... it's still a bit frustrating to have lost after I finally got to play...\""
    "He clenches his fist. Haruki's lips press together so tightly that they become a single thin line."
    mc 1 c wry "\"I see. I'm glad.\""
    h "\"You're glad I'm feeling frustrated? You're kind of an ass aren't you?\""
    mc 1 c considerate "\"I don't mean it like that. Just that... I'm glad even you can feel frustrated about losing.\""
    "The wolf puts a hand on the window sill, looking out at the courtyard once again."
    h "\"I guess...\""
    mc 1 c considerate "\"Hey, I have nothing better to do right now. Do you want to come with me someplace quieter so we can just talk? I kinda want some company.\""
    "He raises an eyebrow, looking me up and down with suspicion."
    h "\"... Sure?\""
    "You don't have to look at me like that, I'm not plotting anything..."
    stop music2 fadeout 2.5
    scene MusicRoom
    show h 1 c at fdis, five with dissolve
    with fade
    play sound "music/slidingdoor.ogg"
    "..."
    "The white wolf takes a look around the empty room, whistling once he looks over all massive inside instruments."
    h "\"I'm surprised they didn't empty out this room for the festival.\""
    mc 1 c talk "\"There's a lot of old, expensive stuff here. They didn't want to risk moving them. Or at least that's what Jun said.\""
    h "\"Jun? Is he that squirelly little tiger that was with you guys on Saturday? I think that was his name anyway.\""
    mc 1 c considerate "\"Yeah, that's him. {size=-2}Although I'm pretty sure he wouldn't like being called squirrely.{/size}\""
    h "\"Well, was there anything you wanted?\""
    play music3 "music/BGM/Spring Classroom.ogg" fadein 5.0
    mc 1 c wry "\"Not really. I just thought we could talk for a bit.\""
    "He crosses his arms, looking at me with a raised eyebrow."
    h "\"Really? We barely know each other and all of a sudden you want to talk? What, did you run out of friends so you decided to go for the next best thing to keep you company?\""
    mc 1 c considerate "\"You talk too much.\""
    h "\"Isn't that exactly why you wanted me to come here?\""
    mc 1 c considerate "\"Fair.\""
    "He cocks his head to the side, looking me over with puckered lips."
    h "\"Is... everything alright? You're acting strange.\""
    "So are you. Since when are you so... nice?"
    mc 1 c worried "\"I've been trying to stay distracted but I'm a little worried about Shoichi.\""
    h "\"You said you hung out with him on Monday, didn't you? Did it look like there was something wrong?\""
    mc 1 c "\"No.\""
    h "\"He didn't look upset or worried or anything?\""
    mc 1 c sigh3 "\"No. He seemed totally fine and energetic.\""
    "Haruki raises an eyebrow."
    h "\"So what's the problem?\""
    mc 1 c sigh "\"Can't you see? He looked totally fine. That's the problem!\""
    h "\"...\""
    mc 1 c sigh2 "\"Don't look at me like that. I'm not crazy!\""
    h "\"You're certainly not helping your case any.\""
    mc 1 c worried "\"It's just... I can't shake this feeling that he's hiding something. I mean... God, he's always been the type to stay silent when he's hurting because he doesn't want to bother others.\""
    h "\"That sounds like a royal pain in the ass. Must be all too familiar to you by now too.\""
    mc 1 c sigh "\"... Was that... was that a gay joke?\""
    h 1 c smile "\"Yes. I'm particularly proud of that one.\""
    mc 1 c sigh3 "\"... Why did I want to talk to you again?\""
    h 1 c "\"Beats me. I was asking myself the same thing.\""
    mc 1 c worried "\"I... I just want to get my mind off of it. I want to be able to enjoy myself instead of just worrying about how he's feeling.\""
    h "\"You shouldn't worry so much. I'm sure he's fine. He probably didn't say anything because there's nothing to say.\""
    mc 1 c avoid "\"But you can't know that!\""
    h "\"Well... if there was he probably would have told you about it by now.\""
    mc 1 c sigh3 "\"But I already told you, he's the type to keep things in.\""
    h "\"You know what, you're right. He's probably destroyed right now. Actually, if you strain your ears a little bit, you can hear the sound of him sobbing uncontrollably over his broken heart.\""
    mc 1 c sigh "\"... Why are you making it worse?\""
    h "\"Hey, I tried to make it better, you kept fighting me over it.\""
    mc 1 c sigh3 "\"Point taken...\""
    play sound "music/chairscoot.ogg"
    "Haruki pulls a chair and takes a seat, sighing as he looks up at me."
    h "\"Listen, I don't know why you thought I would be good company when you're like this. I'm not good at dealing with emotional people. I can insult you a few times if you want. That I'm good at.\""
    mc 1 c sigh3 "\"It's fine. I think I just need to have a normal conversation without worrying that others are worried about me.\""
    h "\"Then I guess you've come to the right person. I don't give two shits about you.\""
    mc 1 c sigh "\"... I know what I just said was basically asking for it but you still could have said that in a nicer way.\""
    "He shrugs."
    h "\"Could've. Should've. Didn't.\""
    mc 1 c sigh "\"You're such an ass sometimes.\""
    h "\"Well, {i}you{/i} would know about asses wouldn't you.\""
    mc 1 c sigh3 "\"Was that another gay joke?\""
    h "\"Yes. I've got a bunch written down. Want to see?\""
    mc 1 c laugh "\"Pffft, no I don't want to see, you weirdo.\""
    h 1 c smile "\"Oh, finally there's a smile.\""
    mc 1 c smile "\"So that's your strategy? Antagonize me until I laugh?\""
    h "\"Nah. Antagonizing you was just supposed to be fun for me. You laughing is an unfortunate side effect.\""
    mc 1 c considerate "\"Sure.\""
    mc 1 c smile "\"By the way, did your little brother come over to see the festival?\""
    h "\"Taro? Not really. He's really busy studying. He's not exactly doing well at school. Why the sudden shift to my brother though?\""
    mc 1 c happy "\"I just remembered you two seemed to be really close when I met him so I was curious.\""
    h "\"Nah, he's an antagonistic little shit. He'll be the death of me one of these days. Your brother is much cuter.\""
    mc 1 c considerate "\"You just say that because he's polite to strangers. He's a nightmare for me to deal with also.\""
    h "\"Is that so? Huh. Would never have thought of it.\""
    mc 1 c smile "\"You know, I was pretty surprised to see your softer side. It was nice.\""
    "Haruki crosses his arms, leaning back on his chair and shooting me an unfriendly glare, with furrowed eyebrows and bared fangs."
    h "\"Soft? I'm not soft. That's for mushy people.\""
    mc 1 c confused "\"Mushy people?\""
    h "\"Yeah. The kind that are all \"woe my feelings\" and whatnot. Blegh, makes me sick just thinking about it.\""
    mc 1 c sigh3 "\"You have issues, dude.\""
    h "\"Don't we all?\""
    mc 1 c smile "\"Now that's a little too negative for my liking.\""
    "The wolf shrugs."
    "He seems to like shrugging quite a lot. I've already lost count how many times he did it today."
    h "\"What about your brother? Did he come over to check on the festival?\""
    mc 1 c "\"Nah. He's not very interested in school festivals and he'd rather spend his time studying and practicing.\""
    h "\"Practicing? Does he also play tennis like you?\""
    mc 1 c smile "\"Yeah. He's pretty good too.\""
    h "\"What's his rank? Do they even have ranks for children leagues?\""
    mc 1 c "\"Right now he's ranked 45th in the country in the U-14 league.\""
    h "\"Oh... That's not very high.\""
    mc 1 c considerate "\"He still has a way to go but he's very spirited.\""
    h "\"It must be pretty hard for him to compete like that.\""
    mc 1 c "\"What do you mean?\""
    h "\"A brother that is famous in all of Japan for playing the same sport, considered one of the most talented players to ever come out of the country... and he's barely in the top 50. He probably gets compared to you a lot.\""
    mc 1 c worried "\"Oh... I never thought of that.\""
    "Haruki raises an eyebrow, putting a hand on his waist and looking at me funny."
    h "\"With all due offense, you're an idiot.\""
    mc 1 c sigh "\"All due offense?\""
    h "\"Yes. I meant that I knew what I was saying could be read as being offensive and that's what I wanted to do.\""
    mc 1 c sigh "\"You're a jerk.\""
    h 1 c smile "\"Thank you.\""
    mc 1 c sigh3 "\"Seriously, why did I ever decide to talk to you?\""
    h "\"I don't know. Hope it wasn't because you wanted to come onto me.\""
    mc 1 c "\"Yeah no. You're quite a catch, I'm sure, but I already have a boyfriend.\""
    h 1 c "\"Aww, are you sure? I was looking forward to rejecting you. It would have been fun.\""
    mc 1 c fsmile "\"I can't tell whether you're joking or not and that worries me a little bit.\""
    h 1 c smile "\"Jeez, relax. I'm mostly joking.\""
    "... Mostly?"
    "This dude really scares me sometimes."
    h 1 c "\"Speaking of homo, how goes it with you and the big gay dog? You two looked awfully chummy on Saturday.\""
    mc 1 c sigh "\"... \"Speaking of homo\"? \"Big gay dog\"? Where the hell are you getting these phrases?\""
    h 1 c smile "\"Hey, it's really dull around here. I have to amuse myself in any way I can.\""
    "I feel like the nicer he becomes to me, the less offensive his insults become and they turn more and more ridiculous instead."
    mc 1 c sigh3 "\"Well, regardless, it's hardly any of your business how things are going between the two of us. It's bad enough you know we're dating.\""
    h 1 c "\"Oh come on. I'm part of the reason you two even hooked up in the first place. At least satisfy my curiosity.\""
    mc 1 c sigh "\"Why are you even curious about that of all things?\""
    "Haruki shrugs."
    h "\"I have very few friends. Not much to talk about. Come on, spill.\""
    mc 1 c flustered "\"T-there's not much to tell. We just k-kissed a few times. And maybe hugged for a bit.\""
    h "\"That's it? Wow you guys are boring. I thought you two would have fucked by now.\""
    mc 1 c sigh3 "\"I object to this entire conversation.\""
    h "\"Oh please, you already have a reputation as a playboy here. I know you've dated a ton before. You expect me to believe you're some kind of bashful virgin? Gimme a break.\""
    mc 1 c flustered "\"That is hardly-\""
    h "\"Hardly any of my business, yeah, got it. No need to parrot it back to me. I'm just saying, if I'd been dating someone for a week I'd have already sealed the deal.\""
    mc 1 c sigh3 "\"You're so crude...\""
    mc 1 c avoidb "\"Besides, it's not like... not like I'm bashful about sex or whatnot. It's just that...\""
    h 1 c smile "\"That?\""
    "He cocks his head to the side, a big grin on his face."
    mc 1 c wince "\"Seriously, why are we even talking about this?\""
    h "\"Because watching you squirm is fun. Come on, you've already said this much, might as well say the whole thing.\""
    mc 1 c sigh3 "\"No, I refuse. Absolutely not. Nuh uh. No way.\""
    h 1 c "\"Tch. What a bore.\""
    mc 1 c avoid "\"Better a bore than a boor.\""
    h "\"Oh ouch, my poor feelings. How will I ever recover from those painful words?\""
    mc 1 c sigh3 "\"Just... just shut up already.\""
    h 1 c smile "\"Heh. Sure thing, boss.\""
    mc 1 c wince "\"Eugh, don't call me that. I think I just felt a chill run up my spine.\""
    h 1 c "\"Alright. Whatever you say, fag.\""
    mc 1 c sigh3 "\"... Why do I bother?\""
    h 1 c smile "\"Beats me. If it makes you feel any better, very few people have gotten this far before.\""
    mc 1 c "\"Oh yeah? And what do they get to show for putting up with you so often?\""
    h "\"They have me to insult them on a daily basis.\""
    mc 1 c considerate "\"Wow. Some treasure.\""
    h "\"They seem to enjoy it at least.\""
    "Part of me is afraid of discovering who these people are but... then again, I do tease and mess with my friends all the time."
    "Guess I'm not one to talk."
    h 1 c "\"So what are you going to do now? Surely you don't plan on staying locked up in a room alone with me... and to be honest, even I wouldn't want to.\""
    mc 1 c sigh3 "\"Gee, thanks. Your presence is lovely too.\""
    h 1 c smile "\"Heh.\""
    mc 1 c wince "\"I dunno... I want to hang out with Shoichi but he's probably really busy today.\""
    "He didn't say anything about us meeting in his messages to me this morning so I'm assuming that's the case unless told underwise."
    h 1 c "\"Why can't you just be upfront and say \"Hey, I want us to spend time together\"?\""
    mc 1 c wince "\"I don't want to be clingy. He might get tired of me if I did that... I don't know if I want to risk it.\""
    h 1 c "\"Oh dear God, why does everything have to be so difficult with you? Are you this indecisive with everything?\""
    mc 1 c considerate "\"Pretty much.\""
    h 1 c "\"If I were in the dog's shoes, I'd get tired of this indecisiveness instead. Just go talk to him for pete's sake.\""
    mc 1 c wince "\"But what if he's really busy and still decides to take time off to be with me? Then I'd just be burdening him.\""
    h 1 c "\"He's your boyfriend, that's what he's there for. Just don't abuse it and you'll be fine.\""
    mc 1 c worried "\"But-\""
    stop music3 fadeout 2.5
    h 1 c "\"For crying out loud, just go already before I smack the ever loving shit out of you!\"" with hpunch
    mc 1 c shock "\"Waah, got it!\""
    h "\"Great. Go hunt your boyfriend around campus, it's his job to keep you entertained, not mine. Besides, I already have plans and I can't spend too much time here.\""
    mc 1 c sigh "\"{i}You{/i} have plans?\""
    h "\"I did just tell you also have friends. You don't have to sound so surprised.\""
    mc 1 c wince "\"I-I'm not surprised!\""
    h "\"Pfft, sure you're not. Anyway, I'm gonna leave now. Good luck with your relationship problems, loser.\""
    play sound "music/slidingdoor.ogg"
    show h 1 c at fdis, offscreenright with moveoridis
    "..."
    mc 1 c sigh3 "\"Might as well...\""
    play sound "music/slidingdoor.ogg"
    scene SCorridor with fade
    "..."
    "I've been standing in front of this door for the past two minutes without having the courage to knock."
    "I can't hear any voices on the inside so I assume that if Shoichi's here, at least he's alone."
    "... Or maybe the room just has better sound insulation than I thought."
    "Ugh, why am I getting so nervous over small things? Just knock on the damn door and be done with it."
    "..."
    "Alright, here I go..."
    play sound "music/knock.ogg"
    "I timidly knock on the door."
    "For some reason my heart is racing a little bit."
    "God, I really hope I don't end up becoming a bother. That's the last thing I want right now."
    "I can't hear any sounds on the other side for a few seconds."
    "Maybe the room is empty after all."
    "Just when I'm about to give up, I hear the sound of the door unlocking from the inside."
    play sound "music/slidingdoor.ogg"
    s 1 u "\"Who-\""
    show s 1 u shock at fdis, five
    show sguniform at fdis, five
    with dissolve
    "Shoichi opens the door, his eyes going wide when he seems me."
    s 1 u "\"[povPetName], what are you doing here?\""
    mc 1 c considerate "\"Oh... erm... hi. To be honest, I'm not quite sure myself, haha...\""
    s 1 u "\"Is everything okay?\""
    mc 1 c wince "\"Yeah, everything's pretty okay. I guess I just... I dunno, I missed you?\""
    show s 1 u shock at fdis
    $ renpy.pause(1.0)
    s 1 u smile "\"I see. I'm flattered to hear that.\""
    mc 1 c worried "\"Sorry to bother you. I know you're busy but I was... kinda hoping we could get some time to hang out together.\""
    s 1 u wince "\"W-well...\""
    show sguniform at fdis, seven
    show s 1 u wince at fdis, seven
    with move
    show hi 1 u smile at fdis, three with moveiledis
    hi "\"Ahh, [povFirstName]-san! I thought it was your voice I heard!\""
    mc 1 c shock "\"Wha- Hitoka-chan?!\""
    hi "\"Hi! What brings you here?\""
    mc 1 c wince "\"I-I could ask you the same question. You're not in the Student Council are you?\""
    hi "\"Well-{nw}\""
    s 1 u considerate "\"I'll explain it! If I leave it up to you you're probably gonna tell a really innacurate version that paints you as some kind of savior or something of the sorts.\""
    "Hitoka pouts, crossing her arms and huffing."
    s 1 u wry "\"A few of our senior members left the council to focus on studying for their entrance exams so we were short-staffed. We were taking volunteer help during the festival.\""
    hi "\"Yeah! So I volunteered to help him. Aren't I thoughtful?!\""
    s 1 u considerate "\"{size=-2}You just wanted an excuse to spend time chatting. You've barely done any work yet...{/size}\""
    mc 1 c worried "\"Why didn't you tell me? I would have offered to help.\""
    s 1 u smile "\"We're not constrained enough that I'd directly ask a friend of mine for help. Part of the reason I can work so hard on this is because I want you guys to have fun.\""
    s 1 u happy "\"Besides, while we are certainly a bit short-staffed, things aren't that bad.\""
    hi "\"He says \"a little\" but in reality he's the only senior left in the council. Over a third of the members left in the past two weeks alone because they couldn't handle studying and the workload of the festival.\""
    s 1 u shock "\"Hitoka! Don't tell him that.\""
    "... You dumbass."
    mc 1 c sigh3 "\"... What can I do to help?\""
    s 1 u wince "\"[povPetName], no! I don't want to burden you with this kind of thing.\""
    mc 1 c sigh "\"And I don't want to watch you working yourself to death. And don't even argue with me on that cause we both know you'd be capable of that. Besides, this might be the only way I get to spend time with you during the festival.\""
    s 1 u considerate "\"It's... it's not that bad. I was trying to rush through things so I'd get the last day free so w-{nw}\""
    play sound "music/fabric.ogg"
    "Hitoka wraps her arms around Shoichi's arm, smiling."
    hi "\"So we can spend the last day together, right? Sorry, [povFirstName]-kun but this is my only chance to spend a festival with Shoichi before he graduates. You understand, right?\""
    s 1 u shock "\"Wha- Don't just decide that kind of thing on your own. I was already thinking of making plans!\""
    hi "\"Whaaaat? But we haven't hung out together at all in months, even though you promised me during Dad's birthday party. Now you're gonna ditch me during the festival too?\""
    show s 1 u wince at fdis
    "Shoichi looks between the two of us nervously."
    s "\"I... I...\""
    "..."
    mc 1 c considerate "\"It's fine. Hitoka's right. This is her only chance to spend a festival with her brother as students of the same high school. You and I already had the past two years together. This is fine.\""
    s "\"But...\""
    hi "\"Alright! We should get back to work. We need to get all this crap done so we can actually have tomorrow free.\""
    hide hi 1 u smile with dissolve
    show sguniform at fdis, five
    show s 1 u wince at fdis, five
    with move
    "Bless her heart, she's totally clueless about us."
    "Man, I can't even imagine how she'd take the news if she found out."
    s 1 u sad "\"[povPetName], I... Why did you say that? I was planning to spend the last day of the festival with you.\""
    mc 1 c considerate "\"It's fine. Hitoka's your sister. She shouldn't have to be fighting with me for your attention.\""
    s "\"Yeah, she is, but... but you're also my... {size=-4}my boyfriend.{/size}\""
    "Shoichi whispers the last part of his sentence so his sister can't hear us inside."
    mc 1 c considerate "\"It's not like it's the end of the world. She doesn't know so she has no idea she's imposing.\""
    s 1 u wince "\"Y-yeah...\""
    mc 1 c worried "\"Is there no way you could get off for today so we could spend at least some time together?\""
    s "\"I don't think so. We need to have at least one official student council member in here to mediate any disputes between students. We're also working on a bunch of forms right now.\""
    mc 1 c "\"What type of forms?\""
    s "\"Complaints, suggestions, that kind of stuff. We get swarmed with them at the end of every day and it usually takes me a full day to get through them on my own.\""
    s 1 u sigh "\"Hitoka showed up saying she was going to help so I could \"go out and enjoy myself too\" but in the time it took me to go through twelve she has done... two.\""
    mc 1 c wince "\"Ouch. That's pretty slow. Or maybe you're just too fast?\""
    s 1 u considerate "\"Nah, she's just slow.\""
    hi 1 u smile "\"I can hear you!\""
    "Her voice echoes from inside the room."
    mc 1 c "\"But apparently a very good listener.\""
    s "\"Yup...\""
    mc 1 c talk "\"If I help, is there any chance you'd get done earlier?\""
    s 1 u think "\"Hmm... that depends. On my own it would still take me about six hours to finish, which would mean I'd finish at 7PM when the festival ends for the day.\""
    s 1 u "\"With Hitoka helping, maybe I could shave an hour off of that. It would honestly depend on how fast you're about to go through these forms.\""
    mc 1 c smile "\"Alright. My goal is to shave off at least three hours off of that timeframe then.\""
    s 1 u shock "\"What? That would mean you have to be going at the exact same pace as I am.\""
    mc 1 c smile "\"Hey, I can be pretty efficient if I set my mind to it. So long as you promise to spend time with me if I manage to do it.\""
    s "\"Y-yeah, of course. If I can spend time with you then I'll do it.\""
    mc 1 c happy "\"Great. Let's get to it!\""
    scene SCRoom
    show hi 1 u smile at fdis, three
    show s 1 u at fdis, seven
    show sguniform at fdis, seven
    with fade
    play music2 "music/BGM/Spring Classroom.ogg" fadein 5.0
    "As soon as I walk into the room, I see multiple piles of papers stacked loosely on top of the table."
    mc 1 c shock "\"Whoa, you weren't kidding when you said there are a lot of these.\""
    s 1 u considerate "\"Yeah. It wouldn't be much of a problem if we had a few people working on it as intended but as things are, it's kinda troublesome.\""
    mc 1 c "\"What about the volunteers? Couldn't they do the work?\""
    s 1 u "\"They have no idea how the council works. The only reason Hitoka can do these forms is because I'm here to tell her what to do whenever she has questions.\""
    hi "\"Hey, I've barely asked any questions!\""
    s 1 u sigh "\"Yes, and frankly that scares me a little bit because I'm afraid of all the errors I'm probably going to find once I go over the forms you worked on.\""
    hi "\"Hey!\""
    mc 1 c "\"Alright, what do you need me to do?\""
    s 1 u "\"The forms are pretty simple. Students fill in their information, the nature of their complaint or dispute and we have to write down what measure is taken about it. Then the forms are returned to the students.\""
    s "\"Before we can return them though, we need to make copies of them and then sign and stamp these copies for our own records. That's what most of the work here is going to be.\""
    s 1 u think "\"Oh, and just so we're clear, we've already taken measures about all of these. We just need to write things down in the forms and then file in the appropriate place.\""
    mc 1 c "\"Sounds to me like your issue lies with beaurocracy weighing you down instead of the workload being super huge.\""
    s 1 u considerate "\"You're... not entirely wrong. It didn't take me more than forty minutes to go through all these and decide what measures needed to be taken.\""
    s 1 u wry "\"That's what the other members of the council are doing right now. They're out putting those measures into play.\""
    mc 1 c wince "\"And that's supposed to take over six hours? How slow are you guys?\""
    s 1 u "\"The council isn't very big in the first place so we have around four members going around campus and mediating over a hundred disputes. Not to mention a lot of students refuse to accept our ruling so it takes a while to work with those.\""
    mc 1 c worried "\"Blegh. I'm glad I never joined the student council.\""
    s 1 u considerate "\"It's a good extracurricular for your student record though. It can help you get into a good college.\""
    mc 1 c "\"Totally useless for me.\""
    s 1 u wry "\"Yeah... I suppose.\""
    s 1 u think "\"Here. Since you said you'll do half of my stuff...\""
    "Shoichi walks up to the largest pile of paper that was set right in front of one of the empty seats and takes roughly half of them, setting them in front of his seat."
    s 1 u smile "\"Here. You can sit next to me. That way I can supervise you while you work.\""
    mc 1 c smile "\"Gotcha.\""
    "I pull up a chair and take my seat as he instructed, picking up and reading the forms in front of me."
    "Hitoka is sitting directly across from us on the table and she seems to be pretty absorbed in the stuff she's reading."
    hi "\"Here, Nii-chan, what was the resolution for this one form? It says here the sewing club filed against the pottery club for ruining a few of their textiles with clay.\""
    s 1 u "\"Yeah, I remember that one. The pottery club will have their annual budget slashed in an amount equal to the cost of materials to make said textiles as well as having to move their machines away from the sewing club's booth.\""
    mc 1 c sigh "\"This is the kind of stuff you get? Couldn't the students settle these issues themselves?\""
    s 1 u considerate "\"A lot of people don't like confrontation so they prefer to escalate issues to us without saying a word about it.\""
    mc 1 c sigh3 "\"That's a pain.\""
    s "\"Agreed.\""
    s 1 u think "\"Oh, by the way, the forms I'm handing you are the empty ones. I'm gonna have you make the copies for the council. If I have to keep interrupting myself to fill both of you into what to write down I'll never get work done.\""
    mc 1 c smile "\"That's fine.\""
    show s 1 u at fdis
    "I pick up a pen and start going over the forms."
    "They're... pretty thorough. Students need to fill out their full name, age, class, student ID number, student ID number of their club or class president if applicable, data on the person or club they are complaining about...\""
    play sound "music/disappointment.ogg"
    "That's a lot of stuff..."
    "No wonder these things take for fucking ever."
    hi "\"Oh, here's another one, Nii-chan. The cooking club has their kitchen right next to the chemistry club's lab and they said the smell of chemicals is so strong people are leaving their Masterclass in the middle of it.\""
    s 1 u think "\"Oh yeah, that one was tough. We had the chemistry club close all windows that are directly next to the cooking club's own windows so that the smell would leave only from the far side.\""
    s 1 u "\"Here's hoping none of those trapped fumes are the toxic kind.\""
    "I try to tune myself out of their semi-constant back and forth, trying to focus instead of copying these as fast as I can."
    "After a few minutes of this, I start to feel something on my leg."
    "At first it barely even registered, but then I realize that... Shoichi's hand is resting on top of my right leg and that he's stroking it idly."
    "When I look to the side, he has one hand under the table and another writing things down on his forms."
    "In fact, he's not even acknowledging what he's doing or that I'm looking at him."
    "And he's stroking me so slowly too, it's almost like he doesn't even realize he's doing it because he's so focused."
    "Although... while the feeling is very nice... it's kinda distracting for me."
    mc 1 c considerate "\"Uhm... Shoichi?\""
    s 1 u "\"Yeah? Do you need help with something?\""
    "Even when I call out to him, the hand remains there."
    "He either really doesn't notice what he's doing or he's very brazen about it."
    mc 1 c wince "\"U-uhm... t-this form here. I'm having trouble reading your handwriting. What's this word supposed to be?\""
    s 1 u think "\"Oh, sorry, I wrote these on a hurry.{nw}"
    show s 1 u at fdis
    extend " Let me see... It says \"equitable\".\""
    mc 1 c considerate "\"G-got it, thanks.\""
    "Ugh, I can't bring myself to call his attention to it."
    "Even though it's distracting I... like it."
    "I've always liked it when he would pet me or hug me, I just tried not to show it..."
    "I just hope Hitoka-chan doesn't notice it..."
    stop music2 fadeout 2.5
    scene SCRoom
    show hi 1 u smile at fdis, three
    show s 1 u at fdis, seven
    show sguniform at fdis, seven
    with fade
    show hours with dissolve
    $ renpy.pause(1.0)
    hide hours with dissolve
    s 1 u sigh "\"Oh man, I can't believe this... we actually managed to finish them in two hours.\""
    hi "\"See? I told you I could be helpful!\""
    s 1 u "\"Sure. Once you stopped goofing around and actually went at it at a reasonable pace.\""
    show hi 1 u smile at fdis, shake1
    play sound "music/stab.ogg"
    hi "\"G-guh...\""
    s 1 u smile "\"Well, with this I should be free for the rest of the day. And if luck would permit it, tomorrow.\""
    s 1 u laugh "\"Ahhhh, it's so good to be done with work!\""
    mc 1 c avoidb "\"Y-yeah. It's really great.\""
    s 1 u "\"Hm? What's the matter? You don't seem very excited.\""
    mc 1 c avoidb "\"O-oh, don't worry. I definitely am... {i}excited{/i}.\""
    s 1 u think "\"Huh?\""
    "..."
    "I still can't decide if he's just very good at playing clueless or if he really didn't notice it."
    "Over the past two hours he kept intermittently touching and stroking my leg."
    "A few times he even went up to my thigh."
    "... Other times he got dangerously close to my crotch."
    "It's a wonder I was able to work at all like this... but I do have a side-effect at the moment that I need to worry about."
    hi "\"Since we're free, how about we go out and do something together?!\""
    s 1 u considerate "\"Sorry, Hitoka. I'm definitely gonna go out with you tomorrow but at least let me spend the rest of the day with [povFirstName].\""
    hi "\"Boo, you guys already hang out together all the time!\""
    s 1 u sigh "\"Yeah but this will be our last festival together before he moves out of the country entirely. Come on, don't be so unreasonable.\""
    "Hitoka sighs, crossing her arms and leaning back on her chair."
    hi "\"Fine fine. If it means that much to you. But you're not escaping me tomorrow, do you hear me?\""
    s 1 u considerate "\"Loud and clear.\""
    hi "\"Okay. I'll see you boys tomorrow. I'm gonna see if my friend's display still has any openings.\""
    s 1 u happy "\"Gotcha. Have fun.\""
    hi "\"Bye bye! Bye, [povFirstName]-kun!\""
    play sound "music/slidingdoor.ogg"
    show hi 1 u smile at offscreenright with moveoridis
    show s 1 u smile at fdis, five
    show sguniform at fdis, five
    with move
    "She blows me a kiss as she walks up to the door, not even giving me a chance to respond."
    mc 1 c considerate "\"She's... as energetic as usual I see.\""
    s 1 u considerate "\"Yeah. And just as pushy too...\""
    s 1 u smile "\"Hey, how about we go look for something to do? I didn't expect to have alone time together this week but I'm definitely not going to waste it.\""
    mc 1 c flustered "\"Uhm... I think I need a minute first.\""
    s "\"Hm? Did something happen?\""
    mc 1 c considerate "\"Erm... you didn't notice what you were doing? I have a hard time believing it.\""
    s 1 u "\"What I was doing?\""
    mc 1 c wince "\"Erm... touching me under the table.\""
    s 1 u smile "\"Oh, that? I thought I was just giving you some encouragement.\""
    mc 1 c flustered "\"I knew it. You knew exactly what you were doing!\""
    s 1 u think "\"Well... no, not at first. I think I just started doing it out of habit and because I just wanted to do it so much I ended up doing it without noticing.\""
    s 1 u smile "\"But eventually I realized it and also noticed you didn't do anything about it so I tried to get a bit bolder. Does this mean I got a reaction out of you?\""
    mc 1 c avoid "\"You certainly got something reacting...\""
    s 1 u laugh "\"Oh wow. Hahaha, I didn't think that would happen. I swear I wasn't trying to. I was trying something a bit more risqué but still innocent.\""
    mc 1 c sigh3 "\"There's nothing innocent about what you were doing, perverted dog.\""
    s 1 u smile "\"Who's the real pervert? Me? Or the guy who got the boner?\""
    mc 1 c wince "\"I... erm... don't try to throw this on me!\""
    s 1 u happy "\"Hehe, it's alright.\""
    "Shoichi squeezes my thigh encouragingly and-"
    play sound "music/chairscoot.ogg"
    mc 1 c dismayb "\"Waah!\""
    show s 1 u smile at fdis
    "I jump back and onto my feet, the sudden shock I felt running up my spine made me move without even thinking."
    s 1 u think "\"Oh wow. That really is pretty noticeable. We should probably wait for it to calm down a bit before we even think of going outside.\""
    mc 1 c dismayb "\"Waaaaah!\"" with vpunch
    "I grab a few sheets of papers and hold them in front of my crotch to hide it from his eyes."
    s 1 u smile "\"Careful. You might poke a hole onto those with that thing.\""
    mc 1 c flustered "\"S-stop teasing me about it!\""
    s 1 u considerate "\"Oh come on. Is it really that embarrassing? I'm your boyfriend. Besides, you've already even touched mine. {size=-2}It was over my shorts but still.{/size}\""
    mc 1 c avoidb "\"I can't not feel awkward about it. I'm not used to showing myself off in front of you off all people.\""
    s 1 u think "\"I get being a little embarrassed. I mean, I have to admit I do feel a bit flustered right now with this whole situation but you don't have to freak out over it.\""
    mc 1 c sigh "\"You weren't exactly calm when you told me about yours either. In fact, you were red as a tomato!\""
    s 1 u smile "\"A bit. But after I did I realized it wasn't that big of a deal and it doesn't bother me much anymore.\""
    s 1 u wince "\"If anything, you being so coy and panicky over it is the thing getting me to freak out right now.\""
    mc 1 c avoidb "\"...\""
    s 1 u considerate "\"Oh, erm... It's not like I'm asking you to show it to me or anything. Just don't freak out so much about it.\""
    play music2 "music/BGM/There is Romance.ogg" fadein 5.0
    "I sit back down next to Shoichi, looking down at the table and feeling my face burning."
    s 1 u wry "\"Are you okay? I didn't mean to make you feel so self-conscious. I'm sorry.\""
    mc 1 c avoidb "\"I'm... fine. Just feeling a bit embarrassed.\""
    show s 1 u happy at fdis
    play sound "music/chu.ogg"
    "I feel something soft against my cheek, realizing a second late that I'd been kissed."
    s "\"Thanks for the help today. Now I get to actually have time to spend with you.\""
    mc 1 c avoidb "\"I hope I wasn't a bother.\""
    s "\"Not at all. You could never be a bother. I love you, [povPetName].\""
    "Shoichi grabs my hand, squeezing it tightly and nuzzling my cheek with his nose."
    s 1 u flattered "\"Hey... can I get a kiss?\""
    mc 1 c flustered "\"H-here?\""
    s 1 u smile "\"We're alone, aren't we? Why not? No one can see inside either.\""
    mc 1 c flustered "\"... Okay.\""
    s 1 u flattered "\"Hehe.\""
    play sound "music/chu.ogg"
    "Shoichi slowly leans into me. I close my eyes in anticipation of it."
    "I feel his lips touching against mine, very gently and slowly at first."
    "Once they come fully into contact with each other, Shoichi wraps an arm around my waist and pulls me in as close as he can given our positions on these two chairs."
    "Our lips smack against each other."
    "Shoichi teases my lower lip with the tip of his teeth, but still never does more than that."
    "The kiss doesn't last long and he soon pulls away from me, smiling from ear to ear."
    s "\"Oh man. I suddenly feel the energy to go the rest of the day without complaints.\""
    mc 1 c happyb "\"Yeah... it was pretty nice.\""
    "I didn't realize how much I wanted to kiss him until I just did."
    mc 1 c flustered "\"Shoichi... I want mo-{nw}\""
    stop music2
    play sound "music/slidingdoor.ogg"
    show s 1 u shock at fdis, five
    "SC Member" "\"Urata-san, I'm done for the day, do you need h-\""
    "A weasel walks into the room, looking at the table and seeing both Shoichi and I."
    "As soon as the door opened, the two of us jumped apart, looking nervously at the door."
    "SC Member" "\"Oh, did you actually get a volunteer to help you?\""
    s 1 u wince"\"Y-yeah. We actually finished all the paperwork a few minutes ago. You don't have to stick around.\""
    "SC Member" "\"Whoa, seriously? That was fast! I thought you said it would take you until the end of the day to do them.\""
    s "\"Y-yeah. But we had two volunteers to help and one of them was a really fast worker so I actually got things done in record time. Pretty neat, huh?\""
    "SC Member" "\"I'm gonna text the other members telling them work is done for the day once they finish their assignments. Everyone was talking about coming over if they got done early to help you.\""
    s "\"T-that's sweet of you guys. Thankfully everything is already done. Go on, you guys worked really hard to put the festival together. Just enjoy whatever you can of it.\""
    "SC Member" "\"Alright. See you next week, Pres!\""
    s "\"See yah.\""
    play sound "music/slidingdoor.ogg"
    "..."
    s 1 u considerate "\"Pretty safe to say the mood just...\""
    mc 1 c sigh3 "\"Tanked, yeah.\""
    s 1 u smile "\"Well, did you manage to calm down at least? If so, we can go do something together.\""
    mc 1 c sigh3 "\"Yeah. The shock took care of it pretty quickly. Do you have any plans for where we can go?\""
    s 1 u think "\"Well, I know what most of the displays and whatnot in the school are. I've been in charge of their paperwork after all.\""
    mc 1 c smile "\"Great. Anything fun or interesting?\""
    s 1 u happy "\"There are a few I wanted to visit. I didn't think I'd have the time to but it could work out.\""
    mc 1 c happy "\"Sure. Lead the way.\""
    s 1 u "\"Are you sure? Don't you have any places you'd like to go?\""
    mc 1 c smile "\"I've been roaming the festival on my own since day 1. I've already visited a lot of places. I'd like to just let you take the lead and have fun if that's alright.\""
    s 1 u smile "\"Heh. Certainly more than alright. I don't mind taking the lead.\""
    mc 1 c happy "\"Great. Where are we gonna go?\""
    s 1 u happy "\"Weeeell, the cooking club has a masterclass going on. It could be fun!\""
    mc 1 c fsmile "\"M-master class?\""
    "Oh no."
    s 1 u smile "\"Yeah. It's supposed to be taken in pairs but they teach you a lot of neat stuff. I thought it would be a fun thing for us to do together.\""
    mc 1 c fsmile "\"I-I see...\""
    "... My life is forfeit isn't it?"
    scene SCorridor
    show s 1 u smile at fdis, five
    with fade
    play music2 "music/BGM/The People Here.ogg" fadein 5.0
    "When we reach the cooking club's room, there are quite a few people hanging out outside the door and chatting as if they were waiting for something."
    "Shoichi took off his glasses before we left the student council room, which I found to be a bit of a pity."
    "He looks pretty handsome in those..."
    "A single girl is sitting on a chair next to the door with an apron and a clipboard."
    s "\"Hi, are you a member of the club?\""
    "The girl, a canary, smiles at us and nods, getting up from her seat."
    "Club Member" "\"Yes. Are you two here to sign up for our Masterclass?\""
    s 1 u happy "\"We are. Are there still any openings?\""
    "Club Member" "\"Only a few left for the class starting in ten minutes. We're cleaning the kitchen right now after the last class finished up.\""
    s 1 u smile "\"That's great. How much is the cost?\""
    "Club Member" "It's ¥4000 for the class. That covers the cost of materials, the cleaning after, etc. Will that be alright?\""
    s 1 u happy "\"Sure. No problem.\""
    "Shoichi pulls out his wallet and fishes out two ¥2000 bills."
    mc 1 c shock "\"Hang on. You're not paying all of it by yourself?\""
    s 1 u "\"Why not? It's no big deal.\""
    "The girl happily takes the money that was offered and puts it inside a small fanny pack she was carrying under he apron."
    "Club Member" "\"Alright, may I take your names please?\""
    s 1 u smile "\"Shoichi Urata and [povName].\""
    "Her smile widens and she nods at us energetically."
    "Club Member" "\"Oh, the student council president?! Thank you for dealing with our little issue with the chemistry club. It was driving us all insane.\""
    s 1 u happy "\"I didn't really do anything. It was the whole team.\""
    "Club Member" "\"Regardless, thank you so much. It's gotten a lot more pleasant after those fumes stopped invading our kitchen. Now, if you two could wait outside for a few minutes, you'll be called in shortly.\""
    s 1 u smile "\"Thank you.\""
    "We leave the girl be and lean against the far wall of the corridor."
    mc 1 c sigh3 "\"You really have to stop with this habit of trying to pay for everything.\""
    s 1 u "\"Hmm? I don't try to pay for {i}everything{/i}. Besides, what's wrong with me treating you? You're constantly pushing Jun-kun into let you pay for his stuff.\""
    mc 1 c sigh "\"Well that's different!\""
    s "\"Why?\""
    mc 1 c sigh "\"Because I- I mean we, {i}we{/i}- Erm, he- Don't try to change the subject!\""
    s 1 u considerate "\"Wow. Your skill with words rivals that of the bards of yore. Very moving speech indeed.\""
    mc 1 c sigh "\"Shut up.\""
    s 1 u smile "\"As thus commandeth, mine liege.\""
    mc 1 c sigh3 "\"Please don't try to imitate a bard's flowery speech now.\""
    s 1 u happy "\"Mimicry? How dareth thee slander this humble minstrel with thine foul lies?!\""
    mc 1 c sigh3 "\"I swear to God I'm going to ditch you. Also, I'm half convinced most of the stuff you're speaking is gibberish.\""
    s 1 u smile "\"It could be. I don't really know. Hell, I'm not even sure what I was saying.\""
    mc 1 c sigh3 "\"You're a dork.\""
    s 1 u happy "\"Sure am!\""
    "Shoichi leans closer to me, putting a hand on my shoulder and whispering into my ear."
    s "\"But I'm your dork so you should get used to it.\""
    play sound "music/heartbeat.ogg"
    "!"
    mc 1 c flustered "\"I-I see.\""
    "Club Member" "\"We're going to start with the next class. Will people please enter the room as I call out your names.\""
    scene SCooking
    show s 1 u smile at fdis, five
    with fade
    "Once we're inside, I get a good look at the kitchen."
    "I think the only time I'd been here before was when Class Rep borrowed the place so she could prepare her nasty concoctions during her pitch for the festival."
    "All the pans are shiny and neatly stacked. Every kitchen island has a supply of fresh produce, meats and all other kinds of products required to cook."
    "I'm surprised just how neat and organized this place is considering they apparently been hosting multiple cooking classes a day."
    "Whoever their president is, they must run a pretty tight ship so to speak."
    "Instructor" "\"Alright, I want every pair to man an island. Every island is fully equipped with an oven, gas burners and enough counter space for the duo to work on.\""
    "The instructor, a busty deer with a pair of round, pink-framed glasses wearing a laced apron, stands in front of the class. Her own counter is flipped from ours so she can access all its features while looking at us."
    "Instructor" "\"The lesson will last for three hours. During this time, you guys will learn to prepare a three course meal. Here are the dishes we'll teach you all to make.\""
    "She wastes no time in beginning her explanation. Grabbing her chef's knife, she pulls out a whole chicken and begins to carve it as she speaks."
    "Instructor" "\"First we will work on our chicken. We will extract from it all the meat we'll need for our appetizer and our entrée. Gripping your knife like this, you'll make an incision here and-\""
    "For what is worth, she is very thorough in her explanation."
    "She points out a few sheets on each of the counters containing the recipes we'll be preparing today."
    "Shoichi and I both put on a couple aprons that were provided to us by the cooking club."
    "Both are white aprons, very plain too. They don't have any flower patterns like the instructor's."
    s 1 u smile "\"Hey, you look pretty cute with that.\""
    mc 1 c smile "\"Heh. Thanks. How about you get started on that chicken?\""
    s 1 u think "\"Me? Alright then.\""
    "I leave Shoichi with the task of carving the meat - mostly because I'll work on the other stuff in the meantime and I doubt he can screw up carving a chicken carcass."
    mc 1 c talk "\"Let's see... wow, these dishes sound fancy.\""
    s 1 u "\"Yeah? What are we going to be preparing?\""
    mc 1 c talk "\"Let's focus on the appetizer first. A wild mushroom and chicken breast ragoût served on top of italian bread toast.\""
    s 1 u think "\"R-ragoo? What's that?\""
    mc 1 c "\"I've never made it before so I'm gonna be going into this blind too. It's supposed to be a really thick sauce that's usually paired up with pasta or bread.\""
    s 1 u smile "\"That sounds pretty nice.\""
    mc 1 c talk "\"Oh wait, according to the instructions we're gonna have to make fresh pasta dough for the entrée. Since that will need a few minutes to rest, I suppose I should get to it first.\""
    "Ugh... that means I'll have to leave Shoichi to do a bunch of stuff while I prepare the dough."
    mc 1 c worried "\"Okay... erm... I'll leave you to carve the chicken and slice the mushrooms and vegetables. Just make sure you stick to the recipe, okay? No fun little additions.\""
    s 1 u sigh "\"Aww. I was already thinking of ways I could spice this up and improve it.\""
    mc 1 c considerate "\"L-let's just stick to the recipes, okay? Besides, the ingredients we're provided are measured for these exact recipes. If you try to change them then something will have to go without.\""
    s 1 u think "\"Hmm... that's a fair point. I wouldn't want to ruin one recipe to make another one better.\""
    "... I think you mean you'd ruin two recipes."
    mc 1 c "\"I'll get to work on the pasta dough. Be careful with that knife.\""
    s 1 u smile "\"No problem. Have you ever made pasta dough before by the way?\""
    mc 1 c think "\"Erm... not really. This will be a first for me too.\""
    s 1 u happy "\"Hehe. Do try not to screw it up.\""
    "I don't want to hear that from you!"
    show s 1 u smile at fdis
    "Let's see... I need to measure out the ingredients here. It seems pretty simple. 100g of flour, 100g of semolina flour and 2 eggs. Pretty basic."
    "I'm surprised it doesn't call for any salt in the dough."
    "I guess that's because it'll already absorb salt while cooking in the water?"
    s 1 u "\"By the way, what's the pasta dough for? Are you gonna make spaghetti?\""
    mc 1 c "\"No. The entrée is supposed to be chicken alfredo with squash ravioli. Man, forming these is going to be a chore.\""
    s 1 u "\"Chicken alfredo with squash? We're just gonna be preparing western foods? I thought we'd do Japanese stuff.\""
    mc 1 c considerate "\"I don't think people would pay for a masterclass where they learn to cook stuff they already eat at home every day.\""
    s 1 u think "\"... Fair point.\""
    show s 1 u at fdis
    "I make a flour well inside the bowl and pour the two mixed eggs in the center, just like the recipe says to."
    "I don't think I've kneaded dough of any kind before so I'm a bit wary of dunking my hands in there."
    "I start off by mixing it with a wooden spoon until it forms a shaggy dough."
    "When it gets too hard to keep mixing it like this, I give up and decide to go by hand."
    "The feeling of it sticking to my fingers is certainly... weird."
    "The instructor goes over everyone's counters, checking up on their progress and giving them tips on what to do."
    "Instructor" "\"That's good. Don't be afraid to really get in there. Don't use your fingers so much, use the bottom part of your palm to gently push the dough down and away from you. Yeah, like that.\""
    "It's... actually much harder to knead it than I thought it would be."
    "It's not super difficult or anything but for something made out of just flour and eggs, I expected it to be soft like putty."
    s 1 u smile "\"I'm gonna get started on the mushrooms now.\""
    mc 1 c shock "\"You've already carved the chicken?\""
    s 1 u "\"It didn't take that long. It mostly came apart on its own.\""
    "... I look over at his station to check on his progress and."
    mc 1 c fsmile "\"That's... uhm...\""
    "Instead of getting clean pieces of meat out of it, he completely mangled and shredded the chicken."
    "There are even a few pieces of bone still protruding from the meat."
    mc 1 c wince "\"Did you even pay any attention to her explanation? Look at your chicken! It looks nothing like hers!\""
    s 1 u think "\"I mean, I didn't see the point in spending so much time to get nice looking pieces when we're gonna shred them anyway to use in the dishes.\""
    mc 1 c sigh3 "\"The point is that you're supposed to be learning a skill here.\""
    s 1 u smile "\"Meh, that's overrated. How often am I going to be carving a chicken in real life anyway?\""
    "... Why did you ask me to come here with you if you had no intent to do things right?"
    s 1 u think "\"By the way, what's the difference between a wild mushroom and a regular mushroom?\""
    "... I wonder."
    "I see he's obviously not even a bit interested in actually learning stuff..."
    "What if I... told a really ridiculous lie about it?"
    "... Would he buy it?"
    menu:
        "Lie":
            "Maybe..."
            mc 1 c happy "\"Oh. They're a special type of mushroom when ingested make your hormones go all wild. They're said to be a great aphrodisiac and also boost energy levels.\""
            s 1 u shock "\"W-wow, really? So are they used to make those market aphrodisiacs?\""
            mc 1 c smile "\"Oh yeah. The mushrooms are processed in factories and turned into liquid extracts. They add some of it into energy drinks too. It's why they're so good at keeping you energized.\""
            s 1 u shock "\"O-oh, wow.{nw}"
            show s 1 u avoidb at fdis
            extend " Wait, you think that's why I always get... a bit {i}excited{/i} after my games? Because of the mushrooms?\""
            mc 1 c happy "\"Could be. Some people are more susceptible to the effects than others. And since your heart is running really fast for a long time during those, the chemicals might travel your body much easier.\""
            s "\"Oh wow. Now it all makes sense...\""
            "Oh my God, I can't believe he's buying this!"
            "Shoichi, you're such a gullible dork, my God."
            s 1 u wince "\"U-uhm... be careful with how much you put in there. It would be awkward if we were both walking around with... you know.\""
            mc 1 c happy "\"Don't worry. I'll be mindful of it.\""
            s 1 u smile "\"Thanks.\""
        "Truth":
            "Nah, I shouldn't mess with him like that."
            "I don't think he'd be upset but if I give him false information and he believes it, he could end up parroting it back to someone and being embarrassed."
            mc 1 c "\"They're usually mushrooms foraged in the wild instead of grown specifically for sale. The kind you'd find in the woods or whatnot.\""
            s 1 u "\"Oh wow. I thought you weren't supposed to eat those. Aren't they poisonous?\""
            mc 1 c considerate "\"Some can be, which is why if you're foraging by yourself, you need to be super careful.\""
            mc 1 c smile "\"I'm pretty sure these were foraged by professionals and then sold to a market.\""
            s 1 u think "\"Then what's the difference from regular, store-bought mushrooms?\""
            mc 1 c considerate "\"Don't ask me. I've never used them before either.\""
            s 1 u "\"I thought you were really savvy on cooking stuff.\""
            mc 1 c sigh "\"That doesn't mean I know {i}everything{/i}.\""
    s 1 u "\"Alright, I need to get to chopping these.\""
    play sound "music/chopping.ogg"
    mc 1 c "\"Make sure you cut as much of the stems out as you can. You only really eat the cap.\""
    s 1 u think "\"Really? That sounds like a waste.\""
    mc 1 c considerate "\"With most mushrooms, the stem is very chewy and fibrous. Not very tasty and the texture is kinda bad.\""
    s 1 u wince "\"Oh. Yeah. Wouldn't want that. I'll make sure to cut them out.\""
    s 1 u "\"Oh hey, your dough is looking pretty good. It's really round and kinda shiny.\""
    "While we were talking I continued to knead the dough as best as I could."
    "It took me a while but it managed to all come together into a cohesive ball of dough, which I'm really proud of."
    mc 1 c smile "\"The recipe says to let it rest for thirty minutes before I can open it and fill it up. In the meantime, I'm gonna start on the ragôut since you already finished with the chicken and the mushrooms.\""
    s 1 u happy "\"Sure. Feel free to. Just tell me what to do next.\""
    mc 1 c "\"Can you chop the onions, shallots and garlic while I work on this?\""
    s 1 u smile "\"Happy to.\""
    play sound "music/grill.ogg"
    "I toss some butter and oil into the skillet, mixing in the mushrooms and making sure to sautée them slowly."
    "Mushrooms take a while to cook... or at least the regular supermarket variety. I don't know how long these take."
    "Well, at least the good thing is that overcooking mushrooms is very difficult to do."
    "I make sure to stir them constantly while adding a few more knobs of butter as I go to keep it from drying out."
    "Once I think they look about done, I add in the shredded chicken, the minced garlic and shallots, some red wine vinegar and some balsamic vinegar as well as salt and pepper."
    mc 1 c smile "\"Wow. That's a lot of cream that goes into this recipe.\""
    "Together with the alfredo... We're probably gonna have a heart attack from all this cream and butter."
    "Here's hoping we don't die from it."
    s 1 u happy "\"Oh wow, that smells really good.\""
    mc 1 c smile "\"Yeah. I'm supposed to cook it down until it gets thick and creamy. Oh, can you cut the bread onto slices so it can toast in the oven?\""
    s 1 u smile "\"Sure. I'll be done with the squash in just a bit.\""
    "Things have been... going much smoother than I thought they would."
    "Shoichi's being really well behaved, all things considered."
    "I thought for sure he'd be trying to sneak weird things into the food but he hasn't so much as a peep about it the whole time."
    "This is... really nice."
    "Cooking right next to him and working together."
    "It's relaxing."
    s 1 u "\"Wow, this bread is a bit stale.\""
    mc 1 c think "\"Some people believe stale bread makes for better toast. I think they're both the same, and if the bread gets {i}too{/i} stale then it just becomes unsalvageable.\""
    s "\"Why does it get stale in the first place? Like, how does it work?\""
    menu:
        "Truth":
            mc 1 c "\"I don't know all the science behind it. For the most part, it just loses moisture as it ages which causes it to become hard.\""
            mc 1 c smile "\"By the way, a neat trick you can use to make bread good again if it's only one or two days old is to wet all of it just a little bit under a faucet and then put it into the oven for ten to fifteen minutes.\""
            s 1 u "\"That actually works?\""
            mc 1 c happy "\"Yeah. It rehydrates the bread and softens it up at the same time as it becomes warm. When you pull it out of the oven it should be dry and steaming when you cut it.\""
            mc 1 c smile "\"You'll just need to flip it around in the oven once or twice but it definitely works.\""
            s 1 u think "\"Huh. I can use it in the future then. We throw a lot of bread out in the house because some days dad just doesn't feel like eating it.\""
            mc 1 c smile "\"Yeah. It's a good way to get that steaming hot loaf of bread like if you'd just bought it from the baker too.\""
            s 1 u happy "\"Man, that does sound good.\""
        "Lie":
            mc 1 c happy "\"Oh, it's pretty simple actually. Bread is made with yeast, right? Well, as the bread gets older, the yeast inside of it grows and starts sucking up all the water inside.\""
            s 1 u shock "\"Really?\""
            mc 1 c smile "\"Sometimes you open those old loaves of bread and you see huge holes inside, right?\""
            s 1 u "\"Yeah.\""
            mc 1 c happy "\"That's the area the yeast already ate. It leaves those big holes inside because it ate the bread from the inside out. And once it grows enough, it starts to change color.\""
            mc 1 c happy "\"That's also why the bread gets moldy.\""
            s 1 u wince "\"Ewww! I've had bread like that before. Hell, I've had bread come straight from the bakery like that!\""
            mc 1 c happy "\"Oh, that happens when they reheat old bread so they can resell it!\""
            s 1 u sigh "\"... I don't think I'll ever be able to eat bread again.\""
            mc 1 c smile "\"Don't let this discourage you. Just make sure to only pick from reputable stores.\""
            s 1 u sigh "\"I'm really scared about this bread we're supposed to be working with now.\""
            mc 1 c happy "\"Hehehe.\""
    s 1 u "\"Alright, I'm putting the slices in the oven now. Hopefully it doesn't burn.\""
    mc 1 c smile "\"There's a timer right here on top of the table. Just use that.\""
    s 1 u smile "\"Oh, good idea.\""
    mc 1 c smile "\"The ragôut should be ready in a few minutes. Can you keep stirring this while I start working on the filling for the ravioli?\""
    s 1 u "\"How come I'm only in charge of prepping and stirring stuff? I want to actually do some cooking too.\""
    mc 1 c considerate "\"O-oh, you do? T-that's...\""
    "uh oh..."
    s 1 u sigh "\"Come on, you're hogging all the fun parts. All the ingredients for the entrée are already prepped. I can cook it while you stir.\""
    mc 1 c fsmile "\"That's... an idea.\""
    s 1 u smile "\"Great. I'll get to work on it.\""
    "W-wait, I didn't say I agreed to it!"
    s 1 u "\"Let's see... it says here to cook the squash in a separate pan until it's soft. I can put that to boil on the side while I work on the rest.\""
    s 1 u smile "\"Huh. This alfredo sauce thing doesn't sound very difficult.\""
    mc 1 c considerate "\"Y-yeah. Just remember you need to cook it until it's a bit thick since it'll be used as filling. Can't be too runny in that situation.\""
    s 1 u think "\"Hmm... that's a fair point.\""
    play sound "music/grill.ogg"
    s 1 u smile "\"Already, I'll just cook the onions in the butter until they start getting golden.\""
    mc 1 c "\"I've mostly used breast meat for the ragôut. Since the raviolis are the main dish I thought they'd go better with the thigh meat. Just make sure to remove any and all pieces of bone once you shred it okay?\""
    s 1 u happy "\"Don't worry about me so much. I've got this!\""
    "... You have never given me any reason to believe you when you say that."
    "In fact, you being confident about it just scares me even more because I'm afraid you're gonna mess up because you're not paying enough attention to what you're doing."
    "Ugh... I suddenly feel a rumbling feeling on the pit of my stomach and it's not nice."
    "Shoichi diligently stirs and works on his skillet."
    "Since I'm trying to pay attention to my ragôut, I can't really keep an eye on him while he does that."
    "I'll just pray nothing goes wrong..."
    s 1 u "\"Hey, I have a technical question.\""
    mc 1 c "\"Yeah, what is it?\""
    s 1 u think "\"How do I know when the onion and butter are done?\""
    mc 1 c shock "\"Wait, you're still just stirring onion and butter together?!\""
    s 1 u "\"Yeah. It said here to stir until golden but the butter kept turning browner so I waited until it got golden.\""
    "I look over to his skillet and it's... a mess."
    play sound "music/disappointment.ogg"
    "Dear God, it even smells weird. How did you manage to do that?!"
    mc 1 c sigh "\"It's way overcooked. You burned the butter. Just put this in the sink and start again.\""
    s 1 u sad "\"Awww, really? I thought I was doing so well...\""
    mc 1 c sigh3 "\"Shoichi, if you're having questions, just call the instructor. She's doing rounds and helping people but she can't know you need help if you don't ask.\""
    s 1 u wince "\"I didn't think I needed help.\""
    "I'm really gonna have to babysit him through this process aren't I?"
    "At least if he manages to cook something edible I'll already be happy."
    "I think it'll be the first time ever."
    "Heh, the prospect is pretty exciting for sure."
    s 1 u sigh "\"Alright, I'm gonna chop another onion and I'll try this again.\""
    mc 1 c "\"This time remember. Only the {i}onion{/i} needs to turn golden. Not the butter.\""
    s 1 u considerate "\"Got it. I'll try not to mess up again, sorry.\""
    mc 1 c talk "\"I'm pretty much done with the ragôut. I'm gonna get started on the dessert.\""
    s 1 u "\"Oh yeah? What's the dessert supposed to be?\""
    mc 1 c talk "\"Says here that it's supposed to be an apple puff pastry turnover. Thank God they're providing us with the puff pastry cause that would be a bitch to make from scratch.\""
    s 1 u think "\"Is it really that bad?\""
    mc 1 c considerate "\"I don't bake all that {i}often{/i} but I did see a few videos on pastries and there were so many steps to making it my head was spinning.\""
    s 1 u wince "\"Yikes. Not good.\""
    mc 1 c smile "\"Yeah. I'll stick to store bought pastry for this. Just need to peel and chop the apples into chunks and then prepare a brown sugar syrup.\""
    s 1 u "\"Man, there is going to be so much food when we're done.\""
    mc 1 c happy "\"Isn't that kind of the point? Food is good after all!\""
    s 1 u smile "\"Hehe. I guess that's true. I'm looking forward to tasting it.\""
    mc 1 c considerate "\"Yeah. Just keep your eyes on what you're making. We don't need any more burned butter.\""
    s 1 u shock "\"Oh shit!\""
    "Yeah, he didn't even notice that his butter and onions were starting to get a bit overdone."
    "Baby steps I guess."
    s 1 u wince "\"Okay, I'm adding the other vegetables and the chicken now.\""
    mc 1 c smile "\"Careful. Don't just dunk stuff into the skillet otherwise some butter could splash off and scald you.\""
    s 1 u considerate "\"Right, right.\""
    "I think this is the first time he ever had someone supervising him while he cooks."
    "His knife skills aren't the best and he doesn't pay much attention to what he's doing... but both of those things can be remedied."
    "It's the unnecessary additions that fuck things over."
    "Since he's not allowed to do that here, we should hopefully get something edible."
    "And if not... well, he looks pretty cute when he's squirming trying to not mess up stuff on the burner."
    "Heh... I'm kinda getting the urge to tickle and tease him a little bit, but I'll avoid doing that while he's handling a hot pan."
    "It's weird... when I think of it... we're dating now."
    "Like... things haven't changed {i}that{/i} much but... when I look at him now, I feel different than before."
    "I'm not confused or conflicted over it anymore either."
    "At this point... I'm pretty sure that I really do have feelings for him."
    "Hell, he's such a dork, I want to kiss him so bad right now..."
    s 1 u "\"Are you okay? You've been staring at me without doing anything for a few minutes.\""
    mc 1 c shock "\"O-Oh, right! I was, erm, thinking of what I needed to prepare for the turnovers.\""
    s 1 u "\"Isn't your syrup done yet?\""
    mc 1 c wince "\"Let me check. Hopefully it's okay.\""
    "Yikes, and I was just giving him crap for not paying attention to his pots too."
    mc 1 c considerate "\"Yeah, it's fine. It's at the perfect consistency actually. I'm gonna drop my apples inside now with a bit of cinnamon.\""
    s 1 u smile "\"Recipe doesn't sound too complicated.\""
    mc 1 c smile "\"It's not. The complicated part will be stuffing the raviolis. We're gonna have to do them together.\""
    s 1 u happy "\"Sure!\""
    "I work on cooking the apples down a bit while I open the puff pastry and cut it into the shapes for the turnovers."
    "After that, it's not all that difficult. This pastry is pretty nice to work with and I can put them together pretty easily."
    mc 1 c smile "\"Okay, gonna put these in the oven to bake. Did you already get the toast out?\""
    s 1 u smile "\"Yeah, you're fine.\""
    "I put them all neatly on top of parchment paper and inside a baking tray and slide it inside the oven."
    "Thanks to the toast, the oven is already pre-heated too so that helps."
    mc 1 c talk "\"I'm gonna open the pasta dough now. How's the filling going?\""
    s 1 u smile "\"I just added the cooked squash to it. Can you taste to make sure the seasoning is okay?\""
    mc 1 c smile "\"Sure.\""
    "Shoichi grabs a spoon and puts a bit of everything from the filling on it, hovering it in front of my mouth."
    "I blow on it a few times so as to not scald my tongue before eating it."
    mc 1 c think "\"Hmm... a little bit more cheese would be nice.\""
    s 1 u happy "\"Alright. I'll add it in. As soon as it melts and incorporates we can get started on stuffing.\""
    mc 1 c considerate "\"Not so fast. You need to chill the filling a bit first otherwise you'd cook the pasta before even putting it in the boiling water.\""
    s 1 u think "\"Oh. That's true.\""
    mc 1 c smile "\"We still have about an hour and a forty minutes to spare so that gives us plenty of time to chill it while we plate the ragôut toast. Just make sure to let the filling cool down before you put it in the fridge.\""
    s 1 u happy "\"Got it!\""
    "I feed the pasta as thinly as I can on the pasta roller."
    "At one point it starts to get really thin and delicate so I need Shoichi's help handling it to avoid ripping."
    "It's a bit of work to get it through but it comes out fine."
    mc 1 c smile "\"Alright, just need to cut them into circles and cover them all with plastic film so it doesn't dry out.\""
    s 1 u happy "\"Handling the pasta dough is kinda like playing around with playdough.\""
    mc 1 c happy "\"You should have touched it when I was still kneading it. It really felt like playing with playdough, haha.\""
    s 1 u smile "\"What's our yield in this recipe?\""
    mc 1 c talk "\"I don't know the exact amount. We're cutting them sorta big so there can't be that many.\""
    "Still, we spread the dough so thin that it became quite long."
    "We ended up having to cut it into multiple sheets because it was getting too problematic to handle it."
    s 1 u happy "\"Let's get started on plating the appetizer. I can't wait to taste it.\""
    mc 1 c happy "\"Sure.\""
    "Our toast is very dry, golden and crunchy so it looks pretty nice."
    "I try to put the ragôut on top in a way that it doesn't look too messy."
    "I sprinkle a bit of grated parmesan cheese and finely chopped herbs to garnish."
    mc 1 c happy "\"This look pretty good!\""
    s 1 u smile "\"It looks pretty tasty. Should we call the instructor over to try?\""
    mc 1 c smile "\"Yeah. Looks like a few other pairs are finishing plating their appetizer too.\""
    s 1 u happy "\"The instructions were all made so we should finish right about now anyway.\""
    mc 1 c happy "\"Yeah but a few people are still lagging behind. My guess is those are the ones that either had to start over due to mistakes or are just slower because they don't have much experience.\""
    s 1 u considerate "\"I also had to start over at some point though.\""
    mc 1 c smile "\"Yeah but you only had to throw away butter and onion. Barely any time waste with that.\""
    s 1 u think "\"Hmm... fair enough.\""
    "I raise my hand, trying to get the attention of the instructor so she can come over and try our dish."
    "Instructor" "\"Oh, you boys are finished too? Let me try it out and see how you did.\""
    "She uses a fork and knife to cut a small piece, quickly putting it in her mouth."
    "Immediately she smiles, nodding appreciatively at the two of us."
    "Instructor" "\"This is very good. The seasoning is perfect and it's very creamy. Good job! How are you doing on the other two?\""
    mc 1 c smile "\"The turnovers are baking and we're waiting for the ravioli filling to cool a bit before we can stuff them.\""
    s 1 u considerate "\"I kinda messed up on the filling at first but he had me fix it.\""
    "She nods, smile still on her face."
    "Instructor" "\"That's very good. One tip I'll give you is that if you didn't leave big chunks in the filling, you can use a piping bag to fill it more precisely and making less of a mess.\""
    mc 1 c talk "\"Is that so? Shoichi, how chunky is the filling you made?\""
    s 1 u think "\"Hmm... I think it could fit in a piping bag? I'm not too sure.\""
    "Instructor" "\"You can also fill it with a regular spoon if you're not sure. It's just a tiny bit harder to be precise with it.\""
    mc 1 c smile "\"Thanks. I appreciate the advice.\""
    "She nods once again and walks off to another duo's station."
    s 1 u smile "\"I guess we just wait for the turnovers to bake and the filling to cool.\""
    mc 1 c happy "\"Pretty much. Hopefully it won't be long.\""
    stop music2 fadeout 2.5
    scene SCooking
    show s 1 u smile at fdis, five
    with fade
    show hour with dissolve
    $ renpy.pause(1.0)
    hide hour with dissolve
    mc 1 c smile "\"The raviolis seem to be done. Help me drain them and plate them up?\""
    s 1 u happy "\"Sure thing.\""
    "Thing continued going smoothly for the two of us."
    "With the class nearly coming to an end, we were rushing to plate up the last of our dishes."
    "I do have to congratulate Shoichi on that ravioli filling. I tried a bit of it before piping it into the pasta dough and the texture and flavor were pretty good."
    "Heh, I can't believe Shoichi of all people actually managed to cook something good."
    mc 1 c talk "\"Here, a bit of grated cheese on top for garnish.\""
    s 1 u "\"Shouldn't we add some kind of sauce to the outside too? It looks kinda dry.\""
    mc 1 c considerate "\"The sauce on the inside is already pretty creamy. You don't wanna drown the plate in sauce.\""
    s 1 u think "\"Hmm... if you say so.\""
    "Instructor" "\"We have three more minutes before the end of class. I'm going to start going through the stations that have already finished plating their last dishes to try them.\""
    "Good thing we're not super late otherwise I'd be freaking out hearing that countdown."
    "Thankfully we haven't had many hiccups during this process."
    show s 1 u smile at fdis
    mc 1 c happy "\"There. Done.\""
    s 1 u happy "\"Nice. With a bit of time to spare too.\""
    show s 1 u smile at fdis
    "Instructor" "\"Alright, let me see what you boys prepared.\""
    "She walks up to us and eyes our two last dishes."
    "Instructor" "\"I'll try the ravioli first. Oooh, the pasta is very tender and soft, cooked perfectly. The inside is pretty creamy, it even oozes out a little bit. That's good.\""
    "She cuts off a piece and tastes it."
    "Immediately her face lights up and she squeals quietly."
    "Instructor" "\"Oh yes, this is very good. Very creamy, the sauce is very rich, there is a good ratio of sauce to meat to squash inside the ravioli. Seems like they were distributed pretty uniformly.\""
    "Instructor" "\"I'll try the apple turnover now.\""
    "The pastry makes a lot of crunchy sounds as she cuts a piece, which seems to make her quite happy."
    "Instructor" "\"You hear this sound when I run my knife on top of the pastry? It's dried out and crunched up nicely. The color is also good, it's a very appealing golden brown. Let's see how it tastes.\""
    "She moves her head quite a bit as she's tasting. It seems like she's pondering something."
    "Instructor" "\"The flavor is pretty good. You did a bang up job on that. My only issue with it is the apples are a tad on the mushy side. I think you might have cooked them too long before stuffing the turnovers.\""
    show s 1 u at fdis
    mc 1 c wince "\"O-oh. I was the one who made the turnovers so it was my mistake.\""
    "Instructor" "\"Just keep in mind when making this sort of recipe that you want the apples to still have a bite to them {i}before{/i} you put them in the oven otherwise it'll become mush.\""
    mc 1 c considerate "\"Gotcha. Thanks.\""
    "She nods, walking away to taste the plates from the rest of the class."
    mc 1 c wince "\"Blegh, I messed up...\""
    s 1 u smile "\"Aww, don't feel bad. Everyone makes mistakes. Besides, it still looks delicious. Let's eat it before it gets cold.\""
    mc 1 c happy "\"Hehe. You're right. Let's.\""
    "We enjoy our food in the last few minutes of class."
    "Everything came out pretty amazing."
    "I think my favorite was the ravioli. That just tastes incredible."
    "I still can't believe Shoichi was the one who made this filling."
    "Although I will toot my own horn right here. The pasta is also really good."
    "Even the apple turnovers were just a {i}tiiiny{/i} little bit mushy. Not nearly as much as I thought they would be given the instructor's judgment."
    "But then again, even something pretty minor can stand out if everything else is done really well."
    s 1 u happy "\"Oh man, this is delicious.\""
    mc 1 c happyb "\"It is. I'm glad you decided to make us do this.\""
    s "\"So am I.\""
    s 1 u "\"Ah, [povLastName], you have a bit of syrup on your face. Hang on, I'll get it.\""
    "He grabs a napkin, gently rubbing it on my face to clean up the dirty spot."
    s 1 u smile "\"There. All better now.\""
    mc 1 c smile "\"Thanks.\""
    "We continue to enjoy our food until we finish every last piece."
    "Oh man, I'm definitely feeling a bit full now."
    "Instructor" "\"Thank you for coming today. I hope you enjoyed this class. If you did, please tell your friends about it. We'd really appreciate it!\""
    play music "music/night.ogg" fadein 5.0
    scene SGateN
    show s 1 u smile at fdis, five
    with fade
    s 1 u think "\"Oh man, it got really dark while we were in there.\""
    mc 1 c happy "\"We did spend three hours inside.\""
    s 1 u smile "\"Everything's already dying down for the day. I don't think there's much we could do here anymore.\""
    mc 1 c smile "\"Yeah, you're right. How about we just head home? Maybe you could stay over for a bit.\""
    s 1 u considerate "\"I would love to, but you have to remember I have a curfew now.\""
    mc 1 c worried "\"Oh... right.\""
    s 1 u smile "\"I can still walk you home.\""
    mc 1 c happyb "\"Hehe. Okay.\""
    play music2 "music/BGM/Recollections.ogg" fadein 5.0
    scene Street1N
    show s 1 u smile at fdis, five
    with fade
    "There's quite a lot of movement in the streets at this time of the night."
    "Probably because the school festival is a really popular event this time of year."
    "There is a cool breeze blowing, gently ruffling our furs as we walk together under the night sky."
    s "\"I hope you had fun today.\""
    "Shoichi breaks the peaceful silence we were in up until now."
    "When I look to the side, I see him eyeing me with a smile."
    mc 1 c smile "\"I did. I was really afraid of straining you by asking us to spend time together. I'm glad that wasn't the case.\""
    s 1 u happy "\"You're my boyfriend. Spending time with you is one of my favorite things to do.\""
    "He gently squeezes my hand for a second before pulling away once more."
    "He's probably wary of being too affectionate in the middle of the busy street."
    s 1 u smile "\"To be honest, it made me pretty happy to have you come to me today.\""
    mc 1 c talk "\"What do you mean?\""
    s 1 u considerate "\"Well... I always tend to be the one dragging you around everywhere. And after we started dating, part of me was really worried you weren't really liking it and was just afraid of saying something.\""
    s 1 u wry "\"I mean no offense by saying this, it's just that it had been your M.O. so far and it was hard for me to not think that was the case.\""
    mc 1 c worried "\"Oh...\""
    "I look down at the floor, focusing on my feet walking step by step."
    "For some reason, I suddenly feel very embarrassed."
    mc 1 c avoidb "\"I was... really upset for a while. It's really frustrating for me when I think about it. This is the first time in my life I've ever felt lost when it comes to how I'm feeling.\""
    mc 1 c avoidb "\"Before you confessed to me and we started dating, I thought that maybe I had feelings for you, but at the same time that... I wasn't sure?\""
    mc 1 c considerate "\"I've always liked spending time with you and once I thought that... maybe you liked me, a tiny little part of me was pretty happy.\""
    mc 1 c talk "\"I think I might have... always liked guys. And... might have just... I don't know. Refused to accept it? Bottled it up so much until even I couldn't notice it? It's confusing for me.\""
    s 1 u considerate "\"I don't blame you. I spent years telling myself my feelings for you were just friendship.{nw}"
    show s 1 u wry at fdis
    extend " It took a while for me to realize I was in love... and even longer to accept it.\""
    mc 1 c flustered "\"Yeah but... when I think about it. I really am happy getting to spend time with you like this. I... think I really do like you a lot. I guess I might have been liking you for a time now...\""
    s 1 u smile "\"Do you have any idea how long?\""
    mc 1 c wince "\"Uhm... I'm not sure. A bit under a month? Maybe more, maybe less? I just didn't notice it for a while.\""
    s 1 u happy "\"Hehe. I can take that.\""
    "Shoichi casually shoulder bumps me as we walk side by side down the street."
    "He giggles happily, and I can't help feeling that hearing him sound so happy is wonderful."
    "I feel butterflies in my stomach."
    mc 1 c flustered "\"I... man this is embarrassing to say. I... look forward to seeing how things will work out between us... and I want us two to become even closer. From now on... I'm in your care.\""
    s 1 u flattered "\"Hehe. I look forward to it too. And I promise I'll take care of you for as long as you're willing to also take care of me.\""
    mc 1 c happyb "\"... Yeah.\""
    scene HouseFrontN
    show s 1 u smile at fdis, five
    with fade
    "We finally reach my house, coming to a stop in front of the gate."
    s 1 u wry "\"Heh. Kinda wish you lived a little bit farther away.\""
    mc 1 c considerate "\"Yeah...\""
    "We stand motionless on our spots. Neither of us seeming to want to say bye."
    "Shoichi looks down at my eyes and I do the same."
    "I feel... happy just having him close by."
    "It's strange."
    "It all came so suddenly and I'm still confused by this whole thing, but..."
    "I'm happy."
    s 1 u considerate "\"I should probably head home already. Can't hang around here forever.\""
    mc 1 c smile "\"Yeah. Thanks for spending time with me today.\""
    s 1 u smile "\"It was my pleasure. I'm glad you had fun.\""
    show s 1 u flattered at fdis
    play sound "music/chu.ogg"
    "Shoichi leans towards me, giving me a quick peck on the lips."
    s 1 u smile "\"You be good, okay?\""
    mc 1 c happyb "\"Be good? What am I, a dog?\""
    s 1 u laugh "\"Well, technically you are.\""
    "I playfully punch him on the shoulder."
    s 1 u smile "\"Good night, [povPetName]. I'll message you when I get home.\""
    mc 1 c smile "\"You better. Bye bye.\""
    stop music2 fadeout 2.5
    show s 1 u smile at fdis, offscreenleft with moveoledis
    "I wave at Shoichi as he walks away, watching him take a turn and disappear from my sight."
    "Once he's gone, I go inside."
    stop music fadeout 2.5
    $ date = None
    jump Day21_Shoichi
