label Day21_Jun:
    window hide
    scene June4 with fade
    play sound "music/windchimes.ogg"
    show blossoms movie
    $ renpy.pause(5.5)
    scene JunHouse with fade
    window show
    play sound "music/knock.ogg"
    $ date = "day21"
    "..."
    "For the third time in three days, I find myself coming here uninvited."
    "Since I still haven't replaced my broken phone, I can't bring myself to try to contact Jun directly to ask to see him."
    "I did try asking Aki to message him for me but there was no response either."
    "When I dropped by yesterday, Yui-san told me Jun was out of the house since Friday and would only be back this morning."
    "To be honest, I felt the hairs on the back of my neck standing up when I heard that."
    "I don't know why but it left me feeling concerned."
    "I also couldn't quite explain to her why I decided to just drop by out of the blue so I couldn't ask her to give him a message for me."
    "So I did what any sane person would do..."
    "I showed up uninvited for the third time on a row."
    "Well... does it count as being uninvited if I told her the day before that I'd be coming?"
    "I did decide to come by after lunch. Both so I wouldn't be roped into joining them for lunch as that still has me feeling all kinds of awkward and so I wouldn't disturb Jun right after he got home from wherever it is he was."
    play sound "music/slidingdoor.ogg"
    "Finally, I hear the sound of someone scurrying behind the door before it unlocks and slides open."
    show yui 1 c smile at fdis, five with dissolve
    "I hold my breath as the door opened, only to exhale in disappointment when I see Yui-san's figure again."
    "Why was I disappointed? Frankly, even I couldn't tell."
    yui "\"[povFirstName]-san, it's good to see you again.\""
    mc 1 c considerate "\"Erm... Good afternoon. I'm sorry to disturb you again. Is Jun home this time?\""
    "The tigress nods, smiling warmly at me."
    yui "\"It's no problem, honey. Jun got home a few hours ago. He's mostly kept to his room though. I did tell him you'd be dropping by. He asked me to let you in when you did.\""
    mc 1 c smile "\"I appreciate it. Thank you for the help. My phone broke a few days ago so I couldn't really get into contact otherwise.\""
    yui "\"Ah, I can see how that would be a problem. Please, come in.\""
    "I do as I'm instructed, taking off my shoes and leaving them on the concrete floor before stepping inside."
    scene JunBedroom with fade
    play sound "music/door.ogg"
    "I knock on Jun's room, opening the door after hearing a soft \"come in\" from inside."
    play music2 "music/BGM/Snowy Day.ogg" fadein 5.0
    show j 1 c watch at fdis, five with dissolve
    "I am greeted to the sight of Jun sitting on his bed with a controller in his hand."
    "He looks away from the screen and up to me as I walk into the room."
    j "\"Good afternoon, [povFirstName]-san.\""
    "I have to admit, his casual greeting does throw me off a little bit."
    mc 1 c wince "\"H-hey there, Jun. W-what's up?\""
    "Ugh. Shoot me."
    j 1 c think "\"I'm just playing a game. See?\""
    "He waves the controller on his hand as if for additional effect."
    mc 1 c worried "\"Yeah. Right. I can see that. More like... erm. What's up with you?\""
    j 1 c watch "\"I'm good. You?\""
    "..."
    "Why do I feel so painfully awkward?"
    "And more importantly..."
    "Why doesn't he?!" with hpunch
    mc 1 c considerate "\"I-I'm doing well. I guess I just came up to check in on you.\""
    j "\"You mean you came {i}in{/i} to check {i}up{/i} on me?\""
    mc 1 c considerate "\"R-right. That.\""
    "Oh God, what the hell am I even doing?"
    "Why is talking so hard all of a sudden?"
    j "\"[povFirstName]-san, are you okay? You're acting a little weird.\""
    mc 1 c wince "\"Yeah, I'm fine. More importantly... are you? I mean, after... erm... after how things ended during the fest-{nw}\""
    j 1 c considerate "\"Please, let me stop you right there. Please remember what I said then. I would prefer to act like none of that ever happened.\""
    "The sudden shift in his demeanor catches me completely by surprise."
    "Still... this isn't the kind of thing I think should be swept under the rug."
    "Besides, if I don't get to talk this out I... I think I might just go insane."
    mc 1 c worried "\"Jun, I... I'm sorry but we really need to talk this through. It's not the kind of thing I can just forget.\""
    j 1 c avoid "\"... I was afraid you'd say that.\""
    "I walk over to his bed and take a seat next to him."
    "As soon as I sit down, Jun's tail lashes behind me and he readjusts himself, moving slightly farther away from me."
    "Just seeing him do that already makes my chest hurt and I don't quite understand why."
    mc 1 c worried "\"Jun... I'm sorry to have frozen like that when you... when you said what you did. What you said was such a wonderful thing and... and I really appreciate it. It just caught me by surprise.\""
    j 1 c considerate "\"It's... alright. I'm... honestly not sure why I said what I did. I was feeling a bit out of it and... it just came out before I noticed what I was doing.\""
    j 1 c wry "\"I never expected to tell you that, it just slipped out. And I never expected you to accept it. It's because I knew that would be the end result that I never said anything.\""
    j 1 c considerate "\"Hehe... Isn't it stupid? Getting upset and hurt over something you already knew was going to happen?\""
    mc 1 c worried "\"That's... not true. It's not stupid or anything. You have a right to get upset when things don't go your way.\""
    j 1 c wry "\"Honestly, it was already pretty stupid for me to say something. I wasn't really thinking and my feelings just came pouring out before I could stop myself.\""
    j 1 c avoid "\"... I fell really hard for you, [povFirstName]-san. It scares me just how much. I... I didn't want to say anything that would risk making you treat me differently.\""
    j 1 c considerate "\"But just looking at how awkward you're acting right now... I really messed that up.\""
    "I... I'm honestly astonished."
    "I never expected this level of introspection from Jun of all people."
    "To be honest, he's always surprising me with his maturity and yet I continue to give him far too little credit."
    mc 1 c worried "\"I'm... I'm not sure what to do. I've been conflicted since you... since you confessed to me.\""
    mc 1 c considerate "\"To be perfectly honest, I got so frustrated with myself over how I handled it that I ended up smashing my phone against a wall. I don't even know why I did it. I just did before I realized.\""
    show j 1 c shock at fdis, jumping
    j "\"What?! You shouldn't do that. Phones are expensive!\""
    mc 1 c sigh3 "\"It's not like I just up and thought \"Hmm, what else would make this day more fun? Oh, I know, let me just smash my phone\" you know. I did it without thinking.\""
    j 1 c considerate "\"Fair enough. I guess we both acted without thinking, huh?\""
    mc 1 c worried "\"Yeah...\""
    show j 1 c avoid at fdis
    "..."
    "To say we feel awkward would be a monumental understatement."
    "I'm trying to come up with words to speak my mind but I don't even know what it is that I wanted to say."
    "At first I planned to come here and properly reject his confession."
    "I wanted to just apologize for how I reacted and try to clear the air."
    "But as soon as I saw him I..."
    "I got confused again."
    "I don't know what I want and it angers me."
    "I guess this is why Saya told me not to talk to him about it until I made up my mind."
    "Heh... I really do have a knack for not thinking things through..."
    mc 1 c worried "\"Jun, I... C-can I get time to think about it?\""
    j 1 c shock "\"H-huh?!\""
    "Before I even realize what I'm saying, words start coming out of my mouth."
    mc 1 c worried "\"I'm not sure how I feel about the whole thing. Or about you. Not yet at least. I'm not saying that in the future I'll accept your confession but... but I'm not sure I won't either.\""
    j 1 c shockb "\"S-so you're saying that... that you might...\""
    mc 1 c considerate "\"It's a pretty big \"might\". To be honest, I'm still really confused. I don't know how I feel and until I get my feelings in order, I can't give you a proper answer.\""
    mc 1 c worried "\"All I know is I never felt like this before. Whenever I got confessed to before, I always knew right away what my answer would be. But with you... I don't know. I want to say yes but I also don't.\""
    mc 1 c considerate "\"My thoughts are a mess right now. That's why I would like for us to just try to go back to normal until I can be sure. Put off my giving you an answer until I get to one.\""
    mc 1 c worried "\"Although I also know that's a really selfish thing to ask...\""
    j "\"... O-okay.\""
    "I could see his eyes almost glinting once he heard my words."
    "It... might have been bad of me to say what I just did."
    "I might have given him hope when there is none, but..."
    "After how I failed to come up with words last time, this time they all just came out with full force before I even noticed what was happening."
    "I understand myself far less than I thought I did. I'm not sure if that's a good or a bad thing."
    "At least I'm trying? I don't even know."
    j 1 c wince "\"Uhm... S-so...\""
    mc 1 c considerate "\"How do we act normal again after this?\""
    j 1 c sigh "\"I was just about to ask the same thing.\""
    show j 1 c avoid at fdis
    "The two of us twiddle our thumbs awkwardly, sitting on the bed together while completely silent."
    "How do you even steer away from a situation like this?!"
    j 1 c considerate "\"U-uhm... s-so...\""
    mc 1 c fsmile "\"Y-yeah?\""
    j 1 c avoid "\"D-do you want to watch me play some games?\""
    mc 1 c shock "\"O-oh. Sure.\""
    "Jun immediately grabs his controller again, unpausing his game and playing it without saying a word."
    "I watch him absentmindedly, too lost in my thoughts to actually pay much attention."
    "... The only thing I notice is him beginning to die. A lot."
    show j 1 c wince at fdis
    "He seems to be pretty flustered just like me. It seems like he's not focusing on his game at all."
    play sound "music/disappointment.ogg"
    "What the hell are we even doing..."
    mc 1 c wince "\"Hey... Can I ask a question?\""
    "Jun freezes as soon as I speak up, his character freezing on-screen alongside him."
    "It takes a full second before he starts moving again."
    j 1 c wince "\"Y-yeah. Sure.\""
    mc 1 c talk "\"Your mom said you were out of the house since Friday. Where were you?\""
    j 1 c considerate "\"T-that? That's an odd thing to ask about.\""
    mc 1 c talk "\"Not really. I even mentioned it to Saya and Shoichi yesterday when I was asking for their advice and-{nw}\""
    j 1 c shock "\"W-wait. Asking for their advice? As in... about me?\""
    mc 1 c shock "\"O-oh!\""
    "I forgot that he might not appreciate knowing that other people have been told about it!"
    j 1 c shockb "\"[povFirstName]-san y-you didn't...\""
    mc 1 c considerate "\"U-uhm...\""
    j 1 c wince "\"N-nooo...\""
    "Jun pauses his game, tossing the controller away and leaning his back against the wall, hugging his knees and burying his face on them."
    mc 1 c worried "\"I-I'm sorry. I tried asking for advice without giving them any information but they kept pressing and-\""
    j 1 c blush2 "\"And what? You didn't know how to say that it was private?!\""
    mc 1 c wince "\"I-I'm sorry. I just... I'm really used to sharing everything with those two s-so...\""
    j "\"Now they're going to know that I'm gay... What if they treat me differently because of it?\""
    mc 1 c considerate "\"Y-you know they'd never do that. If anything they might be awkward about it because they don't want {i}you{/i} to think they think of you any differently.\""
    j 1 c poutb "\"You do know all of this could have been avoided if you just didn't say anything!\""
    mc 1 c considerate "\"Ehehe...\""
    show j 1 c poutb at jumping
    j "\"Don't just laugh it off!\""
    mc 1 c shock "\"S-sorry!\""
    j 1 c blush2 "\"Ugh... my whole face is so hot right now...\""
    mc 1 c worried "\"I'm sorry...\""
    j 1 c avoid "\"I guess... I guess that's fine. I opened myself up to things like this happening when I told you about my feelings anyway.\""
    mc 1 c considerate "\"If it's worth anything, I'm surprised how easily you were able to admit that you're... you know.\""
    j 1 c "\"Gay?\""
    mc 1 c wince "\"Y-yeah.\""
    j 1 c considerate "\"It's not a big deal for me or anything. I've known about it for a few years already and I had time to accept myself. To me it's just part of who I am.\""
    "W-wow."
    "That's such a mature way to look at it."
    "... Meanwhile I couldn't even bring myself to say the word."
    "Ugh... I suck."
    mc 1 c worried "\"... Do your parents know?\""
    j 1 c wry "\"Does it matter?\""
    mc 1 c considerate "\"W-well, not really but... I guess I'm just curious.\""
    mc 1 c wince "\"No matter how awkward it might be, this is a new part of you I only just found out about. I... kinda want to understand it more.\""
    j 1 c sigh "\"... Alright.{nw}"
    show j 1 c blush2 at fdis
    extend " I told them about it a while ago... Back when I was sixteen.\""
    mc 1 c talk "\"How did they react to it?\""
    j 1 c considerate "\"They were shocked. But then again, most people would be.{nw}"
    show j 1 c wry at fdis
    extend " But other than that, they've been really supportive of it.\""
    j 1 c considerate "\"... Mom and Dad kept teasing me about having a crush on you for at least two weeks now. I guess it's gotten really easy for them to tell whenever I talk about you or you come over to visit...\""
    mc 1 c shock "\"O-oh.\""
    "... I suddenly feel very self-conscious about Yui-san knowing I'm alone with her son in his bedroom with the doors closed."
    j 1 c avoid "\"I didn't tell them about me confessing though so... you don't have to worry about that.\""
    mc 1 c wince "\"They didn't notice anything weird about how you're acting. Or were you able to mask it that well?\""
    j 1 c considerate "\"As far as they know, I've been a little bit out of it for a different reason.\""
    mc 1 c talk "\"What is it?\""
    j 1 c wince "\"... I'd rather not say.\""
    mc 1 c worried "\"What? Come on, after all this you can't talk to me about it?\""
    show j 1 c avoid at fdis
    "Jun puts his hands between his legs, looking down at his feet and staying silent."
    mc 1 c worried "\"Jun?\""
    "I hesitantly reach out to him, putting a hand on his shoulder."
    "He shivers at my touch but doesn't pull away."
    "I really want to just reach around him and hug him."
    "I don't like seeing him looking so down and glum. It makes my chest hurt so much."
    "But I also know it could just make things even more awkward, especially considering how we are right now."
    "I... don't want to do anything that could be misconstrued or cause him even more grief."
    "I don't want to be the reason he's hurting..."
    "However, despite my subtle attempt to prod him for more information, Jun remains silent."
    "I guess I'm not really the best at coaxing info out of other people."
    mc 1 c considerate "\"Alright alright. I won't ask anymore. You don't have to keep looking like that.\""
    j 1 c wince "\"S-sorry...\""
    "I decide that a tactical retreat is the best solution for now."
    "Although... if I do end up dating him, I definitely wouldn't like for him to be keeping secrets from me."
    "... That's probably me getting ahead of myself though."
    mc 1 c curious "\"Is it okay if I ask more questions about... erm... your interest in men?\""
    j 1 c considerate "\"I guess? The cat's already out of the bag so there's no problem telling you.\""
    mc 1 c wince "\"W-well...\""
    "What should I even ask him?"
    menu:
        "How long have you known?":
            mc 1 c talk "\"How long have you known about your... erm... preference?\""
            j 1 c considerate "\"Come on, you can at least say the word can't you?\""
            mc 1 c wince "\"Believe me, I'm trying. It embarrasses me for some reason...\""
            j 1 c sigh "\"That's kinda immature.\""
            play sound "music/disappointment.ogg"
            "Guh... I'm being called immature by Jun of all people."
            "Honestly, I guess I had it coming."
            j 1 c wince "\"But lets see... I think I started noticing when I was around fourteen.\""
            mc 1 c talk "\"Really? What made you notice?\""
            j 1 c considerate "\"... It's kinda embarrassing.\""
            mc 1 c considerate "\"It can't be that bad.\""
            j 1 c avoid "\"... I studied in a boarding school for a few years before I moved back home. The male dormitories... didn't really have private showers.\""
            mc 1 c shock "\"O-oh?\""
            j 1 c considerate "\"We had bathroom units with toilets and sinks in the rooms but... if we wanted to shower, we had to use the communal shower in the dorm.\""
            j 1 c avoid "\"I... noticed that I kinda liked... looking at the guys a bit too much.\""
            "..."
            menu:
                "\"So it gave you a \"hard\" time?\"":
                    $ ridiculousj16 = True
                    $ junlove -= 1
                    mc 1 c seductive "\"So... what? Watching the guys walking around naked gave you a bit of a \"hard\" time so to speak?\""
                    j 1 c shockb "\"W-wha-\""
                    "Before I even have time to think about it, I run my mouth and make a perverted joke."
                    mc 1 c considerate "\"Ahahaha, I'm just joking...\""
                    play sound "music/disappointment.ogg"
                    show j 1 c blush2 at fdis
                    "Ahh, he's not even looking at me right now..."
                    j "\"{size=-16}Sometimes...{/size}\""
                    "He mumbles something under his breath that I can't really make out."
                    mc 1 c curious "\"I'm sorry, what?\""
                    j 1 c blush2 "\"I-I said \"it did sometimes\"!\""
                    mc 1 c flustered "\"Ah.\""
                    "No words come to my mind right now."
                    "Congratulations to me, I somehow made things even more awkward."
                    "I seriously deserve a prize for just how far I'm able to cram my foot into the hole."
                    mc 1 c considerate "\"I really shouldn't have asked that should I?\""
                    j 1 c considerate "\"No comment...\""
                    play sound "music/disappointment.ogg"
                    "Oy vey..."
                "Stay quiet.":
                    $ ridiculousj16 = False
                    "I really don't think this is the sort of thing I should make jokes about."
                    "The last thing I want is to make him uncomfortable."
                    "Or... well... more uncomfortable than he probably already is."
        "Have you had a boyfriend before?":
            $ ridiculousj16 = False
            mc 1 c talk "\"So... since you said you've already come to terms with your own sexuality... does this mean you've dated before?\""
            j 1 c think "\"T-that's awfully personal.\""
            mc 1 c considerate "\"I mean... it's not like I asked \"Hey, have you boned a dude before?\".\""
            j 1 c shockb "\"W-wha-\""
            mc 1 c shock "\"No no no no no, I said that's not what I was asking... Not what I was asking!\""
            j 1 c blush2 "\"T-that's a really big lack of tact you know...\""
            play sound "music/disappointment.ogg"
            "I was just trying to be funny for the sake of lightening the mood!"
            mc 1 c considerate "\"S-sorry, I made a bad joke. I just wanted to know if you've had a boyfriend before.\""
            j 1 c wince "\"N-no boyfriends...\""
            mc 1 c talk "\"Oh. Okay.\""
            "That was... huh."
            "I don't know what kind of answer I was expecting but it was kind of anticlimactic."
            j 1 c considerate "\"Although... erm... for the sake of full disclosure... I...{nw}\""
            j 1 c avoid "\"I've sorta kissed a guy before...\""
            mc 1 c shock "\"{size=+4}Whaaaaaaaaat?!{/size}\"" with hpunch
            show j 1 c wince at fdis, jumping
            j "\"L-loud! I'm right next to you, don't shout.\""
            mc 1 c wince "\"S-sorry.\""
            j 1 c avoid "\"Why does it surprise you that much to hear it anyway? Am I unkissable or something?\""
            mc 1 c shock "\"N-no, that's not what I meant at all. I-I think you're really cute and very kissable.\""
            show j 1 c shockb at fdis
            j "\"Ah...\""
            "..."
            "{size=+4}What the hell did I just say?!{/size}"
            mc 1 c flustered "\"I-I-I mean- I just- I didn't-\""
            j 1 c blush2 "\"I-It's alright. You don't have to to say anything more.\""
            "Aaaaah, he's not even looking me in the eye anymore!"
            "I need to change the subject..."
            mc 1 c wince "\"S-so... w-what about this guy you kissed?\""
            "Worst. Change of subject. Ever."
            j 1 c wince "\"W-well... there's not much to tell. He was one of the few openly gay students in my old school and... I kinda went to him for advice back when I was first coming to terms with myself.\""
            j 1 c avoid "\"I remember saying something like \"Maybe I don't really like guys. Maybe I just feel more comfortable around them than I do with girls. It's not like I can test it anyway\".\""
            mc 1 c talk "\"And?\""
            j 1 c considerate "\"... Then he kissed me and asked me what I thought of it.\""
            mc 1 c shock "\"W-whoa. Seriously?!\""
            j "\"Y-yeah. Turns out I really do like guys after all...\""
            mc 1 c wince "\"I-I mean, I don't think a quick peck on the lips is an indicative of anything.\""
            j 1 c avoid "\"... It was full tongue.\""
            "...{w} {size=+4}What?!{/size}"
            mc 1 c shockb "\"...\""
            j 1 c considerate "\"{size=-2}You're about as shocked as I was.{/size}\""
            mc 1 c wince "\"I'm just... wow. That was really bold of the guy. I can't believe you actually let him do that.\""
            j 1 c blush2 "\"... He had always been really nice to me and... I kinda... really liked it.\""
            "I have a hard time conciliating this information with the image I have of Jun in my head..."
            j 1 c considerate "\"But this was four years ago so its been a long time...\""
            mc 1 c considerate "\"You're a lot more worldly than I thought, Jun...\""
            j "\"I don't think I'd go that far...\""
        "What do you like about guys?":
            $ ridiculousj16 = False
            mc 1 c talk "\"If you don't mind me asking... what is it that makes you like guys?\""
            j 1 c wince "\"That's a fairly open-ended question. I'm not quite sure how to answer it.\""
            mc 1 c considerate "\"Well... what kind of guys do you like?\""
            j 1 c wince "\"Uhm... Let me think.\""
            j 1 c considerate "\"I guess... I like guys like you?\""
            play sound "music/heartbeat.ogg"
            "!"
            "Okay, saying things like that certainly isn't good for my heart... nor is it helping."
            mc 1 c considerate "\"Guys like me? What do you mean?\""
            j 1 c wince "\"Well...\""
            j 1 c considerate "\"Gentle, caring, encouraging, affectionate, funny.\""
            j 1 c wince "\"... The physical side doesn't appeal to me as much but... I do have to admit, handsome too.\""
            mc 1 c avoidb "\"I-is that so?\""
            j 1 c considerate "\"Sorry. That's... probably really awkward to listen to.\""
            mc 1 c considerate "\"It's alright. I'm the one who asked the question after all.\""
            j 1 c avoid "\"I just... you're the first person I've met in years that I feel has really made an effort to get to know me and spend time with me.\""
            j 1 c considerate "\"All that put together with your other qualities... there's no way I wouldn't have fallen for you.\""
            j 1 c avoid "\"... I'm sorry that it's a lot. And I'm sorry that I'm kinda pushing my feelings onto you.\""
            mc 1 c worried "\"I already told you you don't need to apologize about that. No one needs to apologize over having feelings.\""
            j 1 c considerate "\"I know but... I'm not exactly making things any less awkward by saying all this, am I?\""
            j 1 c wince "\"I'm just kinda getting nervous and running my mouth and making it worse.\""
            "I can sympathize there."
            "I feel like I'm cramming my foot further down the hole every time I open my mouth."
            "God, I'm awkward."
            mc 1 c talk "\"Soooo... you don't really care much about a guy's appearance.\""
            j 1 c considerate "\"It's... not the priority by any means.\""
            j 1 c avoid "\"... Though I will admit that I swoon a bit sometimes at really handsome guys.\""
            mc 1 c talk "\"Oh? Have you ever swooned at me?\""
            j 1 c wince "\"T-that's a really weird question to ask.\""
            mc 1 c considerate "\"We're already this deep in the rabbit hole, what difference does it make?\""
            j 1 c bored "\"No, I'm not answering that. You just want me to massage your ego.\""
            play sound "music/stab.ogg"
            "Ooof." with hpunch
            mc 1 c considerate "\"F-fair enough.\""
            "I don't think I'll ever get used to getting called out all of a sudden like this..."
            "It's just too jarring."
            mc 1 c considerate "\"Well... I do have to admit I never pictured you as the kind of person who, like, has crushes and thinks like that. I didn't even think you were romantically aware.\""
            j 1 c sigh "\"I'm not a child. Stop acting like I am.\""
            play sound "music/stab.ogg"
            mc 1 c wince "\"S-sorry.\""
            "Sheesh, I seem to just be walking into these now..."
            "I think I better cut my losses before I make it even worse."
        "What is it like?":
            $ ridiculousj16 = False
            mc 1 c considerate "\"Well... what's it like?\""
            j 1 c think "\"What's..."
            show j 1 c watch at fdis
            extend " What?\""
            "Jun cocks his head to the side, confused by my question."
            "I'll admit that wasn't me at my most eloquent..."
            mc 1 c wince "\"I mean... what's it like knowing you're... you know. What's it like knowing and accepting it?\""
            j "\"I dunno. What's it like knowing you don't like tea?\""
            mc 1 c shock "\"H-huh?\""
            j 1 c think "\"It's pretty much the same. It's just a thing that I either like or don't like.\""
            "That's... that's not even remotely the same!"
            j 1 c wince "\"W-why are you frowning at me like that?\""
            mc 1 c judge "\"I'm not frowning.\""
            show j 1 c wince at fdis, shake1
            j "\"Y-yes you are. Stop that. Your face looks scary.\""
            "I continue to just stare blankly at him."
            "This is the kind of reaction he should expect after a non-answer like that."
            j 1 c wince "\"[povFirstName]-san, please stop looking at me like that...\""
            mc 1 c sigh2 "\"Alright, fine.\""
            j 1 c pout "\"It's not my fault you asked me such a weird question to begin with. How am I even supposed to answer that?\""
            "You could at least try!"
            "... Ugh, although I know I'm being unreasonable being annoyed with this."
            "I'm the one prying to begin with so it's not like he's in the wrong for answering that way."
            "Blegh, self-reflection is so annoying, I'd prefer just being certain that I'm right."
            "... Man, I annoy even myself with how annoying I can be sometimes."
    "Trying to think of more questions is pretty hard too..."
    "Ugh, I'm curious about it but I can't think of what to ask..."
    play sound "music/knock.ogg"
    show j 1 c shock at fdis, jumping
    "The two of us nearly jump out of bed when we hear knocking at the door."
    "Apparently we were so lost in our own awkwardness that we kind shut off to the rest of the world."
    yui 1 c smile "\"Jun, I baked some cookies. Why don't you come outside and snack for a bit?\""
    "Yui-san's voice echoes from the other side of the door, as sweet and caring as she usually sounds."
    j 1 c wince "\"C-coming!\""
    "She seems satisfied by his response as I hear her walking away from the door."
    mc 1 c wince "\"Wow. I haven't even been here long and she already baked cookies? Was it just coincidence that I came by while she was planning to make them?\""
    j 1 c sigh "\"No. She just likes to use guests as excuses to do things like that so she gets to snack too while acting like it wasn't for her.\""
    mc 1 c considerate "\"Oh... That's kinda amusing.\""
    j 1 c watch "\"It was at first. It gets old pretty fast though.\""
    mc 1 c considerate "\"Heh. I'll take your word for it.\""
    j "\"Come on. If we leave her waiting for too long she's just gonna barge in.\""
    stop music2 fadeout 2.5
    scene JunLivingRoom
    show j 1 c watch at fdis, three
    show yui 1 c smile at fdis, seven
    with fade
    play music3 "music/BGM/Little by Little I Walk.ogg" fadein 5.0
    "We step outside and into the living room, where we see Yui-san sitting on the floor with her legs under a very thick looking kotatsu, absentmindedly munching on a cookie while watching TV."
    mc 1 c shock "\"Yui-san, isn't it kinda warm to be using a kotatsu?\""
    "Her eyes snap up to me and she smiles, cocking her head to the and leaning back on her arm."
    yui "\"Oh, it's alright. I tend to feel chilly easily. Plus, it's very soft and comfortable.\""
    "I have trouble accepting that explanation, mostly because of just how warm I've been feeling the past couple weeks."
    "But then again, I guess not everyone is the same."
    "... And I also have a kinda heavy coat of fur."
    play sound "music/fabric.ogg"
    "Jun sits on the opposite side of his mother, grabbing a cookie from the platter and taking a bite out of it."
    "Deciding that there's no point in standing around on my own, I take one of the free spots on the kotatsu and try to ignore the warmth around my legs."
    yui "\"So tell me, [povFirstName]-kun, how was the school festival? Jun tells me you spent most of the time wandering around.\""
    mc 1 c considerate "\"Yeah. I wanted to just walk around and try to enjoy the festival for a bit. Visit the stalls and whatnot.\""
    mc 1 c worried "\"Of course, I also spent a lot of time worrying about this walking accident here.\""
    j 1 c wince "\"W-what? Since when am I a walking accident?\""
    mc 1 c sigh2 "\"You nearly set fire to the kitchen.\""
    yui "\"Wait, you did what?!\""
    "Yui-san's eyes go wide and she stares at Jun slack-jawed."
    j "\"T-that only happened once!\""
    mc 1 c sigh2 "\"That's already one too many times.\""
    show j 1 c wince at fdis
    j "\"Uuuu...\""
    "He wiggles around on his seat, looking all sorts of defeated."
    "I have to admit, it's a little amusing."
    yui "\"When I asked you how the festival went you called it \"uneventful\"!\""
    j "\"I-I didn't think it was worth bringing up.\""
    yui "\"You nearly set yourself on fire!\""
    j "\"T-that could have happened to anyone...\""
    mc 1 c sigh3 "\"And yet it didn't.\""
    mc 1 c "\"By the way, didn't you also-\""
    j 1 c sigh "\"S-stop telling on me to my mother!\""
    "Yui-san lifts an eyebrow, staring at with him suspicion."
    "The funniest part of this all is... as far as I know, the fire was the only accident he caused."
    "So I just got him squirming when I got nothing at all to tell."
    "I must not let this power get to my head."
    yui "\"You and I are going to need to talk about this later.\""
    j 1 c wince "\"{size=-2}Y-yes ma'am...{/size}\""
    "Wow, he sounds so defeated that I almost feel bad for teasing him like this."
    "... Almost."
    yui "\"Well... putting {i}that{/i} aside, what else did you boys do? Did you spend any time together? Jun barely told us anything.\""
    j "\"M-mom, stop with the interrogation.\""
    yui "\"What? I'm not interrogating. I'm just curious since you didn't tell me anything.\""
    j 1 c sigh "\"Because there's nothing to tell!\""
    yui "\"Is there really nothing to tell, [povFirstName]-kun?\""
    show j 1 c shock at fdis, jumping
    j "\"M-mom!\""
    mc 1 c happy "\"Snrk...\""
    j 1 c pout "\"Don't laugh!\""
    "... I have to admit I'm loving this."
    "Sorry Jun, it's kinda mean but it's just too funny."
    mc 1 c smile "\"We walked around together for a bit, yeah. I took Jun to a café made by a freshman class that specialized in serving desserts.\""
    show j 1 c watch at fdis
    "Once she hears that, Yui-san's face brightens up and she looks at the two of us with a wide smile."
    yui "\"Really? Was it good?\""
    if cake == "strawberry":
        if cheesecake == "strawberry":
            j 1 c happy "\"Yeah, it was really good. [povFirstName]-kun even remembered that strawberry was my favorite flavor. He ordered a strawberry cake and a strawberry cheesecake and shared his with me.\""
            "Yui-san's gaze softens considerably."
            "She looks at me for a second and I swear a can feel a wave of affection coming from her with the way she looks at me."
            yui "\"I didn't even know you told him about that.\""
            j 1 c gentle "\"That's the thing. I didn't. You know that time when he bought some sweets for me at that shop?\""
            yui "\"Oh yes, those were delicious!\""
            show j 1 c smile at fdis
            "Jun nods enthusiastically."
            j "\"Yeah. He noticed I got more strawberry shortcake than any one sweet and he figured out I liked strawberry from that.\""
            j 1 c happy "\"Hehe. He's really perceptive. Isn't it great?\""
            "Wow, I..."
            "I feel my cheeks getting hot with all this gratuitous praise being thrown my way."
            "Yui-san laughs, staring at her son with kind eyes and a gentle smile."
            yui "\"I'm glad you had so much fun. I wish you had told me about this stuff.\""
            j 1 c wince "\"I didn't think it was a big deal. It was just cake.\""
            "She chuckles again."
            yui "\"If you say so, honey.\""
        else:
            j 1 c smile "\"Yeah. I asked [povFirstName]-san to surprise me and order for me. Can you believe he ended up picking strawberry?\""
            yui "\"Oh my. Isn't that your favorite?\""
            j 1 c happy "\"Hehe. Right? It was really good.\""
            yui "\"I hope you thanked him for it.\""
            j 1 c smile "\"I did. Right, [povFirstName]-san?\""
            mc 1 c smile "\"He did. If there's one thing Jun is good at is thanking people dozens of times when he really doesn't need to.\""
            j 1 c wince "\"H-hey. When you put it that way it almost sounds like a bad thing!\""
            mc 1 c happy "\"Does it now? Oh no, how could that be?\""
            j 1 c pout "\"Am I being mocked?\""
            "Yui-san and I both laugh at Jun's annoyance."
            "Even when he's annoyed he finds a way to be cute. Just seeing his cheeks puffed up and pouty like that makes me want to poke him."
            "Of course, I'd be scared of getting bit or something like that."
            "Never poke an angry tiger on the cheek."
            "... Or anyone else for that matter."
    else:
        if cheesecake == "strawberry":
            j 1 c smile "\"Yeah. Although to be honest, the best part was that [povFirstName]-san ordered strawberry cheesecake for himself and shared it with me. It was really good. I liked it more than my own cake.\""
            mc 1 c considerate "\"Next time I'll make sure to order strawberry for you too.\""
            j 1 c happy "\"Hehehe.\""
            "Well, he's definitely been getting less and less shy about being pampered."
            "Not that I mind. It's pretty cute."
            yui "\"Well, why didn't you order strawberry for yourself then? Isn't it your favorite?\""
            j 1 c considerate "\"I asked [povFirstName]-san to surprise me and order it for me. It was only by coincidence that he ordered strawberry to himself. Then he shared with me once he saw how much I wanted it.\""
            yui "\"... So you complained about what he ordered for you and then ate his cake? After making him order for you in the first place?\""
            j 1 c wince "\"Wha- When you put it that way...\""
            yui "\"That was very impolite!\""
            show j 1 c shock at fdis, shake1
            j "\"Wha-\""
            "Yui-san quickly censures Jun over something so incredibly minor I didn't even stop to think about."
            "I guess she can be very strict despite how warm she is."
            "No wonder her son turned out to be such a goody-two-shoes despite his own... peculiarities."
            j 1 c wince "\"It's not a big de-\""
            yui "\"You should apologize!\""
            show j 1 c shock at fdis
            j "\"Y-yes ma'am!\""
            j 1 c wince "\"I-I'm sorry, [povFirstName]-san...\""
            mc 1 c considerate "\"It's alright. I didn't mind at all.\""
            j 1 c sigh "\"See?! There was no need!\""
            yui "\"No, you still need to apologize when you do something undue, even if the other person doesn't mind it.\""
            j 1 c wince "\"Guh...\""
            mc 1 c considerate "\"No, it really isn't a big deal at all...\""
            play sound "music/disappointment.ogg"
            "This family has the weirdest priorities..."
        else:
            j 1 c smile "\"It was pretty good, yeah. The cakes were a bit on the pricey side but they were worth it.\""
            yui "\"Hmm... I wish I could have tried it.\""
            mc 1 c considerate "\"It kinda sucks cause the girls who made the desserts are the daughters of a pastry chef in town. I looked his shop up afterwards and found out the cakes he makes are easily five times the price.\""
            mc 1 c wince "\"But since his daughters used his recipes and they were also pretty skilled themselves, it ended up being much cheaper for the same quality.\""
            show j 1 c watch at fdis
            yui "\"Oh, that's a shame...\""
            "Yui-san's shoulders sag and I feel kinda bad for bringing this subject up in the first place."
            "I guess everyone in this household is a sweet-tooth huh?"
    yui "\"Hmm... I really want to have cake now. Maybe I should order one.\""
    j 1 c wince "\"M-mom, we already have the cookies. We can't have that many sweets.\""
    yui "\"Nonsense. Sweets are always good.\""
    j 1 c sigh "\"Mom...\""
    yui "\"Oh, I know! I'll call Atsushi and ask him to swing by a bakery on his way home!\""
    j 1 c wince "\"M-moooom!\""
    "Wow, she's not listening to him at all."
    "In fact, I don't think she's even registering his presence at all."
    "Apparently having your head in the clouds is a family trait? I wasn't aware of that."
    yui "\"Just a second, I'm gonna give Atsushi a call.\""
    show yui 1 c smile at offscreenright
    show j 1 c sigh at fdis, five
    with move
    "She stands up and quickly scurries away towards what I assume is her bedroom."
    mc 1 c "\"That was... something.\""
    j "\"She's probably gonna guilt dad into buying sweets on his way home now...\""
    mc 1 c wince "\"Ooof. That doesn't sound good.\""
    j 1 c avoid "\"Well... I guess it's not that bad. He's always just looking for an excuse to eat sweets too.\""
    "..."
    play sound "music/disappointment.ogg"
    "Is this a family of ants by any chance?!"
    mc 1 c smile "\"Still, your mom seemed pretty enthusiastic.\""
    j 1 c considerate "\"Yeah. I guess that's a good thing at least. She was a bit down the past few days so its nice to see her more cheerful.\""
    mc 1 c "\"Did something happen?\""
    j 1 c avoid "\"Just some personal stuff.\""
    "Ah..."
    mc 1 c considerate "\"Sorry, I shouldn't have asked. That was tactless of me.\""
    j 1 c considerate "\"Its okay. Thanks for understanding.\""
    "I seem to keep hitting roadblocks every time I try to ask something."
    "... Maybe I should take this as a sign to not ask so many questions."
    mc 1 c "\"... Was there any reason you didn't tell your parents anything about the festival?\""
    j 1 c considerate "\"... I thought it'd be awkward. I don't think I'd be able to hide how I was feeling if I started talking about it.\""
    j 1 c avoid "\"After all, most of the memorable parts were from when I was with you.\""
    mc 1 c worried "\"Oh... At least it was only \"most\" of them instead of all of them.\""
    mc 1 c considerate "\"That's... a silver lining at least, right?\""
    j "\"... The only other memorable thing was the fire.\""
    "{size=+2}Ooof!{/size}" with hpunch
    mc 1 c wince "\"... I'm sorry.\""
    j 1 c considerate "\"It's okay. I had time to process it anyway. A lot of time actually. The past few days were kinda boring.\""
    mc 1 c "\"Really? I thought you were really busy. I even asked Aki to message you for me but you never answered.\""
    j 1 c shock "\"He did?! Shoot, my phone was turned off.\""
    mc 1 c sigh "\"... Why was your phone turned off if you were bored?\""
    j 1 c wince "\"I only have a cheap feature phone. It's not like I could do much of anything on it in the first place.\""
    "Ah..."
    "I guess that's a fair point."
    j "\"Speaking of phones, how much is it gonna cost to replace yours?\""
    mc 1 c considerate "\"Eh. I'm not sure. I haven't chosen a model yet.\""
    j 1 c wince "\"... I feel kinda responsible for it in a way.\""
    mc 1 c sigh "\"You didn't put a gun to my head and tell me to throw it against the wall. You have nothing to feel responsible about.\""
    j 1 c avoid "\"I guess...\""
    "Seriously, stop trying to take responsibility for things that were totally out of your control!"
    mc 1 c sigh3 "\"Jun, you apologize too much. You need to be fairer to yourself.\""
    j 1 c wince "\"O-oh. S-sorry.\""
    "... Seriously?"
    "You respond to me saying you apologize too much by apologizing?!"
    "Do I need to physically smack some sense into your head?"
    show j 1 c watch at fdis, three
    show yui 1 c smile at fdis, seven
    with move
    yui "\"Alright, I'm back.\""
    j "\"That was quicker than I thought.\""
    yui "\"Yes, isn't that nice?\""
    "She chuckles, seemingly very happy with herself."
    j 1 c considerate "\"Yeah. I'm just surprised Dad folded that quickly.\""
    yui "\"Folded? What do you mean?\""
    j 1 c wince "\"Nothing. Never mind.\""
    stop music3 fadeout 2.5
    play music2 "music/BGM/Dog Days.ogg" fadein 5.0
    scene JunLivingRoom
    show j 1 c watch at fdis, three
    show yui 1 c smile at fdis, seven
    with fade
    show hour with dissolve
    $ renpy.pause (1.0)
    hide hour with dissolve
    "I barely notice the time passing by as Yui-san is very insistent in making conversation and I end up becoming engrossed very quickly.\""
    show j 1 c wince at fdis, jumping
    "Whether it is on purpose or by accident, she seems to have a knack for asking questions that embarrass her son."
    "It takes everything I have to keep myself from giving an answer that might embarrass him even more."
    "It's just too funny to tease him."
    play sound "music/slidingdoor.ogg"
    show j 1 c watch at fdis, fiveh
    show yui 1 c smile at fdis, nine
    show ats 1 n c smile at fdis, oneh
    with move
    "The sound of the door sliding open echoes from nearby the living room and, about a minute later, Jun's father walks into the house."
    ats "\"I'm home. And good afternoon, [povFirstName]-kun, it's good to see you again.\""
    mc 1 c considerate "\"Good afternoon, sir. I'm sorry for the intrusion.\""
    "He scoffs and waves me off."
    "He takes a seat at the kotatsu and dropping what looks like a cake box on the table."
    ats "\"Don't be ridiculous, it's a pleasure to have you here. Don't stand on ceremony so much.\""
    j "\"Welcome home. How was work?\""
    ats "\"It was okay. Peaceful and boring as ever. Feels like no one commits crimes anymore these days.\""
    j 1 c considerate "\"That's a bummer.\""
    "No no. That's not a bummer, that's a good thing."
    play sound "music/disappointment.ogg"
    "Do you two even have a clue what you're saying?"
    yui "\"Welcome home, dear. I hope the commute wasn't too bad?\""
    "Atsushi-san sticks out his tongue - a gesture that I definitely don't expect from a man his age - and groans."
    ats "\"The commute itself was fine but my God it was hot. They need to install air conditioning on public transport.\""
    j 1 c watch "\"Most of them tend to have AC, you're just really unlucky with getting the older trains cars.\""
    ats "\"In that case what is even the point?\""
    j 1 c considerate "\"I guess.\""
    "Atsushi-san scans the table, looking at both me and Jun."
    "For a second I'm a bit worried what he's thinking because he has this serious look on his face all of a sudden."
    "... Then he pouts."
    ats "\"Don't just stand there, you two. I brought cake for you. Eat.\""
    mc 1 c shock "\"W-wha- For us?\""
    "Yui-san chuckles, getting up from her seat and walking to the kitchen for just a few seconds before coming back with plates, forks and a knife."
    "That was... incredibly fast."
    ats "\"Yeah. Yui-san told me you were here and asked me to buy a cake for you boys. Apparently she knew you were coming since yesterday and forgot to tell me. I'd have already had one at the ready if I knew.\""
    j 1 c considerate "\"{size=-2}Ah, so that's how she got him to agree so fast.{/size}\""
    "I have a hard time keeping the smile on my face hearing this."
    play sound "music/disappointment.ogg"
    "Yui-san, please don't use me as an excuse to get your husband to buy you cake..."
    yui "\"Here, let me serve everyone a slice. Atsushi-san, do you want one too?\""
    ats "\"Yes please. At least I'll have something to cheer me up after such a crappy day.\""
    "...  Didn't you {i}just{/i} say you had a good day?"
    "Which is it?"
    ats "\"So, [povFirstName]-kun, what brings you here? It's not often that you visit us.\""
    show j 1 c wince at fdis
    mc 1 c shock "\"W- Me? Erm... n-no reason in particular. I just wanted to hang out with Jun for a bit is all.\""
    "Ugh, even Jun's face looks visibly uneasy."
    "Was my answer that bad?"
    mc 1 c considerate "\"A-and I accidentally broke my phone during the festival so I couldn't really message him about it. I'm sorry for just dropping by uninvited.\""
    ats "\"Nonsense. I already told you not to stand on ceremony. You're welcome to show up whenever. Hell, you could just open the front door and walk in without saying anything and I'd be fine with it. Bahahaha!\""
    "He laughs like he just told the world's most hilarious joke, his voice booming loudly throughout the room."
    j 1 c bored "\"If he did that then he'd walk in on you walking around the house naked.\""
    "Yui-san chuckles, handing us all some very generous slices of cake which I promptly accept so as to not be rude."
    "Atsushi-san grins and shrugs, stuffing his face with said cake."
    ats "\"I'm used to being seen naked and seeing other guys naked on a daily basis. I stopped caring a long time ago. I ain't got nothing to hide.\""
    mc 1 c considerate "\"{size=-2}That's a bit...{/size}\""
    j "\"So you wouldn't mind the fact that someone you're a big fan of gets to walk in on you naked out of nowhere?\""
    "Atsushi-san's face quickly shifts into a frown."
    "He begins mumbling, opening and closing his mouth like a fish without really saying any words."
    ats "\"W-well, w-when you put it like that...\""
    j 1 c sigh "\"Also, like I've said before, you could really stand to have a little bit more modesty.\""
    ats "\"I-I just-\""
    "I don't want to say anything because I don't want to draw attention to myself but..."
    play sound "music/disappointment.ogg"
    "Is this really the kind of conversation you should be having in front of a guest?"
    "I really don't want to be picturing Jun's dad walking around the house with everything hanging free."
    "No no no, bad mental image. Bad!"
    yui "\"Oooh, this cake is really good!\""
    "Yui-san completely ignores the totally out of place conversation happening in front of her, focusing instead on her cake."
    "... How normal does this kind of talk have to be for her to not even bat an eye to it?"
    "This entire family is really weird."
    "... And yet..."
    "I kinda like it here."
    "They're very warm and welcoming..."
    "I find myself laughing along even at this absurd conversation like it were the most natural thing in the world."
    "I guess I do miss this sort of environment."
    "With Mom always at work and Aki spending most of his time either training or studying, I can count on my hands the amount of family time we've had in the past few months..."
    j 1 c watch "\"[povFirstName]-san, are you alright?\""
    mc 1 c shock "\"H-huh?\""
    j "\"You were asked a question and didn't answer.\""
    mc 1 c wince "\"O-oh. Sorry, I was thinking of some stuff and ended up spacing out.\""
    mc 1 c talk "\"What was the question again?\""
    ats "\"I asked how your training has been going. Are you ready for the regional tournament?\""
    mc 1 c considerate "\"O-oh. That's in a few months. Besides, with the courts having been repurposed for the festival, we didn't do much in terms of training for the past couple weeks.\""
    "He puckers his lip, frowning his brow and looking at me like he's suddenly deep in thought."
    ats "\"That doesn't sound good. You should spend this time practicing so you can do well at the tournament.\""
    mc 1 c considerate "\"I'll be fine, really.\""
    "It's not like I can do any better at it than I already do."
    "Getting 2nd place is easy but..."
    "There's no way I can beat Tanabe. Its just not happening."
    "Be it at regionals or nationals, that guy is my superior in every way..."
    yui "\"Honey, don't barrage him with tennis questions.\""
    show ats 1 n c smile at fdis, jumping
    ats "\"Whaaat? It was only two questions.\""
    j 1 c watch "\"That always ends up leading to more.\""
    ats "\"No way, I can control myself!\""
    j 1 c bored "\"Yeah, sure. I don't remember you controlling yourself last time.\""
    show ats 1 n c smile at fdis, shake1
    ats "\"Nnnngg....\""
    play sound "music/disappointment.ogg"
    "... These two talk to each other like they're the exact same age."
    "Is this really a father and son dynamic?"
    stop music2 fadeout 2.5
    play music "music/night.ogg" fadein 5.0
    scene Street1N
    show j 1 c watch at fdis, five
    with fade
    show hours with dissolve
    $ renpy.pause (1.0)
    hide hours with dissolve
    "Somehow, I ended up getting roped into staying for dinner at the Kobayashi residence."
    "While it was certainly fun and I enjoyed the relaxed atmosphere, spending hours with what is essentially three different versions of Jun is really tiring."
    play sound "music/disappointment.ogg"
    "I feel like I was completely drained of all my energies..."
    j 1 c smile "\"Today was really fun.\""
    "Jun pipes up, snapping me away from my thoughts."
    "Compared to how we were earlier today, things are nowhere near as awkward as they were."
    mc 1 c smile "\"Yeah... yeah it was.\""
    j 1 c happy "\"Thank you for coming over today. I'll be honest, it was good seeing you again.\""
    mc 1 c wince "\"We would see each other tomorrow regardless of whether I came over or not.\""
    j 1 c considerate "\"That's true... but then I would feel too awkward to talk to you considering how we'd have left things off.\""
    j 1 c wry "\"And I was really worried this whole time that you might have been disgusted at me after what I said so I would have avoided you for a bit.\""
    "W-what? I can't have given off {i}that{/i} kind of vibe!"
    "Shocked? Sure. Not disgusted..."
    mc 1 c wince "\"I'm not-\""
    j 1 c smile "\"I know, I know. Inside my mind I knew you weren't really that kind of person, but my insecurities got the better of me, I guess.\""
    j "\"I'm just glad we were able to clear the air.\""
    j 1 c happy "\"I'm sure it might sound a bit suspicious considering what you now know about me but... I really love spending time with you, [povFirstName]-san.\""
    "..."
    mc 1 c avoidb "\"... I do too.\""
    j 1 c happyb "\"Ehehe.\""
    "He looks to be in an incredibly good mood. I'm honestly really surprised."
    mc 1 c worried "\"Uhm... J-Jun, you do remember what I said today, right?\""
    j 1 c watch "\"Hmm? You said a lot of things today. Which one are you talking about?\""
    mc 1 c wince "\"Y-you know. My request...\""
    j 1 c think "\"Reque- Oh, you mean how you asked me for time?\""
    mc 1 c considerate "\"Y-yeah, that.\""
    j 1 c watch "\"I do. Why?\""
    "... How can you be so nonchalant about this whole thing?!"
    "You're freaking me out a little bit..."
    mc 1 c wince "\"Is that... alright?\""
    j 1 c smile "\"Yeah. I don't really expect anything out of it but I don't mind waiting for an official answer.\""
    j 1 c considerate "\"I mean... it'll definitely suck if its no and I won't lie, a little part of me hopes it won't be.\""
    j 1 c smile "\"But what matters the most is that you're able to reach an answer you can be happy with.\""
    j 1 c happy "\"So I'm fine with waiting. I'm just glad you're still okay with keeping me around regardless.\""
    "..."
    "Fuck, he's so understanding it's liable to bring me to tears!" with hpunch
    mc 1 c considerate "\"Jun... you really are a treasure.\""
    j 1 c think "\"Huh? What do you mean?\""
    mc 1 c happy "\"Nothing. I don't mean anything by it.\""
    j 1 c watch "\"Hmm... I guess I'll take your word for it for now.\""
    j 1 c smile "\"By the way, since you already know about me anyway, feel free to talk to me if you have any questions.\""
    j 1 c considerate "\"Just... try not to ask ridiculous things.\""
    mc 1 c confused "\"Ridiculous things? Like what?\""
    if ridiculousj16 == True:
        j 1 c bored "\"You know what I mean. Like asking me if looking at other guys gives me boners.\""
        play sound "music/stab.ogg"
        "Gnnnk!" with hpunch
        "Those words catch me by surprise so hard I end up choking on my own saliva."
        mc 1 c wince "\"I-I was joking when I asked that.\""
        j "\"Well, don't ask things like that even as a joke. That's out of line.\""
        "You didn't even have to answer it in the first place!"
        mc 1 c considerate "\"... Noted.\""
    else:
        j 1 c watch "\"Hmm... I'll leave that vague for now. Just have a bit of common sense before you ask.\""
        mc 1 c sigh "\"Like you of all people get to criticize me about common sense.\""
        j 1 c considerate "\"Ehehe... fair enough.\""
        "Wow. He actually agreed with me?"
        "... Neat."
    mc 1 c talk "\"I'll keep that in mind anyway, although I don't really know what I could ask right now.\""
    "My brain is already pretty shot from mental exhaustion. Not to mention the last time I tried to ask stuff it was painfully awkward."
    "We're in a good place right now so I don't want to go back that line so soon."
    "I have a lot of thinking to do regardless..."
    "Can I even see Jun as a potential... uhm... what should I even call it?"
    "Date? Partner? Boyfriend?"
    "I'm not sure what the etiquette is here..."
    j 1 c smile "\"It's okay. So long as you're comfortable I don't mind.\""
    j 1 c considerate "\"I do have to admit that its nice not having to keep it a secret anymore.\""
    mc 1 c smile "\"Heh, is that so? How does it feel?\""
    j 1 c sigh "\"It's freeing. I no longer have to worry about saying the wrong thing or slipping up.\""
    j 1 c wince "\"... Although I guess Keisuke-san doesn't know? Or at least you didn't say you told him.\""
    mc 1 c considerate "\"I didn't.\""
    j "\"Maybe I should just tell him and get it over with.\""
    "... I dunno why but I don't think that's a good reason to come out of the closet."
    mc 1 c considerate "\"Y-you don't have to do that. You can tell people at your own time.\""
    j 1 c bored "\"I kinda have no choice though, do I? Someone has already outed me.\""
    play sound "music/stab.ogg"
    "Ooof!" with hpunch
    mc 1 c wince "\"... I'm sorry.\""
    j 1 c considerate "\"I appreciate the apology. Just... try to be more careful with that sort of information in the future.\""
    mc 1 c wry "\"Y-yeah. I will.\""
    j 1 c think "\"Hmm... How should I even tell Keisuke-san about it?\""
    mc 1 c "\"Do you really think you have to?\""
    j 1 c wince "\"I mean... you guys are the people I hang out with most often. If everyone besides Keisuke-san knows then I might as well.\""
    mc 1 c wince "\"It's not like you're gonna go around telling everyone you hang out with though. You're not telling Vic-kun or Sora-kun.\""
    j 1 c considerate "\"Yeah, that's true... I need to give this some thought.\""
    j 1 c smile "\"Thank you for being so understanding. I'll try not to make you feel awkward about it.\""
    mc 1 c considerate "\"It's okay. You don't need to worry about that.\""
    play sound "music/disappointment.ogg"
    "I already do a good job at making myself feel awkward all on my own."
    scene HouseFrontN
    show j 1 c watch at fdis, five
    with fade
    "We eventually reach my house. It's not all that far from Jun's so it doesn't take very long."
    j 1 c smile "\"Alright, we're here. Thank you again for coming to see me, [povFirstName]-san.\""
    mc 1 c smile "\"Thank you for walking me home.\""
    j 1 c happy "\"Hehehe. It's my duty as your senior after all.\""
    j 1 c smile "\"Have a good night. I'll see you tomorrow!\""
    mc 1 c happy "\"See ya.\""
    play sound "music/slidingdoor.ogg"
    scene LivingRoomN
    show a 1 c at fdis, fiveh
    with fade
    "Heading into the house, I see Aki sitting on the couch watching TV."
    "He turns his head to the door and greets me as soon as I walk in."
    a 1 c wince "\"Welcome home, Aniki. Is everything okay with Jun-san?\""
    mc 1 c considerate "\"Yeah. He said it was nothing.\""
    "Considering how worried I was about Jun and how he was out of his home for a long while, I ended up telling Aki about my concerns."
    "Of course, I left out the whole part about the confession and whatnot."
    "... And while I am still worried about Jun not telling me what he was doing while he was out, I don't want to worry Aki any more than he has to be."
    a 1 c sigh "\"That's good to know at least. I was really worried.\""
    mc 1 c considerate "\"Yeah. Just regular Jun, doing stuff that worried us without thinking.\""
    a 1 c "\"You were out for longer than I thought. What were you up to?\""
    mc 1 c "\"I got roped into staying for dinner.\""
    mc 1 c considerate "\"To which I'm sorry by the way. Since I don't have a phone, I couldn't let you know.\""
    a 1 c "\"It's alright. Mom actually got home early and cooked dinner.\""
    mc 1 c shock "\"Whoa, really?! She hasn't cooked in ages!\""
    a 1 c smile "\"I know. It was pretty good. She left some leftovers for you in the fridge. You can have them tomorrow.\""
    mc 1 c talk "\"Yeah, for sure. Is she in her bedroom now?\""
    a 1 c smile "\"Nah. We were watching TV together and she went to use the bathroom. That was just now so she shouldn't be long.\""
    play music2 "music/BGM/Snowy Day.ogg" fadein 5.0
    show a 1 c at fdis, three with move
    show mom 1 g smile at fdis, seven with moveiridis
    mom "\"[povFirstName], you're home!\""
    play sound "music/fabric.ogg"
    "I hear my mom's voice coming from the staircase and when I turn around I already have her arms wrapped around me."
    mc 1 c talk "\"Yeah, and so are you. I'm shocked.\""
    mom "\"I know. It's not often that I get breaks. I'm sorry about that.\""
    mc 1 c wry "\"It's okay. Sorry I wasn't home when you got here.\""
    mom "\"How was your little friend? Akiyoshi said you were worried about him?\""
    "Of course he did."
    mc 1 c considerate "\"I don't know if I'd call him \"little\". I mean, he isn't tall but he's also one year my senior.\""
    mom "\"You're not even twenty yet. You're all little.\""
    "She grins as she says so, wrapping her arms around mine and dragging me to the sofa."
    "Aki scoots over to one of the sides and mom forces me to sit down with her, taking the middle of the couch."
    mc 1 c sigh "\"I don't know if I can agree with that.\""
    mc 1 c "\"Not like there's much to tell. He was just out of the house for a few days for personal reasons. Once I got there, I was invited to stay for dinner and his parents fawned over me a bunch.\""
    mom "\"Oh. They seem like nice people.\""
    mc 1 c smile "\"They are.\""
    play sound "music/tap.ogg"
    show a 1 c happyb at fdis
    "Mom casually puts a hand on the top of both mine and Aki's head, petting us."
    "This is a habit she's had since I can remember."
    "Aki very clearly loves it. His tail wags enthusiastically under him."
    mc 1 c avoidb "\"Aren't I a little old for you to be doing this?\""
    mom "\"Of course not. You'll always be my son. You'll be forty and I'll still be petting you.\""
    mc 1 c happyb "\"...\""
    "I hate to admit it but... I do enjoy this feeling."
    "It came at such good timing too. I was feeling kinda envious about Jun and his home life."
    mc 1 c considerate "\"Maybe you should try to spend more time home, Mom.\""
    "She muses my question for a few moments, making a quiet humming sounds while she stares at the TV."
    mom "\"It's not like I don't want to. The office is just slammed.\""
    mc 1 c sigh "\"The office is always slammed. You haven't taken time off in almost two years.\""
    mom "\"I know...\""
    "Her voice comes out soft and quiet and I can tell she feels guilty over it."
    mom "\"But there are so many young people at work who hardly get to spend time with their families and if I take time off they won't get to because we're backed up.\""
    mc 1 c sigh3 "\"It's not your responsibility to let them take a vacation though. The administration in your office are the ones who should be worrying about that.\""
    mom "\"Yeah...\""
    "It's not like I can change her mind over it."
    "This has been a point of contention for years already."
    "She just feels all too happy to let others go in front of her, even if it means she barely gets to spend time with her family as a result."
    "I know being charitable is a good thing but this is too much."
    mom "\"It's just hard to say no, you know.\""
    mc 1 c worried "\"I know...\""
    a 1 c smile "\"He {i}definitely{/i} knows.\""
    "Aki laughs."
    mc 1 c sigh "\"Pipe down, pipsqueak.\""
    mom "\"[povFirstName], be nice to your brother!\""
    mc 1 c sigh "\"Yes, ma'am.\""
    a "\"Hey, Mom, do you think you'll be able to come to my next tournament?\""
    mom "\"When is that again, dear?\""
    a "\"In August.\""
    mom "\"Oh. That's a little far. I don't know if I'll be free.\""
    a 1 c sigh "\"Aww...\""
    mom "\"Ask me again in July and we'll see.\""
    a "\"Okay.\""
    "She turns to look at me, examining my face for a few seconds before the corner of her mouth lifts up in a smile."
    mom "\"What about you, [povFirstName]? How are your studies coming along?\""
    mc 1 c wince "\"I know we don't have time to catch up all that often but do you really have to ask me about school of all things?\""
    mom "\"I'm asking about important things.\""
    mc 1 c sigh "\"I dunno, I just feel like we could have other priorities.\""
    a 1 c smile "\"Yeah. Try asking him about his love life instead.\""
    "Aki leans forward on his seat, shooting me a knowing glance and smiling deviously."
    mc 1 c judge "\"You little-\""
    mom "\"Are you dating again?\""
    mc 1 c sigh3 "\"No, I'm not dating.\""
    a 1 c laugh "\"Are you sure?\""
    "... Aki, I'm gonna kick your ass."
    "This is even more infuriating now that I know Jun does have a crush on me and Aki was justified in thinking we were together."
    "Ugh, I wanna smack this brat."
    mc 1 c judge "\"Aki, don't make me shut you up by force.\""
    mom "\"[povFirstName]!\""
    mc 1 c sigh2 "\"Sorry.\""
    "Aki laughs, enjoying the benefits of being the youngest."
    "As in, not getting chastized for anything ever."
    "I swear I'll get back at him somehow."
    mom "\"So, are you hiding something from me now?\""
    mc 1 c sigh "\"No, Mom, I'm not hiding anything from you. I'm not dating anyone. And yes, Aki, I am sure.\""
    a 1 c smile "\"If you say so.\""
    "Little shit suddenly gets ten times livelier when he has to chance to tease me in front of Mom."
    mom "\"You know, I just wish you'd be a bit more... selective with this sort of thing. You've had so many girlfriends already and none of them stuck.\""
    mc 1 c wince "\"Mom, I really don't-\""
    mom "\"And I know you've tried to be safe with them because I raised you to have good sense but you never know, accidents can happen.\""
    mc 1 c shockb "\"M-mom!\""
    mom "\"I'm just saying, honey, think about your future. What happens to your career if you end up having a baby?\""
    mc 1 c flustered "\"Oh my God, we are {i}not{/i} having this conversation!\""
    show a 1 c laugh at fdis, shake1
    a "\"Ahahahahaha!\""
    "Aki clutches his stomach, laughing incredibly hard at my expense."
    "My face feels absurdly hot right now..."
    mom "\"I just want what's best for you, sweetie.\""
    mc 1 c avoidb "\"Mom, I swear I'm not going to end up fathering a child, now can we please stop talking about this? I {i}really{/i} don't want to talk about this kind of thing with you of all people.\""
    mom "\"Tch. You're such a prude. You sound just like your father. Talking about these kinds of things is healthy. You're at the age where its natural for you to have urges and your body-{nw}\""
    mc 1 c flustered "\"{size=+4}Stop! For the love of God, woman, stop!{/size}\""
    stop music2 fadeout 2.5
    scene BedroomN with fade
    show hour with dissolve
    $ renpy.pause(1.0)
    hide hour with dissolve
    "..."
    "Lying down on my bed and looking at the ceiling isn't one of the most interesting ways to pass my time."
    "At the same time, I don't really want to use the computer. Feels like that'd be too much effort."
    "Today was a really full day. I have way too much stuff I need to digest."
    "I toss and turn for a few minutes, stewing in my own thoughts for a while."
    "I wonder... do I really like Jun?"
    "I definitely feel happy spending time with him... but is that all that it is?"
    "I've never really had feelings for anyone before so I don't know what it's supposed to be like."
    "If I dated him... would I become part of his family dynamics too?"
    "Even though they struggle financially, those three seem so happy together."
    "It's not like I'm unhappy at home, but..."
    "Compared to them, I feel like there's something missing."
    "I miss spending family time like we did today."
    "But it was so short that it only left me craving for more."
    "I hate being reminded of the things I don't have."
    "I get used to not having it and it stops bothering me, but then whenever I get reminded it suddenly starts weighing on my mind again."
    "... I'm a mess right now."
    "Ugh... I'm just gonna take a bath and head to bed. I'm way too tired to be thinking right now."
    "... I'll get to talk to Jun tomorrow, too."
    "Just thinking about it, my tail starts wagging."
    "It does make me happy to know he has feelings for me..."
    "I'm scared that I might hurt him if I say yes and then change my mind though."
    play sound "music/fabric.ogg"
    "Goddamnit, why does everything have to be so complicated?!" with hpunch
    "..."
    "Yeah, I should definitely leave the thinking for another day."
    stop music fadeout 2.5
    $ date = None
    jump Day22_Jun
