label Day23_Jun:
    window hide
    scene June9 with fade
    play sound "music/windchimes.ogg"
    show blossoms movie
    $ renpy.pause(5.5)
    play music2 "music/BGM/Spring Classroom.ogg" fadein 5.0
    scene SClass
    show shima 1 u smile
    with fade
    window show
    $ date = "day23"
    play sound "music/schoolbell.ogg"
    "The school bell finally rings, marking the end of the last day of midterms."
    "Reactions are mixed inside the classroom, with many students groaning or cursing as they failed to finish their tests."
    "Others are jubilant to finally be done with this hellish week."
    "After all, the last thing a student body wants to deal with is a full week of tests right after a full week of having fun with a festival."
    "If I could meet whoever it was that made up this scheduling, I'd have some very strong choice words for them too."
    "... After having graduated so they couldn't take it out on my grades of course."
    shima "\"Very well, students. Everyone pass their papers along. Don't even try to keep writing, if you so much as touch the paper with your pen after the bell rings I will give you a zero.\""
    "Shima-sensei goes around collecting everyone's papers."
    "While everyone else has scowls or frowns or just looks plain defeated, the stag alone is the picture of health and peace."
    "... Probably because it wasn't {i}he{/i} that just spent a whole week studying non-stop and stressing over tests."
    "Do I sound bitter? I feel bitter."
    shima "\"Now I want you all to remember, just because your tests are over doesn't mean you can slack off. You still have the entire school year ahead of you, even if there's a few months before midterms start again.\""
    "I doubt anyone is even listening at this point."
    "Most of everyone is just nodding along to everything he says with the most souless eyes possible."
    shima "\"I sincerely hope you've all done well in your tests. The results will be posted next Friday and club activities can resume again next week. You are all excused for today.\""
    play sound "music/slidingdoor.ogg"
    show shima 1 u smile at offscreenright with moveoridis
    "He walks out of the room, carrying all of our exams with them."
    "As soon as he leaves, the class lets out a collective sigh of relief."
    show j 1 u wince at fdis, five with dissolve
    j "\"Finally over...\""
    "Jun is slumped over his desk, exhausted."
    "The poor guy has barely had any breaks since the week started. He'd come over to my place right after the exams were over and we'd study non-stop until 10 or 11PM depending on the day."
    "That only just leaves him time to get home, eat and sleep."
    "That's going to be a miserable existence for anyone, especially if they're not used to this sort of thing."
    mc 1 u talk "\"You hanging in there alright?\""
    j 1 u sigh "\"If I die... tell my mother I love her.\""
    mc 1 u considerate "\"If you can crack jokes then I guess that means you're fine.\""
    j 1 u avoid "\"I want to do something fun. I'm fun-starved. I need to relax.\""
    mc 1 u smile "\"Huh. And here I thought you'd just go straight home and flop onto your bed, not waking up until tomorrow.\""
    j "\"No way. I need to relaaaaax.\""
    mc 1 u happy "\"Yes, I heard you the first time. You don't need to emphasize it.\""
    j 1 u talk "\"Do you have any plans for the day, [povFirstName]-san?\""
    mc 1 u smile "\"Nope. Not a one.\""
    j 1 u considerate "\"How about we do something together? We could invite the others two. I'm sure they'd welcome a break as well.\""
    mc 1 u worried "\"Yeah. I'm still a bit worried about Shoichi. He hasn't talked to me at all since Monday and he looked pretty stressed out then.\""
    j 1 u avoid "\"Oh... right. I forgot about that.\""
    j 1 u considerate "\"But hey, tests are over now. I'm sure he'll have more time to hang out!\""
    mc 1 u smile "\"Yeah, you're probably right. I'll send them all a message.\""
    j 1 u shock "\"Oh. Did you buy a new phone already?\""
    mc 1 u considerate "\"Yeah. I couldn't go too long without one. My mom chewed me out for breaking mine though. Forced me to get one worse than my previous one as a lesson.\""
    j 1 u avoid "\"O-oh...\""
    mc 1 u talk "\"It's alright. I don't even use my phone much so it's not like it makes that much of a difference for me. Also, there. Message sent.\""
    play sound "music/phonebeep.ogg"
    j 1 u happy "\"How about we go out to eat? I'm hungry.\""
    mc 1 u considerate "\"Have you been eating after getting home?\""
    j 1 u considerate "\"Uhm... Sometimes?\""
    mc 1 u sigh "\"Define \"sometimes\".\""
    j 1 u wince "\"I had dinner on Monday. The other days I was too sleepy so I just went to bed.\""
    mc 1 u sigh "\"You've been going without dinner for a week?!\""
    j 1 u considerate "\"Hehehe...\""
    mc 1 u sigh3 "\"Don't just laugh at that. I'm serious, Jun, you need to take care of yourself.\""
    j 1 u avoid "\"I'll be fine. I'm just a little tired is all. I just need a break.\""
    "I sigh, quickly typing an invite to shoot the others while I try my best to look annoyed so I can drive my point home."
    j 1 u wince "\"Come on, [povFirstName]-san, don't be mad at me.\""
    mc 1 u sigh "\"Then eat properly. Preferably now. I'll treat you.\""
    show j 1 u wince at fdis, jumping
    j "\"What? You don't have to treat me. I'm fine paying for myself.\""
    mc 1 u avoid "\"No. I'll treat you and that's that.\""
    "Especially cause I feel a little guilty over this. I've been cooking dinner for me and Aki after Jun had already left for home."
    "I probably should have just taken a dinner break and offered to let him eat with us."
    "But I thought for sure he'd be eating the food he had at home when he got there so I didn't even think of that..."
    mc 1 u sigh3 "\"And I've already messaged everyone. Come on, I asked them to meet us by the gates.\""
    j 1 u happy "\"Okay!\""
    scene SGate
    show j 1 u avoid at fdis, five
    with fade
    show minutes with dissolve
    $ renpy.pause (1.0)
    hide minutes with dissolve
    "Now that exam week is over, the amount of students lingering around after the end of the school day is much bigger."
    "Now that they have the room to breathe and catch up without fearing for their grades, they're taking the opportunity to be social again."
    "Just like we are."
    "Or would be, except..."
    mc 1 u worried "\"Damn, I just got an answer from Keisuke. He says he's gonna be busy with band practice. Saya and Shoichi both just said they couldn't come and didn't speak another word about it.\""
    j 1 u wince "\"Aww, I was looking forward to getting everyone together.\""
    mc 1 u considerate "\"This sort of thing happens, people get busy sometimes. It's no big deal.\""
    j 1 u avoid "\"I guess. I wonder what we should do now.\""
    mc 1 u considerate "\"Guess it'll be just the two of us together today again.\""
    "Because of the exams, we've been spending quite a bit of time alone together lately."
    "It doesn't bother me, but a little voice on the back of my head keeps telling me to panic whenever the two of us are alone in a room."
    "... And Jun hasn't been shy about touching me or leaning against me either."
    "I mean... I guess I did start it but when he does it too I feel self-conscious..."
    "... Although I'm pretty sure I like the attention."
    show j 1 u talk at fdis
    j "\"What do you think we should do? Should we just go out to eat and call it a day?\""
    mc 1 u talk "\"I suppose. Besides, we didn't have any plans either and it's hard to think of stuff to do at the last moment.\""
    j 1 u think2 "\"Yeah, I guess that's true.\""
    "Just then, I spot a few familiar faces leaving the school building all together."
    show j 1 u watch at fdis, zeroh with move
    show gin at fdis, twoh
    show jin at fdis, fourh
    show vic 1 u smile at fdis, sixh
    show ryoji at fdis, eight
    show so 1 u smile at fdis, tenh
    with moveiridis
    "Most of our classmates show up, all of them walking side by side and chatting with each other."
    "And... wait, is that Sora-kun with them? What's he doing there?"
    jin "\"Oh, hey there. I see you guys survived hell week.\""
    mc 1 u "\"Yep. I'm surprised you of all people did.\""
    show jin at fdis, jumping
    jin "\"What's that supposed to mean?\""
    mc 1 u talk "\"Exactly what I said. Anyway, what's up?\""
    gin "\"We're all going out together to celebrate being done with midterms.\""
    j 1 u talk "\"Wait, but Sora-kun, what are you doing with my classmates?\""
    "The panda rubs the back of his neck, laughing nervously."
    so "\"It just... kinda worked out this way I guess?\""
    vic "\"We started chatting every now and then after we met when we... erm... went to see you in the hospital.\""
    "Sora nods, smiling."
    so "\"Yeah. So he invited me to go out with everyone. I don't really know many people in my own class so I thought it'd be nice to go out.\""
    j 1 u happy "\"Oh, I see. Thank you for that!\""
    "The fox smiles and nods, sticking his chest out with pride."
    mc 1 u smile "\"Heh. I'm surprised you can even talk to them. When I first met you you were a stuttering mess.\""
    "The panda's eyes go wide for a second and he blinks rapidly a few times as his brain tries to process."
    so "\"That's... that's not...\""
    gin "\"Do you guys want to join us too?!\""
    "Gin quickly cuts into the conversation, a forced smile on his face."
    mc 1 u "\"Well... we were talking about going out together too but the rest of our group was too busy so we weren't sure what we would do together.\""
    gin "\"That's perfect then. We were going out downtown. Jin wanted to try go karting and we were going to stop for food on the way.\""
    j 1 u shockb "\"Karting?!\""
    "At the simple mention of karting, Jun's eyes immediately light up and I know then and there that we have to go along with them."
    mc 1 u happy "\"Okay, that sounds like a plan we can get behind on, right Jun?\""
    j 1 u happy "\"Yeah!\""
    "He nods excitedly, laughing."
    "Somehow he already seems much livelier than before."
    "Although with Jun, that isn't exactly a challenge either."
    show j 1 u watch at fdis
    mc 1 u "\"Although I have to ask... how did you guys get him of all people to tag along?\""
    "I gesture to Kumagawa with my head and everyone follows my gaze right back to him."
    "The bear, however, doesn't take his eyes from his console for even a single second and doesn't notice our stares."
    jin "\"Honestly, I'm as shocked as you are.\""
    "Jin shrugs, deciding that the thought doesn't really merit any thinking about."
    gin "\"Vic-kun invited him and he came along.\""
    vic "\"Yeah. I was actually a little surprised too but he said yes anyway. Hey, Ryoji-san.\""
    "At the mention of his name, the bear finally looks up and notices us staring at him."
    "He raises an eyebrow and looks confused for a second."
    ry "\"Yes?\""
    mc 1 u talk "\"I don't mean to offend but... what are you doing here? You're one of the last person I'd imagine tagging along.\""
    ry "\"They said they were going downtown and I thought it'd be a good chance to swing by my favorite store to pick up a new game that just came out.\""
    show j 1 u considerate at fdis
    play sound "music/disappointment.ogg"
    mc 1 u smile "\"Ah... I guess that's a reason to tag along. I knew a big videogame nerd like you wouldn't go out into the wild of his own volition. Especially given the risk you might burst into flame on contact with the sun.\""
    "There are some snickers within the group as the bar goes back to playing his game."
    ry "\"Although I suppose karting might be fun too.\""
    show j 1 u shock at fdis
    mc 1 u shock "\"Wait wait wait. You're interested in doing something fun... in real life?!\""
    j 1 u considerate "\"H-hey, [povFirstName]-san, I think you're making too big a deal out of this.\""
    mc 1 u sigh "\"Don't give me that look, you were just as shocked as I was.\""
    gin "\"I didn't know you had an interest in karting, Ryoji-kun.\""
    "The bear shrugs."
    ry "\"It'd be like a real life version of a videogame.\""
    show gin at fdis, jumping
    gin "\"Oh, I see now! Yeah, that makes sense.\""
    mc 1 u "\"I'm sorry but if we start firing cannon balls and missiles at each other while karting that'll be my cue for retiring from the race.\""
    j 1 u think "\"Hmm... I think that could be fun.\""
    "... Surely you're kidding."
    so "\"I wonder if banana peels would actually be able to make a kart slip.\""
    jin "\"How about we buy some before we go and give it a try\""
    mc 1 u considerate "\"... We're going to get kicked out of the venue aren't we?\""
    gin "\"Littering aside, bananas can be a pretty good snack before these kinds of activities. They won't weigh on your stomach and they'll fill you with energy. They're pretty healthy.\""
    mc 1 u suggestive "\"Healthy, huh? Didn't know you had an interest in that sort of thing.\""
    "Gin stutters, looking at me with pursed lips and a frown."
    "He almost seems... confused?"
    "Eventually, he stammers out an actual response, sighing."
    gin "\"We should probably just get going.\""
    stop music2 fadeout 2.5
    play music3 "music/BGM/Groundwork.ogg" fadein 5.0
    scene Cafe
    show j 1 u watch at fdis, zeroh
    show gin at fdis, twoh
    show jin at fdis, fourh
    show vic 1 u smile at fdis, sixh
    show ryoji at fdis, eight
    show so 1 u smile at fdis, tenh
    with fade
    show sometime with fade
    $ renpy.pause (1.0)
    hide sometime with dissolve
    "We all head out to a small coffee shop downtown for a quick eat."
    "The staff has to merge two tables together to accommodate our little menagerie."
    "Because of the day and time we got here, we had to wait a while before they finally got tables for us but the whole process was overall pretty painless."
    mc 1 u talk "\"Hey, there's one thing I always wondered. What's the difference between a coffee shop and a café?\""
    jin "\"How much they want to charge you.\""
    mc 1 u considerate "\"I doubt it can be just that.\""
    j 1 u think2 "\"Maybe how fancy the environment is?\""
    j 1 u talk "\"I mean, this place is nice and all but it's not like the café I went with you before, [povFirstName]-san.\""
    so "\"It's probably the same as the difference between a diner and a restaurant.\""
    mc 1 u considerate "\"I'm pretty sure there are differences other than the price tag and how fancy the place is.\""
    jin "\"Oh yeah? Name one.\""
    mc 1 u wince "\"I dunno, I'm not an expert on the subject. All I know is I've been to some really fancy diners and some really rundown restaurants so I don't think that applies.\""
    gin "\"That's a good point.\""
    so "\"Maybe we could ask a waiter what the difference is?\""
    mc 1 u considerate "\"{i}Sure{/i}. Just call him over and ask \"Hey, why isn't your establishment called a café? Are you guys not fancy enough?\". I'm sure that'd go swimmingly.\""
    show so 1 u smile at fdis, jumping
    so "\"I didn't say you had to phrase it like that.\""
    j 1 u considerate "\"Sora-kun, he's just messing with you.\""
    jin "\"What are you guys going to order anyway? I wouldn't recommend getting anything too heavy. Wouldn't want to get sick on the karts.\""
    vic "\"But if you do, that could serve as a stand-in for a banana peel!\""
    mc 1 u sigh "\"Ew, gross.\""
    j 1 u watch "\"What do they have on the menu anyway?\""
    gin "\"Probably just basic coffee shop stuff. Some sandwiches, a few baked goods and some drinks.\""
    j 1 u think "\"Depending on how many varieties of those things they had, the menu could still end up pretty big though.\""
    gin "\"That's true.\""
    ry "\"You can just look at the huge menu they have behind the counter instead of asking yourselves that.\""
    j 1 u shock "\"Oh, I didn't even notice that!\""
    ry "\"Evidently.\""
    show j 1 u watch at fdis
    "Behind the counter is a huge blackboard with a bunch of different options and prices written down in faded white chalk."
    "I guess the chalk was so faded that we couldn't make out it was actual writing until we were seated."
    mc 1 u talk "\"Wow, they're really old-school. They still have menus on chalk.\""
    so "\"I think the word you're looking for is outdated. They could just go with a simple laminated menu instead. It's much simpler and probably allergy free.\""
    j 1 u talk "\"Can you even be allergic to chalk?\""
    jin "\"Wouldn't surprise me. Some people are allergic to dust.\""
    gin "\"Or pollen.\""
    vic "\"I knew a guy who was allergic to his own fur.\""
    show j 1 u wince at fdis, shake1
    j "\"Ouch, that's gotta be terrible.\""
    mc 1 u confused "\"What a miserable little life that guy must live.\""
    so "\"Some people are allergic to water too. That must suck a lot too.\""
    mc 1 u considerate "\"Sure, but imagine being allergic to {i}yourself{/i}.\""
    ry "\"How about being allergic to dirt and water at the same time. Then you have reactions whenever you're dirty but can't shower because you're allergic to the water.\""
    j 1 u considerate "\"I don't even want to imagine that. I'd probably go insane.\""
    mc 1 u talk "\"I like taking baths way too much to begin with. I'd be very sad if I couldn't.\""
    j 1 u avoid "\"These people must need really strong coping mechanisms and support groups to get through life like that.\""
    "There is a silent agreement on our table as everyone nods along."
    j 1 u watch "\"Is anyone here even allergic to something?\""
    jin "\"Nii-chan and I are both lactose intolerant but I don't know if that counts as an allergy.\""
    gin "\"Lactose allergy is basically the more gung-ho version of lactose intolerance.\""
    ry "\"I'm lactose intolerant too.\""
    so "\"Lactose intolerance is actually a really prevalent thing in most of Asia. It's pretty easy to find people who suffer from it.\""
    vic "\"In that sense I guess I kinda lucked out. European genes here, haha.\""
    mc 1 u "\"Everone in my family is pretty healthy. We don't have any allergies... I think.\""
    j 1 u think "\"I'm allergic to some types of medication. Heparin, Benazepril... Aspirin. There's some others I don't remember off the top of my head.\""
    vic "\"I have no idea what half that stuff is.\""
    mc 1 u "\"How do you even know that stuff? Like, don't you have to be given medicine to find out you're allergic to it?\""
    j 1 u considerate "\"Uhm... sorta? The doctors test you for stuff too.\""
    show j 1 u avoid at fdis
    "I stare at him with a raised eyebrow, feeling very suspicious all of a sudden."
    "The tiger immediately shrinks on his seat, looking away from me and at the menu on the wall."
    j 1 u considerate "\"Hey, did you guys decide on what you're gonna order? I think I'm gonna get a tuna sandwich and some juice.\""
    vic "\"Blegh. I can't stand most seafood.\""
    jin "\"Dude, then you came to the wrong country.\""
    gin "\"Nah, other meats are also really easy to find in Japan.\""
    jin "\"Only cause it gets imported from outside.\""
    gin "\"Hmm... that's true. Japan doesn't have much land to raise livestock.\""
    so "\"I think I'll order a bagel.\""
    vic "\"Are those... pizza squares? Those are a thing in Japan?\""
    j "\"I think they're a thing in most of the world.\""
    "Just like that, the conversation switches back to food once more."
    "However, Jun continues to avoid my gaze and I don't feel comfortable asking him questions like that in public, especially when he looks so desperate to avoid the subject."
    "..."
    scene Kart
    show j 1 u shock at fdis, zeroh
    show gin at fdis, twoh
    show jin at fdis, fourh
    show vic 1 u smile at fdis, sixh
    show ryoji at fdis, eight
    show so 1 u smile at fdis, tenh
    with fade
    play sound "music/crowd01.ogg"
    "After we're finished with lunch, we all head right to the karting venue Jin mentioned."
    "The place is... surprisingly big."
    "There are multiple tracks inside and apparently people can race in groups of 8."
    "Which means since there are seven of us, at least one racer in our track would be some random person."
    "The place looks pretty busy."
    "Probably since it's Friday and classes are done for the day in most schools."
    j "\"Wow, I've never been to a place like this before. It's so huge!\""
    mc 1 u talk "\"Actually, surprisingly neither have I.\""
    jin "\"Yeah, it's pretty neat. I come here every now and then when I just wanna have fun. It feels good to crush the newbies!\""
    gin "\"What he means by that is that he spends most of his allowance here.\""
    show jin at fdis, jumping
    jin "\"Hey!\""
    "The smaller mouse glares at his older brother, who seems as calm and serene as he always does."
    gin "\"He also likes to go the baseball batting cages down the street.\""
    jin "\"Ooooh, that'd be a good idea too! We should go there after we're done here.\""
    j 1 u watch "\"I've never been to one of those. What are they like?\""
    mc 1 u "\"You get a baseball bat and a helmet, get inside a cage and a robot shoots balls at you that you can bat.\""
    show j 1 u shockb at fdis
    "Jun's eyes immediately shine and I can already tell we're going to have to go there as well."
    j "\"A robot?! That's so cool! I wanna go see the robot!\""
    mc 1 u sigh "\"What? No, I don't mean a {i}robot{/i} robot, just a- You know what, forget it, we'll go after we're done with the karts if no one else has any objections.\""
    show j 1 u happy at fdis
    vic "\"None here.\""
    so "\"Yeah, I'm fine with. I wonder if they'd have some place around here where you can play ice hockey.\""
    jin "\"I've never seen any. Wouldn't you need to a team to play that anyway?\""
    mc 1 u "\"You need a team to play baseball and yet you have batting cages anyway.\""
    jin "\"Oh. Right. I guess that's true.\""
    gin "\"Anyway, are we going to join the line or are we just going to stand around here gawking at the place?\""
    j 1 u watch "\"The line doesn't look too big. I don't think it'll take too long.\""
    "Luckily, the line is moving somewhat fast just like Jun mentioned."
    "Apparently each person pays for a number of laps here."
    "Once each racer finishes running five laps they have to drive to the exit and a new set of racers enters after everyone has finished theirs."
    "Which means the one who wins the race is also the one that gets to drive the least amount of time."
    j 1 u talk "\"I didn't even look at the prices. How much is it anyway?\""
    mc 1 u smile "\"I can treat you if you want.\""
    j 1 u considerate "\"No, I'm fine with paying for myself. You already treated me to food, [povFirstName]-san. I don't want to mooch.\""
    mc 1 u happy "\"It's not mooching if I enjoy doing it.\""
    j 1 u wince "\"You and I have very different definitions for the word.\""
    ry "\"It's ¥500 for 5 laps.\""
    j 1 u talk "\"That's not too bad. It's pretty okay actually.\""
    mc 1 u considerate "\"Does that even cover the cost of running the place?\""
    "The bear shrugs, either not knowing the answer to my question or not being bothered enough to give it."
    j 1 u smile "\"How about we go multiple times? Like, say, fifteen laps?\""
    mc 1 u talk "\"Wow, someone's greedy.\""
    j 1 u happy "\"I can't help it. It just looks like so much fun!\""
    mc 1 u smile "\"Just make sure you don't bleed your wallet dry in the process.\""
    j 1 u pout "\"It's only ¥500. I'll be fine!\""
    "Yes, it's only ¥500... if done once."
    "If you keep doing it over and over again it'll stack up."
    "Still, I quietly sigh and just decide to let that go for now."
    "No sense trying to... well, talk sense into him."
    j 1 u talk "\"How fast can these go anyway?\""
    mc 1 u talk "\"I dunno. You'll have to ask the clerk when its our turn. Although it probably doesn't go very fast given that kids are allowed to drive these.\""
    j 1 u watch "\"Yeah, I guess that makes sense.\""
    jin "\"Yeah, they're not very fast. They definitely look faster than they feel, which is a real bummer.\""
    gin "\"I'm glad they're not that fast. You already lose control half the time as is.\""
    show jin at fdis, jumping
    jin "\"You didn't have to tell them that!\""
    vic "\"It's not like people wouldn't figure out once you started crashing onto us.\""
    jin "\"I don't {i}crash{/i}!\""
    j "\"Really? Then what do you call it?\""
    jin "\"... Bulldozing?\""
    mc 1 u sigh "\"Your attempt to make it sound less lame only makes you sound even lamer.\""
    jin "\"Screw you, I'm not lame! You're not gonna tear me down!\""
    mc 1 u "\"No need. You already do that to yourself way better than I could ever hope to.\""
    "I hear a few whistles to my response as the younger mouse stares at me with a murderous temper tantrum."
    j 1 u considerate "\"[povFirstName]-san, you don't have to be so mean.\""
    mc 1 u sigh "\"How am I mean?\""
    vic "\"I'm convinced you don't notice half the stuff that comes out of your mouth.\""
    play sound "music/stab.ogg"
    "What?!" with hpunch
    mc 1 u worried "\"I'm not... I'm not mean, am I?\""
    j 1 u avoid "\"M-maybe not mean. Maybe... abrasive would be a better term?\""
    mc 1 u curious "\"Abrasive? Wow, I'm surprised you know that word.\""
    j 1 u judge "\"There it is! That's what I'm talking about!\""
    mc 1 u shock "\"Huh?!\""
    j 1 u annoyed "\"You say that kind of thing all the time without even caring how insulting it can come out.\""
    mc 1 u wince "\"I-I do?\""
    j 1 u sigh "\"Some days more than others.\""
    vic "\"I think you've insulted every single one of us at least once today.\""
    jin "\"Some more than others.\""
    "Jin frowns, shooting me daggers with his eyes and crossing his arms."
    mc 1 u worried "\"I didn't...\""
    j 1 u considerate "\"It's easy to forgive because we know you don't mean it and sometimes you're just trying to make a joke but it can get annoying every once in a while.\""
    jin "\"That's putting it mildly.\""
    vic "\"I mean, I don't personally mind it all that much. I think it's normal for good friends to insult each other.\""
    gin "\"Not everyone is the same way though. Some people don't like that sort of thing.\""
    so "\"People especially don't want someone following them around basically acting like a mirror to constantly point out and remind them of their flaws.\""
    mc 1 u worried "\"But I... I didn't...\""
    "Jun places his hand on my shoulder and gives me a gentle squeeze, smiling mournfully at me."
    j "\"Just dial down on it for a bit, okay? Most of the time you're okay but it's like you've dialed it up to eleven today.\""
    mc 1 u wince "\"Does... everyone think the same?\""
    show j 1 u watch at fdis
    jin "\"The only one who didn't speak up about it is Ryoji, but then again, I'm convinced he's not even listening to our conversation. Watch.\""
    "Jin taps the brown bear's shoulder a few times and calls out his name."
    jin "\"Yo, Ryoji.\""
    "The bear sluggishly looks up, his eyes quickly scanning around him and looking at each of us."
    ry "\"What?\""
    jin "\"What's your take on it?\""
    ry "\"My take on what?\""
    "The younger mouse makes a gesture with his hand, pointing at the bear with a smug smile on his face."
    jin "\"See?\""
    "Kumagawa frowns, staring at Jin with confusion."
    jin "\"Never mind. You can go back to playing your game. We'll let you know when its our turn.\""
    so "\"What are you even playing? Must be really good for you to be this distracted.\""
    ry "\"Dragon Rush Saga XXXIV.\""
    "The panda frowns."
    so "\"The what? I've never heard about it.\""
    ry "\"It's an obscure gaming series from a mobile game development company. It's pretty terrible.\""
    so "\"Then... why are you playing it?\""
    ry "\"The romanceable girls are cute.\""
    so "\"...\""
    "Sora stares at the older bear with a look that I can't quite identify."
    "It might be disgust or he might just be constipated, who knows?"
    "... It's probably disgust though."
    jin "\"I think he's played more bad games than I've played games in general.\""
    mc 1 u smile "\"That's pretty easy to do when you have no life other than playing games.\""
    show j 1 u sigh at fdis
    "I immediately get a bunch of blank stares pointed right at me and the awkwardness comes flooding in really quickly."
    mc 1 u avoid "\"... I'll shut up.\""
    stop music3 fadeout 2.5
    play music2 "music/BGM/Feelin Good.ogg" fadein 5.0
    scene Kart with fade
    show minutes with dissolve
    $ renpy.pause (1.0)
    hide minutes with dissolve
    "Once our turn in line finally comes, we're each given a kart and the venue employees help us get strapped in properly to our seats."
    "Half of me is surprised Gin managed to fit inside his kart but after the awkward conversation we had not twenty minutes ago, I don't dare voice those thoughts."
    "I'll just ignore the little voice inside of my head telling me to crack jokes at the things I see..."
    "I ended up being given a purple colored kart with the number \"7\" stamped in white on the front of it."
    "All things considered, I don't mind the look of it."
    "I would definitely have preferred the red kart though but, well, I don't really get to choose."
    "Jun was given a green kart with the number \"4\" on it and made a passing comment about how he wished he'd gotten orange instead."
    "The employees went over basic instruction."
    "Taught us how to accelerate, break, how to do curves and general knowledge."
    "They were very thorough with their explanations too because it took almost five minutes for them to finish."
    "On top of the starting line is a big LED screen the does a countdown to take-off."
    "My eyes were glued on the thing as soon as it beeped the first time."
    "5... 4... 3... 2... 1."
    play sound "music/car.ogg"
    "As soon as it rang with the final beep, all engines were revved up to the max and the race started."
    "The whole race is comprised of a small circuit with a few twists and curves mixed in."
    "Nothing too crazy. Definitely no videogame level tracks where we have to make crazy jumps over ramps and whatnot."
    "That'd just be begging for a lawsuit."
    "On the very first curve, the first thing I notice is Jin accelerating even more when we were clearly told to slow down for the curves."
    play sound "music/disappointment.ogg"
    "He tries to go for a drift but ends up spinning out of control instead."
    "The sides of the track are surrounded by a bunch of foam blocks chained together into a single, bendable piece."
    "Once he crashes, the wall sort of deforms around his kart and absorbs the impact."
    "Probably not a bad idea, adding some sort of cushioning to the track will keep people from getting hurt."
    "God forbid their walls were made of car tires stacked on top of each other instead."
    "As soon as you hit them they might all collapse on top of you and I shudder to think of the damage."
    "Having never gone karting before, I'm being extra careful to avoid a fate like Jin's so I'm going a bit on the slow side."
    "Meanwhile, Gin is right ahead of me being another careful, if slightly more experienced driver."
    "Victor and Sora are both speeding ahead and trying to just straight up win without caring about crashing - though they are still noticeably more careful than Jin."
    "Kumagawa and Jun are both at the very back, going super turtly and just... I dunno, enjoying the scenic view?"
    "Frankly, I don't see the point to driving if you're gonna go that slow."
    "Then there's the random person that's also in the track with us."
    "He's currently right behind me and doesn't seem to be making much of an effort to pass me by."
    "I have to say, the feeling of the wind on my face and having my fur and clothes flutter against it is really nice."
    "I didn't know going this fast could be so much fun."
    "Maybe I could try going a little faster?"
    menu:
        "Accelerate":
            "I step foot on the gas pedal and decide to ramp up my speed a little."
            gin "\"Hey!\""
            "I briefly hear Gin's voice as my vehicle goes past him and I begin to gain on him."
            "Victor and Sora are both really far ahead by now and I'm not sure I can gain on them before the end of this lap at least."
            "I also don't want to what Jin did and end up crashing because he's now dead last thanks to that."
            "Behind me, I hear the sound of motors revving up even more and with a quickly glance behind, I see that those on the back decided to accelerate in response to my sudden burst of speed."
            "Gin is right on my tail with Kumagawa and Jun right behind him."
            "The eight driver seems content to just keep pace and lets everyone else pass him by without a care, probably thinking it's not worth it to risk going faster."
            "But then again, he looks younger than us so maybe he's just scared to go too fast."
            "We reach a curve and everyone slows down to keep from losing control."
            "Jun manages to overtake both Kumagawa and Jin by doing a tight curve and rides right next to me."
            j 1 u gentle "\"[povFirstName]-san, I'm gonna beat you!\""
            "He steadily gains on me, going for the tightest possible curves every time."
            "By the time we finish our third lap, Jun is pressed right against me and I'm at risk of being left behind."
            "While I don't think I can get past the other two currently contending for first place, beating Jun is the difference between a podium finish and 4th place!"
            "... Even though there isn't really a podium here."
            "He's really close to me so... maybe if I cut him off on one of the curves I might force him to slow down?"
            menu:
                "Cut him off":
                    $ day23_juncrash = True
                    "Steeling myself, I decide to throw my car at the next curve and cut him off as closely as possible."
                    "Hopefully the scare will cause him to decelerate and the gained momentum on my end will assure I keep my advantage."
                    "On the other hand, if he doesn't... we just might crash into each other."
                    "Still, you need to take risks sometimes!"
                    $ junlove -= 1
                    "As soon as the curve comes up, I do as I planned at nearly ram my car into his."
                    j 1 u shock "\"Wha-?!\"" with hpunch
                    "In his attempt to slow down and avoid me while making the curve, Jun loses control of his kart and spirals out of control."
                    play sound "music/crash.ogg"
                    "He knocks onto the foam barriers and makes a noise... slightly louder than I would have hoped."
                    mc 1 u shock "\"Woah, Jun!\""
                    "I cry his name out but quickly leave him behind."
                    "I wait impatiently for a few seconds while driving to see if the race will be halted or if they'll give us any sign of an accident."
                    "I know they said if there a bad crash the race would stop."
                    "But nothing happens."
                    "If... nothing's happening then that means Jun is fine and still racing, right?"
                    "But I don't see him or his kart again and, sure enough, by the time we reach the end, there are only seven of us in the track."
                    "I cross the finish line a few seconds later, ending the race in 3rd place."
                    scene Kart
                    show j 1 u pout at fdis, zeroh
                    show gin at fdis, twoh
                    show jin at fdis, fourh
                    show vic 1 u smile at fdis, sixh
                    show ryoji at fdis, eight
                    show so 1 u smile at fdis, tenh
                    with fade
                    "By the time we all leave our karts and go back to the lobby, an angry tiger runs up to me, his cheek bulging."
                    "Jun was already out here waiting for us."
                    j "\"You made me crash!\""
                    "He pokes me a couple of times in the chest, hard enough to it hurts."
                    mc 1 u wince "\"Ow ow ow, cut it out. That hurts.\""
                    vic "\"What were you thinking, [povFirstName]-kun? You could have hurt him.\""
                    mc 1 u wince "\"What? I just made a tight curve. He did the same thing to the others to get a lead.\""
                    j "\"Not from that close! You literally threw your car at me to make me break!\""
                    mc 1 u wince "\"Y-you can't know that for sure.\""
                    gin "\"That was kinda shitty, [povFirstName]-kun.\""
                    so "\"Are you alright, Jun-san?\""
                    j 1 u considerate "\"Yeah, I'm fine. The seatbelt stopped me kinda violently and it hurt my chest a bit... kinda left me gasping for air a bit.\""
                    mc 1 u worried "\"Wait, really? I didn't think you could hit the wall that hard.\""
                    j 1 u sigh "\"Going as fast we were? Of course you can.\""
                    mc 1 u worried "\"I-I'm sorry. I didn't mean to hurt you.\""
                    j 1 u avoid "\"Just don't do that sort of thing again. That's dangerous and you could get yourself and other people hurt.\""
                    mc 1 u worried "\"Sorry...\""
                    "An awkward silence rooms over the seven of us, everyone shoots each other glances but no words are said."
                    "Even Kumagawa, who doesn't have his phone or console anywhere in sight."
                    jin "\"So... uhm... should we... go again?\""
                    so "\"I wouldn't mind. Accident aside, it was fun.\""
                    vic "\"Yeah. We could, I guess.\""
                    j 1 u considerate "\"You guys can go. I'll stick this one out.\""
                    mc 1 u wince "\"What? But you said you wanted to go multiple times.\""
                    j "\"I don't think that's a good idea right now. I better just rest for a bit. The crash kinda took a lot out of me.\""
                    mc 1 u worried "\"T-then I'll stay with you.\""
                    j 1 u wry "\"Nah. You should go too. I don't want you to stop having fun on my account.\""
                    mc 1 u worried "\"But I-\""
                    j 1 u considerate "\"Pretty please?\""
                    mc 1 u worried "\"...\""
                    "Jun smiles at me, almost pleading."
                    "Hesitantly, I nod."
                    j 1 u smile "\"I'm gonna watch you guys from the seats. Have fun.\""
                    jin "\"Will do. And you take care of yourself, okay?\""
                    j 1 u happy "\"Yeah, of course.\""
                    "..."
                "Don't":
                    $ day23_juncrash = False
                    "Even though the daredevil inside of me wants to do it, it could be dangerous."
                    "If Jun didn't react fast enough he could crash onto me and that could be pretty ugly."
                    "I don't want to risk our safety just for a silly race."
                    "We go through the curve and as I expected, Jun once again makes it as tightly as possible, managing to pass me by."
                    "He lifts an arm out of his kart and waves at me."
                    j 1 u gentle "\"Bye bye!\""
                    "He accelerates further and manages to gain a sizeable lead over me despite being among the latest racers at the start."
                    "By the time we reach the finish line, Jun solidly placed himself in 3rd place, getting really close to passing by Victor for 2nd."
                    scene Kart
                    show j 1 u gentle at fdis, zeroh
                    show gin at fdis, twoh
                    show jin at fdis, fourh
                    show vic 1 u smile at fdis, sixh
                    show ryoji at fdis, eight
                    show so 1 u smile at fdis, tenh
                    with fade
                    "We all step out of the course, chatting excitedly amongst ourselves."
                    j "\"Hehehe, that was really fun.\""
                    mc 1 u talk "\"You're just being smug because you finished in third.\""
                    j 1 u happy "\"What? Of course not. I was having fun even when I was last place.\""
                    jin "\"Besides, what kind of loser feels smug over 3rd place? Pfft.\""
                    gin "\"Said the loser who finished in last.\""
                    show jin at fdis, jumping
                    jin "\"Hey!\""
                    ry "\"So much for your talks about having so much experience.\""
                    show jin at fdis, jumpingx3
                    jin "\"I never said I was sure to win just because of that.\""
                    ry "\"No, you just said something about how you loved to \"crush the newbies\".\""
                    mc 1 u considerate "\"Talk about instant karma.\""
                    jin "\"Jeez, will you guys lay off me for a second?\""
                    gin "\"We only put you down when you get too full of yourself.\""
                    show jin at fdis, jumping
                    jin "\"Weren't you guys just complaining about [povFirstName]-san doing that?!\""
                    gin "\"I'm your brother, I'm allowed.\""
                    jin "\"The fuck?!\""
                    "The whole group chuckles at the muscular mouse getting all pouty over some silly teasing."
                    "I make sure to keep my mouth shut as much as possible since I don't want to risk getting in trouble again."
                    "I really don't want to get told over twice in the same day."
                    so "\"Should we go again?\""
                    vic "\"I'm up for it. It was really fun.\""
                    j 1 u gentle "\"Yeah! I wanna go again too!\""
                    mc 1 u smile "\"I guess I have nothing against either.\""
                    j 1 u sigh "\"You could try to sound a bit more excited about it.\""
                    mc 1 u considerate "\"At least I said {i}something{/i}. Why don't you get on Kumagawa's case? He's distracted playing games again!\""
                    j 1 u think2 "\"Nah. I'm not close enough to him to do that.\""
                    mc 1 u sigh "\"Damn. I feel so loved.\""
                    j 1 u happyb "\"Hehehe.\""
                    "Jun's tail brushes up against mine for a split second."
                    "It was quickly enough that it might look like an accident, but given what I now know and the look on his face, I can 100\% say it was deliberate."
                    jin "\"Alright, it's decided then. Let's get back in line! And this time I'm not getting last place again!\""
                    gin "\"If I were you I'd aim for not crashing instead.\""
                    show jin at fdis, jumping
                    jin "\"That much is implied!\""
        "Go steady":
            "Nah, there's no point to it."
            "At most I'd be able to get past Gin but the other two on the lead are way too far ahead of us for it to matter."
            "And I really don't want to risk crashing."
            "These karts are already borderline uncontrollable in the best of cases, at least for me."
            "I don't need to add more speed to the mix because then I'm gonna have a hard time even staying on the track."
            "Besides, I'm already having plenty of fun as is."
            "While I'm busy making my decision to just leisurely enjoy myself as is, the loud humming of motors echoes behind me."
            "Before I notice it, both Jun and Kumagawa have accelerated and gone past me in a flash."
            "They even caught Gin by surprise and ended up leaving him behind too."
            "I see Jun weaving through the curves with tight maneuvers, eventually gaining on and passing Kumagawa as well."
            "With how fast he's going, he might even stand a chance of reaching the top 2."
            "Meanwhile, I am left far behind."
            "Only Jin and the other kid on the race are still behind me."
            "Although Jin is borderline crashing on everything, probably because he's so frustrated he's tilting."
            "And the kid... well, he just doesn't seem bothered to try."
            $ day23_juncrash = False
            scene Kart
            show j 1 u gentle at fdis, zeroh
            show gin at fdis, twoh
            show jin at fdis, fourh
            show vic 1 u smile at fdis, sixh
            show ryoji at fdis, eight
            show so 1 u smile at fdis, tenh
            with fade
            "We all step out of the course, chatting excitedly amongst ourselves."
            j "\"Hehehe, that was really fun.\""
            mc 1 u considerate "\"Of course you think so. You got 3rd place.\""
            j 1 u smile "\"What? Are you telling me you didn't have fun just because you finished 6th?\""
            jin "\"Pfft. [povFirstName] is just a cowardly loser who didn't have the guts to go as fast as he could and ended up behind because of it.\""
            mc 1 u "\"This coming from the courageous loser that did and ended up crashing into everything because of it. How does it feel back there in last place?\""
            show jin at fdis, jumping
            jin "\"Wha- How dare you?!\""
            ry "\"So much for your talks about having so much experience.\""
            show jin at fdis, jumpingx3
            jin "\"I never said I was sure to win just because of that.\""
            ry "\"No, you just said something about how you loved to \"crush the newbies\".\""
            mc 1 u sigh "\"And yet you have the gall to act all cocky toward me, huh?\""
            jin "\"Jeez, will you guys lay off me for a second?\""
            gin "\"We only put you down when you get too full of yourself.\""
            show jin at fdis, jumping
            jin "\"Weren't you guys just complaining about [povFirstName]-san doing that?!\""
            gin "\"You're being a dick. They're allowed.\""
            jin "\"The fuck?!\""
            "The whole group chuckles at the muscular mouse getting all pouty over some silly teasing."
            "I make sure to keep my mouth shut as much as possible since I don't want to risk getting in trouble again."
            "I really don't want to get told over twice in the same day."
            so "\"Should we go again?\""
            vic "\"I'm up for it. It was really fun.\""
            j 1 u gentle "\"Yeah! I wanna go again too!\""
            mc 1 u smile "\"I guess I have nothing against either.\""
            j 1 u sigh "\"You could try to sound a bit more excited about it.\""
            mc 1 u considerate "\"At least I said {i}something{/i}. Why don't you get on Kumagawa's case? He's distracted playing games again!\""
            j 1 u think2 "\"Nah. I'm not close enough to him to do that.\""
            mc 1 u sigh "\"Damn. I feel so loved.\""
            j 1 u happyb "\"Hehehe.\""
            "Jun's tail brushes up against mine for a split second."
            "It was quickly enough that it might look like an accident, but given what I now know and the look on his face, I can 100\% say it was deliberate."
            jin "\"Alright, it's decided then. Let's get back in line! And this time I'm not getting last place again!\""
            gin "\"If I were you I'd aim for not crashing instead.\""
            show jin at fdis, jumping
            jin "\"That much is implied!\""
    stop music2 fadeout 2.5
    play music3 "music/BGM/Dog Days.ogg" fadein 5.0
    scene Baseball
    show j 1 u shock at fdis, zeroh
    show gin at fdis, twoh
    show jin at fdis, fourh
    show vic 1 u smile at fdis, sixh
    show ryoji at fdis, eight
    show so 1 u smile at fdis, tenh
    with fade
    show hours with dissolve
    $ renpy.pause (1.0)
    hide hours with dissolve
    "By the time we reach the baseball cage, the sun had already begun to set."
    "The orange light paints the sky above us and covers the streets with a bright, blindling glow."
    "To my amusement, I notice that Jun's fur somehow gets even more bright orange under the direct light of the setting sun."
    j "\"Oh wow, this place is a lot more empty than I thought.\""
    mc 1 u "\"Thank God for that. Now can you let go of my arm, please?\""
    j 1 u wince "\"R-right.\""
    "The streets had gotten much busier by the time we left the karting venue as most people were starting to leave work."
    "Jun had a small freakout in the middle of the crowd like he usually does."
    "... At least he's getting kinda better at those. He didn't go incoherent or catatonic or anything."
    "He just gripped my wrist really tight and whispered to me that he wanted to go somewhere quieter."
    "So at least he still made sense... even if his grip was just as crushing."
    jin "\"I haven't come here in a while. I guess not many people come by this late.\""
    mc 1 u talk "\"It's not even that late. The place still stays on for three more hours.\""
    j 1 u shock "\"Have you been here before? How do you know that.\""
    mc 1 u "\"There's a huge sign on the wall right there showing the hours.\""
    show j 1 u avoid at fdis
    "Jun sheepishly looks at the direction I was pointing, reading the sign."
    j "\"... Oh.\""
    so "\"How do you use these?\""
    jin "\"You go up to the counter and you buy tokens. Each token is good for 10 shots. Then you walk up to an empty cage and you place the token inside the machine so it opens the door for you.\""
    gin "\"They're big enough to hold two people inside but the workers really don't like it when you do that so I wouldn't recommend it.\""
    mc 1 u talk "\"Of course they don't like. They are that big so you have room to swing, not so you can have a guest. They don't want to get sued when someone gets hit over the head with a baseball bat.\""
    gin "\"Heh. Amusingly enough that happened once.\""
    jin "\"Yeah, and whose fault is that?\""
    gin "\"Not mine. I wasn't the one swinging the bat.\""
    jin "\"I told you to duck!\""
    gin "\"Duck where?! With what space?!\""
    "The two begin to bicker, raising their voices at each other and arguing in circles."
    so "\"This is why I'm glad I'm an only child.\""
    vic "\"This is why I wish I were an only child.\""
    mc 1 u "\"This is why you don't bring another person with you into the cage.\""
    j 1 u think2 "\"Especially when the one swinging the bat is a huge man-child.\""
    jin "\"I heard that!\""
    show j 1 u wince at fdis, jumping
    j "\"O-oh. Sorry!\""
    hide j 1 u wince
    hide vic 1 u smile
    hide so 1 u smile
    hide ryoji
    hide jin
    hide gin
    with dissolve
    "I calmly leave the circus clowns behind and walk up to the front desk."
    mc 1 u "\"Excuse me, I want to buy three tokens.\""
    "The clerk nods and we run the transaction very quickly."
    "The twins are still bickering amongst themselves while the others watch."
    "I make my way to a cage and quickly slip inside."
    "They have helmets and bats on a small rack on the corner ready for players to choose which one they want to use."
    "After that, you just need to get in position and hit a button for it to start."
    play sound "music/baseball.ogg"
    "It is only after the echo of my first bat that I hear someone reacting."
    j 1 u shock "\"Aaah, [povFirstName]-san, no fair!\""
    show j 1 u pout at fdis, five with dissolve
    "Jun cries out and runs up to my cage."
    j "\"That's just mean, leaving us behind like that.\""
    mc 1 u smile "\"I wasn't just going to wait around for those two to stop fighting.\""
    play sound "music/baseball.ogg"
    "Once the machine gets started, it keeps spitting out balls until your turn is over at regular intervals so I can't let myself get very distracted."
    mc 1 u smile "\"You should probably go get a token too if you want to play.\""
    j 1 u sigh "\"Fine. But I'll get you back for this later.\""
    mc 1 u happy "\"Hahaha. I'll be waiting.\""
    play sound "music/baseball.ogg"
    hide j 1 u pout with dissolve
    "Jun runs to the front desk with just as much urgency as he ran towards me."
    "At least he seems excited."
    "Hopefully he'll have a good time."
    play sound "music/baseball.ogg"
    "I keep batting for a few minutes until my first ten balls end."
    "I could use the rest of my tokens right now but I decide to check up on Jun since I know he's never done this kind of thing before."
    show j 1 u wince at fdis, five with dissolve
    play sound "music/chainhit.ogg"
    "When I get to his cage, I see him wearing a helmet that is clearly too big for his hand, swinging and failing to make contact with the ball."
    mc 1 u "\"How many was that?\""
    show j 1 u shock at fdis, jumping
    j "\"Waah!\""
    play sound "music/chainhit.ogg"
    j 1 u wince "\"H-hey, you surprised me!\""
    mc 1 u smile "\"I just talked to you. You did the same to me when I got started and you didn't hear me complaining.\""
    j 1 u avoid "\"I haven't hit a single ball yet.\""
    mc 1 u talk "\"Your form isn't very good. Bend your knees a little more.\""
    j "\"Like this?\""
    mc 1 u smile "\"Yeah, that's good enough. Now, when you start your swing, focus on using your hips more than your shoulders. You're barely using your hips at all right now.\""
    j "\"I'll try.\""
    play sound "music/baseball.ogg"
    "A ball flies at Jun and he swings once again."
    "It barely makes contact with the bottom edge of his bat, flying nearly straight down to the floor but, hey, contact is contact."
    j 1 u shock "\"I did!\""
    mc 1 u smile "\"Good job. You're getting the hang of it. How many balls do you have left?\""
    j 1 u avoid "\"That was the last one.\""
    mc 1 u happy "\"Here, I'll put another token in for you. Keep going.\""
    j 1 u shock "\"What? But I can just go buy another one!\""
    mc 1 u smile "\"You're doing well right now. If you take a break now you might lose focus. Just trust me on this.\""
    j 1 u wince "\"... Alright.\""
    "I continue giving him pointers on how to properly swing and how to improve his form."
    "I end up using both of my remaining tokens on this, mostly because I'm just having a lot of fun watching him try his best."
    "Jun listens to me diligently and, by the end of the 3rd token, can already hit most of the balls semi-decently."
    stop music3 fadeout 2.5
    play music "music/night.ogg"
    scene Street2N
    show j 1 u wince at fdis, five
    with fade
    show hour with dissolve
    $ renpy.pause (1.0)
    hide hour with dissolve
    "After we've said our goodbyes to the rest of the group, Jun and I began to walk home together."
    "The sun has already fully gone down by this point and the streets in our neighborhood are pretty deserted."
    "Then again, most workers have already gotten home by now and this is a pretty quiet neighborhood to start with."
    j "\"Ow... my whole body is sore.\""
    mc 1 u considerate "\"Yeah... swinging a baseball bat for a while takes it out of you.\""
    if day23_juncrash == True:
        j 1 u avoid "\"My chest hurts the most though.\""
        "Jun places his hand on the place where the seatbelt had bruised him and I immediately feel myself cringe."
        mc 1 u worried "\"Does it still hurt?\""
        j 1 u considerate "\"A bit. It'll pass.\""
        mc 1 u worried "\"I'm sorry...\""
        j 1 u wry "\"It's okay. You didn't know.\""
        j 1 u considerate "\"Besides, I had a really fun day thanks to you and you spent most of the week helping me out a ton so it evens out!\""
        "... I really don't think it does."
    j 1 u talk "\"I really wonder why Shoichi-san and Mizoguchi-san couldn't come with us though.\""
    mc 1 u "\"I don't know either. They haven't said anything else to me all day.\""
    "I tried messaging both of them to ask if something was going on but I got no answer other than them declining to go out with us."
    "I admit it's got me a bit worried..."
    j 1 u happy "\"Hopefully there's nothing bad happening and we'll all be able to get together again on Monday.\""
    mc 1 u talk "\"Don't forget that club activities will start over again next week so we'll all have practice again.\""
    j 1 u avoid "\"Oh, right... Do you think we could go out together on the weekend then?\""
    mc 1 u "\"I can try asking but I don't know if they'll come.\""
    j 1 u considerate "\"I'd appreciate it if you did anyway.\""
    mc 1 u smile "\"Sure. I'll let you know if they answer me.\""
    j 1 u smile "\"If they say no, how about you just come over to my place? You wanted to watch me play piano again, right?\""
    mc 1 u happy "\"Oh yeah, I forgot I said that.\""
    j 1 u happyb "\"I'd be happy to put on a little show for you. Then we could go out or do whatever it is you want.\""
    "Jun's tail brushes up against my backside, quickly touching the back of my thighs and rustling against my own tail."
    "I feel a bit embarrassed by the touch but... I don't mind it."
    "I'm... starting to warm up to it I think."
    scene JunHouse
    show j 1 u smile at fdis, five
    with fade
    "We reach the front gate of his house, signaling the end of our little adventure through the neighborhood."
    "We both stop, looking at the lights of the house for a few seconds before speaking again."
    mc 1 u smile "\"Alright, here we are. I've delivered you safe and sound.\""
    j 1 u happy "\"Thank you. I'll talk to you later, okay?\""
    mc 1 u happy "\"Of course.\""
    show j 1 u smile at fdis, offscreenright with moveoridis
    play sound "music/slidingdoor.ogg"
    "I watch Jun unlock his house and step inside."
    "Once the door is closed behind him, I begin to walk away myself."
    stop music fadeout 2.5
    $ date = None
    jump Day24_Jun
