label Day24_Keisuke:
    window hide
    scene June5 with fade
    play sound "music/windchimes.ogg"
    show blossoms movie
    $ renpy.pause(5.5)
    scene SClass
    play sound "music/crowd01.ogg"
    window show
    $ date = "day24"
    "..."
    "Murmurs echo all throughout our classroom."
    "Today is one of the most feared days of the year."
    "... Midterms."
    "A hellish week filled with nothing but the most difficult challenges, breaking the spirits of students all around campus, leaving them nothing more than empty husks deprived of their will to live."
    "A week where teachers delight in watching their student's faces contorting with fear, despair and sorrow."
    "When all those who failed to appropriately prepare themselves are handed a cruel dose of reality, staring at questions they'd have no hope of answering."
    "All those around me are now waiting with full dread for the ringing of the ball which announces the end of the road."
    "Just watching their hopes and dreams being crushed as the clock ticks ever closer to the beginning of their worst nightmares makes my heart weep in pity and anguish."
    "Abandon all hope those who walk into these classrooms..."
    show j 1 u talk at fdis, three
    show gin at fdis, seven
    with dissolve
    j "\"Did you see the latest episode of X-Cross Ninja Stars?\""
    gin "\"Yeah. It was pretty great. I wonder how Sagami is going to squirm his way out of that situation.\""
    j 1 u wince "\"Right? It's already been made really clear he's not strong enough to defeat the Demon Lord. Do you think he's going to die?\""
    show gin at fdis, jumping
    gin "\"What? No way! Tomitaka-sensei would never kill him, Sagami's the show's most popular character!\""
    "Ah, truly the very faces of hopelessness and despair."
    j 1 u think "\"Hmm... I don't know."
    show j 1 u watch at fdis
    extend " What do you think, [povFirstName]-san?\""
    mc 1 u talk "\"Huh? Sorry, I was spacing out. What were you saying?\""
    j 1 u sigh "\"... Never mind.\""
    gin "\"Are you alright? You've been staring at that page for the past ten minutes without flipping it.\""
    mc 1 u considerate "\"Yeah, I'm fine. Just... trying to distract myself from my own boredom.\""
    j 1 u watch "\"I don't even know why you're bothering to try to study {i}now{/i}. We only have a few minutes until the bell rings, it's not like it's gonna do you any good.\""
    mc 1 u think "\"This is less for the sake of not studying and more so I won't feel so guilty over barely having studied.\""
    j 1 u bored "\"Oh, is that so? Must be nice being so smart that you don't have to study.\""
    gin "\"Someone's a little bitter.\""
    j 1 u sigh "\"What? Me? Noooo.\""
    mc 1 u "\"What about you? Did you study at all, Jun?\""
    j 1 u avoid "\"That's... f-funny you'd ask. Well, first we'd have to understand what it means to study-\""
    mc 1 u sigh "\"You didn't study at all either did you?\""
    j 1 u sigh "\"I-I studied a little bit...\""
    "You really have no right to be complaining to me."
    mc 1 u sigh3 "\"What were you doing with your time that you didn't even study?\""
    j 1 u avoid "\"W-well, I spent a lot of time preparing for the festival and then I spent the rest of my time practicing the piano.\""
    mc 1 u "\"Just be careful you don't end up flunking out of third year again.\""
    show j 1 u sigh at fdis, jumping
    j "\"I-I'm not gonna flunk!\""
    gin "\"It's okay. I'm sure you'll both do well. Everyone's just trying to distract themselves before tests start. Won't do us any good to obsess about it now.\""
    j 1 u considerate "\"Yeah. That's a good point.\""
    mc 1 u talk "\"It's easy for him to say though. Gin is among the top 30 students in third year.\""
    j 1 u shock "\"Really?!\""
    "The mouse smiles awkwardly, scratching his cheek."
    gin "\"I suppose that's true.\""
    j 1 u wince "\"In that case, shouldn't you be in the same class as Shoichi-san?\""
    gin "\"Yeah, I did make it into that class but I turned it down.\""
    j 1 u shock "\"W-why?!\""
    gin "\"Without me around to keep an eye on him, I don't know if Jin would be able to graduate. Don't tell him I said that though.\""
    show j 1 u shock at fdis, two
    show gin at fdis, five
    with move
    show jin at fdis, eight with moveiridis
    jin "\"I sit right next to you. I heard that!\""
    show j 1 u considerate at fdis
    gin "\"Oh, hey Jin. Beautiful weather we're having today right?\""
    jin "\"Don't try to change the subject!\""
    show jin at fdis, offscreenright
    show gin at fdis, offscreenright
    show j 1 u considerate at fdis, fiveh
    with move
    "Even despite the stress and exhaustion of constant studying, Jin remains as short tempered as always."
    j "\"Is it really okay for these two to be bickering right before the test?\""
    mc 1 u talk "\"Gin has been tutoring Jin since I've known the two. He's the main reason the guy even got into this school in the first place.\""
    j 1 u avoid "\"That's not really what I asked.\""
    mc 1 u considerate "\"Well, I don't really have an answer for what you asked...\""
    "These two are some of the weirdest people I know."
    "It's probably because they're twins. Twins are just weird."
    j 1 u sigh "\"Man, I'm really not looking forward to the tests.\""
    mc 1 u considerate "\"You really should have studied more.\""
    j 1 u annoyed "\"I don't want to hear that from you of all people.\""
    mc 1 u smile "\"Hey, I might not study a lot but I still get good grades.\""
    j 1 u sigh "\"So everyone says. I still remember the results of the mock tests...\""
    mc 1 u think "\"Hmm... we'll probably both do a little bit better than we did in them.\""
    j 1 u wince "\"How so?\""
    mc 1 u smile "\"They usually make the mock tests a little harder than the real midterms to scare students into studying more.\""
    j 1 u shock "\"Wha- Why didn't anyone tell me that?\""
    gin "\"Probably because you would have studied even less if you knew.\""
    "The twins stop bickering just so Gin can cut into the conversation at the best possible timing."
    show j 1 u wince at fdis, shake1
    j "\"T-that's not true...\""
    "We can all plainly tell from the look on your face that it is true."
    mc 1 u smile "\"It's not all bad. At least that means you'll have a better chance now.\""
    j 1 u sigh "\"... I don't know whether that makes me happy or sad to hear.\""
    jin "\"Don't worry, tests are easy. You just got to know a special little trick!\""
    j 1 u shock "\"A trick?!\""
    gin "\"You are not going to teach him how to cheat!\""
    show jin at fdis, jumping
    jin "\"What?! But it's super useful!\""
    j 1 u avoid "\"Oh... cheating? Never mind...\""
    jin "\"Suit yourself. Good luck doing senior year again.\""
    show j 1 u fluster at fdis, fidget
    j "\"I-I'm not going to fail!\""
    "Poor Jun, tests haven't even started and his brain is already shutting down."
    stop music fadeout 2.5
    play sound "music/schoolbell.ogg"
    scene SClass with fade
    show hours with dissolve
    $ renpy.pause (1.0)
    hide hours with dissolve
    "Finally, the final bell rings."
    show shima 1 u smile at fdis, fiveh with dissolve
    shima "\"Time is up. Everyone put down their pens and hand their tests in. Hopefully we won't have a disaster in our hands.\""
    "Shima-sensei smirks when he says so and a few students groan under their breaths."
    "To this day I don't know if he makes jokes like these because he's mean-spirited or if he's really terrible at lighting up the mood."
    "Waves of students pass their tests along to the person sitting in front of them until all stacks make their way to the buck."
    "Shima-sensei promptly files them inside his file and makes sure all students are accounted for."
    shima "\"Very well, that is it for today. You are all excused. Make sure to come ready for more tomorrow.\""
    show shima at fdis, offscreenright with moveoridis
    "Once he says his piece, the buck wastes no time before leaving the classroom."
    "There are a lot of unhappy faces in the classroom as well."
    "A few students immediately get up and make to leave while others hang around to talk and compare answers."
    "Typical post-test stuff. Nothing out of the usual."
    show j 1 u avoid at fdis, fiveh with dissolve
    j "\"H-how did you do, [povFirstName]-san?\""
    mc 1 u talk "\"It wasn't too bad. Although I'm not very good at social sciences so my grades might be a little lower than I expected.\""
    j "\"I swear, if you said that only to get some really high grades I'm going to scream.\""
    mc 1 u considerate "\"Don't be like that. You'll do fine.\""
    j 1 u sigh "\"I wish I could have that much faith in myself.\""
    j 1 u considerate "\"Anyway, I should probably get going. I'm gonna try to hit the library and study a little bit.\""
    mc 1 u "\"At the library? Why not at home?\""
    j 1 u avoid "\"I have a feeling that if I head home, I'll be too distracted by the piano to concentrate.\""
    mc 1 u talk "\"Well... it's not ideal but so long as you're focusing on something productive-\""
    j 1 u considerate "\"Or by videogames.\""
    mc 1 u considerate "\"... Yeah, you should probably head to the library.\""
    j 1 u considerate "\"Hehe... see you tomorrow, [povFirstName]-san.\""
    mc 1 u talk "\"See ya. And take it easy. It won't do you any good if you brick your brain.\""
    j 1 u avoid "\"I'll do my best.\""
    show j 1 u avoid at fdis, offscreenright with moveoridis
    "... I worry for that guy."
    "Maybe I should get going too."
    "Not like I have anything else to do in school."
    "Hmm... I think I'll at least try to see Keisuke before I leave."
    play music2 "music/BGM/On My Way.ogg" fadein 5.0
    play sound "music/slidingdoor.ogg"
    scene SClass2 with fade
    "I wonder if Keisuke hasn't left already."
    "I tried sending him a message but just to not run the risk of him heading home before reading, I decided to try and look for him."
    "A few of the juniors look at me weird after I simply popped into their class without a word but most of them are too busy talking to pay me any attention."
    "Probably discussing today's test just like my classmates are."
    "No sign of Keisuke..."
    "Maybe he's really left already."
    "Although I still have one place left that I could check."
    "Club activities are supposed to be postponed for the week but I really doubt the band members care much about that in the first place."
    "I might not have known them for long but they didn't seem like a very... orderly bunch."
    play sound "music/slidingdoor.ogg"
    scene SCorridor with fade
    "I make my way down the stairs and towards the other building where the light music club's room is located."
    "Thanks to the lack of clubs for the week, students are leaving the school en masse as soon as classes run out."
    "The few that stick around are heading to the library or staying in their homerooms to study."
    "The library must be pretty packed right now."
    "Hopefully Jun won't have a panic attack in there..."
    play sound "music/knock.ogg"
    "Once I reach my destination, I knock on the door and await for some kind of signal."
    play sound "music/door.ogg"
    show ka 1 u smile at fdis, five with dissolve
    "The door opens, a jet black raven appearing on the other side of it."
    "As soon as he sees me, he smiles warmly."
    ka "\"Ah, it's only you. I was afraid a faculty member had shown up.\""
    mc 1 u talk "\"A faculty member?\""
    ka "\"Yes. We're not really supposed to be getting together to rehearse or even get together at all so we're trying to keep a low profile what discussing what to do.\""
    mc 1 u "\"Is Kei-k...suke around? I was looking for him?\""
    "I still have a hard time calling him by his regular name."
    "The habit is much harder to break than I thought it'd be..."
    ka "\"Oh yes, he's here. Come on in, we were taking a break anyway.\""
    scene SBand
    show ka 1 u smile at fdis, zero
    show i 1 c smile at fdis, two
    show k 1 u sigh at fdis, four
    show ku 1 u smile at fdis, six
    show mi 1 c smile at fdis, eight
    show sh 1 c at fdis, ten
    with fade
    "As soon as I walk in, I see the whole band gathered together."
    "Kei-kun has his back turned to the door."
    "His voice sounds annoyed for some reason and he gestures quite often as he speaks."
    "Is he ranting or something?"
    show ku 1 u smile at fdis, jumping
    ku "\"Oh hey, we have a visitor!\""
    "As soon as I walk in, the monkey interrupts Keisuke to loudly announce my arrival, causing all the other band members to notice me as well."
    k 1 u worried "\"[povFirstName]? What are you doing here?\""
    mc 1 u talk "\"I thought I'd check in on you before I headed home.\""
    k "\"Check in on me?\""
    mc 1 u considerate "\"Yeah. You went through all that trouble yesterday to try and help me study only to have to go home right away because I wasn't around.\""
    k 1 u smile "\"What? That? That was fine. Showing up without being able to get a hold of you in the first place was already a huge gamble.\""
    mc 1 u considerate "\"I suppose that's a fair point.\""
    mc 1 u talk "\"But I do have to say, I'm surprised you're all so relaxed. I thought for sure at least monkey boy here would be dejected after the tests.\""
    ku "\"Hehe, why should I even care about that stuff? I've got more important things to do.\""
    mc 1 u sigh "\"Such as?\""
    ku "\"Practicing the guitar of course!\""
    "This guy's priorities are all messed up."
    mi "\"Well, I can't say I'm \"relaxed\" but there's no point worrying about it now. Right, Shoko?\""
    "The coyote girl nods meekly."
    "At least she didn't hide behind someone as soon as I walked in the room."
    "I suppose that's progress?"
    "I'm still surprised someone with a personality like this can be in a band though."
    ka "\"I'm used to helping the band members study. I did the same when Ichigo and I were freshman and I helped Kurusu after he joined too.\""
    mc 1 u talk "\"Oh. But not Shoko-san?\""
    ka "\"Shoko doesn't really need help. She's already a bright student on her own. She even helped Miyu study this year.\""
    "From the corner of my eye, I see Shoko twiddling her fingers, her eyes falling down to the ground and her face getting a tinge redder."
    mi "\"Yeah, that's true. If it weren't for Shoko-chan I'd have been done for.\""
    sh "\"Miyu, you don't have to say it like that...\""
    k 1 u worried "\"Of course, since I joined the band, Kagaho got me to tutor Kurusu in his place.\""
    ka "\"That way each person in the band would only have to tutor one student instead of multiples.\""
    i "\"Yeah. Besides, gotta offload the dead weight.\""
    "Ichigo laughs, her lighthearted tone betraying the sharpness of her words."
    play sound "music/stab.ogg"
    show ku 1 u smile at fdis, jumping
    ku "\"D-dead weight?!\""
    k "\"I will admit, you {i}are{/i} a terrible student. You don't even listen most of the time.\""
    ku "\"W-what do you mean?!\""
    k 1 u "\"Exactly what I said. See, this is what I meant by you not listening.\""
    mc 1 u considerate "\"Isn't that a little harsh?\""
    k 1 u smile "\"Don't worry, it's all in good fun.\""
    ku "\"Tch, if you think this is all it takes to get to me then you don't know me well.\""
    k 1 u "\"He literally doesn't though. He's only met you, what, five times?\""
    ku "\"You know that's not what I meant!\""
    k 1 u smile "\"Do I?\""
    sh "\"Maybe we should go back to discussing our plans?\""
    show k 1 u at fdis
    "The meek, surprisingly low-pitched female voice cuts through the lively chatter, suddenly redirection everyone back to their previous conversation."
    k 1 u "Right, that's true. Sorry for getting distracted.\""
    mc 1 u considerate "\"Uhm... I should probably go. I feel like I'm just intruding.\""
    i "\"Nah, it's fine. We'll just think of it as having our first fan around!\""
    mc 1 u fsmile "\"Y-you will?\""
    k 1 u worried "\"{size=-4}I don't think bands are in the habit of bringing their fans around to rehearsals and meetings, even if they're their firsts.{/size}\""
    i "\"What? So you want him to leave? Welp, sorry [povFirstName]-kun, you heard the man. Off you go!\""
    "She cracks a huge Cheshire cat grin, suppressing a giggle as she speaks, her voice nearly breaking a few times from the effort of it."
    "However, she does manage to pull of a convincing performance and the hare's eyes immediately go wide with horror at her words."
    k 1 u shock "\"Wait, no, that's not what I meant!\""
    mc 1 u considerate "\"{size=-4}That's just cruel, Minazuki.{/size}\""
    "I lean a little closer to her, whispering in her ear while she laughs.\""
    ka "\"Keisuke, can you continue what you were saying before our guest arrived?\""
    k 1 u worried "\"R-right. Yeah, that.\""
    show k 1 u at fdis
    "Keisuke clears his throat, reaching down with his hands to straighten out his shirt a little before speaking."
    "It's a habit he has sometimes that I think he doesn't even notice."
    k "\"As I was saying, we need to find a different place to meet up in and rehearse during this week. Faculty really doesn't want clubs meeting up during this week. Theoretically we shouldn't even still have the key to our room.\""
    mc 1 u sigh "\"How {i}did{/i} you even get it in the first place?\""
    show mi 1 c smile at fdis, jumping
    mi "\"Oh!\""
    "The raccoon raises her hand, cheerfully interjecting."
    mi "\"I told a teacher that Shoko-chan left her personal keyboard in the room and needed my help to pick it up and take it back home.\""
    mc 1 u sigh "\"... And that worked?\""
    "She shrugs, chuckling under her breath."
    mi "\"Sure? Why wouldn't it? The students in this school are stupid trusting. Way more than the ones in my previous school.\""
    "It's a good thing Shoichi isn't her otherwise he'd be sputtering in shock at this point."
    k 1 u worried "\"Right, but that is obviously not going to work again so we need to find a place where we could rehearse. And since we can't just transport some of the instruments there, it'd need to be a place that already has stuff like keyboards and drums.\""
    k 1 u "\"That's why I was thinking of suggesting Kiyoshi-san's shop.\""
    mc 1 u talk "\"I'm... surprised. I thought you wouldn't want to talk to him after what happened last time. At least for a while.\""
    k 1 u sigh2 "\"I'm not a child. I'm capable of taking criticism without crumbling. {size=-2}Although I didn't care for the way he worded it.{/size}\""
    i "\"Okay, I just remembered. You had said that right before [povFirstName]-kun came over but I didn't manage to ask before. Who's this Kiyoshi?\""
    k 2 u annoyed "\"Right. Gotta remember not everyone knows people by names.\""
    k 1 u "\"He's the owner of the large music store nearby the train station downtown. You know, the one right in front of the department of transit.\""
    ku "\"Wait, you mean \"Astro Records and Instruments\"? That wouldn't work. Place rarely ever has openings, especially with this little notice.\""
    ka "\"Yeah, I'm afraid I have to agree with Kurusu. That store is great but it's also huge and one of the most popular in town. I had to book a room with two weeks notice when I was still in Junior High.\""
    mi "\"Oh yeah, I know that place. It's where I bought my electronic drum set. The owner is kinda weird but he's also nice.\""
    k 1 u haughty "\"Hehe. Fret not. I know the owner personally and I'm sure I could get him to squeeze us in this week.\""
    ku "\"Wait, you do?!\""
    k 1 u smile "\"Yeah. He's a friend of my father. He was the one who taught me to play guitar too.\""
    ka "\"Hmm... this just makes me more and more curious to see how good you are with the guitar.\""
    k 1 u "\"Hard pass.\""
    k 1 u smile "\"Anyway, my point is that getting a room there is going to be a cinch.\""
    if day10 == "keisuke":
        mc 1 u talk "\"You say that but when I went with you to the store for you to buy a mic you had to test it at the store floor because he didn't have any room.\""
        k 2 u sigh "\"That... that was a fluke. He wasn't going to reschedule a previous customer so I could test out a product for five minutes. That's not reasonable.\""
        "..."
        "No offense but him rescheduling a customer that's been waiting for weeks just because you have personal connections with him isn't really \"reasonable\" either."
        "Is this what nepotism looks like?"
    else:
        mc 1 u talk "\"Wow, I knew you and Kiyoshi-san went way back but I didn't know it was so easy for you to get your way with him.\""
        k 1 u "\"Well... with some things more than others. He's a little bit messed in the head and sometimes does things that I can't anticipate.\""
        k 1 u sigh "\"... But for the most part he's just that guy who's really close to your family that shows up every now and again to annoy the everliving crap out of you because he thinks he's so funny.\""
        i "\"You've just described an uncle.\""
        k 1 u worried "\"H-have I?\""
    ka "\"So long as you're confident that can work then I have no objections. The place is top-notch. The installations easily leave our club room eating the dust. We'll just have to pool the money together to cover for a week of room rental.\""
    k 1 u "\"There's no need, I can cover it just fine.\""
    ku "\"Dude, we know you're like... uber rich or something but we don't want you to pay our way into things. We're all a band together so we'll share the burden equally.\""
    k 1 u worried "\"I didn't mean...\""
    sh "\"You say that but you're always broke and always need to ask for more time to pay your share.\""
    show ku 1 u smile at fdis, jumping
    ku "\"T-that's not relevant here!\""
    show k 1 u at fdis
    ka "\"Message us when you get an okay for the room so we can figure out how much we all owe. If all goes well we can start getting together for rehearsal tomorrow.\""
    k 1 u smile "\"Alright. So unless there's any other business we need to discuss then this should be all for today, huh?\""
    ka "\"Yeah, probably for the best. I still need to help Ichigo study a little more before I'm comfortable letting her take the rest of her tests.\""
    i "\"Do we really have to?\""
    "The calico pouts, rolling her eyes at the raven."
    ka "\"I'm afraid we do.\""
    i "\"Alright, fine, but you're gonna owe me for this. Buy me a scone or something on the way home.\""
    ka "\"I get the feeling this conversation of who owes whom what is a little backwards here.\""
    mi "\"Hey, Shoko, Should we hit up that new bakery that opened by the old market? I heard their chocolate croissants are really good.\""
    sh "\"That sounds good.\""
    "The conversation topic immediately shifts away from the band and back to a much more mundane chatter."
    k 1 u smile "\"I'm gonna head to Kiyoshi-san's shop right now. Would you like to come with me, [povFirstName]?\""
    mc 1 u talk "\"Yeah sure, why not?\""
    ku "\"Wait, does this mean I'm the only one who's gonna be left alone.\""
    i "\"Sounds like it.\""
    show ku 1 u smile at fdis, jumping
    ku "\"That's not fair! C-can I go with you girls to the bakery?\""
    mi "\"Hmmmm... I don't know.\""
    "The raccoon smiles, obviously teasing her bandmate, making a long over exaggerated humming sound as if she were thinking about it."
    ku "\"N-no way...\""
    "The monkey sulks, his shoulders drooping crestfallen."
    sh "\"Miyu-chan, that's a little mean...\""
    mi "\"Hahaha. Sorry, I just wanted to have a little fun. Sure, you can come with.\""
    ku "\"Alright!\""
    stop music2 fadeout 2.5
    play music3 "music/BGM/Dog Days.ogg" fadein 5.0
    scene Station
    show k 1 u smile at fdis, fiveh
    with fade
    show sometime with dissolve
    $ renpy.pause (1.0)
    hide sometime with dissolve
    "Man, it's good to stretch my legs and finally get out of that cramped school."
    "I stretch my arms and shoulder, making sure that everything is still in its right place."
    "There's something about the stress of exams that makes all your limbs feel heavy like lead."
    mc 1 u considerate "\"I know it's the same thing every year but I'm still not used to midterms.\""
    k "\"Maybe if you studied once in a while you'd have an easier time with them.\""
    mc 1 u smile "\"Come on, even you've got to know that's not realistic.\""
    k 2 u gentle "\"Is that so? I thought you were trying to be a little bit more like me.\""
    "Ugh... not this..."
    mc 1 u sigh3 "\"Can we pretend Aki never said that? Please?\""
    k 1 u smile "\"Aww, why? I thought it was kinda cute.\""
    mc 1 u fsmile "\"C-cute?\""
    k "\"Yeah. You're just cute in general.\""
    mc 1 u sigh3 "\"I'm... what?\""
    "This entire conversation does not compute."
    k "\"It's not so bad. You're acting like it's this huge thing when it's really not.\""
    mc 1 u "\"Amusing for you to be saying that when I was the one having to say it last night.\""
    k 1 u considerate "\"Well, I've had time to process it.\""
    k 1 u "\"When you think about it it's not really that strange. People change because of their relationships to other people, it's only natural.\""
    k 1 u smile "\"Like me for instance. I've also taken inspiration from you for a great many things.\""
    mc 1 u talk "\"Really? That's news to me. Like what.\""
    k "\"Well, I've been trying to be a little more relax and casual. I don't people avoiding me because I'm too strict or uptight.\""
    mc 1 u confused "\"That's... actually a pretty good point.\""
    k 1 u calm "\"And I've also been trying to be a little more open with others as well.{nw}"
    show k 1 u worried at fdis
    extend " Trust me, the last thing I want is to give my friends the impression that I'm keeping them at a distance.\""
    mc 1 u smile "\"That's surprisingly insightful of you?\""
    k 2 u sigh "\"Surprisingly? Have you even met me at all? All I do is obsess about the image I project to other people.\""
    k 1 u smile "\"Of course, it goes without saying that any pretensions of being taken seriously by you lot have long since been abandoned.\""
    mc 1 u smile "\"Oh yeah, that ship has sailed a long time ago.\""
    k 1 u sigh "\"... Not only has it sailed, it's sunk under the tempestuous, raging waves in a spiraling vortex leaving hundreds dead in its wake.\""
    mc 1 u fsmile "\"W-what? T-that got really dark really fast.\""
    k 1 u worried "\"Oh... sorry. What was I trying to say again?\""
    k 1 u smile "\"Ah, got it. What I mean is, it's okay to take a little bit of inspiration from other people. It's how you grow really. You shouldn't be embarrassed.\""
    mc 1 u considerate "\"I don't know... it feels a little bit embarrassing when the person in question is my b-boyfriend.\""
    k "\"Still can't say that with a straight face huh?\""
    mc 1 u sigh3 "\"Give me a break. You've had a lot longer to get used to it than I have.\""
    mc 1 u worried "\"Every time I feel like I might be making a breakthrough I get a new pang of worry, self-doubt, paranoia and a little bit extra worry for spice.\""
    mc 1 u considerate "\"My brain is one giant pile of stress and anxiety at this point.\""
    k 1 u worried "\"That... that's not good. That's not good at all actually.\""
    "Oh oh. I didn't mean to make {i}him{/i} freak out in my stead."
    mc 1 u considerate "\"I-I'm sure things will get better soon. It just hasn't really hit me yet. A lot of things have happened all at once lately and my brain can only handle one major epiphany at a time.\""
    k "\"If you say so...\""
    "Great, now I've passed my paranoia along to him like some kind of emotional flu or something."
    "I really have to learn when to keep my mouth shut..."
    k 1 u "\"Oh, we're here.\""
    scene MusicStore
    show k 1 u at fdis, fiveh
    with fade
    "The place is a lot more packed than the last time we came along."
    "Maybe because of the time of day? I'm not quite sure."
    "Maybe Mondays just suck so much people need a little bit extra music to get through it? That guess is as good as any."
    k 1 u smile "\"There he is.\""
    "Keisuke points behind a row of discs where the lizard, Kiyoshi, is chatting cheerfully with what seems to be a pair of customers."
    "Is he trying to make a sale maybe?"
    "I just know there's a lot of pointing towards a few different pianos he has lined up on that corner of the store."
    mc 1 u "\"You know, I still don't understand why a guy who owns such a successful business still works on the shop floor like a common salesman.\""
    k "\"Kiyoshi-san just likes dealing with people. I've seen him defuse annoyed customers a few times. He definitely has a talent for customer service.\""
    k 1 u considerate "\"... And the fact that it allows him to work surrounded by dozens of instruments and records and whatnot probably doesn't hurt either.\""
    mc 1 u talk "\"I... guess? I just thought since he manages a chain of stores he'd spend a lot more time working on papers and files and whatnot to manage all of them at once.\""
    k 1 u uncomfortable "\"Kiyoshi-san? Working with files and other important documents? Now there's a real nightmarish idea.\""
    mc 1 u shock "\"H-huh? Is he that bad?\""
    "From the corner of my eye, I see the lizard shaking hands with the couple, a big flashy smile on his face."
    "He notices us by the door and waves at us, making his way in our direction."
    show k 1 u at fdis, seven with move
    show ki 1 u smile at fdis, three with moveiledis
    ki "\"Lookit what I got here, my two favorite people, Kei-chan-boy and Not-Alex!\""
    show k 1 u sigh at fdis
    mc 1 u fsmile "\"H-huh? \'Not-Alex\'?\""
    ki "\"Sorry kid, I kinda forgot your name. No biggie though right?\""
    k "\"Of course it's a \"biggie\". His name is [povFirstName] and he's my closest friend. Don't just casually forget about him that casually... {size=-4}Also, I already asked you to please stop calling me that.{/size}\""
    ki "\"Do what do I owe the pleasure of you twoses visit?\""
    "Twoses?"
    k 1 u "\"I actually wanted to talk about booking a room for band practice at the back.\""
    ki "\"Oooh, does this mean I'ma get the chance to watch yer band playing live at my shop? Dang kid, that sounds great.\""
    k 1 u smile "\"Heh, I thought you'd get excited about that.\""
    ki "\"Fer sure! I can check my bookings to be sure but I think I should have some openings for early July.\""
    mc 1 u shock "\"T-that far?!\""
    ki "\"Yeah, this is a busy time o' year. Most musical events and competitions happen around August so there's a lot of preparin' going on.\""
    k 1 u "\"I was actually hoping you could squeeze us in this week.\""
    ki "\"W-what, this week?! That's way too short notice!\""
    mc 1 u talk "\"Funny, that's exactly what half of your bandmates said.\""
    k 1 u considerate "\"Come on, I'm sure it's not big a deal right? You've made exceptions for me before.\""
    "The lizard's usually jovial smile immediately disappears into a frown."
    "He crosses his arms, clicking his tongue and shifting his body weight around from one leg to the other."
    ki "\"Y'er really killing me here, kid. After the way we left things off the last time we talked you have some guts comin' over to my shop and demanding favors!\""
    k 1 u uncomfortable "\"I-I mean...\""
    play sound "music/tap.ogg"
    show k 1 u shock at fdis, jumping
    ki "\"Nah, just messin' with ya kid. Wanted to make ya sweet a lil' bit.\""
    "He laughs heartily, giving Keisuke a few very strong looking pats on the back and making the hare jump."
    "Heh... \'Jumping Hares\'. That could be a cool name for a band."
    "Still, the sound of the impact from each pat is impressive actually."
    k 1 u wince "\"J-Jesus, I'm not one of your drum sets, you don't need to hit me so hard.\""
    ki "\"Oh sorry, got a lil' excited, hehe.\""
    play sound "music/disappointment.ogg"
    "This guy really doesn't act his age does he?"
    "Although to be fair, he doesn't {i}look{/i} to be his age either."
    mc 1 u talk "\"Do you play the drums too?\""
    "I have to admit that Keisuke's comment just now kinda piqued my interest a little bit."
    show k 1 u at fdis
    ki "\"Sure I do, kid. What with me being a former professional drummer and all!\""
    if day10 == "keisuke":
        mc 1 u shock "\"W-wait? I remember you saying you used to be a musician but since you're Keisuke's former {i}guitar{/i} teacher I assumed...\""
        k 1 u worried "\"Right, I didn't tell you that. Kiyoshi-san plays quite a few instruments. Guitar, bass, drums, piano...\""
        ki "\"I even teach lil' kids about music on a cute toy xylophone I have out the back!\""
        mc 1 u shock "\"Wow, that's really impressive.\""
        ki "\"Nah, not really. When you live your whole life for music it's only natural that you'd pick up a lot of instruments. I've been playin' since I was eight so I've had a good few decades to learn 'em.\""
        mc 1 u worried "\"That's... still very impressive. Now I kinda feel inferior for not knowing anything about music.\""
        k 1 u considerate "\"If it makes you feel any better, I know that feeling. I've been through it too.\""
        ki "\"Ya know, I can teach ya music too if ya wanna. I give private lessons every now and again.\""
        mc 1 u shock "\"Really? I think I could actually be-\""
        k 1 u sigh "\"Before you rush into an agreement without any further consideration, please take a second to imagine just how expensive it would be to take private lessons from a former pro musician and owner of a successful business...\""
        "O-oh..."
        ki "\"Aww kid, why did ya have to go and ruin the sale like that?\""
        mc 1 u considerate "\"I-I think I'll pass for now.\""
        ki "\"Ey, suit yerself.\""
    else:
        mc 1 u shock "\"Whoa, really?! You used to be a professional drummer?\""
        "The lizard chuckles, shaking his head sideways."
        ki "\"Ya know, most people come to my store {i}because{/i} they know who I am. It's kinda refreshing to have this kind of conversation every now and again.\""
        k 1 u smile "\"Kiyoshi-san spent six years in a popular band. They still play to this day but he retired to open his store.\""
        mc 1 u wince "\"Really? You traded in a life as a professional musician to be a business owner? That doesn't sound anywhere near as glamorous.\""
        ki "\"Glamour's got nothin' to do with it, kid. My dream always was to get as many people into music as I could. Selling instruments, giving lessons and advice and encouraging budding musicians is my way of doing it.\""
        k 1 u sigh "\"It's why his customers all love him, even though he's a giant pain in the ass.\""
        ki "\"Hey now, is that really how ya should be talkin' 'bout me to my face when you're here to ask for favors?\""
        k 1 u worried "\"R-right. Sorry.\""
        ki "\"Eh, it's no sweat off my back.\""
    k 1 u "\"Either way, maybe we should circle back to what I initially came here to discuss before we got too absorbed in idle conversation. Is there anyway you could get us a room?\""
    ki "\"That's... ya do know yer askin' a lot from me right?\""
    k 1 u considerate "\"Y-yeah?\""
    show k 1 u wince at fdis
    "The lizard shrugs, putting his hand on top of Keisuke's head and ruffling his fur a little."
    ki "\"A'ight, just so long as ya know. Sure, but I can't really cancel on anyone so I'll have to keep the store open a little longer for y'all. You'll need to be okay with rehearsing at night.\""
    k 1 u shock "\"R-really?! That's amazing! That's even better than what I hoped.\""
    ki "\"Hehe, and as an upside, I won't have any other customers to tend to so I'll be able to watch y'all.\""
    k 1 u considerate "\"That's... less amazing but still quite good.\""
    ki "\"Hey, yer words can hurt too ya know!\""
    show ki 1 u smile at fdis, five
    show k 1 u at fdis, eight
    with move
    show zin 1 c at fdis, two with moveiledis
    zin2 "\"Kiyoshi-san, I'm sorry to interrupt. Can I speak to you?\""
    "A familiar looking young man peers at us from behind one of the nearby disc stands."
    "His fur is a little matted from sweat and his shirt is almost clinging to his body."
    "What the hell has he been doing?"
    ki "\"Oh yeah, sure. What do ya need?\""
    "The lizard immediately switches from his regular persona to a more customer service oriented one."
    "I have to admit, the change is a bit surprising with how out of nowhere it came."
    "His tone of voice and his body language completely changed."
    "Is he... trying to be professional?"
    "Didn't know he had it in him."
    zin2 "\"Uhm... I'm having a bit of a hard time working the bass amp in the room. There's a lot of distortion on the sound and it's glitching out a little. I tried changing the plug but...\""
    "The lizard frowns, musing the problem to himself for a few seconds."
    "Finally, he clicks his tongue and turns to look at us."
    ki "\"Y'all excuse me for a sec, I'll be right back.\""
    show ki 1 u smile at fdis, offscreenleft
    show zin 1 c at fdis, three
    show k 1 u at fdis, seven
    with move
    "He walks away towards the back of the shop where I assumed the practice rooms he books are located."
    "The young man sticks around, his eyes focused solely on Kei-kun while he twiddles his thumbs awkwardly."
    k 1 u worried "\"Erm... is something the matter?\""
    "The hare doesn't fail to notice the sudden unfamiliar attention."
    zin2 "\"Sorry, I was just wondering... I think I know you... aren't you the guy who sang during a school festival? I saw the video online.\""
    k 1 u uncomfortable "\"Y-you did?!\""
    mc 1 u considerate "\"Oh no...\""
    "The boy nods, a sheepish smile forming across his lips."
    zin2 "\"I really liked you guys' performance. I just joined a band myself but we're still at the stage of trying to mesh with each other and figuring out the dynamics.\""
    k 1 u considerate "\"Ah... yeah, I know how that is. It's also hard to create the courage to show people what you can do, especially when you don't know them super well.\""
    "... Part of me wants to interject here and point out that Kei-kun hasn't even done that much yet."
    "But that would probably be a super cruel and needless thing to do so I'll just keep my damned mouth shut."
    "The boy nods, his eyes focused solely on Keisuke to the point that I doubt he even notices I'm here."
    zin2 "\"You know, you and your band should sign up for the next competition they're organizing in town. A few big heads in the industry always show up to scout new talent. Could be a chance to get your big break. It's what I'm banking on myself.\""
    k 1 u worried "\"A band competition huh... I'll have to think about it.\""
    zin2 "\"Sure, no worries. I mean, there are {i}some{/i} worries since applications end soon but you get what I'm saying.\""
    ki "\"Zi-kun, I fixed the amp for you!\""
    "Kiyoshi-san's head pops up from the door to the back and he calls out to the boy."
    show zin 1 c at fdis, jumping
    zin2 "\"Oh, guess I've gotta go now. Can't afford to waste any minutes in my booking. Maybe I'll see you later!\""
    show zin 1 c at fdis, offscreenleft with moveoledis
    show k 1 u worried at fdis, fiveh with move
    "He runs off, turning around to wave at us one last time before he goes through the door and disappears from view."
    mc 1 u talk "\"Well... that guy is energetic at least.\""
    k "\"Yeah, I suppose that's true.\""
    mc 1 u smile "\"Still, that's a pretty interesting idea. I didn't know they had band competitions. I'm sure if you told your bandmates they'd all be really interested in taking part.\""
    k 1 u sigh "\"They probably would... it's what I'm worried about.\""
    mc 1 u fsmile "\"You're... worried that they'll want to play? You lost me.\""
    k 1 u worried "\"Ever since the school festival, Ichigo has been pushing me to step down as manager and play with the band. She's been trying to get me to show them my guitar skills too...\""
    k 1 u sigh "\"Honestly, I don't know why she's so intent on convincing me. If I become a vocalist that just means she won't sing as much since we'd have to share songs.\""
    k 1 u avoid "\"It makes no sense...\""
    mc 1 u considerate "\"To be perfectly honest, no one in that band makes any sense so I don't think it's {i}that{/i} outlandish.\""
    mc 1 u think "\"Well... I guess the raven isn't all that bad. Pretty no-nonsense for the most part.\""
    k 1 u sigh "\"I know. It's just a headache. I hate pushy people. Why can't they just take no for an answer? Ugh...\""
    show k 1 u wry at fdis
    "I give him a few encouraging pats on the back although definitely not at all like Kiyoshi-san's."
    "Keisuke flashes me a smile, reaching down to grab my hand and give it a quick squeeze before letting go."
    "I have to admit, he keeps growing more and more on me."
    mc 1 u considerate "\"You know, you were teasing me earlier about being \"cute\" but you're also pretty cute yourself when you let your guard down.\""
    k 1 u considerate "\"I suppose I might have my moments.\""
    show k 1 u at fdis, seven
    show ki 1 u smile at fdis, three
    with move
    ki "\"I'm back, sorry 'bout that. Where were we?\""
    "Kiyoshi-san returns from his magical trip to fix whatever electronic issues he was having out back."
    k "\"Right. So... since you already agreed you'd let us use the room... how much are you going to charge us? And how long can we use it for? I assume your usual going rate isn't going to cover staying late.\""
    ki "\"Eh, it'll be fine. I'm just doing this as a favor for y'all. I know you'd never accept charity so I'll still charge ya but I don't have any need to go above my regular price.\""
    k 1 u worried "\"Are you sure? We'd all be willing to pay if you did.\""
    "He waves Kei-kun off, chortling loudly."
    ki "\"Kid, I'm not interested in yer money, keep it. If I can help ya with yer band then I'm already a happy camper.\""
    k 1 u wince "\"O-okay then. I'll text them to tell them how much it'll cost for each person. What about times?\""
    ki "\"Well, store usually closes at 8PM but it's not like I have anywhere to be after that. If y'all wanna use the rooms until 10 it'd be fine by me.\""
    k 1 u shock "\"Two whole hours?! That's... wow, I don't know what to say.\""
    mc 1 u smile "\"That's pretty good considering we're in the middle of midterm week. They might even have trouble findind time for all of that.\""
    k 2 u gentle "\"Nah, trust me, they'll all be very excited about it too.\""
    k 1 u smile "\"They'd sooner lose study than rehearsal. They're kinda amazing like that.\""
    "But that's... that's a bad thing. Surely even you can see how that's a bad thing right?!"
    ki "\"Ya know, y'all should consider signing up for the next band competition.\""
    show k 1 u uncomfortable at fdis, jumping
    k "\"H-huh?\""
    mc 1 u smile "\"Oh wow, that boy said the same thing.\""
    "I can see the discomfort immediately taking over Keisuke's facial expression."
    "It's... actually kind funny how easily and quickly he went from one extreme emotion to the other."
    ki "\"Oooh, so he told ya about it already? That's good. I'ma be one of the sponsors this year and it's one of the biggest competitions in the region so ya should consider it.\""
    k 1 u worried "\"Y-yeah, I've been made aware...\""
    k 1 u sigh "\"Well, not aware of the part about you being a sponsor but still.\""
    mc 1 u considerate "\"You could at least bring it up with them. I'm sure they'd all find it a great opportunity.\""
    k 1 u worried "\"I know...\""
    ki "\"I dunno what's going on in that head of yours this time but ya worry too much, kid. It's always something with ya. Give yerself a break every now and again, yer too young to be this stressed out. Gonna develop an ulcer you will.\""
    k 1 u sigh "\"Now that's a future to look up to...\""
    "I do the same thing he did just a little bit ago, reaching for Keisuke's hand and giving it a slight squeeze."
    show k 1 u wry at fdis
    "He squeezes it back right away before letting go and recomposing himself."
    k 1 u "\"Well... I guess everything's settled. I appreciate you going so far to help us. I promise I'll find a way to make it up to you, Kiyoshi-san.\""
    ki "\"Aww, it's not biggie kid. That's what family's for.\""
    k 1 u worried "\"But we're not-{nw}"
    play sound "music/punch.ogg"
    show k 1 u wince at fdis, jumping
    extend " OW!\""
    "I elbow him hard on the side to get him to stop before he can say something incredibly hurtful by accident."
    play sound "music/disappointment.ogg"
    "Jeez, learn to read between the lines at times man..."
    ki "\"Whoa, that was a strong one. Seems he's knocked some air outta ya. Ya need to sit down or somethin'?\""
    k "\"I-I'll be fine. I think we should be on our way anyway. I need to tell everyone about our arrangements and then get some studying done before the end of the day...\""
    ki "\"Oh yeah, that's fair. Yer still a student so ya need to take it seriously. Okay then, I'll see yas tomorrow.\""
    k 1 u considerate "\"See you later, Kiyoshi-san.\""
    stop music3 fadeout 2.5
    play music "music/crowd01.ogg"
    play music2 "music/BGM/Let it Happen.ogg" fadein 5.0
    scene Station
    show k 1 u sigh at fdis, fiveh
    with fade
    "As soon as we are out of the store and down the street, Keisuke lets out a loud sigh."
    mc 1 u considerate "\"That worked out better than expected, right?\""
    "I try to somehow cheer him up."
    "I don't know why he's upset but it's pretty obvious when he's upset about something."
    k "\"I suppose so.\""
    mc 1 u "\"Then why do you look so down about it?\""
    k 1 u considerate "\"Don't get me wrong, I'm happy we got the room to practice but...\""
    k 1 u sigh "\"I just know having Kiyoshi-san hovering over us while we practice is going to turn into a really big headache really fast.\""
    mc 1 u considerate "\"I'm sure he can't be that bad.\""
    k 1 u "\"I hope not. But if he acts anything like he did when he was teaching me we're probably going to be in trouble.\""
    k 1 u worried "\"Which reminds me, I should probably make sure we don't have any ashtrays or other small objects in throwing range when we do rehearse.\""
    "... That fact that that's something that even needs to be considered greatly worries me."
    k 1 u considerate "\"Anyway, sorry for rambling so much. I really should stop complaining that often.\""
    if keiwhine == True:
        mc 1 u considerate "\"It's... well, I won't say it's fine but you shouldn't worry all that much about it.\""
        k 1 u worried "\"Well, I'm not just going to forget what you guys said. It's something I need to be a little more on the lookout for so I don't annoy everything with my constant complaining.\""
        mc 1 u wry "\"I think you're taking this a little too seriously.\""
        k "\"Hmm... I don't know. Just something to think about.\""
    else:
        mc 1 u considerate "\"Why are you even apologizing in the first place? Is this about what Kiyoshi-san said that other day? You're not still thinking about that are you?\""
        k 1 u sigh "\"Even if not {i}everyone{/i} agrees with him doesn't mean that it's not a problem because someone else still might.\""
        k 1 u worried "\"It's just better to be on the lookout for that sort of thing so it doesn't keep happening.\""
        k 2 u annoyed "\"Believe me, now that I started being more conscientious of it I started to realize just how often I get an urge to complain.\""
        mc 1 u considerate "\"That's... so long as you're okay with it... I guess?\""
        "Not that I agree with it but there's not much point in arguing with him over something so petty either."
    k 1 u wry "\"Anyway, I've taken far too much of your time already. And I do need to get home and study a little bit.\""
    mc 1 u wince "\"Don't be ridiculous, I enjoy spending time with you. You're not \"taking up\" anything.\""
    k 1 u smile "\"Hehe. I appreciate that, I really do.\""
    k 2 u gentle "\"Once midterms are over I'll make sure to take us both on a real date.\""
    mc 1 u fsmile "\"Y-you don't have to worry about that sort of thing.\""
    k 1 u smile "\"It's only natural for me to want to, no? It's not like it's something I'm obsessing over either.\""
    mc 1 u considerate "\"I know, I know... {size=-4}It's just a little bit embarrassing to hear it said out loud.{/size}\""
    k 2 u gentle "\"Hehe. That's part of the reason I say it. Teasing you is just so fun.\""
    mc 1 u sigh3 "\"Just don't complain if I end up biting you in response.\""
    k 1 u smile "\"Who says I wouldn't like that?\""
    mc 1 u flustered "\"W-what?!\"" with hpunch
    k 2 u gentle "\"Hahaha, I'm just kidding, don't worry.\""
    mc 1 u considerate "\"I-I say, that's really fu-{nw}"
    k 1 u smile "\"Or {i}am{/i} I?\""
    "The hare winks at me, sporting a mischievous grin."
    "The whole gesture along with his words causes my brain to overheat to never before seen proportions."
    "I need to look away, covering my mouth with my hand and feeling my face growing ridiculously hot."
    "I don't even know how to respond to that."
    k "\"Hehe, you're really cute when you're embarrassed. But I do have to leave.\""
    k 2 u gentle "\"I will see you later, [povFirstName]. Bye bye.\""
    mc 1 u avoid "\"Y-yeah. Bye bye...\""
    stop music2 fadeout 2.5
    show k 1 u smile at fdis, offscreenright with moveoridis
    "Keisuke walks away and disappears into the masses of people walking around the streets."
    "Most likely he already had a car waiting for him somewhere nearby."
    "Ugh... I'm really getting completely toyed with by a junior."
    "I really can't let this continue. I absolutely refuse to just let him take the lead in our relationship."
    "I need to find a way to fight back somehow!"
    "...{w}"
    play sound "music/disappointment.ogg"
    extend " But for now I'm just going to head home and try to relax a little bit."
    jump Day25_Keisuke
