label Day21_Keisuke:
    window hide
    scene June2 with fade
    play sound "music/windchimes.ogg"
    show blossoms movie
    $ renpy.pause(5.5)
    scene Black with fade
    window show
    $ date = "day21"
    "..."
    "I seem to wake up before my eyes even open."
    "It seems the fatigue of the previous days walking around nonstop has caught up with me."
    "My body feels weak and just... lazy."
    "Ugh... I don't want to get up..."
    "However, slowly I seem to recall something..."
    play sound "music/flashback.ogg"
    show cg9_1base
    show cg9_1_mcblush
    show cg9_1_keiblush
    with squares
    "... !!!"
    play sound "music/fabric.ogg"
    scene Bedroom with fade
    "Waaah!"
    "I shoot up from my bed, my eyes now wide open."
    play sound "music/heartbeat2.ogg"
    "Just remembering what happened yesterday has my heart beating fast."
    "Did... did that seriously happen?"
    "I didn't dream that did I?"
    "..."
    play sound "music/phonebeep.ogg"
    "I grab my phone from the end table next to my bed and unlock it, browsing my messages."
    "O-okay... nothing from Kei-kun it seems."
    "I'd have thought he'd have sent me a message commenting on it."
    "... Or maybe it never actually happened and I'm slowly losing my mind."
    "Hah... what is wrong with me?"
    "Wait, it's only 6:43? It's way early."
    "Is he even awake at a time like this?"
    "..."
    "I tentatively began to write a message for him but can't bring myself to hitting send."
    "What would I even say?"
    "\"Did yesterday really happen?\""
    "That would probably just be hurtful."
    "\"From now on I'm in your care.\""
    "... What am I, a fifteen year old girl?"
    mc 1 n sigh3 "\"Never mind...\""
    "I place the phone back down on the table."
    "Since I'm already up anyway, I might as well get dressed and do stuff with my day..."
    scene LivingRoom with fade
    play sound "music/fabric.ogg"
    "I walk downstairs, quickly flopping on the couch and turning the television on."
    "The whole place is really quiet. I guess no one else in the house is up this e-"
    show a 1 u at fdis, five with moveiledis
    a "\"Huh? Aniki? What are you doing up so early?\""
    "Or not."
    play music2 "music/BGM/Windswept.ogg" fadein 5.0
    "I sit up properly on the couch and take a good look at Aki."
    mc 1 c confused "\"Why are you wearing your uniform?\""
    a 1 u sigh "\"Just because your school has today off after the festival doesn't mean mine does. Our festival is only in November.\""
    "Oh... right. Today is only just Friday."
    "It's a good thing we got the day off. I'm feeling way too lazy to go to school today."
    mc 1 c considerate "\"Right right. I forgot. Sorry, I'm just not all there today.\""
    a 1 u "\"Are you okay?\""
    mc 1 c talk "\"More or less. I just feel pretty tired. Kinda want to just be lazy.\""
    a 1 u sigh "\"You're only eighteen. You shouldn't be acting like an old man.\""
    play sound "music/stab.ogg"
    mc 1 c considerate "\"Y-yeah. I get you...\"" with hpunch
    "Aki... your tongue is way too sharp for a twelve year old..."
    a 1 u sigh "\"So you're just going to sit around all day and do nothing?\""
    mc 1 c considerate "\"That's what I was planning on.\""
    a 1 u "\"Must be nice not having anything better to do with your time. Oh wait, your midterms are next week, maybe you should study.\""
    mc 1 c sigh3 "\"Are you incapable of saying anything that isn't negative?\""
    a 1 u sigh2 "\"I can. I choose not to.\""
    mc 1 c considerate "\"It wouldn't kill you to smile sometimes you know.\""
    a 1 u "\"I smile plenty. You just don't get to see it because you always force me to silently judge you.\""
    "No, there's nothing silent about it..."
    mc 1 c smile "\"Come on, sit down with your older brother for a bit and relax. You don't have to be in school for nearly another two hours still.\""
    a 1 u avoid "\"I was just getting ready.\""
    mc 1 c smile "\"Well, your fur is already brushed, you're already on your uniform. What else is there for you to do? Have you had breakfast?\""
    a "\"Yeah.\""
    mc 1 c happy "\"Then you've got plenty of time to kill.\""
    a "\"I usually get there early in the day you know. Not everyone gets there at the last minute before the gates close.\""
    mc 1 c smile "\"Maybe, but today you get a chance to spend some quality time with your brother before you leave. Wouldn't you prefer doing that?\""
    a 1 u avoidb "\"It's... not that big of a deal.\""
    "Are you a tsundere? Your tail is wagging pretty hard even though you're trying to deny it."
    play sound "music/fabric.ogg"
    "Aki sits next to me and I immediately wrap my arm around his tiny little shoulder, pulling him a little closer."
    mc 1 c smile "\"See, that wasn't so hard? Tell me, how have you been doing at school.\""
    a "\"I-I'm fine. Nothing much to talk about.\""
    mc 1 c smile "\"Is that so? How are your friends? Have you been getting along well with your classmates?\""
    a 1 u sigh2 "\"What's with these questions? Are you mothering me now?\""
    mc 1 c happy "\"No way. I'm just taking some time to make sure my little brother is doing alright.\""
    a "\"It's creepy so I'd much prefer if you stopped.\""
    play sound "music/stab.ogg"
    "H-harsh!" with hpunch
    "Aki... you're gonna make your big bro cry..."
    a 1 u avoidb "\"... Well, I've been getting along okay for the most part.\""
    "Ah, he still answered the question."
    mc 1 c considerate "\"Really? That's good. Sometimes I worry you don't have enough friends. You never bring anyone home or talk about them much.\""
    a 1 u sigh2 "\"That doesn't mean I don't have any. I just don't see any reason to talk about it.\""
    a 1 u sigh "\"Besides, the last thing I need is you embarrassing me in front of my friends.\""
    mc 1 c sigh "\"How would I embarrass you? I'm pretty tame around most people.\""
    a 1 u avoidb "\"You always find a way.\""
    mc 1 c sigh "\"Name one instance where I embarrassed you!\""
    a 1 u avoid "\"I... uhm... err...\""
    a 1 u sigh2 "\"The point is, I don't want you around my friends.\""
    mc 1 c sigh "\"You just dodged the question!\""
    a "\"I don't owe you any answers.\""
    "So not cute. So so so not cute at all."
    mc 1 c sigh3 "\"You know, I might be older and all but I do still have feelings.\""
    a 1 u avoid "\"...\""
    "I wonder why he doesn't want me around his friends."
    "Is it something I did?"
    "Wait... could it be..."
    "D-did Aki enter his moody teenage years?!" with hpunch
    "No, bring back my cute little Aki! The one that loved to snuggle and spend time with me!"
    a 1 u sigh "\"Aniki, you're making a really scary face...\""
    mc 1 c considerate "\"O-oh, sorry. I was lost in thought.\""
    "... My mind scares me sometimes."
    a 1 u "\"Hey, Aniki?\""
    mc 1 c talk "\"Hmm? Yeah?\""
    a 1 u "\"Do you... think you'd have some free time now that the festival is over?\""
    mc 1 c think "\"Hmm... hard to say. We have midterms next week and then there's also the school trip.\""
    a 1 u wince "\"Ah... I see...\""
    mc 1 c "\"Why do you ask? Is there something you wanted?\""
    a 1 u avoid "\"... I was wondering if you could help me practice sometime.\""
    mc 1 c talk "\"...\""
    "I... wasn't expecting that level of frankness."
    mc 1 c smile "\"Yeah, sure. I can try to make some time.\""
    a 1 u happy "\"Really? You promise?\""
    mc 1 c happy "\"Well, it'll be a bit difficult to find the time but I can't say no to my cute little younger brother.\""
    a 1 u sigh "\"Ugh, can you not say it like that? It sounds creepy.\""
    mc 1 c sigh "\"Do you need to criticize everything I do?\""
    a 1 u smile "\"Yeah. That's what I'm best at.\""
    "So not cute..."
    a 1 u "\"So, Aniki, what are you going to be doing for all of today.\""
    mc 1 c "\"I already told you. Just lazing around.\""
    a 1 u sigh "\"Sure, but lazing around doing what?\""
    mc 1 c happy "\"Nothing.\""
    a "\"... So you're just... gonna sit around staring at space?\""
    mc 1 c smile "\"That sounds good.\""
    a "\"Are you sure we're related at all?\""
    mc 1 c considerate "\"Hey, I did the honor student shtick for years. Gimme a break.\""
    a 1 u "\"It's not a shtick. You should take your studies more seriously than that.\""
    mc 1 c sigh "\"Yeah yeah. I already have enough people to build a whole choir preaching that to me.\""
    a 1 u sigh "\"Then maybe you should start listening.\""
    mc 1 c smile "\"Hmm... nah, not interested.\""
    a "\"Are we sure you're the oldest here?\""
    "You poor thing, if you can't accept a modicum of levity into your life, you're going to be completely destroyed by stress when you grow up."
    mc 1 c smile "\"Well, different people have different points of view. I'll leave it at that.\""
    a "\"The hell does that mean?\""
    "That you're a headstrong little shit but I dare not say that to your face."
    "Somehow I can't picture such a conversation going well at all."
    mc 1 c happy "\"Anyway, do let me know if you need any help okay? You don't have to tiptoe around asking for it.\""
    a 1 u avoid "\"Where did that come from?\""
    mc 1 c smile "\"Well, you just asked me for help with practice so I thought I should clear things up.\""
    a 1 u avoidb "\"... Thanks.\""
    "Heh, he's so not honest about what he wants."
    mc 1 c "\"This reminds me, I haven't practiced myself in a while. The courts being closed while they prepare for the festival is always such a bother.\""
    a 1 u "\"You could go to a private tennis club. That way you'd always have access to courts.\""
    mc 1 c sigh "\"No thanks. I don't like the environment in those private clubs. Besides, they're really expensive.\""
    a 1 u worried2 "\"They're not that bad. I go to one and it's pretty good. And it's not that expensive either.\""
    "Yeah, and it's because you go to one that I pulled out of mine a few years ago."
    "Aki might be mature in a lot of ways but he still has a child's understanding of money."
    "There's only so many ways you can stretch the income in a house that only has one working parent."
    "Although we are doing pretty well for the most part. Not in any danger of going broke or anything."
    "Maybe I might just be a tad overcautious."
    "Mom isn't the spending type either and she lets me manage most of the household groceries so we're able to save money pretty often."
    "Hmm... I guess it wouldn't hurt to treat ourselves a little more often."
    "But somehow I don't think a monthly recurring expense is the way to do it."
    "I much prefer sticking to the school's tennis club."
    mc 1 c "\"I'm glad you're enjoying the club you're in but it's not the same for everyone.\""
    a 1 u sigh2 "\"Yeah yeah, whatever you say.\""
    mc 1 c sigh "\"You really need to work on your attitude a bit. If you're always this dismissive you're gonna have a hard time making friends.\""
    a 1 u smile "\"Don't worry. You're the only one I'm comfortably being dismissive around.\""
    "... I don't know whether that should make me happy or upset."
    a 1 u "\"... You don't look all too happy about it.\""
    mc 1 c sigh "\"Oh really? How did you guess?\""
    a 1 u sigh "\"Y-you don't have to look at me like that. I was only joking.\""
    "..."
    show a 1 u wince at fdis, shake1
    a "\"A-all right, I get it. I take it back, please stop glaring at me.\""
    mc 1 c sigh3 "\"Sometimes I really get the feeling you don't respect me at all.\""
    a 1 u avoid "\"I was just teasing a bit... of course I do.\""
    mc 1 c smile "\"Is that so? Would you be willing to put that in writing? Hang on, let me just get a piece of paper.\""
    a 1 u sigh "\"I take it back, you suck.\""
    mc 1 c happy "\"Aww, thank you. I try.\""
    a 1 u sigh2 "\"That wasn't a compliment!\""
    stop music2 fadeout 2.5
    scene LivingRoom with fade
    play sound "music/tickingclock.ogg"
    "Ah, I'm bored..."
    "It's only been about an hour since Aki left and I'm already bored."
    "I consider doing something at the computer but I'm not quite sure what."
    "I want to do something but at the same time I don't want to get up from the couch."
    "If I keep this up I might actually turn into a couch potato."
    "And I'm pretty sure no one wants that. Not even I want that."
    play sound "music/message.ogg"
    "My phone starts buzzing in my pocket."
    "I immediately pick it up, not thinking much of it."
    "!"
    "I see Keisuke's picture in the message screen and freeze."
    "After a second's hesitation, I decide to open it and see what it says."
    "\"Morning. Are you awake yet? I was wondering if you wanted to do something today.\""
    "... How so like Kei-kun to have proper grammar and punctuation even in a text message."
    "That's... a lot more normal than I thought it would be."
    "Somehow, I expected things to be a lot more awkward..."
    "But then again, you can't gauge awkwardness from text message very well."
    "Hesitantly, I begin typing back."
    "\"i'm awake. wht did u have in mind?\""
    "Considering what I know of Kei-kun, I can imagine him cringing just by reading the way I type."
    "Heh, maybe that's why he rarely ever messages me."
    "Oh, he's typing back."
    "\"Come over? And bring your tennis gear too. I'll have a car go pick you up. Thirty minutes sound okay?\""
    "Wha... my tennis gear?"
    play sound "music/disappointment.ogg"
    "Is tennis his idea of a date?"
    "... But then again, he never called this a date did he?"
    "Maybe I'm expecting too much..."
    "\"yeah, sounds good. see ya.\""
    "Well... I guess my plans to sit around doing nothing are a bust."
    "Good thing I already showered when I woke up."
    "Gonna pack my stuff real quick. Will probably even have time to spare."
    "That means I can come up with a plan of attack for my awkwardness."
    "... I really hope I don't screw this up."
    play music2 "music/BGM/In That Mood.ogg" fadein 5.0
    play sound "music/slidingdoor.ogg"
    scene KeiRoom
    show k 1 c smile at fdis, seven
    show kur 1 u smile at fdis, three
    with fade
    "Kei-kun's house is just as fancy as always."
    "Just the trek from where the cars park to his room is almost five minutes."
    "Seriously, this place is unnecessarily big."
    kur "\"Please go right in.\""
    k 2 c gentle "\"[povFirstName], good to see you.\""
    "As soon as I open the door to his room and am ushered inside, Kei-kun calls out to me."
    "... The very first thing I notice is he just addressed me differently from usual."
    mc 1 c talk "\"G-good to see you too. Did you just call me... [povFirstName]?\""
    k 1 c worried "\"Hmm? Yeah, I did. Why? Don't you like that?\""
    mc 1 c considerate "\"You just dropped the honorific, it's not like it's a big change.\""
    "Although from the prim and proper Kei-kun, it does stick out like a sore thumb."
    kur "\"I will leave you two to your devices. Unless there is anything else you require of me?\""
    k 1 c smile "\"Ah. No, thank you very much, Kuroda. You're dismissed.\""
    kur "\"As you wish. Do not hesitate to call if you need anything.\""
    play sound "music/slidingdoor.ogg"
    show kur 1 u smile at fdis, offscreenleft with moveoledis
    show k 1 c smile at fdis, fiveh with move
    mc 1 c talk "\"Man, I'm always surprised when I come here. This place really is uselessly big.\""
    k 1 c sigh "\"You can say that again.\""
    mc 1 c "\"By the way, how come every time I come over I'm always seen inside by Kuroda instead of Alex? Isn't {i}he{/i} your private butler?\""
    k 1 c "\"Yes and no. He might be called that in name but Alex barely does any kind of butler duties.\""
    mc 1 c talk "\"Then what does he do around here?\""
    k 1 c smile "\"Mostly whatever I ask him to do. He has no obligations around the house like Kuroda does. He does tend to keep an eye for intruders so he's always hanging around just outside.\""
    "So what he's saying is that they can afford to hire someone to just stand around waiting to be called."
    "This family really astonishes me sometimes."
    k 1 c worried "\"But getting back to what was said earlier, if I may ask, why did me calling you by your name bother you?\""
    mc 1 c considerate "\"I already said it didn't bother me. And why are you being so weirdly formal all of a sudden?\""
    mc 1 c worried "\"I'm just not used to you calling me that way. I don't think I've seen you call anyone without honorifics before.\""
    k 1 c "\"I'm sure it's happened once or twice before, but you're right, I don't make a habit of it.\""
    k 1 c smile "\"I just thought that since you and I are now a couple, we could start calling each other by our first names.\""
    k 2 c gentle "\"Of course by that I mean I want you to start calling me \"Keisuke\" instead of \"Kei-kun\" too.\""
    mc 1 c fsmile "\"I-Is that so?\""
    k 1 c worried "\"... Does it bother you?\""
    mc 1 c considerate "\"No, that isn't the right word to describe it.\""
    "More like... it weirds me out just how normal he's being."
    "I guess I was expecting a lot more awkwardness when we talked for the first time after yesterday."
    "But then again, even yesterday he was pretty calm about the whole thing."
    "Kei-kun might just be a much more confident than I gave him credit for."
    "... At least when it comes to interpersonal skills."
    mc 1 c talk "\"Well... it's not like I mind it. Although I'm pretty used to calling you Kei-kun so I might slip back to it every now and again.\""
    mc 1 c smile "\"But if you want me to call you Keisuke then I will.\""
    k 2 c gentleb "\"... Thank you.\""
    "Kei-k... Keisuke might just have some pretty old-fashioned ideas of dating."
    mc 1 c considerate "\"I do want to know why the sudden request though.\""
    k 1 c worried "\"Sudden? I thought this would be pretty normal now that we're dating.\""
    "Well, I can't really say anything otherwise."
    "I have never done this kind of thing when I dated before, but then again I was downright resistant to even spending time with them."
    mc 1 c smile "\"Well... never mind. I guess it doesn't matter to me one way or another anyway.\""
    k 1 c smile "\"Yeah, that's a good way to look at it.\""
    mc 1 c talk "\"Did you have something you mind when you called me over?\""
    "I lightly shake my tennis bag for effect."
    "Kei-kun chuckles and points at it."
    k "\"That's for later. Feel free to go ahead and set it down wherever you want for now. Let's just enjoy some time together first.\""
    "Wherever I want? That's a bit more lax than I was expecting."
    play sound "music/fabric.ogg"
    "I do as I was told, putting my bag on the floor up against the wall and out of the way."
    "Last thing I need is for someone to trip on this."
    k 1 c "\"Oh, actually, before I forget.\""
    "Kei-k- Keisuke walks up to his desk and opens a drawer."
    "He grabs something from inside that I can't quite see and walks up to me."
    k 1 c smile "\"Here you go. I believe these are your brother's.\""
    mc 1 c shock "\"Aki's earbuds.\""
    k 1 c wry "\"Yeah. It turns out they were in my bag after all. I brought them to school on the last day of the festival but... with all the craziness that happened, I forgot to give them to you. I'm sorry.\""
    mc 1 c smile "\"It's alright. Aki will be the one happy to get these back.\""
    k 2 c gentle "\"Next time I see him I will make sure to thank him for lending them to me. And for being patient when I accidentally took them away.\""
    show k 1 c wry at fdis
    play sound "music/tap.ogg"
    "I turn myself around so I can walk up to my bag and store these but am grabbed by the wrist before I have the chance to."
    mc 1 c talk "\"Huh? Do you need something?\""
    k "\"Nah, not really.\""
    "He gently squeezes my wrist, his hand moving down my arm until it's wrapped around mine."
    "I was so caught by surprise with the sudden grabbing of me that I didn't even realize what he was doing at first."
    mc 1 c avoidb "\"T-that's my hand.\""
    k 2 c gentleb "\"Indeed it is. Shocking, huh?\""
    "He doesn't seem remotely fazed by his total awkwardness."
    "In fact, he seems to find it funny for some reason."
    k 1 c smile "\"Is it alright for me to hold it like this?\""
    mc 1 c avoidb "\"I-I don't mind. If that's what you want.\""
    play sound "music/disappointment.ogg"
    "Oh man, this is painful..."
    "Every word out of my mouth is painful."
    "Why must I be so friggin' awkward?"
    k 1 c considerate "\"Sorry, is this too much too soon?\""
    mc 1 c considerate "\"M-maybe?\""
    "He pulls away, awkwardly scratching the back of his neck."
    k "\"Sorry. I'll make a mental note to better control myself.\""
    mc 1 c wince "\"No no, you're fine. I just wasn't ready for that.\""
    k 1 c smile "\"Heh. I have to admit, it's cute to see that for all your experience you can still be this awkward around the subject.\""
    "Gee, thank you for surmising my suffering."
    "I finally let go of a breath I didn't even know I was holding, awkwardly stepping away and stuffing the earbuds inside my bag."
    "My mind is scattering to try and come up with something to say to land us on neutral ground."
    "Something that will allow me to stop acting like a nervous wreck would be a good starting point."
    mc 1 c talk "\"So... how are your nerves doing? After the show yesterday and all.\""
    k 1 c avoid "\"... I have mixed feelings.\""
    "Oh oh."
    "Did I just poke the hornet's nest?"
    mc 1 c considerate "\"What's wrong?\""
    k 1 c sigh "\"... I won't lie. I enjoyed performing yesterday. It felt really good.\""
    k 1 c avoid "\"But I hate how sudden it was. I feel like I had no time to prepare.\""
    mc 1 c considerate "\"To be fair, you can't quite predict losing your own voice. Ichigo wasn't prepared for that either.\""
    k 1 c sigh "\"Fair enough. I just really hate the circumstances that led to the whole thing, even if I don't mind what happen.\""
    mc 1 c smile "\"Is it safe to say you enjoyed performing?\""
    k 1 c avoid "\"... Yeah.\""
    mc 1 c happy "\"That's great then, you should be happier!\""
    k 1 c sigh "\"[povFirstName], you're way too chill about everything.\""
    "Well... I wouldn't say {i}everything{/i} but I do like to think I'm pretty relaxed in general."
    mc 1 c "\"If it bothers you then I don't mind talking it out but as it is, I don't see the issue.\""
    k 1 c avoid "\"I guess that makes sense. I'm just being oversensitive.\""
    "Oh oh. Those aren't words I like to hear."
    mc 1 c considerate "\"Are you... by any chance... sulking?\""
    k 1 c sigh "\"Wow, Sherlock. You cracked the case. How could you tell?\""
    "Oh no..."
    play sound "music/disappointment.ogg"
    "You mean to tell me I tried to redirect the conversation from an awkward topic and accidentally stepped on a landmine?"
    "Out of the frying pan and into the fire..."
    mc 1 c considerate "\"Sorry... I shouldn't have brought it up.\""
    k 1 c avoid "\"Not your fault. It's not like you knew. I didn't exactly advertise that I was upset either.\""
    mc 1 c "\"Did you maybe ask me to come over so I could keep you company and get your head off of it?\""
    k 1 c sigh "\"No... well, yes. But... not really.\""
    mc 1 c sigh "\"... Which one is it?\""
    k 1 c avoid "\"I just wanted to spend time with you, okay? Sue me.\""
    "Heh. And I'm the only one who's awkward about admitting these things?"
    mc 1 c considerate "\"And tennis is your idea of a way to spend time together?\""
    show k 1 c at fdis
    "He looks at me with confusion for a second before his eyes snap to my bag."
    k "\"Huh? No, not really. I just felt like I hadn't gotten some good practice in a while and I couldn't wait until after the midterms to get started so I thought this would be a way to kill two birds with one stone.\""
    play sound "music/disappointment.ogg"
    "So asking me to play with you is just a matter of convenience?"
    "I don't know why but that sort of annoys me a little bit."
    "... I'm probably being overly picky."
    k 1 c smile "\"Who knows. Maybe I'll finally manage to steal a set from you.\""
    mc 1 c considerate "\"Yeah... Sure...\""
    k 1 c worried "\"What? You don't think I can do it?\""
    mc 1 c smile "\"I didn't say a thing.\""
    k "\"But did you try to hint at it?\""
    "Dude, you really need to relax a little bit and stop trying to find hidden meaning in everything..."
    mc 1 c talk "\"Stop trying to read so much into it.\""
    k 1 c "\"Yeah yeah, my bad.\""
    play sound "music/knock.ogg"
    "There is a sudden knock on the door."
    "The sound echoes loudly. Whoever it is that is knocking must have pretty heavy hands."
    k "\"Yes?\""
    "The door is open just slightly, so there is a sliver of space in it."
    kur "\"Forgive me for the disturbance. Master Kiyoshi has dropped by and wants to see you.\""
    k 1 c uncomfortable "\"Kiyoshi-san? Here? Now?\""
    kur "\"Yes. May I let him in?\""
    k 1 c sigh "\"Yeah, sure. See him in.\""
    show k 1 c worried at fdis
    "There is some shuffling behind the door and it's clear Kuroda walk away, probably to go fetch the lizard."
    mc 1 c talk "\"Uhm... I take it from your reaction you weren't expecting any more visitors?\""
    k "\"Yeah. I have no idea what he's here for.\""
    mc 1 c smile "\"Maybe he wants to check up on his old guitar. See if you're taking good care of it.\""
    k 1 c smile "\"You joke about it but I wouldn't put that sort of thing past him.\""
    mc 1 c wince "\"Wait, really?\""
    k 1 c calm "\"Kiyoshi-san is an instrument maniac after all.\""
    "... How come you make that sound like a compliment when by all means it shouldn't be."
    "You two have the weirdest relationship..."
    "Although I guess everything about Kei-kun is out of norm."
    "Now that I think about it... agreeing to date him is the equivalent to throwing myself into a snake nest isn't it?"
    "... I'm eventually going to have to deal with that family of his."
    "Ugh, no, happy thoughts for now. Don't get ahead of yourself."
    "I really need to get my bearings on my own situation before I try to think of anyone else's."
    play sound "music/slidingdoor.ogg"
    show k 1 c at fdis, three with move
    show ki 1 u smile at fdis, seven with moveiridis
    "The door is nearly flung open, the lizard stepping inside and taking a quick glance around the room."
    k 1 c "\"Morning, Kiyoshi-san.\""
    ki "\"Wow, your room is... exactly the same as it was the last time I was here.\""
    k 1 c worried "\"What exactly were you expecting?\""
    "It seems like he completely ignored Keisuke's greeting and just started doing a tour of the room."
    ki "\"Oh no wait, I think this is new.\""
    "He crouches in front of the entertainment center and starts looking at a little snow globe type adornment with great interest."
    "Keisuke and I both share a look of puzzlement."
    "Or, well, I look puzzled while Keisuke merely shrugs."
    "He's probably used to this sort of thing already."
    k 1 c "\"Kiyoshi-san, it's rude to just barge in without saying a word.\""
    "The lizard, acting as if he'd only just noticed us, turns around with a broad smile and puts his hands to his hips."
    ki "\"Ah, there you are. I've been meaning to talk to you. And hey, it's the mute kid from last time too.\""
    mc 1 c fsmile "\"M-mute?\""
    "This guys is either unbelievably rude or just completely clueless."
    "I'm still not quite sure which."
    k 1 c worried "\"Did you want something, Kiyoshi-san? It's unusual for you to show up at the estate.\""
    ki "\"What? Do I need a reason to come over to my long time friend's house and visit my adorable little nephew?\""
    k 1 c sigh "\"I am not your nephew and you are not my uncle. Also, you {i}never{/i} come here so yes, I'd imagine you'd need a reason for it. Even last time you had me come over instead.\""
    ki "\"Pffft, details details. Our familial bond cannot be tied down just a single common word like \"family friend\". Aren't I right, mutey?\""
    "M-mutey?!"
    "Also, \"family friend\" isn't even a single word. It's an expression!"
    k 1 c worried "\"Kiyoshi-san, please refrain from insulting my friends while you're here?\""
    "He puts a hand to his chest, his mouth hanging agape and his eyebrows raised higher than I thought they could be, especially in a reptile."
    ki "\"What? {i}Insulting{/i}? Me?! I would never!\""
    "He is apparently trying his best to look shocked and insulted (ironic) but Keisuke doesn't even react to it."
    k "\"Kiyoshi-san, you're of course welcome to continue this little game but just know I'll be calling Alex if that's the case.\""
    ki "\"Whoa whoa whoa, let's not get ahead of ourselves okay? There's no need for that!\""
    "And he immediately drops the exaggerated, pompous expression in favor of holding his arms in front of his body looking fairly frazzled."
    k 1 c sigh "\"God damnit. I don't know what annoys me the most. That you act that way or that just name dropping Alex is enough to get you to stop.\""
    ki "\"Tch. Each and every time I keep having to tell you. You're way too uptight, Kei-chan.\""
    k 1 c angry "\"Don't call me K-{nw}"
    show k 1 c sigh at fdis
    extend " Ugh, actually nevermind. This is just a waste of precious energy.\""
    ki "\"Oh, ouch. That's a harsh thing to say.\""
    k 1 c avoid "\"Frankly, you deserve worse. What an annoying person you are.\""
    ki "\"W-what?\""
    "Whoa, even I am taken aback by that comment."
    "Kiyoshi-san stares at the hare with wide open eyes, obviously incredible shocked."
    mc 1 c considerate "\"H-hey, Keisuke... that was a bit-\""
    show k 1 c worried at fdis
    ki "\"{size=+4}Bahahahahahahaha!{/size}\"" with hpunch
    "The lizard suddenly lets out a deafeningly loud laugh, one that almost seems like he's roaring from how loud it is."
    ki "\"Dang, you've got spunk. I've never seen you be this upfront before. I like it, you should be more forceful more often.\""
    mc 1 c fsmile "\"H-huh?\""
    "He... he {i}liked{/i} Keisuke's insult?"
    "What the hell is wrong with this person."
    k "\"[povFirstName], I know what you were going to say but Kiyoshi-san isn't someone that can be understood with common logic. If you try to play nice or act normally he's just going to have his way with you.\""
    ki "\"Gee, kid, that doesn't sound ominous at all. That all the love you have for your uncle Kiyoshi?\""
    k 1 c sigh "\"Just tell me whatever it is you came over here to tell me already. I don't want to spend all day going around in circles.\""
    "The lizard smiles, shrugging and lifting his hands with their open palms to the sky, shaking his head sideways with great amusement."
    ki "\"What? Who says I didn't just come over to play around with you for a bit?\""
    k 1 c "\"... Kiyoshi-san, I'm giving you five seconds to start talking before I call Alex over to eject you from the building.\""
    "The lizard frowns."
    ki "\"Not an ounce of humor. Are you really your father's son?\""
    k 1 c sigh "\"Quite unfortunately. Now spill.\""
    "Smiling again, the lizard fishes inside his pocket for a while."
    "I hear the rustling of... dozens of pairs of keys coming from inside. Or at least I think they are keys."
    "But it's way too loud. Why would someone walk with that many keys in their pocket?"
    ki "\"I wanted to congratulate ya on your performance, kiddo.\""
    k 1 c worried "\"My... my performance?\""
    "Keisuke's whole demeanor stiffens right away."
    "At the mention of a piece of information that Kiyoshi-san shouldn't know, Kei-kun's whole body stands up straighter than usual."
    ki "\"Yeah. I mean, I was super disappointed when ya said you wouldn't perform but dang, kid, you really had me.\""
    play sound "music/phonebeep.ogg"
    "He starts fiddling with his phone and before I know it, he's shoving it in our faces, playing some loud music."
    show k 1 c shock at fdis
    play sound "music/BGM/My Voice Phone.ogg"
    "My jaw hits the floor when I see what it is."
    "In front of my eyes is a video taken of the band performance yesterday."
    "It is taken from somewhat far eye and kinda blurry but both Keisuke's appearance and voice are unmistakable in it."
    "The lizard is smiling from ear to ear as he shows us, kinda humming along with the song."
    show k 1 c worried at fdis
    play sound "music/phonebeep.ogg"
    "Keisuke presses the pause button on Kiyoshi's phone, stopping the song on its track and staring at the lizard with a face whiter than I'd ever seen, even from him."
    k "\"How... how did you get this?\""
    ki "\"How? It's on the internet. Someone had forwarded it to me while I was asleep and I saw it right after I woke up. That's why I came over to talk to ya. You didn't have to lie just so I wouldn't come watch.\""
    k "\"N-no. That's not it. That's not it at all! I wasn't even... why is this on the internet?!\""
    "The lizard shrugs, putting the phone back in his pocket."
    ki "\"I dunno. It's the era of smartphones so ya couldn't think it wouldn't be recorded.\""
    k "\"I... I wasn't even supposed to be singing in the first place. Do you think I had time to think of that?!\""
    "Kiyoshi muses the question for a second, stroking his chin thoughtfully."
    ki "\"Ya saying this was a fluke?\""
    k 1 c angry "\"Of... of course it was a fluke! As if I'd want my face plastered all over the internet!\""
    "He shouts, his voice so loud it almost sounds like a roar."
    "There have been very few times when I've seen Keisuke this angry."
    "I almost take a step back instinctively."
    k 1 c sigh "\"I... Crap, this is bad. At least... at least this is probably just some silly impromptu video. How many views does it even have? Ten? Twenty?\""
    "Kiyoshi cracks a smile... except this time it seems different."
    "His brows are furrowed and the corners of his mouth barely curve up."
    "He crosses his arms, almost like he were craddling himself."
    "Is that a look of... pity?"
    ki "\"Yer... a little off.\""
    k 1 c wince "\"H-how off?\""
    ki "\"Wrong by around a factor of a thousand.\""
    stop music2 fadeout 2.5
    show k 1 c shock at fdis
    "I feel my heart sink the instant I hear that."
    "One look to the side and Keisuke's face says everything."
    k "\"Y-you're kidding. Please tell me you're kidding!\""
    ki "\"It's got almost twenty thousand views. Honestly, even I was shocked.\""
    "He speaks nonchalantly, the words he says and his demeanor around them not matching up."
    "He speaks almost as if such a result were a foregone conclusion, despite saying that it is surprising."
    "Keisuke's face completely drains of color, having gotten whiter and whiter with each passing second."
    "At this point he almost looks like a ghost."
    k "\"No no no no no no. Please say \"just kidding\" or something of the sorts.\""
    "The lizard shakes his head in negative, pulling his phone out of his pocket once again."
    play sound "music/phonebeep.ogg"
    ki "\"If you don't believe me then see it yourself.\""
    "Instead of playing the video again, he scrolls down and shows us the screen."
    "19247 views... and the video was only just posted a bit under twelve hours ago."
    "How..."
    k "\"This... this is really bad.\""
    mc 1 c considerate "\"It's definitely surprising but... is it really all that bad.\""
    k 1 c worried "\"My family was already getting on my case over being a {i}manager{/i} at a band. Now there's a video of me singing live going viral? They'll flip out.\""
    "Kiyoshi laughs dryly, clearly picking the worst timing to find humor in the whole situation."
    ki "\"Don't get over yer head, kid. You're still a few million views short of being viral.\""
    k 1 c angry "\"So so {i}so{/i} not the point.\""
    play sound "music/fabric.ogg"
    "Kei-kun nearly jumps at Kiyoshi's hand, snatching the phone away from him."
    ki "\"H-hey!\""
    k "\"How... how do I delete this?\""
    ki "\"You can't delete it, you're not the user who uploaded it.\""
    k "\"Then... then I'll stake a copyright claim. Ask the website to pull it down for using my image without permission.\""
    ki "\"Ya could try but it'd probably just pop up again in another site. I mean, I've seen this thing getting posted in a bunch of social media too.\""
    k 1 c sad "\"You're... you can't... no...\""
    play sound "music/fabric.ogg"
    "The hare completely deflates, stumbling backwards and falling on his bed."
    "He stares at the floor, completely lost in a daze."
    mc 1 c worried "\"Come on... it can't be that bad.\""
    k "\"Do I really need to explain to you why it's bad again?\""
    mc 1 c considerate "\"Maybe... maybe your family won't notice...\""
    k 1 c sigh "\"The company has people whose entire job description is to scour the internet for any possible PR issues. This will be getting reported to my father before the end of the day.\""
    ki "\"To be honest I'm surprised he doesn't know already. Although I'm not about to tell him either.\""
    k "\"I don't think I've ever seen you have this much good sense before.\""
    ki "\"Pfft? Good sense? I just don't want you sending Alexander over to beat the crap out of me.\""
    k 1 c avoid "\"Oh... good... I'm being treated nicely just for fear of physical punishment. Isn't that just great?\""
    ki "\"H-hey, I was just joking.\""
    mc 1 c sigh "\"That was just a stupid joke to make. Even at the best circumstances it'd be tone-deaf.\""
    "The lizard winces, hugging his arms and rubbing his elbows awkwardly."
    ki "\"Come on, kid, I thought ya'd be happy to see it trending.\""
    k 1 c sigh "\"Suuuure. Because I don't already deal with enough crap at home. What I need is {i}more{/i} stuff put on my plate.\""
    ki "\"I don't know what to tell ya. I just thought it'd make you happy to get all this attention. I mean, come on, all these people are saying good things about the performance.\""
    k "\"That hardly matters right n-{nw}"
    show k 1 c worried at fdis
    extend " Wait... all of them?\""
    ki "\"Yeah, you should read the comments. They've got nothing but praise for ya guys.\""
    "Keisuke lifts the phone to his face."
    k 1 c "\"It's locked.\""
    "He mutters dryly, not an ounce of humor or... anything really in his voice."
    ki "\"Here, let me.\""
    play sound "music/phonebeep.ogg"
    "The lizard runs his finger on the fingerprint scanner around the back and the screen magically comes to life."
    ki "\"Just scroll down and look. I'm sure you'll like what you see.\""
    "Following Kiyoshi's instruction, Keisuke begins to scroll down the screen."
    "I take a seat next to him so I can see the comments too."
    mc 1 c talk "\"Oh wow. This one is asking when will be you guys' next show.\""
    k 1 c worried "\"Look at this one. \"Who's the raven on the stage? He's super cute\".\""
    mc 1 c "\"Wait, there are comments like that for pretty much every member of the band.\""
    k 1 c smile "\"I don't see any for Kurusu though.\""
    mc 1 c considerate "\"So he's the butt-monkey even for people who've never met him before? That's just sad.\""
    k 2 c gentle "\"When you try too hard to be cool, you just come off as desperate instead.\""
    mc 1 c smile "\"Hey, look. \'assvenger97\' says he would buy a ticket to a concert if you guys played at a livehouse.\""
    k 1 c worried "\"No way. Really?\""
    ki "\"See? What did I tell ya? Isn't this a good thing?\""
    k 1 c sigh "\"... I'll admit that I'm flattered at all the compliments, but that doesn't change anything.\""
    show ki 1 u smile at fdis, shake1
    ki "\"Aaaaah, goddamnit. You're killing me here, kid. Ya can't be happy about one single thing!\""
    k 1 c worried "\"W-what? I didn't mean to-\""
    ki "\"Seriously, always complaining about something. Ya gotta whine a little less and get stuff done more.\""
    k 1 c wince "\"Do... do I really whine that much?\""
    "He shoots me a questioning look."
    "I'm not quite sure where to look or what to say."
    "Of course I have my own opinions about it, but..."
    "It's not something I ever stopped to think about before so I'm not sure what to say."
    "When I try to look back and think of my interactions with Keisuke..."
    menu:
        "I guess he..."
        "Complains too much":
            $ keiwhine = True
            $ keilove -= 1
            mc 1 c worried "\"... Kinda? You do tend to complain a fair bit.\""
            k 1 c worried "\"Oh.\""
            mc 1 c wince "\"But it's not like it's a bad thing or anything!\""
            ki "\"Sure it's a bad thing. Whatcha talking about? It's a terrible thing. No one wants to work with the guy that has fame as a whiner.\""
            mc 1 c sigh2 "\"Kiyoshi-san, you're not helping.\""
            ki "\"Yes I am. He ain't a kid any more. Can't keep acting like one and complaining about everything when he doesn't get his way. Ya gotta grow up at some point and learn to deal.\""
            k "\"Learn to deal, huh?\""
            mc 1 c worried "\"That's way too harsh. You don't have to say it like that.\""
            ki "\"Hey. If ya cared then you would too. Ya can't coddle people forever. He needs to know why what he's doing isn't gonna work forever.\""
            "I nearly jump out of my seat, standing face to face with the lizard."
            "I can't even begin to understand why but I realize I am incredibly irritated right now."
            mc 1 c sigh "\"There is such a thing as tact. You don't have to just drop something like this as if it were a bomb.\""
            "The lizard shrugs."
            ki "\"Tough love is my thing. I don't do coddling.\""
            k 1 c considerate "\"... Thank you for this lesson, Kiyoshi-san.{nw}"
            show k 1 c worried at fdis
            extend " Now would you mind leaving? I kinda wanna have some time to think right now.\""
            "Kiyoshi blinks a few times, stunned."
            "He probably didn't expect to be asked to leave after speaking up."
            "I don't blame him, but even though he had good intentions, there is a good way to say things and this wasn't it."
            ki "\"Alright. If ya want me gone then I'll go. Still, I wanted to tell ya I'm damn proud of ya regardless. That okay?\""
            "Keisuke nods, his eyes glued to his feet, looking anywhere but at the lizard's face."
            "Kiyoshi stands there, expecting some kind of response."
            "Once he realizes he's not getting any, the lizard sighs, rubbing his forehead."
            "I think this is the first time I've seen him actually drop the overly cheerful act and act serious."
            ki "\"I'll keep in touch, kid. Come to me if ya need anything. I mean it.\""
            play sound "music/slidingdoor.ogg"
            show ki 1 u smile at fdis, offscreenright with moveoridis
            show k 1 c worried at fdis, fiveh with move
            "He walks out of the room without any further words or even a single backwards glance."
            "However, despite him leaving, Keisuke's eyes continue focused on his feet."
            mc 1 c worried "\"... Kei-kun?\""
            "I try calling him with the gentlest voice possible but he doesn't seem to respond to me at all."
            "The room is taken up by an awkward silence that hangs over us like a dark shroud."
            "I keep switching my weight from one foot to the other, just staring at Keisuke and waiting for some kind of response."
            "After what feels like an eternity, I decide there is no point to this exercise in patience."
            mc 1 c wince "\"Do you want me to leave too?\""
            show k 1 c sigh at fdis
            "Finally, he shifts on his seat, sighing."
            k "\"You're... mostly fine. I much prefer if you're honest with me, even if I don't like what I hear.\""
            k 1 c avoid "\"It wouldn't do for us to start our relationship with a lie, especially one as silly as this.\""
            play sound "music/stab.ogg"
            "For some reason, I feel like I just got stabbed right in the chest."
            "I hadn't even considered that when I spoke up."
            "In fact, there are lots of things I didn't even consider before I spoke."
            "I... really need to do better at the whole thinking before I say anything."
            k 1 c considerate "\"I guess I have some more stuff about myself I need to consider.\""
            mc 1 c considerate "\"You don't need to worry about it so much.\""
            k 1 c worried "\"You just said it yourself. I complain too much. No one wants to be around a whiner.\""
            mc 1 c talk "\"That's not true. You still have me, Saya-chan, Shoichi, Jun.\""
            k 1 c sigh "\"... I know you're trying to cheer me up but the way you said it makes it sound like everyone also thinks of me as a whiner.\""
            mc 1 c fsmile "\"W-what? T-that's not what I-\""
            k 1 c avoid "\"You really suck at emotional support sometimes.\""
            "I'm trying okay!"
            mc 1 c sigh3 "\"Sorry...\""
            k 1 c considerate "\"Well, there isn't much that can be done about it. If anything, I appreciate the candor.\""
            k 1 c smile "\"I myself have a hard time being honest when I know it might hurt someone else's feelings so I get how difficult it must have been.\""
            mc 1 c shock "\"Wait, what?!\""
            "Kei-kun has trouble being {i}honest{/i}?! If anything I've always known him for being overly blunt!\""
            k 1 c worried "\"W-what? Did I say something wrong?\""
            mc 1 c considerate "\"N-no. Sorry, I reacted to something stupid. Don't mind me.\""
            k "\"... Something tells me you're hiding something from me.\""
            "I've already basically insulted him once in the past five minutes, I don't need to do it again."
            "One earth shattering realization at a time."
            mc 1 c considerate "\"So... you know, since I'm already here and all, do you think we could talk about yesterday?\""
        "Is fine":
            $ keiwhine = False
            "Even if I search as far back as my recollection will allow me – which is surprisingly not that far, mind you – I can't seem to recall Kei-kun being \"whiny\"."
            "He's very opinionated and vocal about it, sure, and he has complained on occassion but..."
            "I dunno, none of it ever struck me as being \"too much\"."
            mc 1 c talk "\"I'm sorry but I can't agree with that.\""
            "The lizard's brow twitches and he stares at me in consternation."
            ki "\"Come on now. You gonna keep quiet and let me be the bad guy.\""
            mc 1 c worried "\"No. If I really did think that I would have said something. Believe me, I even tried to think about it but I just never felt like he complained too much or bothered me with it.\""
            "Kiyoshi's mouth hangs agape."
            "It feels like he's shooting daggers at me with his eyes."
            ki "\"Yer kidding me? All he ever does when he talks to me is complain. I mean, sure, I don't mind giving emotional support. The kid's like a nephew to me but come on, he's gotta grow out of it at some point.\""
            k 1 c worried "\"Kiyoshi-san...\""
            mc 1 c "\"I'm sorry but I just can't agree with you on that.\""
            ki "\"Just because ya can't see it doesn't mean it ain't there.\""
            mc 1 c sigh "\"The same can be said right back at you.\""
            ki "\"Kid, you haven't been around the block as long as I have okay. Trust me, I know what I'm talking about. It's for his own good.\""
            mc 1 c sigh2 "\"What does that have to do with anything? Just because you're old doesn't mean you're right.\""
            k "\"Guys...\""
            "He stares at me in shock, his brow raised impossibly high and his jaw looking like it even popped out of its socket considering how wide open it is."
            ki "\"Are... are ya serious?\""
            mc 1 c sigh "\"And besides, even if you {i}were{/i} right, do you not know the meaning of tact? There is a right way and a right time to say things.\""
            "The lizard points a finger at me, puffing his chest and suddenly taking a somewhat threatening posture."
            "For a second I feel an urge to back away from him but decide to stand my ground instead."
            ki "\"Okay, you listen to me-\""
            k 1 c angry "\"Enough!\"" with hpunch
            "Keisuke's voice echoes loudly inside the spacious room, snapping our attentions completely to him."
            "He stands from where he's been sitting, looking at the both of us with anger and contempt."
            k "\"If you two are going to fight then kindly take it somewhere else. I am not in the mood to entertain fools!\""
            mc 1 c fsmile "\"E-entertain fools?\""
            "I've never seen him talk like this before. What the hell?"
            "It sounds like a line straight out of some kind of overly pompous drama."
            ki "\"Sheesh kid, calm d-\""
            k 1 c annoyed "\"Don't tell me to calm down. Not when you were just about to have a shouting match with [povFirstName] right in front of me.\""
            k 1 c avoid "\"And I mean this for both of you. If you can't behave then go away!\""
            "I swallow a couple of times, feeling my stomach sinking at the sound of his words."
            "Oh man, I've done it now. He's really really pissed."
            mc 1 c fsmile "\"Kei-kun, I-\""
            k 1 c sigh "\"{size=+2}Don't{/size}... don't \"Kei-kun\" me. Just listen to what I have to say and behave. That's all I'm asking here.\""
            "The lizard and I trade a few glances, obviously feeling very confused and embarrassed at the situation."
            "I can't remember the last time I got yelled at like I was a kid."
            "Man this takes me back."
            mc 1 c worried "\"I'm sorry...\""
            ki "\"Yeah, same here. Didn't mean to hurt yer feelings.\""
            k "\"It's... fine. For whatever it's worth, I appreciate your candor, Kiyoshi-san. I'll think over it... later when I don't have a headache.\""
            "Kiyoshi nods, looking down at his feet."
            ki "\"I think I better be on my way then. Don't need to sour yer mood even more.\""
            k 1 c worried "\"I appreciate it.\""
            play sound "music/tap.ogg"
            show ki 1 u smile at offscreenright with moveoridis
            show k 1 c avoid at fdis, fiveh with move
            play sound "music/slidingdoor.ogg"
            "The lizard gives Keisuke a few friendly taps on the shoulder and walks out of the room without another word or backwards glance."
            play sound "music/fabric.ogg"
            show k 1 c sigh at fdis
            "Keisuke collapses back on his bed, sighing loudly and burying his face on his hands."
            k "\"I think I preferred when he barely even noticed you existed.\""
            mc 1 c considerate "\"Sorry...\""
            k 1 c worried "\"You don't have to apologize. Kiyoshi-san can be a pain in the ass. I'm honestly surprised you didn't lose your temper with him way before now.\""
            mc 1 c considerate "\"Well, I like to think I'm a patient person.\""
            k 1 c wry "\"Heh. That's a good joke.\""
            "J-joke? I was being serious!"
            k 1 c sigh "\"Ugh, I'm not even kidding. This whole thing actually gave me a headache.\""
            mc 1 c wince "\"Is there anything I can do to help? Do you want me to leave?\""
            k 1 c calm "\"Nah. Don't be silly. I might be upset but I still value your presence here. Besides, I also appreciate you backing me up with Kiyoshi-san.\""
            mc 1 c smile "\"Awww. Of course, that's what I'm here for.\""
            k 1 c sigh "\"I just want to talk about something else. Anything at all.\""
            mc 1 c talk "\"... Well, we could talk about last night?\""
    play music2 "music/BGM/Let It Happen.ogg" fadein 5.0
    k 1 c wince "\"Oh no. We already talked enough about the performance.\""
    mc 1 c considerate "\"I don't mean talk about the show. I mean... talk about after the show.\""
    k 1 c "\"Oh. You mean talk about us?\""
    "He zeroes in on what I meant to say without a wasted second... and doesn't seem at all bothered or embarrassed to discuss it."
    mc 1 c wince "\"Y-yeah. Is that alright?\""
    k 1 c smile "\"Sure. I don't mind at all. Besides, I'm pretty sure it must be terribly awkward for you.\""
    mc 1 c sigh3 "\"It's a weird concept to try and get used to. I'm surprised you're so okay with it.\""
    k "\"I've had plenty of time to get used to the whole thing. Besides, romance has never been a topic that made me pause.\""
    "Lucky bastard."
    mc 1 c considerate "\"So... uhm... after yesterday I guess we're... What exactly are we?\""
    k 1 c "\"Well, considering I confessed to you and asked you to be my boyfriend, I think the obvious answer would be \"boyfriend\" but maybe that might be a bit too on the nose. Maybe it's a trick question?\""
    mc 1 c sigh "\"You don't need to be a smartass.\""
    k 1 c smile "\"You were basically asking for it. What the hell kind of silly question was that?\""
    "I'm being mocked. Why is it that I always end up being mocked?"
    k 1 c "\"So yes. I assume we are boyfriends now... unless that isn't okay with you after all?\""
    mc 1 c considerate "\"N-no. I have no objections to it, just... trying to wrap my head around it.\""
    k 1 c smile "\"It's not really that complicated.\""
    mc 1 c sigh "\"Says the guy who admits to having had a \"long time\" to get used to it.\""
    k 2 c gentle "\"Heh. Fair enough, I suppose I have a bit of an edge over you when it comes to it.\""
    mc 1 c "\"This might be a stupid question to ask but... erm... what do we tell other people?\""
    k 1 c "\"Are you assuming we tell them anything at all?\""
    mc 1 c wince "\"W-we're not?\""
    k 1 c worried "\"Not unless you want to. I don't think people are entitled to details on our personal lives. I see no reason why we have to tell anyone.\""
    mc 1 c wince "\"But what about our friends? Wouldn't it be wrong to keep it from them?\""
    k 1 c "\"Why would it?\""
    mc 1 c wince "\"W-well...\""
    "Shit, I'm drawing a blank here."
    "I want to come up with reasons why we shouldn't keep quiet about it but I can't really think of any legitimate ones."
    if day20confesskei == True:
        mc 1 c worried "\"What about Saya-chan?\""
        k "\"What about her?\""
        mc 1 c wince "\"Doesn't she know you planned on confessing to someone during the festival? I can't imagine her not coming to you to ask about it.\""
        k 1 c worried "\"That... is a fair point. I guess I was so desperate to get some advice on how to confess that I didn't stop to consider her knowledge on the matter.\""
    mc 1 c talk "\"Are you seriously telling me you wouldn't tell anyone about it? Not even Saya-chan? Isn't she one of your closest friends? Why is it so bad that she and our other friends know?\""
    k 1 c sigh "\"You're misunderstanding me. I didn't say it was {i}bad{/i} if they found out. Just that there is no merit to it.\""
    mc 1 c sigh "\"No \"merit\" to it? What are you, a robot?\""
    k 1 c worried "\"W-what? No. I'm just thinking about things logically.\""
    k 1 c worried "\"What difference does it make if they know or not? At best our friendships won't be affected and everything stays the same. At worst we get discriminated because, hey, not everyone is so accepting.\""
    mc 1 c considerate "\"I don't think we're in danger of that with our friends.\""
    k 1 c "\"But why run the risk at all? That's my point. We have nothing to gain from it and everything to lose. Even if failure is unlikely, it's a terrible business decision.\""
    mc 1 c sigh "\"Relationships aren't a business decision.\""
    k 1 c sigh "\"I know that, that's not what I meant. I was just making a comparison to better exemplify my point.\""
    mc 1 c sigh3 "\"Come on, Kei-kun. You can't treat this sort of thing like it's some kind of cold cut logical decision.\""
    k 1 c worried "\"I don't see why not. But then again, like I already said two times, I have nothing against the idea. I just have nothing for it either.\""
    mc 1 c "\"So if I said I wanted to tell them?\""
    k 1 c "\"Go for it. I'm not stopping you.\""
    "... Somehow that answer still leaves me dissatisfied."
    "Which is weird because I don't even {i}want{/i} to tell them either... at least not now."
    "But the difference between not being willing at the moment and not wanting to at all... somehow irks me."
    k 1 c worried "\"[povFirstName], you have a somewhat scary look on your face. I don't like it.\""
    mc 1 c sigh2 "\"Sorry sorry. I'm just thinking things over.\""
    k "\"Did... I mess up somehow?\""
    "Hmm... I don't know if I'd call it a mess up exactly."
    "It's just a difference in perspective, I suppose. A very annoying one but it's not like it isn't understandable."
    mc 1 c sigh3 "\"No, you're fine. I just wasn't expecting us to disagree so much on something right out of the gate.\""
    k 1 c "\"Well... we are very different people with incredibly different life experiences. You can't expect us to be on the same page on everything.\""
    mc 1 c worried "\"That doesn't really sound like a very ideal situation for a relationship.\""
    k 1 c smile "\"That's what communication is for. If we disagree we talk it out... like we just did. It's not that hard.\""
    mc 1 c worried "\"Maybe for small things but... sometimes talking about things is really hard. Not everyone can bring themselves to do it.\""
    k 1 c "\"Then what is even the point of getting into a relationship if you're not willing to be honest with each other about your feelings?\""
    play sound "music/stab.ogg"
    "Oof!"
    "That... that one digs deep."
    mc 1 c considerate "\"It's not like I disagree with you, I just don't think it's that easy.\""
    k 1 c worried "\"Then it should be. Otherwise you're just creating your own problems.\""
    "Are we just going to disagree about {i}everything{/i} right from the get go?"
    mc 1 c worried "\"Maybe we should talk about something else...\""
    k 1 c "\"Why? If you have something bothering you – and your face makes that readily apparent – then you should talk about it.\""
    mc 1 c sigh2 "\"... I'm just thinking that you and I seem to be disagreeing quite a lot quite soon.\""
    k 1 c worried "\"... I suppose that's true. That's why communication is important.\""
    "Communication isn't a holy grail either."
    "If it were that easy there wouldn't be so many people breaking up every day."
    "Sometimes being open and honest is the hardest thing you can do, even when it's the only thing that can fix your problems."
    mc 1 c worried "\"I guess...\""
    k "\"Are... are you alright? I hope I haven't hurt your feelings or anything.\""
    mc 1 c sigh3 "\"I'm not a doll made of glass. My feelings are fine. I'm mostly just annoyed at the disagreements.\""
    k 1 c smile "\"What? You're not the type that can handle a little adverse opinion?\""
    mc 1 c "\"I never said that.\""
    show k 2 c gentle at fdis
    play sound "music/fabric.ogg"
    "Keisuke laughs, standing up from the bed and staring at me with a smile."
    k 1 c smile "\"Look, we're gonna have plenty of disagreements in the future. That's just the nature of having relationships with other people. We'll just have to work through them.\""
    mc 1 c considerate "\"Yeah, I guess... although that's gonna take a lot of patience.\""
    k "\"Most relationships require patience, not just romantic ones.\""
    mc 1 c smile "\"Heh. I guess that's true. So we're really doing this, huh?\""
    k 1 c "\"Doing what?\""
    mc 1 c "\"Dating. You and me.\""
    k 1 c smile "\"A little late to be asking that don't you think?\""
    mc 1 c considerate "\"Yeah, well, I'm a very awkward person so I need lots of reassurance.\""
    k "\"I don't mind providing that.\""
    play sound "music/chu.ogg"
    "Before I can react, Keisuke presses his lips against my cheek."
    "At this point I've already grown to expect his cheek kisses. Somehow they feel like a Keisuke trademark by now."
    "But..."
    mc 1 c avoidb "\"You know... we're dating now.\""
    k "\"Yes, I'm aware. I seem to recall being the one to ask you out even.\""
    mc 1 c sigh3 "\"Well... shouldn't that mean you'd be kissing me somewhere other than my cheek?\""
    k 2 c gentle "\"Oh. So is that what this weird remark is about? You want me to kiss you on the lips.\""
    mc 1 c avoidb "\"... It's not like it'd be a terrible idea or anything.\""
    k 1 c smile "\"Hmm... I agree.\""
    play sound "music/heartbeat.ogg"
    "I can feel my heart skipping a beat in my chest."
    "Is this it, are we going to kiss for real now?"
    "I stare at him red-faced, waiting for any indication of movement."
    "I don't even realize I am holding my breath until I begin to feel short of it."
    "He leans slightly towards me-"
    k 2 c gentle "\"Nah. You know what, I prefer to keep you on your toes for a little while longer.\""
    mc 1 c shockb "\"W-what?!\""
    k 1 c smile "\"Sorry. I'm not the kind of guy to just give it all up at once. You'll have to work for it.\""
    "Is...{w} {i}is he teasing me{/i}?!"
    "I'm getting teased by a junior? Are you kidding me?!"
    "No no no no no. There is no way I can let him take the lead in our relationship."
    "If I let things start off like this then before I know it it'll be too late to go take it back."
    mc 1 c sigh "\"Fine. Both can play this game. Just you wait. Eventually, when you least expect it, I'm just going to grab you and kiss you!\""
    show k 1 c shockb at fdis
    k "\"!\""
    "Keisuke's eyes immediately go wide. I guess he wasn't waiting for me to fire back."
    "His cheeks begin to burn so red that the color shows through that pristine white fur of his like a canvas."
    "..."
    "Wait...{w} {size=+4}What the hell did I just say to him?!{/size}" with hpunch
    "No no no. Act cool, [povFirstName]. Don't let him know you're embarrassed."
    "If I back down now then he's gonna take the leading role and I absolutely cannot allow myself to be manhandled by a guy younger than me."
    mc 1 c avoidb "\"Y-yeah. You better stay on your toes too.\""
    k "\"Y-yes sir.\""
    "Waaah, don't look at me like that. If you're acting so surprised it just makes me even more conscious about how dumb I sounded just now."
    show k 1 c avoidb at fdis
    "..."
    play sound "music/disappointment.ogg"
    "Ugh, I just made things so awkward that even the usually confident Kei-kun is having trouble dealing with the mood."
    mc 1 c considerate "\"S-so... you wanted to play tennis?\""
    "Lousy attempt at rescuing the mood."
    "Kill me."
    k "\"Yeah... Do you mind if we do?\""
    mc 1 c considerate "\"Of course not... Can it be right now? Please?\""
    k 1 c sigh "\"Y-yeah. Let me just get changed.\""
    show k 1 c at fdis
    "Kei-kun walks up to his wardrobe, opening the door and fishing his tennis bag from inside."
    play sound "music/zipper.ogg"
    "He grabs a shirt and some shorts from inside and before I notice it-"
    mc 1 c shockb "\"Waaaah! D-don't undress while I'm still here. I-I'm gonna go get dressed in the bathroom.\""
    k 1 c worried "\"But-{nw}"
    scene Black with fade
    "I cowardly run away from the situation, too embarrassed at the idea of seeing him get half naked in front of me."
    "I already have a hard time with nudity as it is. Throw in the fact that we're dating now and that's a recipe for disaster inside of my brain."
    stop music2 fadeout 2.5
    play music3 "music/BGM/On My Way.ogg" fadein 5.0
    scene TennisClub
    show k 1 t at fdis, fiveh
    with fade
    "Man, it's been a while since I've properly stepped in a tennis court."
    "Almost a full month? Maybe more?"
    "Well, however long it's been, it feels good to be here again."
    "And the courts in Keisuke's estate are so well kept too."
    "Damn, the ones at our school aren't even half as nice."
    mc 1 t talk "\"Man, you weren't kidding when you said you had tennis courts at your place.\""
    k 1 t smile "\"For good or bad, my father is fond of tennis so he had this built quite a few years ago. Not that I'm complaining.\""
    mc 1 t smile "\"Must be pretty nice getting a private court to practice in, huh?\""
    k 1 t "\"Nah. I don't use it as often as you think. I think the last time was... God, maybe last year?\""
    mc 1 t shock "\"Really? How come?\""
    k 1 t worried "\"Well... First of all, do you see anyone in this house I could practice against?\""
    "Oh... fair point."
    mc 1 t wince "\"None of the butlers know how to play tennis?\""
    k 1 t "\"You've seen how my grandmother reacted to Alex playing videogames with us. And videogames {i}aren't{/i} the thing I'm banking my future on. You really think any servant would be caught dead playing with me?\""
    "Ouch... his family is more messed up than I thought."
    "This whole situation makes me really sad."
    "No one should have to go through this kind of crap."
    k 1 t smile "\"Well, not that it matters. What's important is that we're both here right now and we're ready to practice, right?\""
    mc 1 t smile "\"Right.\""
    mc 1 t talk "\"How do we decide who takes the first serve?\""
    k 1 t smile "\"Well... given that it's my house, my court and I was the one who called you here, maybe I get to decide?\""
    mc 1 t considerate "\"O-oh... flexing on me already, are you?\""
    k 2 t gentle "\"Every now and again it isn't so bad.\""
    k 1 t smile "\"I'll take the first serve then.\""
    mc 1 t talk "\"Do we both call in and out and whatnot?\""
    k 1 t "\"Yeah. Neither of us would cheat so I don't see the issue with it.\""
    mc 1 t "\"Alright. Give me your worst.\""
    k 1 t doom "\"You're gonna regret asking for it.\""
    "Wha- Scary! What was with that scary look on his face just now?!"
    stop music3 fadeout 2.5
    play music2 "music/BGM/Straight.ogg" fadein 5.0
    show k 1 t at fdis
    "We both take our positions in the court."
    "Keisuke bounces the ball on the ground a few times and gets ready to serve."
    "From all the times we've practiced together, I know that he takes a while to get going and also has a really bad temper when he's losing."
    "So if I want to steal the initiative, I should break his first serve."
    "He's going to start scrambling to catch up and that'll give me the perfect chance to take the whole game from him."
    "No plan could be more perfect!"
    play sound "music/tennishit.ogg"
    "Keisuke tosses the b-"
    play sound "music/ballfence.ogg"
    mc 1 t shock "\"... Huh?\""
    "The ball has already been served."
    "It has hit the fence behind us and fallen to the floor even."
    mc 1 t shock "\"A quick serve? Here?\""
    show k 1 t serious at fdis
    "Keisuke smiles deviously."
    "Since when did he learn to do that?!"
    "Quick serves aren't easy to pull off. You have to almost nearly hit the ball out of your hand just after tossing it."
    "It's not something you can become proficient with overnight."
    "And it was nearly just as fast as his regular serves."
    k "\"15-Love.\""
    "I shake my head a few times, trying to put myself back together."
    "Okay, just switch gears."
    "A quick serve is very much a surprise tactic. It's not like it's in any way superior to a regular serve."
    "If anything, once the surprise element is gone, it is downright a worse option."
    "Which means there's no risk of it coming twice on a row."
    "Kei-kun gets into position, moving to toss again-"
    mc 1 t judge "\"!\""
    "Crap, I flinched."
    play sound "music/tennishit.ogg"
    "Even though I kept telling myself he wouldn't do it twice in a row, my body still flinched as soon as he began his toss."
    "I nearly jumped forward to return a serve that didn't came."
    "Instead, he shot a regular topspin serve at me."
    play sound "music/tennishit.ogg"
    "My reaction was delayed by a few seconds and I could barely reach the ball before it double bounced."
    play sound "music/tennishit.ogg"
    "Kei-kun rushes the net, finishing the ball at a wide angle in a way that I just can't reach it."
    k 1 t smile "\"30-Love.\""
    "Hah... he's got me."
    "Even if in my mind I tell myself that a quick serve won't come, now that he's added this new variable right at the start of the game before I've had the chance to properly switch into gear, my body is confused."
    "It'll take me a while to get back to normal even if I was doing really well before this."
    "I guess this is what I get for being hasty."
    "I put too much stock into wanting to break his serve right off the bat and because of that when I lost the first point, my spirit wavered a little."
    "I take a few deep breaths, trying to stabilize myself."
    "Mistakes happen. No point dwelling in them. Forget what came before."
    "Focus on the next point..."
    k 1 t serious "\"...\""
    "When he sees the look on my face, Keisuke's own face scrunches up."
    "I guess he's being cautious of me? I have to admit, I'm a little bit glad."
    "Don't overthink things, just go with what feels natural."
    play sound "music/tennishit.ogg"
    "Keisuke hits his serve, this time a shallow slice aiming for my left hand."
    "The match has barely started and he's already varying his shots to an annoying degree. First a wide flat quick serve, then a wide topspin and now a slice aiming for the center."
    "It's too many variables to keep track of so early in the game."
    "Annoying..."
    play sound "music/tennishit.ogg"
    "However, my body is moving much better now."
    "I reach the ball and hit it towards the open side of the court."
    "Same as always, just put as much power into the ball as possible."
    "That ought to do the trick."
    play sound "music/tennishit.ogg"
    "Keisuke doesn't seem at all fazed by it."
    "It looks to me like his form has improved a lot."
    "Has he been keeping up practice this past month while the school courts were closed?"
    "But he said no one ever practices with him here at his house so..."
    play sound "music/tennishit.ogg"
    "Well, it doesn't really matter. If I'm able to pick up his serve, it'll eventually become a battle of groundstrokes."
    "Kei-kun will try to make it hard for me to hit strong balls by confusing me with his myriad of different shots."
    "Meanwhile I'll try to keep him from using said shots by hammering with one strong ball after the other."
    "Our fundamental strategies haven't changed once... and have no reason to change now."
    "We've just continued to pursue further refinement in our own particular styles."
    play sound "music/tennishit.ogg"
    "This time it's much harder to get through Keisuke's defense."
    "Usually when I end up in a rally like this, I force the other player on the defensive and make them have to try their best to keep me from clinching the point then and there."
    "But despite me doing my best on offense, Kei-kun himself isn't backing down from the attack either."
    "He's always been a very aggressive player in his own way but I'm stunned at how well he's managing to press the attack."
    "If things keep going like this, I might be the one finding myself in a disadvantage."
    "Which means..."
    play sound "music/tennishit.ogg"
    "I try hitting a drop shot."
    "Skillful tennis isn't exactly my thing but that doesn't mean I can't do it."
    "Throwing an unexpected shot every now and again isn't exactly the hardest thing to do, and the resulting effect is that my opponent is thrown off their usual pace."
    "Or at least that's how it should be."
    show k 1 t doom at fdis
    "Keisuke doesn't hesitate for even a second."
    "He immediately dashes for the ball as if he were waiting for it to go there the whole time."
    play sound "music/tennishit.ogg"
    mc 1 t shock "\"Wha-\""
    "He hits a flat shot at such a ridiculously wide angle that I have no chance of ever reaching the ball."
    "I don't even bother running after it because it is so impossible it borders on hilarious."
    mc 1 t shock "\"How did-\""
    k 1 t smile "\"40-Love.\""
    stop music2 fadeout 2.5
    scene TennisClub with fade
    "My whole body is dripping with sweat."
    "I didn't expect such a thing to happen but... Keisuke is pushing me farther than he ever did before."
    if day5 != "Shoichi":
        "Even that one time we played at the rented court when Shoichi arbited the game for us... I had a hard time with that one but that was because my head was out of the game."
        "Here though... I'm just getting pressured from how well he's doing."
    "I've managed to defend my own serve quite well but I haven't managed to break his either."
    "I might be the one coming closest to breaking a serve but at the end of the day, so long as he's managed to defend his own serve, we're still a stalemate."
    "We've even got ourselves into a tie-break..."
    show k 1 t worried at fdis, fiveh
    "I suppose if there is one positive, it's that he seems to be running much more ragged than I am."
    "I guess this is when I thank my better athletic disposition... even if stamina isn't my forte."
    "But after the finals of the prefectural tournament against that akita guy, I've at least had the good sense to focus on improving myself in that area so I suppose I am doing better than I was a month ago."
    "Keisuke on the other hand... I'm sure the difference in our physique is rearing its ugly head for him now."
    "He might be very in shape but my body is just naturally built better than his. That's not a difference he can easily make up for."
    "Because of that, he's panting quite obviously and struggling to even stand."
    "I can't blame him, every single one of his games went into a 40-all stalemate and had the two of us constantly trading advantage for over ten minutes until he managed to keep the serve."
    "This match has already gone for well over two hours by now. This is definitely an anomaly for a one-set match."
    "His legs must be feeling it now more than anything."
    "I kinda feel sorry for him..."
    mc 1 t worried "\"Hey... are you going to be okay? Maybe we should stop.\""
    k 1 t wince "\"Don't... don't be ridiculous. This is my chance to finally take a serve from you.\""
    "... I'm afraid he's thinking with his pride instead of with his brain."
    "That... really bothers me."
    mc 1 t worried "\"Okay...\""
    "I need to end this soon but Keisuke keeps stubbornly clinging to his service when it's his turn to serve."
    "The tiebreak score is already at 14-14..."
    "Well... my turn to serve now."
    play music2 "music/BGM/Power Switch.ogg" fadein 5.0
    "If I want to finish this as quickly as possible then I should probably go for a flat."
    "But I also know that's what he would expect."
    "During this whole match, it became painfully obvious that he'd gotten a very good read of my style."
    "His reactions kept getting faster and faster and he managed to anticipate what I would do."
    "If that's the case then I should do something I've never done before."
    "And what better time than when his legs are barely managing to keep him up?"
    show k 1 t serious at fdis
    "I toss the ball and get myself in positing to serve."
    "I have to make it look like it'll be a strong one."
    "Then... when I would normally swing to hit the ball, I stand still."
    play sound "music/tennishit.ogg"
    "Keisuke seems to catch on a second too late as I lower my racket and hit the ball from below instead."
    show k 1 t shock at fdis
    "An underarm serve."
    "It's especially effective for a player like me who hammers rocket after rocket when he serves."
    "This entire match, I've mostly only hit strong shots at Keisuke."
    "And even when I varied from that pattern, even my most basic slice is still faster than many guys' serves."
    "So he's come to expect my shots to both have a lot of punch and to hit close to the line."
    "With him standing so far back to deal with my serve and being so prepared to run after a fast ball, his body freezes at the sight of that pathetically slow ball barely flying over the net."
    play sound "music/ballbouncing.ogg"
    "The ball bounces and rolls away while the hare stands motionless on his corner."
    mc 1 t "\"15-14. Match point.\""
    "Since neither of us has yielded any points during our serve at the tiebreak, that means he is the next one to serve."
    "But regardless, hopefully the psychological impact of that shot will give me even the slightest edge so I can close this out."
    "While I don't particularly want to stop playing, having missed being on a court far too much this past month, I really don't want him to overexert himself."
    k 1 t avoid "\"...\""
    "He seems to be mulling something over to himself as he gets in a position to serve."
    "At the very least, he doesn't seem as laser focused as he was before."
    "Which is good because he can be pretty scary when he's focused..."
    play sound "music/tennishit.ogg"
    "Keisuke serves... nothing different from the usual so far."
    "My hope that he was rattled enough by the last point to make a mistake getting slightly weaker now."
    play sound "music/tennishit.ogg"
    "But I continue to press an attack, not wanting him to have even a little bit of breathing room."
    "I must make things as difficult as possible for him."
    play sound "music/tennishit.ogg"
    "Eventually it starts to become obvious..."
    "Keisuke is having a hard time keeping up. Not because of any kind of mental imbalance or anything of the sorts."
    "He's exhausted."
    "I guess once I broke his concentration for even just a second, the exhaustion caught up to him full force."
    play sound "music/tennishit.ogg"
    "His shots are getting weaker by the second and he's running slower."
    "Soon enough I see an opportunity and-"
    play sound "music/ballfence.ogg"
    stop music2 fadeout 2.5
    play music "music/breeze.ogg" fadein 5.0
    "The ball I've hit zooms past the net, bouncing on the court and going straight for the fence behind it."
    "Keisuke couldn't reach it."
    k 1 t sigh "\"Hah... hah... damn it...\""
    play sound "music/fall.ogg"
    show k 1 t sigh at fdis, shake1, fall
    "He promptly falls to the floor."
    mc 1 t shock "\"Wha- Keisuke!\""
    "I run over to him in an attempt to help him get up."
    "However, he completely ignores my presence, lying on his back and panting heavily instead."
    "Man, he's much more tired than I thought he'd be."
    "It's a little bit scary even..."
    mc 1 t worried "\"Are you alright?\""
    k 1 t sigh "\"Yeah... only thing hurt is my pride...\""
    "He makes no move to get up from the ground and I eventually give up on waiting."
    play sound "music/fabric.ogg"
    "Instead, I sit right next to him, hugging my knees and watching him closely."
    k 1 t worried "\"You don't have to stay on the ground just because of me.\""
    mc 1 t "\"I know.\""
    k 1 t worried "\"... Thanks.\""
    "I watch Keisuke's chest moving up and down as he struggles for air."
    "He gasps almost desperately for it and it almost looks like he's suffocating at times."
    "But little by little his breathing stabilizes."
    "For some reason, it's relaxing to just sit around like this."
    "Besides, there's a nice breeze coming from the nearby woods so it feels nice too."
    k 1 t "\"Man, I was so close this time...\""
    mc 1 t smile "\"You really were. I was surprised to see it.\""
    "Funny, I'm used to seeing him get really mad whenever he loses."
    "In comparison, he seems to calm and relaxed now."
    "Part of me can't help but find it weird."
    k 1 t worried "\"Aren't you uncomfortable sitting around on the ground?\""
    mc 1 t happy "\"Aren't you uncomfortable lying on it?\""
    k 1 t eyesc "\"Now that you mention it... yeah, I am, but I still prefer this over standing right now.\""
    mc 1 t considerate "\"Are you that tired?\""
    k 1 t worried "\"I think I'd look like a newborn fawn learning to stand and I really prefer to save myself that embarrassment.\""
    mc 1 t smile "\"Heh. I suppose that makes sense. Did you at least enjoy the match?\""
    k 1 t smile "\"Yes. It was very instructive. I feel like I've gotten one step closer to matching you.\""
    play sound "music/disappointment.ogg"
    "That's not what I meant. I was asking if you had fun, you weirdo."
    mc 1 t "\"You're pretty calm right now. I'm surprised.\""
    k 1 t "\"How so?\""
    mc 1 t considerate "\"Well... let's just say my run-ins with your post-match temper haven't always been the best.\""
    k 1 t worried "\"Oh... sorry about that.\""
    mc 1 t smile "\"You can be pretty angry when it comes to tennis. Even made me question whether you truly enjoyed it sometimes.\""
    k 1 t "\"Hmm...\""
    mc 1 t talk "\"What's with that unenthusiastic \"hmm\"?\""
    k 1 t worried "\"I do enjoy tennis. It helps me relax.\""
    "... Relax?"
    "Most of the times when I've seen you angry where during or after playing tennis."
    "And now you're telling me that was you feeling {i}relaxed{/i}?"
    "Jesus, how high-strung are you?"
    k 1 t "\"What about you, [povFirstName]? How come you enjoy tennis so much?\""
    mc 1 t talk "\"Me? Why do you ask?\""
    k 1 t sigh "\"You asked me a question first. It's only fair that I get to ask one back.\""
    play sound "music/disappointment.ogg"
    "We're not playing a question g- Oh never mind."
    mc 1 t "\"I think I might have mentioned this before... or did I never say this in front of you? My dad taught me about tennis shortly before he died.\""
    k 1 t worried "\"Really? I don't think you ever told me that.\""
    mc 1 t smile "\"Yeah. It turns out he had played it competitively while he was still in high school but stopped once he went to college.\""
    mc 1 t happy "\"The first time I've ever seen his eyes really glint were when he talked about it.\""
    mc 1 t smile "\"He really loved tennis and I enjoyed learning about it from him. I started playing because of him.\""
    k 1 t smile "\"It must have been nice.\""
    mc 1 t considerate "\"Yeah. In a sense, I'm really lucky. I got to find something I really loved from someone who was so dear to me.\""
    mc 1 t wry "\"Sometimes I wonder what he'd think of me if he knew I was about to go pro.\""
    k 1 t "\"Hmm... that's hard to say.\""
    mc 1 t talk "\"Really? How so.\""
    k 1 t "\"Well, parents aren't always the most logical. Even if they love that you have passion for something they might sometimes still oppose it because they think it'd be too risky or too hard.\""
    k 1 t worried "\"He might have pushed you to go to college instead of choosing tennis because there'd be less risk and a higher chance for a stable future.\""
    mc 1 t considerate "\"Yeah, I see your point. Unfortunately I remember very little about him nowadays. I can't even really say what kind of personality he had so it's hard to guess how he'd respond.\""
    k 1 t smile "\"I mean... regardless of his opinions on what you should do in your future, I'm sure he'd still have been proud of you.\""
    hide k 1 t smile
    mc 1 t smile "\"... Yeah. I like to think so too.\""
    show k 1 t smile at fdis, fiveh with dissolve
    "Kei-kun sits up from the ground, carefully dusting his back and pushing himself up."
    "I stand alongside him, trying to offer him a helping hand but he declines it with a gesture."
    k 1 t smile "\"I guess this sort of makes us birds of a feather, since my father is the reason I got into tennis too.\""
    if day5 == "keisuke":
        mc 1 t talk "\"Yeah. I remember you mentioning that to me once. I can't believe he expected you to just quit cold turkey once you graduated.\""
        k 1 t sigh "\"Right? I can't believe how stupid he was.\""
    else:
        mc 1 t talk "\"Wait, really? I didn't know that!\""
        k 1 t smile "\"Oh, did I not tell you? My father forced me to learn tennis when I was a kid because he enjoyed it and he thought it'd look good if his son became a well known player.\""
        k 1 t worried "\"Made me practice until I'd nearly throw up, for hours and hours on end. And the worst part is he did all of this with an expectation that I'd quit once I reached college.\""
        k 1 t sigh "\"Why can't I have a normal, healthy home life?\""
        mc 1 t considerate "\"... Sorry.\""
        k 1 t "\"But yeah. One way or another, I guess we were both influenced into playing tennis because of our fathers.\""
    k 1 t smile "\"Although I suppose the difference is your dad wanted to actually share something he loved with you while mine just wanted to be able to brag about me to his peers.\""
    mc 1 t considerate "\"Y-yeah...\""
    k 1 t "\"Either way, none of that really matters now. There are more important things to focus on.\""
    mc 1 t talk "\"Yeah? Like what?\""
    k 1 t sigh "\"To start of? A bath would be nice. I'm sticky and sweaty and gross and I hate it.\""
    mc 1 t happy "\"Pffft. I thought you were going to say something actually sagely for once.\""
    k 1 t worried "\"Why are you looking down on me like that? Being clean is really important too.\""
    "I'm not saying it isn't but... you really should work on your delivery."
    "You sounded way too somber for someone about to ask for a shower."
    stop music fadeout 2.5
    play music2 "music/BGM/Summer Day.ogg" fadein 5.0
    scene KeiHouseN
    show k 1 c smile at fdis, fiveh
    with fade
    "Kei-kun and I sit by the porch on his house, absentmindedly gazing at the leaves and trees rustling in the distance."
    "I'm surprised how much time passed by while we spent the entire day idly chatting about nothing in particular."
    "It's weird. When I look back, I feel like we really didn't do anything at all, and yet we were capable of spending a full day feeling entertained."
    "He showed me a little bit more of his guitar playing, we played games, chatted, ate together."
    "In fact... I'm shocked how well everything went."
    "No awkward interruptions, no angry family members. None of the things I've come to expect the last few times I've come to visit."
    mc 1 c talk "\"Hey, Kei-kun-{nw}"
    k 1 c smile "\"Keisuke.\""
    mc 1 c wince "\"Oh, right.\""
    "He's corrected me a few times on the way I call him."
    "For some reason he is oddly insistent that I don't call him Kei-kun anymore."
    "It's weird to break out of a habit I've kept up for so long."
    mc 1 c "\"Anyway, what I was going to say was: what happened to your family? I'm surprised neither your grandmother or your father showed up at all today.\""
    k 1 c calm "\"Ah, that? They are out of town at the moment. Father is having a meeting with board partners in the company headquarters located in Tokyo. He should be back by Sunday.\""
    k 1 c "\"Grandmother is merely spending time with her equally old friends in another one of our estates near Osaka.\""
    mc 1 c talk "\"Oh. That explains the calm.\""
    k 1 c calm "\"Indeed. The times when they are both travelling are somewhat rare, especially since grandmother spends most of her time at home nowadays. Regardless, they are my favorite times to spend at home.\""
    mc 1 c smile "\"Must be nice not having to deal with drama.\""
    k 1 c "\"Make no mistake, the drama is never really gone. I still have to deal with the spying eyes of their servants. I just choose to ignore most of that.\""
    mc 1 c wince "\"Oh... that's a little bit less nice.\""
    k 1 c smile "\"Don't worry. I get by.\""
    "I guess that's not that bad."
    "Jeez, every time I hear about Keisuke's family dynamics, I feel like they've been lifted straight from a soap opera of some kind."
    k 1 c smile "\"Thank you for spending the day with me. It was nice to have a lazy day to just spend at home. I'm happy I was able to share it with you.\""
    mc 1 c happyb "\"Awww. It was my pleasure.\""
    mc 1 c smile "\"I was just going to sit around the house all day today so it was nice to have a reason to get off the couch and do stuff.\""
    k 2 c gentle "\"Heh. I guess this was mutually beneficial then.\""
    "I nod, looking up at the clouds in the sky."
    play music "music/night.ogg"
    scene SkyN with fade
    "Keisuke follows my gaze, staring at them intently and with a lot of curiosity."
    k 1 c worried "\"Can I ask you a question?\""
    mc 1 c "\"Shoot.\""
    k 1 c "\"Why do you stare at the sky so much? I noticed that you tend to completely zone out and look at the sky fairly often.\""
    mc 1 c smile "\"It's relaxing.\""
    k 1 c smile "\"I see.\""
    "He gigles to himself, as if my answered amused him greatly."
    mc 1 c "\"Why do you ask? I thought you also liked watching the sky.\""
    k 1 c smile "\"I do. I think I even ranted to you about how you can't really see the stars from here anymore at some point.\""
    mc 1 c talk "\"Oh yeah. I think I remember that.\""
    k 1 c calm "\"But if you ask a thousand people their reasons for doing something, you'll get a thousand different responses.\""
    k 1 c smile "\"Sure, many of them might be similar, but every has slightly different thoughts and motivations relating to certain things.\""
    k 2 c gentle "\"Two different people might say watching the sky relaxes them, but maybe it's because one likes to see the clouds and the other the stars. Or maybe they might have completely different reasons to be relaxed.\""
    k 1 c smile "\"In summary, people are unique. It's good to get perspective on why they do the things they do, even if you yourself also share that activity.\""
    mc 1 c talk "\"That's... surprisingly thoughtful. Is this why you asked me earlier why I got into tennis?\""
    "Keisuke nods, still smiling."
    play sound "music/fabric.ogg"
    "I feel something soft and warm brushing against the back of my hand."
    "One quick glance down and I see that Keisuke has placed his hand on top of mine, squeezing me softly, a red smile on his face."
    "Seeing this, I can't help but blush a little, smiling myself."
    "I don't bother to move my hand away, instead just deciding to enjoy the feeling."
    k 1 c smile "\"I want to understand you more, you know.\""
    mc 1 c "\"What do you mean?\""
    k 2 c gentle "\"Exactly what I said. I want to understand the way you think. I want to get to know more about you. I want to feel closer to you.\""
    k 1 c smile "\"I think it's pretty natural given you're the one I've fallen for and all.\""
    play sound "music/heartbeat.ogg"
    "Oh man, that's kind of an embarrassing thing to hear."
    "But... it also makes me happy."
    mc 1 c smile "\"If all goes well... we'll have plenty of time to get to know each other more.\""
    k 2 c gentleb "\"Yes. I certainly hope so.\""
    "Keisuke squeezes my hand a little tighter and in that moment, I truly feel at peace and content."
    "I feel warmth."
    stop music fadeout 2.5
    stop music2 fadeout 2.5
    $ date = None
    jump Day22_Keisuke
