label Day22_Keisuke:
    window hide
    scene June3 with fade
    play sound "music/windchimes.ogg"
    show blossoms movie
    $ renpy.pause(5.5)
    scene Station
    play sound "music/cicada01.ogg"
    window show
    $ date = "day22"
    "It's early in the morning and I'm already standing around in the middle of the shopping district waiting for a certain someone."
    "Yesterday before I headed home, Keisuke asked me to come to town with him so we could hang out."
    "I also assume he'll be bringing Alex with him because... well, Alex will force his way here anyway."
    "Although considering Keisuke's track record of slipping away with Alex, even that isn't a given..."
    "I suppose I could have asked about it yesterday but it sorta slipped my mind."
    "Besides, I don't even know what he's got planned anyway."
    "Or even if he has some kind of plan."
    "From the corner of my eye, I see a familiar gigantic figure cutting its way through the 10AM crowd."
    show k 1 c smile at fdis, three
    show al 1 u at fdis, seven
    with dissolve
    "Following shortly behind him is Keisuke, who is so dwarfed by the tall wolf that I don't even notice him until he's standing right in front of me."
    k 1 c "\"Good morning, [povFirstName].\""
    mc 1 c smile "\"Morning to you two. I see you came as well, Alex.\""
    al "\"It is my job after all.\""
    "So I guess this wasn't meant to be a date, then."
    mc 1 c talk "\"Did he finally manage to catch you or did you just decide to let him come with?\""
    k 1 c considerate "\"I'll avoid making a fuss when he comes with me. At least for the foreseable future. I don't need him to get into even more trouble with my family.\""
    al "\"Thankfully. It has only taken him nine years to see reason.\""
    k 1 c worried "\"Hey, come on, at least I'm trying.\""
    "The corner of Alex's mouth quirks up and I can immediately tell the wolf has been having fun teasing Keisuke with this."
    mc 1 c smile "\"How kind of you, Lord Keisuke, to understand the plight of even those below you. Truly a noble soul.\""
    k 1 c sigh "\"Keep that up and I'm turning right around and going home.\""
    mc 1 c fsmile "\"S-sorry, I'll stop now.\""
    "Jeez, why does Alex get to make fun of him and I don't?"
    mc 1 c talk "\"So what's the plan?\""
    k 1 c smile "\"I wanted to check out the shopping mall. I hear it's something people do to pass time. I don't think I've ever been to one with friends.\""
    mc 1 c smile "\"The shopping mall, huh?\""
    "How awfully and deliciously cliché of him."
    "Not that I mind. Just gives me more ammo to tease him with."
    mc 1 c smile "\"You're in luck then. The nearest mall has a lot of fun things we can do.\""
    k 2 c gentle "\"Really? Damn, I'm looking forward to it.\""
    play music2 "music/BGM/Hanging Out.ogg" fadein 5.0
    scene Mall
    show k 1 c smile at fdis, three
    show al 1 u at fdis, seven
    with fade
    "Since he has no idea where the mall even is, I have to guide Keisuke on the way there."
    "The first thing I feel as soon as we step inside is a wave of airconditioned air right to the face."
    "Usually I am all for air conditioning, but the air inside is so dry and... air conditioned that it nearly makes me choke as soon as we step in."
    k 1 c worried "\"Whoa. It's kinda chilly in here.\""
    mc 1 c considerate "\"That's most malls.\""
    al "\"You should have brought a jacket like I told you to.\""
    k 1 c sigh "\"It's thirty two degrees. It's too hot for a jacket.\""
    al "\"Yes, but you never know when there will be a sudden temperature drop or maybe rain.\""
    k 1 c avoid "\"The weather report said it would be hot all day today with no rain.\""
    al "\"The weather report isn't always right. It's better to be safe than sorry.\""
    k 1 c sigh "\"What are you, my mother?\""
    "Alex raises an eyebrow, which is borderline the most expressive he is on a general basis."
    "It's kinda weird how I've been getting better at picking up on his humor just from these slight tells."
    "Like how now, for instance, he is annoyed."
    k 1 c "\"Sooo what do we do? Do we just walk around?\""
    mc 1 c talk "\"You wanted to kill time at a mall? Well, that's basically how you kill time at a mall.\""
    k 1 c smile "\"That's very interesting.\""
    "Eh. It gets very old very fast but I can see why he'd think so."
    mc 1 c smile "\"Most people just walk around checking the stores. Most of them are clothing stores, electronics and there is also the obligatory food court.\""
    k "\"Those all sound like they'd be fun to browse.\""
    mc 1 c talk "\"They also have an arcade and an annexed building with an indoors ice skating rink.\""
    k 1 c shock "\"Really? That's really cool.\""
    mc 1 c smile "\"You want to try the arcade?\""
    k 1 c smile "\"Nah. The arcade I'm pretty \"meh\" on. I do want to go check out the ice skating ring.\""
    mc 1 c "\"You do? I didn't think that would be your thing. Have you ever gone ice skating before?\""
    k 1 c calm "\"Nope!\""
    "He declares it with so much happiness and glee you could mistake him for a proud veteran."
    "Somehow, I think this will end horribly if we do go there."
    k 1 c smile "\"What about you, [povFirstName]? Have you skated before?\""
    mc 1 c talk "\"Yeah. Been a couple years but Aki used to drag me around to ice skate every now and again. Kids love it for some reason.\""
    k 1 c calm "\"Hehehe. I can't wait to try it.\""
    play sound "music/disappointment.ogg"
    "Oh oh. It is pretty much certain that we're going to go there isn't it?"
    al "\"Perhaps it would be wise to avoid ice skating.\""
    k 1 c "\"Why?\""
    al "\"I've heard horror stories of people falling down and having their fingers chopped off by the blades another skaters' shoes.\""
    "No, that kind of thing doesn't really happen often. It's why they give you security gloves and everything..."
    show k 1 c scared at fdis, shake1
    k 1 c scared "\"W-whoa, really?\""
    play sound "music/disappointment.ogg"
    "DON'T BELIEVE HIM SO EASILY!"
    mc 1 c sigh3 "\"While it's true that skates are plenty sharp, they give you a ton of protective gear specifically because of it.\""
    k 1 c worried "\"But accidents can still happen, right?\""
    mc 1 c "\"Well... sure. There is always some risk. Just like there is risk of your car crashing, your plane going down, you getting run over. Etc.\""
    k "\"... I don't like this game. Please stop mentioning that sort of thing.\""
    mc 1 c sigh2 "\"Don't tell me you're the type to get paranoid over this kind of thing?\""
    k 1 c wince "\"I'd rather not hear about it...\""
    "..."
    mc 1 c judge "\"Let's go check out some stores.\""
    k 1 c shock "\"Woah woah woah. [povFirstName], wait for me! [povFirstName]!\""
    scene Mall
    show k 1 c smile at fdis, three
    show al 1 u at fdis, seven
    with fade
    "After the world's shortest chase sequence with Keisuke running after me on the corridors, we begin browsing the stores."
    "Most of them are clothes stores, with the occasional ice cream or bubble tea stands sprinkled around the corridors."
    "There's one store that specializes in snow globes of all things. I don't even know how there can be enough people buying snow globes year round to justify a specialized store."
    k 1 c "\"Woah, this one looks really neat.\""
    "Right now Keisuke is looking at shirts."
    "I could kind of already guess what his taste in shirts was considering the type of thing I've seen him wear but..."
    "He's only looking at plain button-down shirts. Every single one of them is basically the same as the shirt he's wearing right now except in a different color."
    "Could you be more basic?"
    k 1 c smile "\"Oh hey, Alex, what do you think of this one? I think it'd look good on you.\""
    "Alex raises an eyebrow staring at yet another button-down shirt and I swear I can hear him scoffing under his breath."
    al "\"Too formal for me.\""
    k 1 c "\"Is that so? I find this kind of thing pretty casual.\""
    "That statement is already plenty scary on its own..."
    mc 1 c smile "\"What about this one?\""
    "I pick up a shirt that seems to be about in Keisuke's size and present it to him."
    k 1 c nervous "\"A... a tank top? Somehow I don't think that would be very much my style.\""
    mc 1 c talk "\"Why not? They're super comfy and everything. Plus, they look good, don't they?\""
    k 1 c worried "\"Sure, they look very flattering... on you. I don't think I have the body type to pull it off.\""
    mc 1 c happy "\"I'm sure you'd look fine!\""
    k 1 c sigh "\"Hard pass.\""
    mc 1 c worried "\"Awww.\""
    "He continued rifling through the clothing options, never really settling on anything."
    "I guess he was more interested in seeing what was available than actually buying something."
    k 1 c "\"I'm surprised at how big of a selection they have here.\""
    mc 1 c smile "\"It is a pretty large store so they're bound to have more stuff.\""
    al "\"Plus, it is a very popular national chain store so they have access to more products.\""
    k 1 c smile "\"Wow. I didn't know that. That's very interesting.\""
    mc 1 c considerate "\"Not really. It's just a store, it's no big deal.\""
    k 1 c smile "\"Do all their other stores have big selections like these.\""
    al "\"No. I think this is their biggest location in town so it probably has the best selecion.\""
    k 2 c annoyed "\"Ah, yes, that makes sense.\""
    "I get the feeling they didn't even hear me..."
    mc 1 c talk "\"By the way, it's almost lunch time. What do you guys want to do.\""
    k 1 c "\"Oh. Is it that late already?\""
    al "\"Remember, you have to be back to the estate by 2PM.\""
    k 1 c sigh "\"Yes yes, I'm well aware.\""
    mc 1 c talk "\"Is there something you need to do at 2PM.\""
    k 1 c "\"Nothing big, really. I scheduled with a private tennis coach for the day and that'll be at 2.\""
    mc 1 c talk "\"Really? I thought you said you didn't have private coaches.\""
    k 1 c avoid "\"I didn't, but after losing yesterday I started getting impatient and decided to call one to see how it'd go.\""
    "Ah, so I'm the reason he's hiring a coach."
    "... Wait, how did he even find one from one day to the next?"
    mc 1 c sigh "\"How did you have time to even search for one?\""
    k 1 c smile "\"I asked Alex to look into that for me when we went to shower after practice yesterday.\""
    mc 1 c sigh "\"... Part of me can't help but feel that you were being sneaky when we weren't together.\""
    k 1 c worried "\"W-what? No, I would never-\""
    mc 1 c smile "\"Relax, I'm just joking.\""
    k 1 c wince "\"That's not a funny joke.\""
    al "\"You make it too easy.\""
    k 1 c annoyed "\"That's none of your business.\""
    show k 1 c avoidb at fdis
    play sound "music/tap.ogg"
    "Alex smiles, placing a big head on the top of Keisuke's head and gently ruffling his fur."
    k "\"W-what are you doing?\""
    al "\"Giving you a head pat. Shouldn't I?\""
    k "\"... Do whatever you want.\""
    "Alex looks at me and flashes me a smile."
    "I think he's opening up a little more around me."
    "Or at least that's the feeling I get... that he's not holding back as much just because I'm around."
    play sound "music/phonebeep.ogg"
    k 1 c "\"It's 11:32... I will preferably like to be home by 1:30 so I have time to prepare myself for practice.\""
    mc 1 c talk "\"That means we don't have that much time... but we also won't take two hours to get through lunch, especially in a mall.\""
    k "\"Yeah, I was thinking the same.\""
    k 1 c smile "\"You know what? Maybe we could try the ice skating thing.\""
    mc 1 c suggestive "\"You sure? What about the risk of losing fingers.\""
    k 1 c worried "\"Wha- I... I'll be extra careful.\""
    "Keisuke shudders a little at the mention of missing limbs."
    "He really is taking this far more seriously than he has to, it's kinda cute."
    al "\"We should probably be quick if that is the case. I can't imagine us having more than forty five minutes before we need to go to the food court.\""
    k 1 c "\"True.\""
    stop music2 fadeout 2.5
    play music3 "music/BGM/The People Here.ogg" fadein 5.0
    scene SkateRink
    show k 1 c worried at fdis, three
    show al 1 u at fdis, seven
    with fade
    "It takes a five minute walk for us to get to the rink, which is already definitely going to cut into our time before we have to leave for lunch."
    "There are quite a lot of people around and skating, even for this early in the day."
    k "\"Wow, this place is pretty packed.\""
    mc 1 c "\"It's Saturday so there are already a lot more people free because of it. Add together the fact that this is a chilly place to hide in during summer heat and you've got a recipe for a crowd.\""
    k "\"I guess that's a fair point.\""
    mc 1 c "\"I don't see any lines forming so hopefully we won't have to wait to get in the rink.\""
    k 1 c "\"How do we... erm, how does this work?\""
    mc 1 c smile "\"Just sign up at the counter and get some skates.\""
    k 1 c "\"That's pretty easy.\""
    "What else were you expecting?"
    al "\"If you don't mind, I'll just watch from outside the ice.\""
    k 1 c worried "\"How come?\""
    "Alex stares at the ice for a few seconds, frowning."
    al "\"I don't think I have the dexterity required for this sort of activity.\""
    mc 1 c smile "\"Translation: he doesn't want to embarrass himself in front of you by falling a bunch.\""
    "His frown intensifies, creating a crease between his eyebrows that is admittedly somewhat humorous to look at."
    k 1 c "\"Okay. We won't be long so wait for us, Alex.\""
    show al 1 u at offscreenleft
    show k 1 c at fdis, fiveh
    with move
    "The wolf nods, walking towards a nearby sitting area."
    "I guess he feels comfortable enough with me that he doesn't feel the need to shadow us constantly for Keisuke's safety?"
    "That'd be nice if it is the case."
    "At the reception area, we pay for tickets and rent some skating gear."
    "Nothing too outrageous. Just the skates themselves and some safety gloves."
    "There's a clerk by the door to the rink itself that checks to make sure we're wearing the equipment correctly and after that we manage to walk inside hassle free."
    "I go inside first, skating a bit away from the entrance and turning around to watch Keisuke."
    show k 1 c worried at fdis
    "As horrible as this might make me, I definitely wanna watch him take his first steps in the ice."
    "Just managing to stay standing your first time in the ice is already deceptively hard and a part of me really wants to watch him lose his balance and fall."
    k 1 c shock "\"W-whoa!\""
    "As soon as he steps foot in the ice, he begins to lose his balance and has to lean on the outer rails to avoid falling."
    "His legs are completely freaking out and sliding everything."
    "It somehow reminds me of Irish dancing for some reason."
    k "\"Whoa whoa whoa whoa, how do you do this?!\""
    "Even the clerk that helped us in is trying to hold back from laughing."
    mc 1 c laugh "\"You just keep your balance.\""
    k 1 c wince "\"How?!\""
    mc 1 c smile "\"You just do it.\""
    k 1 c sigh "\"...\""
    "Keisuke definitely doesn't seem amused by my explanation."
    "It's not my fault, I'm not an instructor, I don't know how to properly explain it."
    k 1 c worried "\"Oh God, I can't even take my hands off of the rail.\""
    mc 1 c smile "\"At least you've managed to get your feet mostly grounded.\""
    k 1 c sigh "\"I can't even stand!\""
    "I laugh, grabbing one of his arms and trying to pull him along with me."
    k 1 c shock "\"What are you doing?\""
    mc 1 c laugh "\"Just come with me.\""
    k 1 c shock "\"N-no, I'm gonna fall.\""
    mc 1 c considerate "\"Everybody falls on their asses at first. It's how you learn.\""
    show k 1 c worried at fdis
    "I gesture to the people skating along with us."
    "Sure enough, there are people falling everywhere."
    "And there are also many who, just like Keisuke, are walking alongside the edges holding onto the rails so they can stay up."
    k 1 c worried "\"This proves nothing...\""
    "Keisuke however is channeling his internal mule, being incredibly stubborn about it."
    mc 1 c sigh3 "\"For crying out loud, just try to skate and get it over with. If you fall you fall.\""
    mc 1 c annoyed "\"Or do you just intend to cling to the edge for thirty minutes?\""
    k 1 c worried "\"... Can you at least catch me if I fall?\""
    mc 1 c "\"That'd be a bad idea. You might take me along with you and that would increase the chances of one of us getting hurt.\""
    k 1 c sigh "\"You suck.\""
    show k 1 c worried at fdis
    "His whole body is still shaking a little but he reluctantly lets go of the edge."
    "I grab his arm and try to slowly skate backwards while holding onto him."
    "I avoid going fast so he has an easier time keeping his balance."
    "The hare is shaking like a leaf the entire time, looking more at the floor than at me."
    "It's a good thing I've got some experience skating otherwise we would both be falling on our asses."
    k 1 c wince "\"Aaaaaah, h-hold onto me!\""
    "I try letting go of him for just a second so he can skate on his own but he immediately freaks out and-"
    show k 1 c shock at fdis
    play sound "music/fall.ogg"
    mc 1 c laugh "\"Pfft...\""
    "I try my hardest to hold back laughter but a very loud snort still manages to come out."
    "Keisuke panics and immediately loses control of himself, falling face first on the ground."
    k 1 c wince "\"Ow ow ow. The ice is hard...\""
    mc 1 c smile "\"Of course it's hard. It's ice!\""
    "I shouldn't have to state the obvious here."
    k 1 c worried "\"T-this was a bad idea. Can we leave?\""
    mc 1 c smile "\"Nope. We're not leaving until you've managed to skate on your own.\""
    k 1 c shock "\"Wha-\""
    mc 1 c happy "\"This was your idea. I'm not letting you run away now. I'll make you see it to the end.\""
    k 1 c worried "\"Oh no...\""
    "I try helping him up onto his feet and he nearly pulls me down along with him."
    "I didn't think he could be {i}this{/i} clumsy but it is definitely refreshing to see him failing so hard at something as basic as standing."
    mc 1 c smile "\"There you go.\""
    "His legs shake like two leaves blowing against the wind and he grabs my arm with a grip so strong it might cut off circulation."
    "I have painful flashbacks to the times we went out with Jun into a crowd."
    mc 1 c considerate "\"Very good. Now let's go slow at first, okay?\""
    k 1 c wince "\"A-alright. J-just be gentle with me, this is my first time.\""
    "SNRK!"
    "Oh God, I was barely able to contain a laugh just now."
    "I'm not going to say anything because I think his head just might explode if he realizes what he just said."
    "I lead Keisuke along the edges, letting him get a few for how to glide on the ice and all that."
    show k 1 c worried at fdis
    "Slowly, he starts building up some confidence and getting better at basic standing."
    "He's not doing badly, at least not when I'm holding him."
    "But part of me wants to let him go and watch him fall again..."
    "I might just be a terrible person after all."
    mc 1 c talk "\"You think you'll be okay if I let you go?\""
    k 1 c nervous "\"W-w-w-what? P-p-p-please don't let go of me!\""
    mc 1 c considerate "\"Alright alright, I won't. Calm down. There's no need to lose your mind.\""
    "Ow ow ow ow ow, there's also no need to grip me so hard!"
    mc 1 c wince "\"Come on, you have to try and skate on your own for at least a little bit.\""
    k 1 c wince "\"No! I-I'll fall!\""
    mc 1 c considerate "\"Falling is part of the experience. How many times do you think I fell when I was first learning?\""
    "Hell, I still fall sometimes when I try to go faster."
    "And I'll be honest, it's hard to keep my balance when there's someone grabbing and shaking me..."
    k 1 c worried "\"I still don't like it.\""
    mc 1 c smile "\"I'll help you up if you fall but you've got to at least try to do it on your own.\""
    k "\"... Okay.\""
    "I slowly let go of his arm until he is standing all on his own."
    "His body swerves violently to the sides at first but he manages to somehow stay on his feet."
    k 1 c shock "\"I-I'm doing it! I'm standing!\""
    mc 1 c happy "\"Good job! Now once you've gotten more used to it, try going forward.\""
    k 1 c wince "\"A-alright...\""
    scene SkateRink with fade
    show sometime with dissolve
    $ renpy.pause (1.0)
    hide sometime with dissolve
    "Keisuke diligently follows my instructions."
    "He still falls quite a few times and I can't keep myself from laughing at those since they are just too funny, but he at least doesn't get {i}too{/i} discouraged."
    "By the time Alex comes by to tell us we need to have lunch, he's at least capable of going forwards on its own."
    "Pretty small steps but, hey, progress is progress."
    "At least it was still fun trying to teach him, even if I fail miserably as a teacher (a fact that he definitely did not let escape me as he kept remarking it every chance he got)."
    "I do feel a bit uncertain as I don't know if HE had fun..."
    "But by the end of the day when we've bid our farewells, he was still smiling..."
    "I definitely feel like my time together with him was short today but I was still able to enjoy his company... and Alex's."
    "Going home, I make sure to shoot him a message thanking him for the invite."
    "For some reason, I can't stop smiling as I type to him."
    "I hope Monday comes soon..."
    $ date = None
    stop music2 fadeout 2.5
    stop music3 fadeout 2.5
    stop music fadeout 2.5
    jump Day23_Keisuke
