label Day24_Shoichi:
    window hide
    scene June9 with fade
    play sound "music/windchimes.ogg"
    show blossoms movie
    $ renpy.pause(5.5)
    play music2 "music/BGM/Spring Classroom.ogg" fadein 5.0
    scene SClass
    show shima 1 u smile
    with fade
    window show
    $ date = "day24"
    play sound "music/schoolbell.ogg"
    "The school bell finally rings, marking the end of the last day of midterms."
    "God, this whole week sucked. Exam weeks always suck."
    "It's not like the tests were particularly hard but man are they ever annoying."
    "... And Jun spent pretty much the entire week in a catatonic state."
    "I'm really afraid for his grades just watching his body language."
    "... Jun-kun, keep fighting."
    shima "\"Everyone please pass your papers along. Hopefully we won't have anyone failing right from the get-go, huh?\""
    "Most students have such defeated looks on their faces, meanwhile the stag doesn't seem to care at all."
    "Sometimes I think that he might secretly enjoy watching our misery."
    "I maintain that teachers as a whole are all evil."
    shima "\"Results of your tests should be out by the end of next week. Anyone who scored below 50 will have to take remedial lessons on their failing subjects after class. Hopefully it doesn't come to it for anyone in this classroom.\""
    "I doubt anyone is even listening at this point."
    "He gives the same spiel every year. People have learned to tune it out by this point."
    shima "\"Other than that, club activities will restart on Monday. You are all dismissed for today.\""
    play sound "music/slidingdoor.ogg"
    show shima 1 u smile at offscreenright with moveoridis
    "He walks out of the room, carrying all of our exams with them."
    "Everyone's hope and dreams..."
    "As soon as he leaves, the class lets out a collective sigh of relief."
    "I hang back for a couple minutes, letting my brain rest for a bit before I try to think any more complex thoughts."
    "... And also because I talk to some of my classmates so we can compare answers."
    "From what I can gather, there seems to barely be any consensus on the answers for today's tests."
    "I don't know whetehr I think that's a good or a bad thing."
    show j 1 u fluster at fdis, five
    j 1 u fluster "\"I think I just lost a few years from my life...\""
    "As I'm heading back to my desk to pick up my bag, I see Jun slumped on his, looking completely defeated."
    mc 1 u talk "\"You okay there, big guy?\""
    j "\"I've barely gotten any sleep this past week...\""
    mc 1 u considerate "\"Come on, it can't have been that bad.\""
    j "\"The last time I slept was on Wednesday.\""
    "I take it back, that is really bad."
    mc 1 u considerate "\"You should head home and try to relax.\""
    j 1 u wince "\"Y-yeah. I kept telling myself I'd rehearse as soon as tests ended but I don't feel like I have the energy for that...\""
    play sound "music/tap.ogg"
    "I give him a few comforting pats on the back, feeling sorry for the poor tiger."
    mc 1 u considerate "\"Hang in there, I'm sure you've done your best.\""
    j 1 u sigh "\"I really need to get better with studying...\""
    mc 1 u "\"Maybe look into getting a tutor?\""
    j 1 u considerate "\"Y-yeah...\""
    j 1 u wince "\"What are you going to be doing with the rest of your day, [povFirstName]-san?\""
    mc 1 u "\"Hmm... I'm unsure. I wanted to spend time with Shoichi but we haven't talked much this year since he's so busy.\""
    mc 1 u sigh "\"He basically keeps his phone turned off whenever he's studying so no one will disturb him.\""
    j 1 u avoid "\"K-keeping his phone turned off? {size=-4}That's a good idea, why didn't I think of that?{/size}\""
    mc 1 u "\"Man, you really need a good lesson on self-discipline if you want to have any chance of actually graduating.\""
    j 1 u wince "\"You're telling me that like I don't already know...\""
    mc 1 u talk "\"Do you have any idea how well you did on the tests?\""
    j 1 u avoid "\"Probably not well at all... I could barely even understand some of the questions.\""
    mc 1 u considerate "\"That... doesn't exactly make me hopeful.\""
    j 1 u considerate "\"Is there any chance they'll give me a do-over if I pretend like I was sick and on bed rest this week.\""
    mc 1 u sigh "\"... You literally already came to class and took the tests. They'll know it's a lie.\""
    j 1 u think "\"Oh... right. That's a good point.\""
    "My God, his brain must really be fried right now."
    "Jun might be a little oblivious but that was just downright stupid."
    mc 1 u considerate "\"Well... I'm sorry if this sounds like I'm ditching you, but...\""
    mc 1 u smile "\"I'm gonna try checking up on Shoichi, hopefully he'll have some free time now.\""
    j 1 u considerate "\"Nah, you're not ditching me. I really need to head home and rest for a bit... Good luck with Shoichi-san.\""
    mc 1 u smile "\"Thanks. Do be careful when crossing the streets. Don't need you being run over because you weren't paying attention.\""
    j 1 u avoid "\"Please don't say something so morbid with a smile on your face...\""
    stop music2 fadeout 2.5
    play music3 "music/BGM/Summer Day.ogg" fadein 5.0
    scene SCorridor with fade
    "The hallways are filled with students heading home."
    "Usually a lot of the student body sticks around after class."
    "Either staying in their classrooms to chat or maybe going to their clubs."
    "But this? This is a mass exodus."
    "Not that I blame them. Who would want to stay here after a whole week of tests?"
    "Most of the people I see are dragging their feet, looking absolutely exhausted."
    "Midterms are no joke, they're a student's worst nightmare."
    "I make my way to Shoichi's classroom."
    "Hopefully he won't have bailed already."
    show k 1 u at fdis, seven
    show sa 1 u at fdis, two
    with dissolve
    sa "\"Oh, [povFirstName]-kun.\""
    "On my way over there, I somehow run into Keisuke and Saya walking together and chatting."
    "Since her class is between mine and Shoichi's and I'm going the opposite direction, I guess it's not too weird that I'd find her here, but..."
    "What is Keisuke doing on this floor?"
    mc 1 u talk "\"Hey there. Kei-kun, I'm surprised too see you of all people here.\""
    k 1 u worried "\"What? Why?\""
    mc 1 u smile "\"I know you're smart but I didn't expect I'd find you taking the senior's midterm.\""
    k 2 u gentle "\"Ah, that's what you mean.\""
    k 1 u smile "\"Obviously I wasn't. I just came up to your floor to try and talk to Urata.\""
    sa 1 u smile "\"Yeah, and I bumped into him on my way out and we spent a few minutes chatting. Happy coincidence, huh?\""
    mc 1 u considerate "\"And then you bumped into me on the way back. A threeway coincidence.\""
    show k 1 u at fdis
    sa 1 u argue "\"Eugh, don't call it that.\""
    mc 1 u happy "\"Alright alright, fine.\""
    mc 1 u smile "\"Either way, how did you guys do with your tests?\""
    sa 1 u considerate "\"I did my best. Hopefully that'll be enough.\""
    mc 1 u smile "\"You've always been really good with your academics so I doubt you'll go badly.\""
    sa 1 u happy "\"Hehe, thanks. That helps me cheer up a bit.\""
    k 1 u calm "\"I'm pretty sure I'll do well. I've been reviewing the subjects quite often for the past month and I have a very good grasp on it.\""
    mc 1 u talk "\"Wow. Good to see at least someone is calm about it.\""
    show k 1 u at fdis
    sa 1 u "\"Jun-kun is probably freaking out, huh?\""
    mc 1 u "\"You have no idea. If you squinted and turned my head {i}just{/i} right I could barely make out the smoke coming out of his head.\""
    k 1 u smile "\"Hopefully that doesn't mean he's crashed and burned.\""
    mc 1 u considerate "\"... I wouldn't hold my breath if you I were you.\""
    k 1 u worried "\"That bad?\""
    mc 1 u sigh "\"Yesterday I tried asking him about his exponential map, since one of the questions in the Math test was about exponential functions... he thought I was talking about a game called \"Exponential\" that had a map in it.\""
    show sa 1 u wry at fdis
    k 1 u sigh "\"You're kidding.\""
    mc 1 u sigh3 "\"I wish I was. Then I could at least laugh it off since it sounds absolutely ridiculous.\""
    sa "\"That's pretty bad, yeah. I'm really worried for Jun-kun now.\""
    k "\"Academically or in general?\""
    sa 1 u considerate "\"Both.\""
    mc 1 u considerate "\"Yeah... that's understandable.\""
    "I love the dude but he seems to have no control over his own life most of the time..."
    sa 1 u smile "\"How about you? It probably was super easy for you like always, huh?\""
    mc 1 u considerate "\"I wouldn't say that.\""
    k 1 u "\"Did you even study at all?\""
    mc 1 u talk "\"Hmm... I did review the subject a little bit the days before but not much other than that.\""
    sa 1 u sigh "\"I hate how you can barely study and still do well.\""
    mc 1 u considerate "\"You wouldn't be the first to tell me that.\""
    k 1 u worried "\"I do two to four hours of review and study every day when I get home from school. It's so unfair that you can get by with barely anthing.\""
    "I can't help that I'm good at retaining information..."
    sa 1 u talk "\"Where are you going anyway? The exit is the other way.\""
    mc 1 u "\"I was planning on meeting up with Shoichi.\""
    if sayaquestion == "Truth":
        show sa 1 u laugh at fdis, jumping
        show k 1 u worried at fdis
        "Saya laughs and squeals, making Kei-kun look at her funny."
        "But otherwise, she remains completely silent."
        k "\"That was... weird.\""
        mc 1 u "\"You think so? I can't tell anymore.\""
        sa 1 u think "\"Hey, Kei-kun, didn't you say you had someone waiting to pick you up at the gate?\""
        k 1 u worried "\"O-oh, right. I had almost forgotten.\""
        k 1 u "\"If you two will excuse me, I need to go.\""
        mc 1 u talk "\"Alright. Catch you later.\""
        sa 1 u happy "\"Bye bye.\""
        show k 1 u at fdis, offscreenright with moveoridis
        show sa 1 u smile at fdis, five with move
        "As soon as he walks away, Saya starts smiling from ear to ear."
        "Staring at her smile like this is really starting to creep me out too."
        mc 1 u worried "\"Uhm... what are you doing?\""
        sa 1 u happy "\"Hehe. Checking up on the boyfriend are we?! That's so cute!\""
        mc 1 u sigh "\"Yes. Please, say it louder. I think there's a deaf child in America that didn't hear you the first time.\""
        sa 1 u bored "\"What? I wasn't even that loud.\""
        "I look around me for any signs of people having overheard us."
        "No heads turning our way so I guess that's a good sign..."
        sa "\"You worry too much.\""
        mc 1 u sigh3 "\"And you're way too carefree about this stuff.\""
        sa 1 u smile "\"Nah, I'm just the right amount of carefree.\""
        mc 1 u sigh3 "\"Whatever you say.\""
        mc 1 u "\"Is this why you \"casually\" reminded Kei-kun he needed to leave? So you could talk freely about it?\""
        sa 1 u happy "\"Yes! Aren't I sneaky?\""
        "Mhm, a veritable modern day ninja."
        sa 1 u smile "\"Anyway, I wish I could hang out with you guys but I'm sure you two mustn't have had time to yourself this week so I'll give you two some space.\""
        sa 1 u think "\"Well... And I also really need to pick up a shift at the diner today. I didn't do any over the week and I'm a bit strapped for cash.\""
        sa 1 u laugh "\"See you later, [povFirstName]-kun. Go get him!\""
        show sa 1 u laugh at offscreenright with moveoridis
        "..."
        "I think I liked it better when she didn't know about us."
    else:
        sa 1 u considerate "\"Oh? Worried about your {i}friend{/i}, are we?\""
        mc 1 u avoid "\"T-that's right.\""
        k 1 u worried "\"Saya-san, why did you sound so annoying when you said that?\""
        sa 1 u bored "\"...\""
        "..."
        "Ugh, this really sucks."
        "Shoichi already told me Saya already pretty much knows, I don't have to pretend like I'm oblivious."
        "And he was even so stupid understanding telling me that I can decide when I'm ready to tell others even though he was clearly sad that I didn't tell her the truth when she asked..."
        "Ugh, stupid considerate husky, now I'm second-guessing myself."
        "M-maybe this would be an opportunity to tell the both of them?"
        mc 1 u worried "\"W-well, I was meaning to tell you guys this at some point but... the truth is we-\""
        show sa 1 u shock at fdis, jumping
        show k 1 u at fdis
        sa "\"Y-yes?\""
        mc 1 u worried "\"...\""
        mc 1 u considerate "\"W-we were talking about his plans earlier and he told me he was gonna ask his dad to stay on the volleyball team a little longer. Crazy huh?\""
        sa 1 u bored "\"O-oh. Yeah... crazy.\""
        k 1 u worried "\"W-wow. From the stories I heard of his father, that must take a lot of courage.\""
        "..."
        play sound "music/disappointment.ogg"
        "Why is this so freaking hard?!" with hpunch
        "It's like... lying the first time just made it even more awkward to tell her."
        "Come on, [povFirstName], you can do this. Just tell her!"
        mc 1 u wince "\"W-well, there was one other t-\""
        sa 1 u complain "\"Sorry, [povFirstName]-kun, I'm kinda in a hurry and I can't stick around for too long. I scheduled a shift for right after class and I'll be late if I stick around. We'll talk later okay?\""
        mc 1 u shock "\"Wha- But-\""
        sa 1 u considerate "\"See ya. You two, Kei-kun!\""
        show k 1 u shock at fdis
        show sa 1 u considerate at offscreenright with moveoridis
        show k 1 u shock at fdis, five with move
        "..."
        play sound "music/disappointment.ogg"
        "What the hell? That was the perfect chance to tell her too!"
        k 1 u wince "\"Why is Saya-san acting so strangely?\""
        mc 1 u considerate "\"She's strange as a general rule but... yeah, that was strange even for her.\""
        "... I think tell him why she is being weird."
        "And even if I could, it'd be unfair since that would mean I basically waited for her to leave before I told someone."
        k 1 u "\"Well, I need to be on my way too anyway. I have someone waiting to pick me up after class. If you want to meet Urata then you should hurry, I don't know how long he'll be around.\""
        mc 1 u talk "\"Gotcha. See you later, Kei-kun.\""
        k 1 u smile "\"Bye bye.\""
    scene SClass with fade
    play sound "music/slidingdoor.ogg"
    "Let's see... hopefully Shoichi will still be here..."
    "Wow, there are... quite a few students still here."
    "Are they... studying?"
    ukn "\"Oh, [povFirstName]-kun, what are you doing here?\""
    show i 1 u smile at fdis, seven
    show ka 1 u smile at fdis, three
    with dissolve
    "A voice calls my attention and on the other side of the classroom I see a familiar figure."
    mc 1 u talk "\"Minazuki? You're in this class?\""
    i "\"Me? Pfft, of course not, don't be ridiculous. I'm just visiting a friend who is.\""
    "She points at the raven sitting on the desk she's sitting on."
    "I don't think I've ever seen him before."
    "No, wait..."
    mc 1 u talk "\"Wait, isn't that the bassist of the band that performed during the festival?\""
    i "\"Yup. Kagaho-kun is the band's leader.\""
    ka "\"That is not true.\""
    i "\"Shh, just roll with it. It gives you more respect.\""
    mc 1 u "\"Well, I guess it makes sense you two would be friends since you're both in the band. I was already shocked you of all people would be in a band though.\""
    "The calico laughs."
    i "\"Hopefully you enjoyed the performance. From what I heard, our manager is your friend too.\""
    mc 1 u smile "\"Oh yeah, Kei-kun mentioned he'd joined your band as the manager.\""
    i "\"He's the one who composed the song I sang too. Sadly, I had asked him to fill in for me as a singer the day of the show but he refused.\""
    mc 1 u talk "\"Wait, what? Why would you ask him that?\""
    ka "\"She had lost her voice the day ofI  and instead of calling it off she just waltzed into a doctor's office and made them fill her with meds so she could still sing.\""
    mc 1 u shock "\"What?!\""
    i "\"It's not my fault, we couldn't just cancel the performance and Kei-chan didn't want to sing.\""
    "The raven sighs."
    ka "\"If you say so. I still disapprove. Either way, did you come here for some reason in particular, [povLastName]?\""
    mc 1 u talk "\"Ah, right. Yeah, I was looking for Shoichi but I guess he isn't here.\""
    "I mean, even if I had failed to spot him, he'd have come to me once he saw me talking to people in his class."
    i "\"Urata-kun? I didn't see him when I got here so my guess is he'd already left.\""
    ka "\"Yes. Maybe you should try the student council room? It's just a hunch but I think he might have gone there. He didn't seem like he was heading home.\""
    mc 1 u smile "\"Alright, cool. Thanks for the help... erm...\""
    ka "\"Kagaho.\""
    mc 1 u considerate "\"Right. Thanks for the help, Kagaho-san. You two have a good day.\""
    i "\"Yeah. Maybe come watch us rehearse later, [povFirstName]-kun. I'm sure that would shock and fluster Kei-chan and I'd love to see that.\""
    mc 1 u smile "\"You're evil. I like it.\""
    "She laughs again."
    ka "\"Just throwing this wild idea out there... maybe don't torment our juniors?\""
    i "\"Hmm... Nah, tormenting him is more fun.\""
    mc 1 u talk "\"See you guys later.\""
    scene SCorridor with fade
    show minutes with fade
    $ renpy.pause(1.0)
    hide minutes with fade
    "Wow, the secondary building is completely deserted."
    "I guess it makes sense since clubs are suspended until Monday but still."
    "Let's see... what floor was the student council room on again?"
    "I've only been there a couple times and I needed to ask for directions every time..."
    "Isn't there anyone around here I could ask?"
    "I'll try checking the next f-"
    show h 1 u at fdis, five with dissolve
    "Just as I'm heading to the stairs, I see a familiar white wolf going down."
    mc 1 u talk "\"Haruki? What are you doing here?\""
    "He raises an eyebrow as soon as he sees me."
    h "\"You suck at greetings.\""
    mc 1 u "\"And you just plain suck. Anyway, I asked a question?\""
    h "\"I was meeting up with someone.\""
    mc 1 u talk "\"Was it with Shoichi?\""
    h "\"What? No. I already get enough of him on volleyball practice, why would I want to see him outside of that?\""
    mc 1 u smile "\"Is this one of those mysterious other friends you said you have?\""
    h "\"Yes. And why are you even talking to me in the first place?\""
    mc 1 u talk "\"It's impolite to pass by someone you know without greeting them.\""
    "The wolf rolls his eyes."
    h "\"Who gives a crap about that?\""
    mc 1 u smile "\"Hey, if you didn't want to talk to me you could have just ignored me.\""
    h "\"... I never said I didn't want to.\""
    "This guy's a real tsundere isn't he?"
    ukn "\"Yo, Haruki, wait for me you dipshit!\""
    "I hear a voice shouting from the other floor alongside hurried steps."
    show h 1 u at fdis, sevenh with move
    show kiga 1 u at fdis, twoh with moveiledis
    "A sabercat comes running down the stairs, panting."
    kiga2 "\"Jeez man, I asked you to wait for me.\""
    h "\"Great. Thanks to you this dork caught up to me.\""
    "He looks at me, while he speaks he also gestures to his... friend?"
    "The tiger finally notices my presence and turns to look at me after catching his breath."
    kiga2 1 u smile "\"Oh, would you look at that, it's [povLastName]-san.\""
    mc 1 u considerate "\"Please don't call me that. [povLastName]-san is my mother.\""
    h 1 u smile "\"I just call him fa-\""
    mc 1 u sigh "\"Let's not.\""
    show h 1 u at fdis
    "The wolf shrugs."
    mc 1 u "\"And anyway... have we met?\""
    kiga2 1 u smile2 "\"Nope, but pretty much everyone in this school knows who you are.\""
    mc 1 u considerate "\"I suppose you've got a good point.\""
    kiga2 1 u "\"Either way, what's a big shot like you doing talking to this loser?\""
    "He points at the wolf with his thumb."
    "Haruki's eyes narrow in a scowl."
    h "\"Fuck you.\""
    kiga2 1 u smile2 "\"You wish, buddy.\""
    "Haruki eyes the sabercat with a downright murderous look."
    "Please don't tell me I'm going to have to break a fight up right now..."
    kiga 1 u smile2 "\"I'm Kiga, by the way. Kiga Kasama. I'm this guy's only friend. Or at least I thought I was.\""
    h "\"You're not my only friend. I have lots of friends.\""
    kiga 1 u laugh "\"Lots of friends? You're cool and all but don't flatter yourself.\""
    h "\"I'm going to punch you.\""
    kiga 1 u smile2 "\"Sure you are.\""
    mc 1 u considerate "\"If I were you I'd stop giving him such a hard time. I wouldn't put it past him...\""
    kiga 1 u laugh "\"Nah, it's alright. Little wolfy here is tame.\""
    "Oh dear lord, this guy has a death wish."
    "Haruki's neck fur is bristled, his tail is lashing and he's baring his fangs."
    "For the love of all that is sacred, shut up!"
    kiga 1 u "\"Anyway, not important. Haru, why didn't you tell me you knew... should I just call you [povFirstName]-san?\""
    mc 1 u talk "\"Yes, that's fine.\""
    "Also, \"Haru\"?"
    h "\"Fuck off, I don't have to tell you every detail of my life. Also, this guy is just an annoyance that pops up every now and again. Hardly worth a mention.\""
    mc 1 u sigh "\"That was a little uncalled for.\""
    h "\"Fuck you.\""
    mc 1 u judge "\"...\""
    h "\"Don't just give me the silent treatment either.\""
    kiga 1 u smile "\"I see you've found his weakness already. Keep ignoring him. Drives him crazy.\""
    h "\"I've ditched you once. I can do it again.\""
    kiga "\"Point taken.\""
    h "\"And {i}you{/i}.\""
    "He turns to me with fury in his eyes."
    "Oh oh, he's not gonna turn his annoyance on me is he?"
    mc 1 u worried "\"I swear I'm innocent, I'm not the one giving you a hard time.\""
    h "\"Weren't you on your way to see the dog?\""
    mc 1 u shock "\"Wha- I didn't tell you that.\""
    h "\"Why else would you be here?\""
    mc 1 u sigh "\"Hey, when I asked you the same thing you took offense to it.\""
    kiga 1 u sigh "\"He takes offense to everything. Don't take it personally.\""
    h "\"...\""
    "Wow, Haruki is just silently fuming while glaring at this guy."
    "Is... is this the secret code to dealing with Haruki?"
    "Where was this knowledge all along?"
    "Is there a manual hidden somewhere?"
    kiga 1 u "\"I still wish you'd told me you knew [povFirstName]-san. I've been wanting to talk to him for a while now.\""
    mc 1 u shock "\"You have?\""
    "Haruki rolls his eyes."
    kiga 1 u smile "\"Yeah. You're a guy that thrives on attention, right? How would you feel about standing center stage?\""
    mc 1 u wince "\"W-what?\""
    h "\"Here comes the sales pitch.\""
    kiga 1 u smile2 "\"You know, I think you'd be perfect for the drama club. You've got this confident aura around you, you're handsome. The girls would love you.\""
    mc 1 u sigh "\"... What?\""
    h "\"That's the exact same speech you gave me five minutes ago... it's why I ditched you in the first place.\""
    kiga 1 u smile2 "\"Hey, it's true. You both fit the criteria. What do you say, [povFirstName]-san?\""
    mc 1 u sigh "\"I say... I'm confused.\""
    kiga 1 u smile "\"Come on, just say yes. Our club is in need of more guys, we're almost all women in there.\""
    mc 1 u sigh3 "\"Sorry dude, I already have my hands full. Not joining a new club.\""
    kiga 1 u wry "\"Oh well, worth a shot.\""
    h "\"You've already tried to recruit me over a dozen times. It's not just {i}a{/i} shot.\""
    kiga 1 u smile2 "\"I'm persistent. It's a good trait to have.\""
    h "\"It's annoying.\""
    kiga 1 u smile2 "\"Say, is Haru right? Are you on your way to meet the student council president?\""
    mc 1 u wince "\"Y-yeah, why?\""
    kiga "\"Hmm... I wonder if {i}he'd{/i} be willing to join the drama club.\""
    "Haruki and I both groan at the same time."
    h "\"You've already asked him that once.\""
    kiga 1 u "\"For the sake of full disclosure, I've asked him more than once. You just weren't around for the other times.\""
    mc 1 u "\"You know Shoichi?\""
    kiga 1 u smile2 "\"Sure. I'm in the student council too so I see him almost every day.\""
    mc 1 u shock "\"Oh. How do you even have time to tend to both clubs at the same time?\""
    kiga 1 u "\"I'm pretty sure you know how much Pres is juggling, do you really find two clubs all that impressive?\""
    mc 1 u considerate "\"W-well, it's not like it's a competition.\""
    kiga 1 u smile2 "\"Heh. If you say so, pup.\""
    "... Pup?!"
    h "\"Come on, we were leaving remember?\""
    kiga 1 u worried "\"Hmm...\""
    "The wolf sighs, glaring at Kiga."
    h "\"What is it this time?\""
    kiga 1 u sigh "\"Oh? Nothing in particular. It's just that now I got to thinking about it, Pres shouldn't have any reason to be in the student council room.\""
    mc 1 u shock "\"He doesn't? But I already checked his classroom and they said they thought he came here.\""
    kiga 1 u worried "\"... I really hope he's not doing what I think he is.\""
    mc 1 u curious "\"What you think he is? What are you talking about?\""
    kiga "\"He has the terrible habit of hoarding work. We caught him a few times keeping quiet about issues that needed to be fixed so he could do it when no one was looking.\""
    kiga "\"I {i}thought{/i} that after we basically staked an intervention and forced him to take a day off he'd stopped doing that.\""
    mc 1 u sigh "\"Wait, I think I remember that. Wasn't that back in April?\""
    "There's no way I could forget that sort of thing. It was the day he came to pick me up before class."
    "Shoichi having free time that early in the morning and not being at school is a damn miracle already."
    kiga "\"Yup. I was the one who spearheaded that motion cause he'd been overworking himself really hard and that's not healthy. Of course, someone else had to go and screw up some papers so we had to whisk him back.\""
    mc 1 u "\"Doesn't sound like that worked out all that well for you.\""
    kiga "\"You're telling me...\""
    h "\"That's great. Really {i}lovely story{/i}. Can we go now?\""
    kiga "\"Would you mind hanging back for a bit? I kinda wanna go with [povFirstName]-san and see if he's really there right now.\""
    h "\"Are you freaking kidding me? I'm going to ditch you.\""
    kiga 1 u smile2 "\"Is that so? Fine by me, go ahead and leave.\""
    h "\"...\""
    "Haruki glances at the exit for a few seconds but otherwise stays rooted to his spot."
    h "\"I hate you.\""
    kiga 1 u laugh "\"I knew it.\""
    kiga 1 u smile2 "\"Anyway, if you'd do the honors, [povFirstName]-san?\""
    mc 1 u shock "\"U-uhm, sure.\""
    "The sabercat makes a gesture towards the stairs as if asking me to go first and I follow through with it."
    scene SCRoom
    show kiga 1 u at fdis, twoh
    show h 1 u at fdis, sevenh
    with fade
    play sound "music/door.ogg"
    "The three of us quickly make our way to the student council room."
    "As soon as we try to open the door we find it unlocked it."
    kiga "\"Yup, someone's inside. This door should have been locked otherwise.\""
    "We quickly go inside and-"
    show kiga 1 u at fdis, oneh
    show h 1 u at fdis, nineh
    with move
    show s 1 u shock at fdis, five
    show sguniform at fdis, five
    with dissolve
    s "\"Wha- [povFirstName]?\""
    "Quickly find Shoichi sitting at the table, a stack of papers next to him."
    kiga "\"Bingo.\""
    h 1 u smile "\"Pffft. What the hell are those glasses?\""
    "Haruki starts laughing as soon as his eyes fall on Shoichi's eyewear."
    s 1 u sigh "\"What on Earth is going on here? Kasama-kun and... Haruki? Okay, Kasama I can understand but what on Earth are you doing here, Haruki?\""
    h "\"Beats me. These two idiots are the ones who dragged me here.\""
    kiga "\"We ran into [povFirstName]-san when we were leaving the building. He told us he came here looking for you. I thought it was weird you'd be here since you're the one who said we didn't need to show up today cause all the work was taken care of.\""
    s 1 u wince "\"T-that's... I can explain. I just-\""
    h 1 u "\" Take those glasses off before you start talking, dumbass. You look like a dork.\""
    mc 1 u sigh "\"Haruki, shut up!\""
    h "\"You shut up. Don't tell me what to do, fag.\""
    "Nice. Real classy move."
    show s 1 u sigh at fdis
    hide sguniform at fdis
    s "\"There. You happy now?\""
    h "\"I'm not {i}unhappy{/i}.\""
    kiga 1 u annoyed "\"Pres, you lied to us.\""
    s 1 u wince "\"W-well, \"lie\" is a really strong word...\""
    kiga sassy "\"Oh? What would you call it, then?\""
    s 1 u worried "\"Errr... Okay, you got me there.\""
    kiga 1 u "\"How much?\""
    s 1 u shock "\"How much what?\""
    kiga 1 u annoyed "\"How much work needs to be done?\""
    s 1 u considerate "\"I-it's not much. It's something I can handle in twenty minutes. Thirty at most.\""
    kiga 1 u "\"Great, then we can do it in fifteen if I help.\""
    s 1 u shock "\"Wha- you don't have to!\""
    kiga "\"I don't care, I'm doing it anyway. Besides, I plan on running for council president next year and I'm gonna have a hard time if I have no idea what needs to be done.\""
    s 1 u wince "\"R-right...\""
    h "\"You're kidding, right? We had one foot out the door already and now you wanna stay here for fifteen more minutes? We were supposed to go to the arcade.\""
    kiga 1 u smile "\"Hey, if you want us to leave faster you can always pitch in and help.\""
    h "\"Are you crazy? Absolutely not.\""
    kiga 1 u "\"Well, at least I tried. [povFirstName]-san?\""
    mc 1 u "\"Sure, I don't mind helping.\""
    s 1 u shock "\"[povPetName]?! No way!\""
    mc 1 u talk "\"What? I'm already here anyway. Might as well.\""
    s 1 u sigh "\"You guys are killing me here. I didn't want to bother anyone with this.\""
    kiga 1 u "\"I'm a member. This is literally my job.\""
    s 1 u worried "\"... Fine.\""
    "The three of us take seats at the table, with Kiga quickly snatching away the pile of papers from Shoichi and dividing it among us."
    "Haruki of course wants no part in it. Instead he just leans back on his chair and puts his feet on the table."
    s 1 u sigh "\"Please don't do t-\""
    h "\"Bite me.\""
    "Shoichi's attempt at parley is quickly rebuffed."
    kiga "\"Don't even bother, he doesn't listen to anyone.\""
    h "\"You're goddamn right.\""
    play sound "music/disappointment.ogg"
    "Somehow, Haruki is a lot harder to take seriously when he's around the sabercat."
    "... He goes from acting like a delinquent to looking like a petulant child."
    "Scary difference."
    kiga 1 u smile "\"Oh, is this it? This stuff is really easy to solve.\""
    s "\"Hence why I wanted to handle it on my own.\""
    kiga 1 u sigh "\"Nope. You already have a lot on your plate. Don't need to add more to it.\""
    mc 1 u smile "\"By the way, Kiga-kun, you said you planned on running for president next year?\""
    kiga 1 u smile2 "\"That's right. I've been here since my freshman year so I already have a good idea on how stuff works and the workload involved. Besides, I'm Pres' right hand man.\""
    mc 1 u curious "\"Wow, really? That's impressive.\""
    s 1 u "\"He's not wrong. He's been especially useful lately after the other seniors quit.\""
    mc 1 u "\"I guess that means Keisuke already has some competition.\""
    s 1 u considerate "\"Don't tell him I said this but... I don't see him winning the elections.\""
    mc 1 u considerate "\"That's... kinda sad.\""
    kiga 1 u sassy "\"Like I'm gonna lose to some guy who hasn't stepped foot in the council before. No one would be crazy to vote for him.\""
    mc 1 u talk "\"Do you know Kei-kun?\""
    kiga 1 u "\"We were classmates last year. Guy is crazy stuck-up. Barely talks to anyone too.\""
    "Sounds like Kei-kun alright."
    kiga 1 u smile "\"By the way, Pres, I don't know if you know this but the school play is coming up and I th-\""
    s 1 u sigh "\"Please don't. I'm getting really tired of having to turn you down.\""
    kiga 1 u worried "\"Sheesh, you're not even gonna let me finish?\""
    h "\"I told you. The sales pitch is getting old and annoying. You should really cut that out.\""
    kiga 1 u smile "\"Never. With enough perseverance I'm sure I can get my way.\""
    mc 1 u considerate "\"That's... kind of a creepy thing to say.\""
    s "\"Welcome to my world.\""
    kiga 1 u wry "\"Come on, our budget's already been slashed and we need more guys for the next play. At least give it a try.\""
    s "\"I already said no, stop being pushy.\""
    kiga 1 u wry "\"But-\""
    "Shoichi, [povFirstName] and Haruki" "\"No!\""
    "Our voices echo in unison, leaving the sabercat in stunned silence."
    kiga 1 u avoid "\"Jeez, you guys are mean.\""
    s "\"No, you're just annoyingly persistent.\""
    kiga 1 u smile "\"Annoying? What are you talking about? It's one of my best qualities.\""
    h "\"Not in a million years.\""
    kiga 1 u "\"Wow, that's rude.\""
    h "\"Just do your job in silence.\""
    kiga 1 u sassy "\"You're not even working. Far as I know, you're the only person here who doesn't get a say. We clear?\""
    h "\"Fuck off.\""
    mc 1 u sigh "\"Are you... are you sure you two are friends?\""
    kiga 1 u smile2 "\"Yeah, best buds. Why you ask?\""
    h "\"Best buds my ass.\""
    kiga 1 u smile "\"See? The puppy agrees.\""
    h "\"You call me puppy one more time and I'll have you eating through a straw.\""
    kiga 1 u "\"Point taken.\""
    s 1 u "\"Huh... I didn't know you two were friends... I guess I can see how that dynamic would work.\""
    s 1 u smile "\"At least now I know our friend group isn't the only dysfunctional one.\""
    h "\"Who you calling dysfunctional, eh?\""
    "The wolf sits up on his chair and glares at Shoichi."
    s 1 u sigh "\"My mistake. You guys are the very picture of normality.\""
    kiga 1 u smile2 "\"Hehe, sorry about that. Haru-kun has a bit of a temper.\""
    s "\"What? {i}No way, get out of here.{/i}\""
    h "\"Don't call me Haru-kun.\""
    kiga 1 u laugh "\"Aww, come on, don't be that way Haru-kun. You know you love it.\""
    "Oh oh, his fur is bristling up again."
    "Seriously, it's like sitting right next to a ticking time bomb."
    s "\"Let's just focus on getting this done fast, please. I really don't want to have to break up a fight right now.\""
    kiga 1 u "\"Sure. I can be quiet.\""
    h "\"Can you? Where has that information been this whole time?\""
    kiga 1 u sassy "\"Up your butt. Now if you're not going to help, at least do shut up.\""
    show s 1 u shock at fdis
    "?!" with hpunch
    "Haruki cracks his knuckles and leans forward on his seat... but he stays at that."
    "Shoichi and I stare between the two of them with a sudden sense of tension."
    "Seriously, being around these two isn't good for my heart..."
    stop music3 fadeout 2.5
    play music2 "music/BGM/Dog Days.ogg" fadein 5.0
    scene SGateE
    show kiga 1 u at fdis, oneh
    show h 1 u at fdis, nineh
    show s 1 u sigh at fdis, five
    with fade
    show sometime with dissolve
    $ renpy.pause(1.0)
    hide sometime with dissolve
    "Somehow, I don't know how, we all manage to finish up the work and exit the building with all limbs still attached."
    s "\"{size=-4}Those were the tensest twenty minutes of my life...{/size}\""
    mc 1 u sigh3 "\"{size=-4}I'll say.{/size}\""
    kiga "\"You're slipping a little, Pres. You said you'd take twenty to thirty minutes to do all the work yourself but it still took us twenty with the three of us working on it.\""
    s "\"I was otherwise preoccupied.\""
    mc 1 u sigh "\"We both were.\""
    kiga 1 u "\"How so?\""
    s "\"Let's just leave it at that.\""
    "As they say... ignorance is bliss."
    h "\"God, that was really really boring. How do you two manage to do that sort of thing every day?\""
    kiga 1 u sassy "\"What the hell are you talking about? You didn't do anything, you just browsed your phone the whole time.\""
    h "\"Exactly, and I was {i}still{/i} bored. Imagine if I were doing actual work.\""
    kiga "\"Mhm.\""
    s 1 u "\"If you guys will excuse us, I... really need to get away from you two as fast as possible.\""
    kiga 1 u sigh "\"What? That's kinda rude.\""
    h "\"It's like you tried to come up with an excuse and decided halfway that you weren't going to bother.\""
    s "\"That's about how done with you two I am right now.\""
    kiga 1 u worried "\"What did we do?\""
    mc 1 u considerate "\"It's just too much tension for us to deal with.\""
    kiga "\"Tension?\""
    s "\"The fact that you don't even realize what we're talking about scares me a little bit, not gonna lie.\""
    h "\"It's not like we're missing out on anything. Just let the homos be.\""
    show s 1 u shock at fdis
    s 1 u shock "\"Wha- Haruki!\""
    "Shoichi's face immediately drains of color when the wolf calls us that."
    kiga 1 u sassy "\"Dude, do I need to wash your mouth with soap? You insult basically everyone that talks to you.\""
    "However, it seems to completely fly over the sabercat's head."
    "... Haruki probably calls far too many people that for Kiga to even notice."
    "Like... not a blip on his gaydar."
    h "\"Fuck off, I'll curse however much I want.\""
    kiga "\"You do you... as in, literally no one would want to do you except for maybe you.\""
    h "\"Pfft, like I care.\""
    kiga "\"You really need to get laid.\""
    h "\"And you really need to mind your own business.\""
    s 1 u sigh "\"Okaaaay. As pleasant as this whole... \"experience\" has been, we really should get going. In the meantime, do try not to kill each other.\""
    kiga 1 u smile2 "\"Hah, he would never. He loves me too much.\""
    h "\"That's right, keep testing me. See what happens.\""
    mc 1 u sigh3 "\"See you two later.\""
    kiga 1 u considerate "\"Okay. See you on Monday, Pres.\""
    s 1 u "\"Yup. See ya.\""
    h "\"Later, cockwaffles.\""
    show h 1 u at offscreenleft
    show kiga 1 u considerate at offscreenleft
    with moveoledis
    "We walk away as fast as we can't without looking like we're purposely trying to get away as fast as we can."
    mc 1 u sigh "\"Did... did he just call us \"cockwaffles\"?\""
    s 1 u sigh "\"Yuuup.\""
    mc 1 u sigh "\"... What does that even mean?\""
    s "\"Beats me. Probably nothing nice, that's for sure.\""
    mc 1 u sigh3 "\"Was it just me or did Haruki sound a bit... more childish than usual?\""
    s 1 u "\"No, it wasn't just you.\""
    s 1 u sigh "\"Kiga's apparently grabbed the wolf by the balls, so to speak. I've never seen him tamer.\""
    mc 1 u sigh "\"Is that an actual saying?\""
    s 1 u smile "\"Hmm... probably somewhere in the world, yeah.\""
    mc 1 u sigh3 "\"I'm too exhausted from the tension to find it funny.\""
    s 1 u think "\"I feel you.\""
    "Shoichi stretches his arms for a bit, rotating his shoulders and yawning."
    s "\"Man, it's good to finally be moving again.\""
    mc 1 u "\"What were you even doing there? I didn't think you'd go right to work as soon as the tests ended.\""
    s 1 u considerate "\"I was feeling a little restless all week not having time to work on stuff so I decided to give everyone a day off and get to work myself.\""
    mc 1 u sigh "\"You are a legitimate workaholic.\""
    s "\"I can't disagree with you there...\""
    mc 1 u talk "\"Speaking of, how did you fare in the tests?\""
    s 1 u think "\"Hmm... I think I did well. I'll probably get at least a 90 on them.\""
    mc 1 u smile "\"Hey, that's pretty good. Your dad should be persuaded by grades that high.\""
    s 1 u sigh "\"I wish I could feel more confident of that.\""
    mc 1 u considerate "\"You don't have to be so negative. You'll just drive yourself crazy like that.\""
    s 1 u worried "\"I guess? Sorry, I'm not used to {i}not{/i} obsessing about my problems.\""
    mc 1 u sigh "\"Jesus, you really are a type A personality. You need to let loose a little.\""
    s 1 u sigh "\"Believe me, I would if I knew how.\""
    "Sounds like your dad managed to impart quite a few neurosis on you over the years..."
    "Hmm... is there something we could do together?"
    "Or... wait, does Shoichi even have time?"
    mc 1 u talk "\"By the way... are you free right now?\""
    s 1 u considerate "\"No, sorry. I have to be mindful of my curfew, remember?\""
    mc 1 u sigh "\"Yeah, I was afraid of that.\""
    s 1 u "\"Was there anything you wanted?\""
    mc 1 u sigh3 "\"For starters? To spend time with my boyfriend.\""
    s 1 u wince "\"O-oh... sorry. I can't.\""
    s 1 u think "\"Unless...\""
    mc 1 u "\"Unless what?\""
    s 1 u "\"Well... you could come over maybe?\""
    mc 1 u considerate "\"Isn't your dad going to be home?\""
    s 1 u considerate "\"Yeah but he likes you so he won't mind you being over. We just can't be too obvious when he's around.\""
    mc 1 u smile "\"That might prove difficult.\""
    s 1 u talk "\"Really? How come?\""
    mc 1 u happy "\"Are you really going to be able to keep your hands off of me? Remember, I'm quite a catch.\""
    s 1 u sigh "\"Yes, I will.\""
    mc 1 u suggestive "\"You sure?\""
    s "\"More and more sure with each passing second.\""
    mc 1 u happy "\"Okay then. I guess I can visit after all.\""
    s "\"I've half a mind to cancel my offer...\""
    mc 1 u smile "\"Nope, too late. No backsies.\""
    scene ShoichiLiving
    show s 1 u at fdis, five
    with fade
    "It's not long before we get to Shoichi's house."
    "Thank God he lives nearby the school. I really wasn't in the mood to grab a bus or anything of the sorts."
    s "\"Dad? I'm home.\""
    mc 1 u happy "\"So, where's your timeclock? I'm assuming he has you punching one to make sure you're abiding by your curfew.\""
    s 1 u sigh "\"Har har, aren't you hilarious.\""
    show s 1 u at fdis
    "There is no response whatsoever."
    "The house is completely quiet as far as I can tell."
    mc 1 u talk "\"Maybe he's not home?\""
    s 1 u "\"Nah, I can see his briefcase on the couch. He's probably just taking a nap. He does that after work sometimes.\""
    mc 1 u talk "\"I wasn't aware that was a routine.\""
    s 1 u considerate "\"It is... one he does when he has a particularly exhausting day. And usually he's always on a bad mood during those.\""
    mc 1 u worried "\"O-oh...\""
    s 1 u considerate "\"Here's hoping he reins it in a little since we have a guest.\""
    mc 1 u "\"Do I even still count as just a guest after twelve years?\""
    s 1 u talk "\"As far as Dad is concerned, even Hitoka is probably a guest.\""
    mc 1 u sigh "\"That's just cold.\""
    s 1 u considerate "\"... Yeah.\""
    s 1 u wry "\"Anyway, I'm gonna go get changed. Be right back. You're welcome to do so too if you have a change of clothes with you.\""
    mc 1 u "\"Nah. Wasn't planning on going anywhere after class so I didn't bring one.\""
    s 1 u talk "\"Oh. Gotcha.\""
    show s 1 u at fdis, offscreenright with dissolve
    "..."
    "While Shoichi is away, I take a seat on the armchair, looking around myself for anything that might hold my interest."
    "I've only been here a couple of times before so the whole place still feels a little alien to me."
    "... I can't help but feel a little on edge knowing Takehiko-san is supposed to be home."
    "Not knowing where he is and him not even knowing that I'm here really makes me anxious..."
    show origami at fdis with dissolve
    "Looking at the nearby coffee table, I spot the little origami box."
    "I pick it up very gingerly, manipulating it between my hands and examining it with curiosity."
    "... Knowing what I know now, this thing suddenly has a very different meaning from last time I saw it."
    "The first time I saw it, I thought it was a bit weird that Shoichi kept all of these, let alone having it immortalized in an acrylic box."
    "But now... I find it kinda cute."
    "... I still think this thing is super ugly though."
    "Really wish Shoichi would have framed one of the better ones..."
    show s 1 c smile at fdis, five with moveiledis
    s 1 c smile "\"Hey, whatcha looking at?\""
    hide origami with dissolve
    mc 1 u "\"Oh. Hey, I was taking another look at this.\""
    s 1 c "\"The origami? Why?\""
    mc 1 u talk "\"Well... now that I know what I know, I kinda got interested in it.\""
    s 1 c considerate "\"Oh... you probably think it's a little creepy don't you?\""
    menu:
        "Maybe a little":
            $ sholove += 1
            mc 1 u considerate "\"Well... I'd be lying if I said it isn't a little weird.\""
            mc 1 u talk "\"I mean, don't get me wrong. I'm flattered you kept it all these years because... you know. But still, kinda weird.\""
            s 1 c considerate "\"Yeah. I always know it was weird but I couldn't make myself throw them away.\""
            mc 1 u smile "\"It's alright. I'm still touched by the gesture.\""
            s 1 c smile "\"Thanks. Gotta be honest, kinda relieved I wasn't crazy.\""
            s 1 c think "\"... Well, that I wasn't crazy about the fact that me keeping them all was a little crazy. Not that keeping them wasn't-{nw}"
            show s 1 c considerate at fdis
            extend " You know what, you get the point.\""
            mc 1 u happy "\"Haha, I do I do.\""
            mc 1 u smile "\"Thank you for being such a sentimental dork. It's sweet... kinda.\""
            s 1 c smile "\"In a weird, somewhat creepy way?\""
            mc 1 u laugh "\"Yeah, you got it.\""
        "Not at all":
            mc 1 u talk "\"Nah, I don't think so.\""
            s 1 c "\"Really?\""
            mc 1 u smile "\"Yeah. It's kinda cute.\""
            s 1 c smile "\"Huh... I have to say, I didn't expect that to be your response.\""
            mc 1 u considerate "\"Really? What were you expecting?\""
            s 1 c think "\"Well... {i}I{/i} always had a little voice in my mind telling me that it was creepy that I kept all of these for so long.\""
            s 1 c "\"Hell, sometimes the voice didn't come from the back of my mind. It came from my dad criticizing me for \"wasting\" so much space in my closet keeping the box with them.\""
            mc 1 u considerate "\"You know what? I can kinda see his point.\""
            s 1 c laugh "\"Right?\""
            s 1 c smile "\"So... I dunno. It's just not what I expected. I... guess I wasn't crazy this whole time? Somehow I feel a little annoyed to be wrong.\""
            mc 1 u smile "\"And here I thought people would get happy when told that they are {i}not{/i} in fact acting like obsessive creeps.\""
            s 1 c laugh "\"Hey, I never said it made sense.\""
    s 1 c smile "\"Hopefully you'll stick with me even if I'm being weird or not making sense or... well, you get the gist.\""
    mc 1 u considerate "\"I've already have twelve years experience with that job. And it's 24/7, buddy.\""
    s 1 c happy "\"Point taken.\""
    show s 1 c smile at fdis
    "Shoichi sits on the couch directly across from me."
    "Despite how tense things were just a bit earlier things to the dynamic duo, he seems really relaxed and... happy."
    "It brings a smile to my face just seeing him like that."
    mc 1 u talk "\"By the way, are you sure Takehiko-san is home?\""
    s 1 c wry "\"Yeah. I checked his room when I went to get changed. You know, since the door was already ajar. He's definitely taking a nap.\""
    mc 1 u "\"Maybe we should be a little more quiet when we talk then?\""
    s 1 c considerate "\"I wouldn't worry about that. A missile could fall in the neighborhood and he wouldn't wake up.\""
    mc 1 u smile "\"Well, realistically speaking, if a missile fell in the neighborhood, he wouldn't wake up because he, you know, died.\""
    s 1 c happy "\"What? Of course not. He'd just wake up to find himself dead.\""
    mc 1 u considerate "\"How do you wake up to find yourself dead? Dead people don't just wake up.\""
    s 1 c think "\"I dunno... maybe it's some zombie voodoo stuff?\""
    mc 1 u wry "\"Really? \"Zombie voodoo stuff\"? That's... so incredibly realistic and likely to happen.\""
    s 1 c smile "\"In my defense, I never claimed it was either of those things.\""
    mc 1 u smile "\"Fair enough.\""
    mc 1 u "\"Do you have any plans to talk to your dad about the volleyball club today?\""
    s 1 c considerate "\"No way. Like I told you before, I'm gonna leave that for after we get the results.\""
    mc 1 u "\"But you already said you did well, why do you need to wait?\""
    s 1 c sigh "\"You don't really think he's just going to take my word for it, do you?\""
    mc 1 u talk "\"Well... yeah. I do.\""
    s "\"You poor, sweet summer child...\""
    mc 1 u sigh3 "\"Don't look down on me for not having a weird childhood.\""
    s 1 c smile "\"{i}You{/i} didn't have a weird childhood.\""
    mc 1 u "\"No. Not at all.\""
    s 1 c happy "\"Come on, you yourself are weird. By definition that makes your childhood weird too.\""
    mc 1 u sigh "\"Wow. Thanks. I feel so loved.\""
    s 1 c smile "\"You're welcome.\""
    ta 1 c "\"Shoichi?\""
    show s 1 c shock at fdis, jumping
    "Takehiko-san's voice echoes from down the hall and Shoichi immediately jumps to his feet."
    show s 1 c wince at fdis, twoh with move
    show ta 1 c at fdis, seven with moveiridis
    stop music2 fadeout 2.5
    "The older husky walks into the living room, immediately stopping on his tracks when he sees me sitting on his chair."
    s 1 c considerate "\"Hey there. Sorry, did we wake you?\""
    ta "\"No. I set an alarm so I would wake up right about now.\""
    "His eyes fall straight on me and he stares at me in silence for a few seconds."
    "Immediately I begin to feel nervous."
    "I... I feel like I'm sweating from my forehead..."
    ta "\"I didn't know you were coming over, [povFirstName].\""
    "As soon as those words are spoken, he takes a seat at the couch, right next to the spot Shoichi had been sitting on."
    s 1 c worried "\"...\""
    "Shoichi bites his lip, looking at his father with uncertainty."
    "He looks so nervous around him..."
    "Is this all because he brought me over without asking?"
    ta "\"What are you doing? Are you just going to stand there gaping all day like an idiot? Sit down, boy.\""
    show s 1 c shock at fdis
    s 1 c shock "\"R-right.\""
    show s 1 c wince at fdis
    "Shoichi quickly goes back to his seat, looking between the two of us."
    "Meanwhile, Takehiko-san is just... watching me."
    "I feel... really weird being stared at so intently."
    "He spends quite a few seconds in silence."
    "He'd always been a very quiet man and this isn't the first time something like this has happened but..."
    "After what Shoichi told me last week when he spent the night, I suddenly feel really weird about the whole thing."
    ta "\"So... it was exam week at school this week wasn't it?\""
    mc 1 u shock "\"Huh? Y-yeah, it was.\""
    ta "\"Do you suppose you did well?\""
    mc 1 u wince "\"I... think? I didn't have a hard time answering the questions at least.\""
    ta "\"That's good. Hopefully Shoichi won't do too terrible either.\""
    s 1 c worried "\"That's unfair. I always do well in my tests.\""
    ta "\"Mhm. And hopefully that streak will remain.\""
    mc 1 u considerate "\"Shoichi's been working really hard and studying a lot. I'm sure he'll do really well.\""
    ta "\"He could stand to work harder, if you ask me. Kids nowadays have no sense of work ethic.\""
    s "\"Dad...\""
    ta "\"What about your sister? Did you check up on her?\""
    s 1 c shock "\"H-huh? I wasn't aware that I should.\""
    "Takehiko-san raises a single eyebrow."
    "His expression remains just as unreadable as always."
    "I just can't tell what the man is thinking, especially because he's prone to long periods of silence."
    ta "\"This is her first year in high school. It is your job as her older brother to take care of her. You can't really be {i}that{/i} incompetent, can you?\""
    s 1 c worried "\"N-no. I'm sure she did fine.\""
    ta "\"How? You just said you didn't check up on her. Or are you just making stuff up now?\""
    s "\"I-I can ask her now.\""
    ta "\"Bah, forget it. There's no point now.\""
    "..."
    "It's... difficult to bite my tongue."
    "I know if I tried to say anything I'd just make things harder for Shoichi."
    "But... this kind of crap makes me furious."
    "I'd caught a glimpse of it during Takehiko-san's party a while ago but Shoichi kept steering me away from his father for most of the time."
    "Not to mention the older husky was far too busy entertaining his guests."
    "But now... he's just being vicious. And for no reason."
    "This isn't the Takehiko-san I remember..."
    "Is this why Shoichi always refused to let me come over after his parents divorced?"
    "... What happened here?"
    mc 1 u considerate "\"You know, the first thing Shoichi did after the exams were over was head to the student council room and start working there... alone.\""
    mc 1 u worried "\"Shoichi is the most hardworking person I know. You should give him some slack.\""
    show s 1 c shock at fdis
    "Shoichi chokes, staring at me with wide open eyes and a face of pure shock and terror."
    "Before I even realized what I was doing, I was talking back to Takehiko-san."
    "I just couldn't stand having him talk to Shoichi like this anymore."
    "The man leans forward on his seat, his eyes suddenly growing even colder than usual."
    "He stares at me with a pure detachment that I did not think possible"
    ta "\"... Is that so?\""
    s 1 c considerate "\"He's just saying that. You know how he is, he has a tendency to run his mouth and all. You should just f-\""
    show s 1 c worried at fdis
    ta "\"I don't believe I was talking to you. Don't speak unless you are spoken to.\""
    s "\"R-right. Sorry, sir.\""
    "I feel rage boiling inside of me."
    "I have to physically grip the arms of the chair, otherwise I might actually try to punch this man."
    ta "\"I appreciate that you somehow thought it appropriate to offer me your opinion... without being asked. However, I'd appreciate if you didn't try to talk about my son as if I didn't know him\""
    mc 1 u sigh "\"But you're-\""
    show s 1 c worried at fdis, jumping
    s "\"[povFirstName]!\""
    "Shoichi cuts me off, staring at me with pleading eyes."
    "I can already tell, he wants me to shut up more than anything else at this moment."
    "I'm just making things harder for him."
    "Even I can tell that Takehiko-san is very annoyed right now, even despite his icy exterior."
    "But..."
    menu:
        "I can't bring myself to stay silent":
            $ sholove += 1
            $ day24shoichidefy = True
            "I can't."
            "I just can't swallow this for even one more minute."
            mc 1 u sigh "\"You're being unfair to him, of course I'm going to say something. You expect too much.\""
            ta "\"I expect competence. Nothing more. Just as my father expected of me.\""
            mc 1 u angry "\"I don't care about what kind of baggage you have. You're taking things too far!\""
            show s 1 c shock at fdis
            "Ah, I've done it now."
            "I've let my temper completely take me over and shout out those last few words."
            "Shoichi whimpers on his seat, clearly horrified."
            "I see a flash of anger going through the older husky's eyes for barely even a second."
            "It's still enough to send a shiver right up my spine."
            ta "\"Is that so?\""
            "His voice is even more monotone than usual."
            "The man stands up, looking down on me with a hardened expression."
            "A part of me is sounding an alarm inside my head, telling me I screwed up."
            ta "\"I'll only say this once. So long as he lives under my roof, my son will obey my rules and work to fulfill the high expectations I have of him. I will not have anyone urging him to be a rebellious delinquent. If you cannot follow these rules you are not welcome here.\""
            mc 1 u angry "\"What?! You're kicking me out? Because I asked you not to be a dick to him?\""
            ta "\"Get out of my house, [povLastName]. And don't come back until you can respect me in here.\""
            mc 1 u sigh "\"You can't be serious! Shoichi, he's being crazy. You're not going to listen to him, are you?\""
            s 1 c worried "\"...\""
            "He immediately looks away from me."
            "Shoichi is pressing himself so far back on the couch it's almost like he's melting into it."
            "He's clearly so uncomfortable just being here."
            "... And he's completely avoiding my gaze."
            "My heart sinks as soon as I see it."
            mc 1 u worried "\"... Shoichi?\""
            ta "\"Leave.\""
            "Shoichi doesn't speak a single word."
            "It's not like I expected him to go against his father to defend me, but..."
            "He won't even look at me?"
            mc 1 u worried "\"Fine...\""
            hide s 1 c worried
            hide ta 1 c
            with dissolve
            "I grab my bag and walk out the door."
        "I need to be quiet":
            $ sholove -= 1
            $ day24shoichidefy = False
            "It hurts."
            "Few times in my life have I felt this enraged before."
            "Keeping it in hurts me."
            "I tighten my fists so hard I can feel the nails puncturing the skin on the palm of my hands."
            "For somehow, the sting and pain helps me clear my head."
            mc 1 u "\"Please, sir... you don't have to be so harsh on him.\""
            "Takehiko-san raises an eyebrow."
            ta "\"You call this harsh? It's not like I'm being unfair. A young boy needs a firm hand to guide him into adulthood, even if it has to go against his will.\""
            "What?! That's ridiculous!"
            "Ugh, but I can't say that out loud!"
            "I... can't make things even harder for Shoichi."
            ta "\"What? Is that it? Nothing more to say?\""
            mc 1 u avoid "\"... No, sir.\""
            "The older husky makes a humming noise, examining me with renewed interest."
            ta "\"You say that, and yet I can tell from your face that you have more you want to say.\""
            mc "\"That's not true, sir.\""
            ta "\"Tch. So you'll just speak your mind, contradict me and then refuse to say a word? More spunk than sense, I see.\""
            s "\"Dad...\""
            "Takehiko-san shakes his head, getting up from his seat."
            ta "\"I suppose I shouldn't be surprised. I shouldn't have expected better from a household without a father.\""
            show s 1 c shock at fdis
            "?!"
            "I feel like I just had a bucket of cold water thrown all over me."
            "I feel like the blood coursing through my veins itself has suddenly frozen over."
            "I... I can't believe I just heard someone say that."
            "Takehiko-san stares at me disapprovingly, the same judgmental silence as always."
            show s 1 c worried at fdis
            ta "\"Regardless, I don't have time to waste like this. If you've got no further business here, I would like to ask you to leave. Shoichi needs to study some more and do his chores, isn't that right?\""
            "Shoichi looks up at me, his eyes moist and starting to go red."
            "He's fighting back an urge to cry..."
            s "\"Y-yeah. You should probably head home today, [povFirstName]. I-I'm really busy.\""
            "Takehiko-san nods, the very edge of his lip curving up in what I can barely call a smile."
            ta "\"And please, do remember to call ahead the next time you wish to come over.\""
            "He makes a gesture towards the door, as if he were \"inviting\" me to leave."
            "I look at Shoichi one last time."
            "... I feel bad leaving here like this."
            "I did my best to stay silent and even still..."
            s "\"...\""
            "Shoichi nods at me, as if saying it's okay for me to leave."
            hide s 1 c worried
            hide ta 1 c
            with dissolve
            "Before my heart can hurt even more than it already does, I do as I am asked."
    scene Black with fade
    "WOTB: Hey there, everyone."
    "WOTB: First of all, for the sake of full disclosure I will say - this update {i}is{/i} in fact just a bit smaller than the usual size. All my updates tend to be very consistent on how big they are but I couldn't make this one any longer."
    "WOTB: I spent two weeks of my month working on my move, packing boxes, shopping for furniture, moving to the new apartment, unpacking, all that really time consuming stuff. And all of that really put a limit on how much work I could do."
    "WOTB: And when I finally had time to work again, I had to also tend to the commissions I needed to take up to pay for my move in the first place."
    "WOTB: To add to that, I actually managed to get through all the events I had planned for this update in fewer lines than I thought. I had {i}thought{/i} it would take me about 1700 lines to write everything (average update size is 1500)."
    "WOTB: Instead, it ended up taking me 1350 lines. Again, I really and sincerely apologize for this. I don't want anyone to think that this will be a new standard going forward.\""
    "WOTB: The size of my updates has been consistently the same for over a year and that's one of the things I pride myself on."
    "WOTB: You guys can be assured that next month, since I'll have more time, I'll get back to producing regular sized updates."
    "WOTB: Oh, and if you guys notice a lot more typos this update than usual, it's because I didn't have as much time as I usually do to typocheck so... there wasn't much proofreading done this update either. I'm sorry."
    "WOTB: Until then, I hope you all enjoyed the content that I did manage to put out. See you all again next month!"
