label Day23_Keisuke:
    window hide
    scene June4 with fade
    play sound "music/windchimes.ogg"
    show blossoms movie
    $ renpy.pause(5.5)
    scene LivingRoomE
    play music "music/cicada01.ogg" fadein 5.0
    play sound "music/pageflip.ogg"
    window show
    $ date = "day23"
    "I idly flip through the pages of my textbook, not really focusing on anything in particular."
    "I'd decided to study a little bit before midterms started tomorrow but so far I've mad very little progress."
    "I already know most of this stuff but I thought getting a refresher couldn't hurt."
    "... To be perfectly honest, I'm just trying to emulate Kei-kun a little."
    "I sorta envy his diligent attitude towards everything."
    "It reminds me how I used to be that way when I was a kid."
    "I was able to force myself to sit down and get things done even though I hated doing it more than anything."
    play sound "music/disappointment.ogg"
    "What happened to all the discipline I used to have?"
    show a 1 c at fdis, five with moveiledis
    a "\"Huh? What a surprise, I can't believe you're actually studying.\""
    "Aki comes down from the stairs, looking over my shoulder at my textbook and notes."
    mc 1 c "\"To be honest, neither can I.\""
    a 1 c sigh "\"Whoa. You actually agreed with me? Do you have a fever or something?\""
    mc 1 c considerate "\"That's kinda harsh.\""
    a 1 c "\"You're being surprisingly agreeable today. What's up?\""
    mc 1 c "\"I'm trying to be a little more like Kei-kun.\""
    a 1 c "\"Like Keisuke-san? How so?\""
    mc 1 c think "\"Well... I just kind of admire and envy his straightforward attitude.\""
    mc 1 c considerate "\"No matter what it is, he has that sort of \"if I'm going to do it, I'll do my best at it\" attitude that I seem to lack.\""
    a 1 c avoid "\"Hmm... is that so?\""
    a 1 c "\"Hey, Aniki? You've been spending a lot of time with Keisuke-san lately haven't you?\""
    mc 1 c talk "\"Hmm? I... I guess so.\""
    a 1 c smile "\"It kinda looks like you've been watching him a lot more carefully if you've managed to notice that much.\""
    mc 1 c confused "\"Huh? What do you mean?\""
    a 1 c "\"Well, you've known Keisuke-san for a little over a year but until now I'd barely hear you talking about him and I don't remember him ever coming over on his own.\""
    a 1 c smile "\"Now all of a sudden you've been going to visit him, he's been showing up here a lot more and you talk about him quite a bit too.\""
    mc 1 c shockb "\"I-I do?\""
    a 1 c smile "\"Yeah. It kinda makes me happy.\""
    mc 1 c wince "\"Why would that make you happy?\""
    a 1 c "\"I mean, you just said it yourself right? You're trying to be more like Keisuke-san. Ever since your last year of Junior High you've started acting like you just don't care about things anymore.\""
    a 1 c considerate "\"I was a little worried. I mean, you used to be really focused and straightforward too. How could I not worry?\""
    mc 1 c wince "\"D-do you really think that?\""
    a "\"Yeah.\""
    play sound "music/disappointment.ogg"
    "Ah... great. Now I'm making my little brother worry about me..."
    a 1 c smile "\"And I think you might be rubbing off on Keisuke-san too now that I think about it.\""
    mc 1 c shock "\"Me? Rubbing off on that guy? No way.\""
    a 1 c "\"Sure you are. I might not hang out with you guys all that much but he's really different from how he used to act a few months ago.\""
    a "\"I mean, he smiles a lot more and he's not as rough around the edges. The last time he came over while I was home he was even clinging to you.\""
    mc 1 c considerate "\"That was just because of the storm. It's not like it had some kind of deep meaning.\""
    a 1 c think "\"You say that but...\""
    mc 1 c "\"But?\""
    a 1 c "\"Ah, nothing. Just thinking out loud.\""
    mc 1 c sigh3 "\"You're just gonna leave me hanging after saying this much?\""
    a 1 c smile "\"Sounds about right, yeah.\""
    "Sometimes you really scare me with how mature you are for your age."
    a "\"This is just a thought but maybe you should have Keisuke-san come over? You two could study together.\""
    a 1 c happy "\"Who knows, maybe his diligence might be contagious after all.\""
    mc 1 c sigh3 "\"I can't just call him out of nowhere and ask him to come over. He has other things to do with his time.\""
    a 1 c "\"It won't hurt to try. It's pretty obvious you're no longer used to studying so you might need all the help you can get. Especially since you left it for the day before your midterms.\""
    mc 1 c sigh "\"What do you mean \"it's pretty obvious\" I'm not used to studying.\""
    a 1 c sigh "\"I can see your notes from here. They're a mess. You've crossed out a bunch of your text and I can see a lot of unfinished sentences.\""
    mc 1 c avoidb "\"Wha- That doesn't mean anything. My mind was just wandering, this isn't the best I can do.\""
    a 1 c "\"No offense but... if you're mind is going to be wandering while you're studying, isn't that all the more reason to have someone come over that can help you focus?\""
    "Ugh... I hate that he has a point."
    mc 1 c sigh3 "\"I hate having to spend a Sunday studying...\""
    a 1 c sigh "\"This is your fault for not studying before today.\""
    mc 1 c worried "\"I did study... a little bit. Not that much though. Enough to maintain my current grades at least.\""
    a 1 c "\"You're lucky you're quick a quick study. If it weren't for that you'd be borderline flunking out of school by now.\""
    mc 1 c considerate "\"I'm well aware...\""
    a 1 c sigh "\"Just make sure you don't bother Keisuke-san too much. It's unseemly to be having to depend on a junior to get your grades up.\""
    mc 1 c sigh "\"You're the one who just told me to call him over. Make up your damn mind.\""
    a 1 c "\"It's okay to ask for a little help but you shouldn't abuse it.\""
    mc 1 c sigh3 "\"You know I'm not the kind to abuse other people's kindness.\""
    a 1 c think "\"It's never too late to start.\""
    mc 1 c sigh "\"You know, it's sad that you have so little faith in me.\""
    a 1 c smile "\"That's just your imagination. I believe in you lots.\""
    mc 1 c sigh "\"Uhuh.\""
    a 1 c "\"Anyway, I'm heading out.\""
    mc 1 c shock "\"Already? You only just got home this morning.\""
    a 1 c "\"I know, but I want to hit the club for a bit. Maybe look for a practice partner.\""
    mc 1 c talk "\"Oh. So that's why you've got your tennis gear with you.\""
    a 1 c sigh "\"Of course. What else would I be doing with it? Cosplay?\""
    mc 1 c sigh "\"Don't talk to me like that.\""
    a 1 c "\"Anyway, I'll be back in a few hours. Good luck with your studies. Try not to bother Keisuke-san too much okay?\""
    show a 1 c at offscreenright with moveoridis
    play sound "music/slidingdoor.ogg"
    "Somehow I don't even feel like I'm the older brother anymore..."
    "Although he does have a point."
    "I guess it couldn't hurt to check in on Kei-kun and see what he's been up to."
    "... God knows I'm gonna need help if I want to improve my grades."
    play sound "music/calling.ogg"
    "Sending a message feels too impersonal when I'm asking him to drop whatever he's doing and come over. I'll try calling him instead."
    "..."
    k 1 c "\"Hello? [povFirstName]?\""
    "The call connects and suddenly I hear Keisuke's voice on the other side."
    mc 1 c "\"Hey there. Sorry to call all of a sudden. Are you busy?\""
    k 1 c eyesc "\"I'm afraid so. I don't really have time to talk right now.\""
    mc 1 c worried "\"O-oh. Sorry to bother you, I didn't know.\""
    k 1 c smile "\"It's alright. You just said it yourself, you didn't know. Now, is there anything you wanted?\""
    mc 1 c considerate "\"Ahaha... it's nothing big. I just wanted to know if you could come over. Maybe we could study together a bit. Midterms are tomorrow and all.\""
    k 1 c worried "\"Oh. I'm sorry, I'm currently tied down with some other stuff I need to do. I... can't really leave the estate right now.\""
    mc 1 c worried "\"Did something happen?\""
    k 1 c sigh "\"I'll tell you about it sometime later. I'm sorry but I'll need to end the call right now.\""
    mc 1 c worried "\"A-alright. I hope everything's okay.\""
    k 1 c wry "\"I'll talk to you later.\""
    play sound "music/phonebeep.ogg"
    "..."
    "Well... that sucked."
    "I wonder what is going on. His voice seemed really serious."
    play sound "music/disappointment.ogg"
    "Ugh, now I'm going to have an even harder time concentrating than I was before!"
    "Thanks for he genius idea, Aki..."
    "..."
    "Maybe I should try calling someone else?"
    "I think... I think Shoichi might be studying today."
    "Saya doesn't really believe in studying the day before a test so she's probably relaxing."
    "But Shoichi rarely ever even takes a break."
    "Yeah, I'll try talking to him."
    play sound "music/calling.ogg"
    "I quickly select his number from my contacts list and wait listen to the dialtone, waiting for him to pick it up."
    "Huh? It went straight to voicemail."
    play sound "music/disappointment.ogg"
    "Ugh, right, he has a habit of turning his phone off when he's studying."
    "Of all the annoying habits to have. What if this were an emergency?"
    "And I don't have the number for his landline either."
    "I guess I'll try to drop by."
    "What's the harm in that, right?"
    "I'll just gather my things before I go so we can already study there."
    "Hopefully Takehiko-san won't be too annoyed that I showed up without warning."
    scene Street2E with fade
    "There aren't many people around the streets at this time of day."
    "The area is already pretty quiet most of the time and without people coming and going from work or school, it's pretty much a ghost town."
    "Good thing Shoichi doesn't live all that far from me."
    "Not as close by as his previous place but still close enough."
    "Takes me about twenty minutes to get there."
    play sound "music/knock.ogg"
    "I knock on his door, waiting a few seconds for a response."
    play sound "music/door.ogg"
    scene ShoichiLiving
    show ta 1 c at fdis, five
    with fade
    "I immediately see the figure of an older husky."
    "Takehiko-san regards me with a raised eyebrow for a second."
    ta "\"[povFirstName]... what a surprise?\""
    mc 1 c considerate "\"H-hi there, good afternoon. Sorry to drop by unannounced. I wanted to talk to Shoichi but he's not answering his phone.\""
    ta "\"He is in his room studying. He doesn't have time to be playing around with his phone.\""
    mc 1 c fsmile "\"R-right. That's what I was imagining. I was hoping he and I could study together. I even brought my textbooks and notes and whatnot.\""
    "His eyes widen ever so slightly and Takehiko-san stares at me with stunned silence."
    "He holds a finger to his chin, lost in thought for a few seconds."
    ta "\"Hmm... You did get him to improve his grades quite a bit when you two were younger... I suppose it might work again.\""
    mc 1 c considerate "\"Y-yeah, sure.\""
    "He still wants Shoichi's grades to improve? They're already really high!"
    "Isn't that a little bit greedy?"
    ta "\"Alright, come on in. You know where his room is.\""
    "Takehiko-san sits back down on the sofa, pulling out a laptop that was on the coffee table and typing away on it."
    "It's like... as soon as he let me in, he completely ignored my existence."
    "I can't tell if that's rude or impressive."
    "He could have at least wished me a good afternoon too."
    play sound "music/knock.ogg"
    "I knock on the door but after a few seconds I hear no response."
    play sound "music/knock.ogg"
    "I try knocking again, this time a little bit louder, but still get nothing."
    "Is he asleep or something?"
    "There's no way."
    play sound "music/door.ogg"
    stop music fadeout 2.5
    play music2 "music/BGM/Snowy Day.ogg" fadein 5.0
    scene ShoichiBedroom
    show s 1 c at fdis, five
    with fade
    "I carefully open the door, peeking in to see what he's up to."
    "I see Shoichi sitting at his desk, earbuds plugged into his computer and writing something down on his notebook."
    "He's definitely studying. Maybe he has music on and that's why he didn't hear me?"
    mc 1 c talk "\"Uhm... Shoichi?\""
    "I speak a little louder than I normally would."
    "His ears twitch ever so slightly and pulls on of his earbuds off, turning his head around."
    s 1 c think "\"Do you need any-{nw}"
    show s 1 c shock at fdis
    extend " Huh? [povFirstName]?\""
    mc 1 c considerate "\"Hey there. Sorry for the intrusion. {size=-2}I tried knocking on the door but you didn't answer so I let myself in...{/size}.\""
    s 1 c talk "\"What are you doing here?\""
    mc 1 c talk "\"I was kinda hoping we could study together? I figured you'd still be at it and I kinda need a presence that can help me stay focused.\""
    s 1 c smile "\"Study? Wow, I totally didn't see that coming. No wonder Dad let you in.\""
    mc 1 c happy "\"What? Why? Do you think he would have turned me away if he thought I would distract you.\""
    s 1 c "\"I 100\% do, yeah.\""
    "Oh... I didn't think I'd actually be right."
    "... Now I feel kinda insulted."
    mc 1 c considerate "\"A-anyway, what are you studying right now?\""
    s 1 c happy "\"Before we start though, I have a question.\""
    mc 1 c talk "\"What is it?\""
    s 1 c smile "\"How come you just decided to study all of a sudden? That's so unlike you.\""
    mc 1 c sigh3 "\"...{w} Why does everyone keep asking me that?\""
    s 1 c talk "\"Everyone?\""
    mc 1 c sigh "\"Aki asked me the same thing earlier today. He acted like it was a big deal when he walked in and saw me studying.\""
    s 1 c smile "\"Well, considering how much you tease him for being a responsible student, do you really think he'd let pass the opportunity to fire back?\""
    mc 1 c sigh2 "\"Still, it's not like I'm some kind of delinquent or problem child. I also study!\""
    s "\"Yeah. At five minute increments and only on a superficial level. Other than that you're perfectly happy letting yourself be carried by just watching class.\""
    mc 1 c sigh "\"Why do I feel like I'm getting talked down to here?\""
    s 1 c sigh "\"Oh please. Isn't that why you stopped studying with me in the first place? You hate having to put in the effort.\""
    s 1 c smile "\"Which brings me back to my earlier question: how come?\""
    mc 1 c wince "\"W-well... I just thought it would be easier to concentrate if I had someone around who didn't let me slack off.\""
    s 1 c smile "\"Oh I won't, trust me on that. By the time I'm done with you you'll be reciting pi to the fortieth decimal.\""
    mc 1 c sigh3 "\"That's good... and also mildly concerning. Especially considering how that's not even part of our coursework.\""
    s 1 c happy "\"Shh. Don't fight it, just let it happen.\""
    mc 1 c sigh "\"Okay, now you're just being plain creepy.\""
    s "\"Hehehe.\""
    "I came here to study, not to be made fun of."
    "If  wanted that I'd have stayed at home."
    s 1 c smile "\"But seriously, what changed?\""
    mc 1 c sigh3 "\"Oh my God, you're such a broken record. Can we move forward please?\""
    s 1 c talk "\"Fine fine. Forgive me for wanting a bit of levity.\""
    show s 1 c at fdis
    mc 1 c "\"So, what are we going to be studying?\""
    s 1 c talk "\"I was going over Social Studies since that's going to be tomorrow's test.\""
    mc 1 c talk "\"Yeah, that's probably smart.\""
    s "\"Currently looking at philosophy. Was reading the chapter on Plato and the theory of forms.\""
    mc 1 c wince "\"Ugh... philosophy is so boring.\""
    s 1 c sigh "\"Already? I literally only read the chapter name to you.\""
    "I already regret this decision."
    stop music2 fadeout 2.5
    play music "music/night.ogg" fadein 5.0
    scene ShoichiBedroom
    show s 1 c talk at fdis, five
    with fade
    show hours with dissolve
    $ renpy.pause (1.0)
    hide hours with dissolve
    s "\"-and with that we finish the ancient Greece portion of our philosophy textbook.\""
    mc 1 c sigh3 "\"Thank {i}Gooood{/i}.\""
    s 1 c smile "\"You know, there's a certain irony to be had by exclaiming that while studying Greek philosophers.\""
    mc 1 c sigh "\"All I know is I'm glad these people died when they did otherwise this chapter might have been twice as long.\""
    s 1 c sigh "\"Jesus, [povFirstName], that's horrible.\""
    mc 1 c sigh "\"Yeah yeah, I'm a terrible person. Sue me.\""
    s "\"I don't think I like you when you're like this.\""
    play sound "music/knock.ogg"
    show s 1 c at fdis
    "There is knocking on the other side of the door."
    s 1 c "\"Come in.\""
    play sound "music/door.ogg"
    show s 1 c at fdis, twoh with move
    show ta 1 c at fdis, ten with moveiridis
    "Takehiko-san opens the door, walking inside while looking around at the room."
    "His eyes rest on us for a second and he squints."
    s "\"We've just finished going over philosophy. We were going to get started on economics next.\""
    mc 1 c fsmile "\"W-we were?\""
    "Oh God, spare me from this."
    "Why do all the worst subjects have to be in the same test?"
    show ta 1 c at fdis, seven with move
    "Takehiko-san nods, walking towards us."
    play sound "music/pageflip.ogg"
    "He grabs Shoichi's notes and idly flips through them, quickly reading through the important points before moving to the next one."
    "The whole thing seems very bizarre to me but Shoichi merely stares at his father like this is the most natural thing in the world."
    "After a couple minutes of this and no words being said, Takehiko-san places the notebook back down on the desk."
    "The corner of his mouth quirks up ever so slightly, barely noticeable."
    "He puts a hand on top of Shoichi's head and idly runs his fingers through it, petting him."
    ta "\"That's good. I suppose you're not hopeless after all.\""
    s 1 c wince "\"U-uhm... thank you.\""
    ta "\"I'm going to order food. I'll call you boys over when it arrives and then you can take a break to eat.\""
    s 1 c "\"Sounds good.\""
    mc 1 c considerate "\"I appreciate the offer but I don't know if I should. I'm usually the one who makes dinner at home.\""
    "Takehiko-san raises an eyebrow, looking at me like I'd just said something completely absurd."
    ta "\"What about your mother?\""
    mc 1 c considerate "\"She usually works a lot of overtime every day so she's rarely home for dinner, let alone to make it.\""
    ta "\"That's unfortunate. Mothers should prioritize taking care of the house and the children before all.\""
    "... The whole thing rubs me the wrong way."
    "I can understand why he'd think like that but... that's such an antiquated belief."
    "But still, I don't really want to ruffle any feathers."
    "Besides, it's not like I could change his mind even if I tried."
    "If anything, I'd just make this whole situation very uncomfortable."
    mc 1 c considerate "\"W-well, she has to make money to support the house somehow.\""
    "The older husky sighs, rubbing the bridge of his snout, his left brow twitching a few times."
    ta "\"I suppose that cannot be avoided. You should call your brother and let him know you'll be late. He can make arrangements.\""
    mc 1 c shock "\"What? But-{nw}"
    s 1 c blank "\"I'm sure if it came to it Aki could take care of himself. And it's just for one night. He can just order food. He has his own allowance.\""
    mc 1 c wince "\"W-well, sure he does but...\""
    "I'm shocked that Shoichi is even going along with this."
    "Usually he'd be the type to tell me to take care of Aki."
    "I mean, yeah, he gets on my case for being overbearing from time to time but he's not on to tell me to just leave Aki be."
    "This whole conversation feels really weird."
    ta "\"Stay. Studies are more important. And Shoichi is making good progress having you around so I'd rather you not leave just yet.\""
    play sound "music/disappointment.ogg"
    "It's not like I'm here to tutor him you know..."
    "And I couldn't even if I wanted to, I don't remember a lot of this stuff."
    ta "\"I'll order food. You boys carry on.\""
    show s 1 c considerate at fdis
    show ta 1 c at offscreenright with moveoridis
    show s 1 c considerate at fdis, five with move
    "Without another word, almost as if he were leaving no room for debate, Takehiko-san leaves the room."
    "It's not like what he said is really wrong. I know he places a lot of value in studying and insisting I stay is his way of looking out for me."
    "But somehow, the whole conversation left a bitter taste in my mouth..."
    s "\"Sorry about that. Dad can be really strict when it comes to academics but he means well.\""
    mc 1 c sigh3 "\"I didn't really feel like I had a choice on the matter.\""
    s "\"Yeah, he kinda has that authoritative tone of voice.\""
    mc 1 c wince "\"I'm surprised you actually went along with him. I thought you'd try to talk him out of it and would say I needed to go home to take care of Aki.\""
    s 1 c worried "\"W-well, Aki is old enough to be able to fix himself dinner. It's not like it's a big deal.\""
    mc 1 c sigh "\"It's not about it being a big deal, it's about the principle.\""
    s 1 c considerate "\"I guess... Dad just suggested it because he thought it'd be better for you.\""
    mc 1 c sigh3 "\"And for you as well it seems.\""
    s 1 c wince "\"Huh?\""
    mc 1 c "\"He said he didn't want me to leave yet because you were making \"good progress\".\""
    mc 1 c sigh3 "\"Which, to be honest, I don't know how I could possibly be helping you here.\""
    s 1 c talk "\"Well... it's true that I'm having an easier time grasping the material with you around.\""
    mc 1 c wince "\"You are?! How?\""
    s "\"Since I'm having to explain it to you, it forces me to try and articulate my thoughts as best as I can to make it easy to understand.\""
    s 1 c "\"That ends up helping me too since I understand things better that way.\""
    mc 1 c smile "\"Huh... Didn't think of that.\""
    s 1 c considerate "\"Yeah, so me helping you study is also helping me to study.\""
    mc 1 c sigh "\"... Glad I could be useful for something?\""
    s "\"Come on, don't say that sort of thing.\""
    s 1 c "\"Here, we should probably get started on the next subject. If we're lucky we might be able to get at least halfway through before dinner break.\""
    "... I have a feeling I'm going to be stuck here all night."
    play music2 "music/BGM/Summer Day.ogg"
    scene Street1N
    show s 1 c at fdis, five
    with fade
    show hours with dissolve
    $ renpy.pause(1.0)
    hide hours with dissolve
    "God, my whole body is sore..."
    "By the time we were able to run through the entire material to Shoichi's satisfaction it was already almost 11PM..."
    "Having to sit still on an uncomfortable wooden chair the whole time really makes my back hurt."
    mc 1 c considerate "\"... You really don't have to walk me home you know.\""
    s 1 c talk "\"Well, you refused to spend the night so I thought the least I could do was walk you home.\""
    show s 1 c at fdis
    "And of course once I was ready to head home, this happened."
    mc 1 c worried "\"I'm not a small child you know.\""
    s 1 c talk "\"Nobody said you were. I'm just looking out for you like I would any other friend.\""
    show s 1 c at fdis
    "Somehow that answer still leaves me dissatisfied."
    s "\"Thanks for coming over today by the way.\""
    mc 1 c considerate "\"Wait, you're thanking {i}me{/i}? Shouldn't it be the other way around? You helped me a ton more than I did you.\""
    s 1 c smile "\"Nah, you're just imagining things. Having you around to bounce ideas off of helped me catch on to the material much faster.\""
    s 1 c happy "\"I've half a mind to steal you away for the rest of the week to keep studying.\""
    mc 1 c fsmile "\"Y-you're kidding right?\""
    s 1 c think "\"What? Doesn't sound like a bad idea to me. It would help both of us tremendously too.\""
    "I don't think I could handle an entire week of this..."
    mc 1 c considerate "\"N-no. Please have mercy...\""
    s 1 c "\"Huh?\""
    mc 1 c considerate "\"Nothing, I said nothing.\""
    show HouseFrontN
    show s 1 c at fdis, five
    with fade
    "As soon as we take a turn on the street, my house becomes visible from the distance."
    "Right away, I notice a car parked right by the entrance."
    mc 1 c talk "\"That's weird. Do we have guests or something?\""
    s 1 c talk "\"Why are you asking me? If you don't know it then how should I?\""
    mc 1 c considerate "\"I wasn't literally asking you. Just talking out loud.\""
    s 1 c smile "\"Probably shoudln't do that. People will start thinking you're crazy.\""
    mc 1 c sigh "\"You're the only one here.\""
    s 1 c happy "\"And I'm still people so be careful I don't start thinking you're crazy.\""
    "I roll my eyes, grabbing my keys and going for the door."
    mc 1 c talk "\"Do you wanna come inside real quick? Get some water or something?\""
    s 1 c smile "\"Sure. I have to admit I'm also curious to see who's the mystery visitor.\""
    mc 1 c "\"It's probably just someone from my Mom's work.\""
    s 1 c sigh "\"At 11PM? I very much doubt it.\""
    mc 1 c considerate "\"I'd believe anything her work asks her to do at this point.\""
    play sound "music/door.ogg"
    scene HouseEntrance
    show s 1 c at fdis, five
    with fade
    "I wait for Shoichi to get in first and then make sure to close and lock the door behind me."
    "I put the keys on the little key holder we have by the front door where I immediately notice my mother's keys are still absent from it."
    "Only Aki's are here at the moment."
    mc 1 c talk "\"That's... weird.\""
    show s 1 c at fdis, offscreenleft with moveoledis
    "While I'm busy examining and storing my keys, Shoichi finishes taking off his shoes and heads into the living room."
    "I hurry to take mine own off and follow suit."
    scene LivingRoomN
    show s 1 c shock at fdis, oneh
    show al 1 u at fdis, five
    show k 1 c worried at fdis, sevenh
    show a 1 c smile at fdis, ten
    with fade
    "The first thing I see is a very tall wolf sitting on our sofa with a teeny-tiny cup of tea in his hand, his body turned towards the door to see who was coming in."
    "Shoichi stands frozen by the doorway staring at the scene."
    "Alongside Alex I also see Keisuke staring at the two of us with a weird look on his face."
    k "\"Is something the matter?\""
    "He sputters those words out very uncertain."
    "It takes me a few seconds to compute that he's probably a little rattled by the looks on our faces."
    s "\"Urushihara?! What are you doing here?\""
    k "\"I could be asking you the same thing. Isn't it a little late to be showing up to someone's house?\""
    mc 1 c sigh "\"Like you're one to talk.\""
    k 1 c wince "\"T-that's not what I meant.\""
    a 1 c "\"So you were out with Shoichi-nii? You could have at least said something. We were worried.\""
    mc 1 c confused "\"Worried? Huh? Why would you be worried? And, not to mean any offense but, what are you two doing here?\""
    "I make a gesture towards the two unannounced guests with my chin."
    k "\"I felt bad about not having time to talk to you earlier today so I came here as soon as I was free. I even brought my notes and textbooks.\""
    "I look at the seat right next to him and immediately my eyes are drawn to his school bag."
    "But even with that explanation, the whole thing just sounds too absurd to my mind."
    mc 1 c sigh "\"You came over at {i}11PM{/i} to {i}study{/i}?!\""
    k 2 c sigh "\"What? No, of course not. That'd be stupid.\""
    k 1 c "\"I came over at 9PM. Then Aki-kun said you weren't home and asked if I wanted to wait until you arrived.\""
    "..."
    "Okay, I think it's safe to say I've mentally checked out at this point."
    "I just... can't."
    mc 1 c sigh3 "\"You do know that's just as weird, right? Like... it's not possible that you can't see just how friggin' weird that is.\""
    k 1 c worried "\"I just thought I could help a little. I mean, what about Urata? He's also here late at night.\""
    s 1 c sigh "\"Don't include me in this. I just came here to walk him home after he spent the day at my place.\""
    s 1 c "\"Still, you didn't tell me you had asked Urushihara to study with you first. Why would you even do that? You guys are in different years and all, you don't study the same material.\""
    a 1 c "\"Well, Keisuke-san was the whole reason he was even studying in the first place.\""
    s 1 c shock "\"H-huh? Is that so?\""
    mc 1 c sigh "\"Aki, for once in your life are you incapable of keeping your mouth shut?\""
    a 1 c wince "\"What did I do? It's the truth!\""
    "Somethings are better left unsaid."
    "Especially when they are embarrassing."
    k 1 c "\"I... made you want to study? I think I'm lost.\""
    mc 1 c considerate "\"It's not a big deal. Don't dwe-{nw}"
    a 1 c smile "\"Oh, he said since he's spending so much more time with you lately he's starting to feel inspired by how responsible and diligent you are.\""
    show s 1 c wince at fdis
    show k 1 c shockb at fdis
    k "\"O-oh. That's... I'm... I'm flattered.\""
    mc 1 c sigh "\"Okay, this time you absolutely did it on purpose you dick!\""
    a 1 c happy "\"Hehehe.\""
    s "\"This... this is a lot of stuff to absorb all at once.\""
    "Now that's just wonderful."
    "Aki managed to find a way to brick two people's brains all at once."
    mc 1 c sigh3 "\"Seriously, this isn't a big deal, don't overthink it.\""
    k 2 c gentle "\"It's still kinda nice to hear. I'm glad our time together has been having such a positive impact!\""
    s 1 c worried "\"I wasn't even aware you guys were spending so much time together.\""
    mc 1 c fsmile "\"Seriously, it's not a big deal. Why is everyone making such a big deal out of it?\""
    k 1 c "\"Well... I guess we {i}have{/i} been spending a lot more time together now that I think about it.\""
    k 1 c smile "\"I'm definitely not complaining about it though.\""
    show k 1 c at fdis
    s 1 c considerate "\"I see. Guess I'm a bit out of the loop since I've been too busy to hang out lately.\""
    "..."
    play sound "music/disappointment.ogg"
    "Why does the mood feel so awkward all of a sudden?"
    a 1 c "\"Sheesh, why is everyone so quiet? This isn't a funeral.\""
    mc 1 c sigh3 "\"You really need to learn to be quiet sometimes.\""
    a 1 c sigh "\"You're one to say that.\""
    s 1 c sigh "\"Hang on. As... confused as I already am, I still feel like I need to recognize the huge elephant in the room... or in this case it'd be a wolf I guess?\""
    "Shoichi's eyes fall onto Alex's figure and he makes a pointing gesture to the wolf."
    s "\"I guess I get why Urushihara is here but seriously, who is this guy?!\""
    k 1 c worried "\"Oh. Right. I guess I forgot to explain. It's a bit of a long story but-{nw}"
    al "\"I'm his bodyguard.\""
    k 2 c sigh "\"That's... not how I would have put it but I suppose it's true.\""
    mc 1 c sigh3 "\"No, that's exactly the way to put it. You were just going to blabber a lot to try and dodge the question.\""
    s 1 c sigh "\"Right... I think I remember Saya-chan mentioning something about a bodyguard. Although she did describe him being \"tall like a mountain\" so I was expecting a little more... well, just more.\""
    a 1 c "\"That's easy to say when you're also ridiculously tall.\""
    s 1 c worried "\"I suppose that's a good point.\""
    show k 1 c at fdis
    al "\"My apologies. I should have introduced myself first since I'm the only stranger in the room.\""
    s 1 c considerate "\"Nah, that's quite alright. This whole situation was already pretty confusing so I don't blame you for feeling awkward.\""
    "Alex frowns, staring at Shoichi with a slightly confused look on his face."
    "Of course, Shoichi probably wouldn't be able to notice it but I've kinda gotten used to reading the nuances in Alex's expressions, even if just a little."
    "Like how when he's frowning that means he's mad but when he's frowning that means he's amused and when he's frowning he's also thinking about something."
    "Honestly, the real takeaway here is that he frowns a lot."
    mc 1 c talk "\"Alex can come off as really intimidating at first but he's a good guy.\""
    al "\"I just feel like I have to put this out there for clarity's sake but \'Alex\' is just a nickname. My name is Alexander.\""
    s "\"Nice to meet you, Alexander. I guess you really are as much of a foreigner as you look.\""
    "Alex blinks a few times, cocking his head slightly to the side."
    al "\"I... look foreign? I thought I blended in well with the locals.\""
    s 1 c wry "\"Well, you don't really have any noticeable accent but you {i}are{/i} way taller than a Japanese and you don't usually see wolves with your fur pattern over here.\""
    s 1 c considerate "\"... Also, the fact that you walk around with an uncovered tattoo is also a bit of a dead giveaway.\""
    show s 1 c at fdis
    al "\"It is? No one ever said anything about it. At least other than the time I was barred from entering a bathhouse because of it.\""
    mc 1 c considerate "\"Tattoos are kind of a yakuza thing in Japan so people don't look at them with very good eyes. I'm surprised you didn't already know that.\""
    al "\"Oh.\""
    "He muses over it for a few seconds, echoing a low-pitched humming sound from his throat for a second."
    al "\"Maybe I should cover it up?\""
    k 1 c calm "\"Your tattoo is fine. More than fine even, it helps you do your job. People avoid you in the street because of it.\""
    mc 1 c considerate "\"Well...\""
    "It's not like the super jacked, tall as sin, always frowning wolf needs any help to look threatening."
    "He already has that covered with or without the tattoo."
    s 1 c think "\"... Anyway, I really should leave. Dad will wonder why I've been gone for so long.\""
    s 1 c considerate "\"And... uhm... nice running into you, Urushihara.\""
    k 1 c worried "\"Nice running into me? That's... are you okay? {size=-2}You usually don't say nice things like that.{/size}\""
    s 1 c smile "\"... I'm just fine, don't worry about it. I'll hopefully see you guys tomorrow. Might not have time to stop and say hi though.\""
    a 1 c happy "\"Have a good night, Shoichi-nii. Thanks for looking after my brother!\""
    mc 1 c sigh "\"Looking after? What the hell do you think we were doing together?\""
    a 1 c smile "\"You were being a bother of course.\""
    mc 1 c sigh2 "\"You little-{nw}"
    s 1 c happy "\"Haha, have a good night too, Aki-kun. I'll talk to you later.\""
    show s 1 c at offscreenleft with moveoledis
    show al 1 u at two
    show k 1 c worried at fdis, six
    show a 1 c smile at nine
    with move
    play sound "music/door.ogg"
    "Shoichi out towards the entrance and before I know it, I hear the key turning and the door being opened and closed behind him."
    "He... wasted not time at all leaving."
    "Actually... he didn't even say bye to me..."
    k 1 c considerate "\"We should actually be on our way too.\""
    mc 1 c wince "\"Already?\""
    k 1 c wry "\"Yes, well, ideally I'd have liked to spend more time together but I can't get home too late and I did spend two hours waiting for you to arrive. I just wanted to make sure you were alright.\""
    k 2 c sigh "\"... To be perfectly honest, I was about to call a few of our family's workers to form a search party.\""
    mc 1 c sigh "\"I was out for two hours, you're being ridiculous.\""
    k 1 c worried "\"I guess. I just didn't know you had a habit of staying out so late.\""
    a 1 c "\"He doesn't actually. I was pretty surprised too. Usually he at least calls beforehand... or answers his phone.\""
    mc 1 c worried "\"Wait... answer my phone?\""
    k 2 c sigh "\"Right. I tried calling you before coming over but there was no answer. I tried some more along with Aki-kun after I arrived and while we were waiting but all calls went straight to voicemail...\""
    mc 1 c shock "\"I...\""
    "I reach for my phone in my pocket, pressing the power button to light up the screen."
    mc 1 c sigh3 "\"... Right. Shoichi made me turn it off while we were studying so I wouldn't get distracted. I'm not used to turning it off so I forgot it completely.\""
    k 2 c annoyed "\"Oh. I suppose that makes sense. I should have thought of that.\""
    mc 1 c sigh3 "\"Yeah. Shoichi is a special kind of annoying when it comes to studying. Full of all these little rules and regulations.\""
    a 1 c sigh "\"Turning your phone off when you study is super basic, what are you talking about?\""
    mc 1 c sigh "\"Shh. Nobody asked you, Wonder Boy.\""
    a "\"Wonder Boy? Do I even want to ask?\""
    mc 1 c smile "\"It's because you always think you're {i}soooooo{/i} wonderful.\""
    a 1 c sigh2 "\"... So that's a no.\""
    show a 1 c at fdis
    k 1 c wry "\"Anyway, I should really be on my way. I'll talk to you later, [povFirstName].\""
    mc 1 c considerate "\"Right. Sorry you came all this way for nothing.\""
    k 1 c smile "\"Nah, nothing to be sorry for.\""
    show k 2 c gentle at fdis, five:
        ease .2 zoom 1.5 xoffset -30 yoffset 200
    k "\"{size=-6}I got to see you so it wasn't a wasted trip.{/size}\""
    "Keisuke gives me a quick, gentle squeeze on the shoulder as he passed me by on the way to the door, immediately making my ears twitch and my face grow hot."
    mc 1 c flustered "\"R-right.\""
    show k 1 c smile at fdis:
        ease .2 zoom 1.0 xoffset 0 yoffset 0
    k "\"The door's already open so we'll just see ourselves out. Have a goodnight.\""
    al "\"Thank you for kindly receiving us.\""
    "Alex bows to the two of us."
    a 1 c smile "\"Sure. Good night guys.\""
    show k 1 c smile at offscreenleft
    show al 1 u at offscreenleft
    with moveoledis
    play sound "music/door.ogg"
    show a 1 c at fdis, fiveh with move
    "I quickly follow behind the two, locking the door after saying our farewells."
    "When I get back to the living room, I see Aki has hopped to the bigger couch, flipping the pages of some book I don't recognize."
    mc 1 c sigh3 "\"You know, I get that you like to tease me but we really need to have boundaries about the things you tell others.\""
    a "\"What do you mean?\""
    mc 1 c sigh "\"I mean that you didn't have to tell anyone that I was feeling \"inspired\" by Kei-kun.\""
    a 1 c sigh "\"Why are you doing air quotes with your fingers, you literally said you were trying to be more like him.\""
    mc 1 c sigh "\"They didn't have to know that!\""
    a 1 c "\"This kind of friendship where you hide everything from everyone really doesn't make any sense to me. So what if they know that? It's not a big deal.\""
    mc 1 c sigh "\"You're saying that {i}now{/i} but the only reason you told them was because you knew it'd embarrass me.\""
    a 1 c "\"Just because I knew you'd make a big deal out of it doesn't mean I agree that it is a big deal.\""
    "He goes back to flipping the pages of his book, not even looking at me anymore."
    a "\"You need to be a little more honest with your friends. You bottle things up too much.\""
    mc 1 c sigh "\"I'm not taking relationship advice from a twelve-year old.\""
    a 1 c sigh "\"Fine. Feel free to keep floundering about and feeling awkward about everything.\""
    mc 1 c sigh3 "\"Floundering? Where did you even learn that word? It's a bit too advanced for someone your age.\""
    a 1 c "\"I like to read.\""
    mc 1 c "\"... What {i}are{/i} you reading anyway?\""
    "I circle around the couch, sitting down next to Aki and peering at his book."
    "He closes it, giving me a glimpse of the cover."
    a 1 c "\"It's a simplified version of Macbeth. My world literature teacher assigned this to us.\""
    mc 1 c fsmile "\"Shakespeare? That definitely is way too advanced for your grade.\""
    a 1 c sigh2 "\"It's fine. This one is actually really dumbed down and I have a hard time enjoying it cause all the characters act like what a man in his forties thinks modern kids talk like.\""
    mc 1 c talk "\"Yikes. That doesn't sound good.\""
    a 1 c worried2 "\"Yeah. Reading a character talk in modern slang inside a period novel really isn't fun. Kinda kills the immersion really.\""
    mc 1 c considerate "\"Sorry you have to go through that then.\""
    a 1 c "\"I'll be fine. I'm almost done with it. At least writing the report on the book will be really easy.\""
    mc 1 c "\"Book reports are the most tedious things to work on though.\""
    a 1 c "\"I can think of worse stuff. I can just regurgitate what I remember of it on the paper and I'll be sure to do well.\""
    "That's... a somewhat gross way of putting but I guess it works."
    mc 1 c sigh3 "\"Just make sure you don't stay up too late. I'm heading to bed.\""
    a 1 c smile "\"Don't worry. I'll just finish this chapter and I'll go to sleep. Have a good night.\""
    mc 1 c talk "\"You too.\""
    stop music2 fadeout 2.5
    stop music fadeout 2.5
    scene BedroomN
    show Lights
    with fade
    "Immediately as I get to my bedroom, I shut the door behind me, turn off the lights and plop myself down on my bed."
    "I feel so mentally exhausted after hours of Shoichi drilling philosophy and the likes into my head that I barely have the energy to take off my clothes before sleep."
    play sound "music/fabric.ogg"
    "A couple of seconds later and without getting up from the bed, I dress myself down to my underwear and go under the covers."
    mc 1 n sigh3 "\"... My head hurts.\""
    "I'm pretty sure I just might dream of Plato tonight."
    "... And that is so clearly not a good thing."
    jump Day24_Keisuke
