label noroute:
    scene Black with fade
    "Before I even realized how much time had passed, the day of graduation had finally arrived."
    "Despite my best efforts, I was again unable to win in the All-Japan Junior tournament..."
    "Still, despite these setbacks, I decide to go forward with my professional life."
    "Two weeks after graduating, I announced my debut into the world of professional tennis."
    "One week after that, I was flying to the U.S. where I'd be living from now on."
    "My new base of operation..."
    "As for the others... well..."
    "Jun managed to graduate too despite an alarming number of absences."
    "He managed to get accepted at the music school he'd wanted to go to in Germany. He and I still talk every now and then. He seems to be very happy whilst studying to become a game composer."
    "Shoichi also graduated, with honors I might add, and got accepted into a prestigious college in Tokyo. Because of our busy schedules, we don't have as much time to talk as we'd like but we're still close."
    "Saya came with me to the U.S. and we share a flat together. She's a bit difficult to live with but I can't say I'd rather have someone else here with me."
    "Keisuke is now the captain of the tennis club at my old school. His father made him agree to quit tennis and inherit the company if he did not win at the All-Japan Junior... I'm not quite hopeful about his odds."
    "Aki has been working even harder now that I'm gone. He's decided that he'd take care of our mom at the same time as he goes to school. Bless his heart, he's still as naive as always."
    "I guess you could say my dreams have finally come true... oddly enough, it feels emptier than I imagined."
    "Don't get me wrong, I love the fact that I made it... but at the same time, I guess I expected more."
    "No, it's not even that. I can't really complain about the place that I've gotten to. I like it here and I'm doing good progress..."
    "The problem is that I still have regrets..."
    "In the end, I think what I regret most was not properly enjoying the last year of my student life..."
    "Perhaps if I'd been more decisive about what it was that I wanted things could have turned out differently."
    "... But then again, indecision has always been one of my traits."
    "Oh well, I guess there's not much point in lamenting what could have been."
    "From now on, I'm in charge of my own future so I have to start walking with my own two feet."
    "There's no room for mistakes now!"
return