label SchoolFestival:
    window hide
    scene May29 with fade
    play sound "music/windchimes.ogg"
    show blossoms movie
    $ renpy.pause(5.5)
    scene Black with fade
    window show
    if schoolfestival == "shoichi":
        $ date = "day19"
    elif schoolfestival == "keisuke":
        $ date = "day18"
    elif schoolfestival == "jun":
        $ date = "day17"
    play sound "music/tickingclock.ogg"
    "..."
    "Somehow, I'm faintly aware of the fact that I'm already half awake."
    "My eyelids feel so incredibly heavy that the idea of opening them starts to feel like wishful thinking."
    "No, more importantly than that... I just don't want to."
    "My bed is so nice and comfortable and warm..."
    "For some reason, I feel like I've gone through seven rounds of wrestling with a truck."
    "... Well, hyperbole aside, I do feel kinda sore."
    "I haven't been sleeping very well lately and feel tired all the time."
    "Although this is already more or less old news to me (thank you, insomnia), last night was many times worse."
    if schoolfestival == "shoichi":
        "The reason was painfully obvious to me."
        play sound "music/flashback.ogg"
        show StadiumCloset behind s
        show s 1 v cry at fdis, five
        with flash
        s "\"[povPetName]... I... I really wanted to win...\""
        "Shoichi had been training and looking forward to that competition for months."
        "Even if he always tried to hide his excitement when asked, I knew better than anyone else how important it was to him."
        "And up to the time I fell asleep, he still hadn't answered any of my messages."
        "I don't want to see him looking like that anymore..."
        hide StadiumCloset
        hide s 1 v cry
        with flash
    elif schoolfestival == "keisuke":
        "I'm not... quite sure why."
        "Lately I've had so many strange thoughts coming over me."
        show k 2 c gentleb at fdis, five with dissolve
        "Most of them... are about Kei-kun."
        "I don't know why but the more time I spend with him, the more time I want to spend with him."
        play sound "music/flashback.ogg"
        show TennisFence behind k
        show k 1 u angry at fdis, five
        with flash
        k "\"I don't need your help!\""
        "Even though he's stubborn to a fault..."
        play sound "music/flashback.ogg"
        show KeiRoom behind k
        show k 1 u worried at fdis, five
        with flash
        k "\"I'm always worried that somewhere, deep down, you actually disliked me...\""
        "Even though he's hardly ever honest about how he really feels."
        play sound "music/flashback.ogg"
        show SRooftop behind k
        show k 1 u sad at fdis, five
        with flash
        k "\"I don't know the first thing about you guys. I'm just so... so self-absorbed...\""
        "... Even though he's surprisingly flawed and vulnerable."
        play sound "music/flashback.ogg"
        hide SRooftop
        hide KeiRoom
        hide TennisFence
        show k 1 u smile at fdis
        with flash
        "I've seen so many sides to Kei-kun, both old and new."
        "Lately, whenever I find myself distracted, I think about it."
        "I can't help but want to see more."
        "Even when I go to bed and am just trying to sleep, I think about it."
        "{cps=*0.5}Maybe I'm...{/cps}"
    elif schoolfestival == "jun":
        "I'm not... quite sure why."
        "Lately I've had so many strange thoughts coming over me."
        show j 1 c happy at fdis, fiveh with dissolve
        "I guess... if I had to try and come up with a reason, it'd be because I'm troubled over my thoughts about Jun."
        "Ever since he first arrived, he's been kind of like a typhoon in my life."
        "Constantly flipping everything on its head, it's scary when I think just how much I've come to love his presence in my daily life."
        "Just trying to think of how things would have been if he weren't here makes my chest hurt..."
        play sound "music/flashback.ogg"
        show MusicRoom behind j
        show j 1 u cshock at fdis, fiveh
        with flash
        j 1 u cshock "\"{cps=60}Because I got here too late, classes had already started and the gates were closed, so I was locked outside.{/cps}{nw}\""
        j "\"{cps=80}I had to stick around until they were open again this afternoon so I could get inside and talk to a teacher.{/cps}{nw}\""
        j 1 u cshockb "\"{cps=90}But she refused to show me around school. I ended up trying to find my class on my own and got lost. And then-{/cps}{nw}\""
        mc 1 t wince "\"Ah, I get it I get it, slow down!\""
        "He's clumsy and silly and always kind of on edge. Saying he's not good with people would be a huge understatement."
        play sound "music/flashback.ogg"
        show HospitalRoom behind j
        show j 1 c considerate at fdis, fiveh
        with flash
        j "\"I tripped on my shoe laces when I was getting up and ended up hitting me head on the piano. Next thing I know, I'm in the hospital.\""
        "... And at this point, I already know for a fact that he's hiding something about his health... something possibly serious."
        "He's not very honest about it..."
        "But..."
        play sound "music/flashback.ogg"
        show SRooftop behind j
        show j 1 u happy at fdis, fiveh
        with flash
        j 1 u happy "\"I believe that the reason we can feel so awful about the things we do is {i}because{/i} we love what we do. We love it so much that we want to devote everything we have to it, and that makes us worry when we feel like we're not making progress.\""
        j 1 u happyb "\"Those feelings of helplessness are awful, but, in a way, I feel like they are also wonderful. Because to me they are the proof that I really love the piano more than anything else!\""
        "He's got such a good heart."
        "Even if he's a giant doofus and always looks like he's just no good at most things, he's gentler than anyone I've ever met."
        "And somehow, I find myself wanting to protect that gentle heart of his."
        "Because every time I see him smile like that, I feel... happy."
        "It's gotten to a point that he's in my mind even when we're not together."
        "It's making me feel restless and confused and..."
        "... And I don't know what's happening to me..."
    play sound "music/knock.ogg"
    "I hear the sound of knocking, suddenly dragging my attention away from my own thoughts."
    play sound "music/door2.ogg"
    scene Bedroom
    show a 1 u at fdis, five
    with fade
    "When I open my eyes I see Aki at the door."
    "I lazily prop myself up on my elbows, looking at my brother while blinking groggily."
    mc 1 b "\"Good morning...\""
    a "\"Wow, were you actually awake before I knocked on the door?\""
    mc 1 b avoid "\"Somewhat. In the process at least.\""
    a "\"And here I thought I'd need the bucket.\""
    mc 1 b sigh2 "\"You throw water at me and you die.\""
    a 1 u smile "\"Oh no, not water. Just the bucket.\""
    mc 1 b sigh "\"... You want to throw a bucket on me?\""
    a "\"To wake you up, yeah. That way I won't damage the bed.\""
    mc 1 b sigh "\"Buckets are heavy, you'd break my nose!\""
    a 1 u happy "\"Don't be so melodramatic. Either way, you should get up already. Today's your school festival.\""
    mc 1 b sigh2 "\"As if I'd forget something that important.\""
    if schoolfestival == "jun":
        a 1 u "\"{size=-4}You've already forgotten something else important this weekend.{/size}\""
        mc 1 b "\"Did you say something?\""
        a 1 u sigh "\"Nah. Just get out of bed already before I get the bucket.\""
        mc 1 b sigh2 "\"I'm coming, I'm coming. Jeez, at least give me a minute...\""
    play music2 "music/BGM/On My Way.ogg" fadein 5.0
    scene LivingRoom
    show a 1 u at fdis, five
    with fade
    "By the time I finally go downstairs, I am no more awake than I was minutes ago."
    "Even after showering, drying all my fur, brushing my teeth, etc."
    "I still feel like just crawling back onto my bed and sleeping through Summer."
    "... The season hasn't even started yet and I already hate it."
    mc 1 u sigh3 "\"Aki, is the AC on at all? I'm melting.\""
    a "\"It's only a bit warmer than the previous days, it's not that bad.\""
    mc 1 u sigh3 "\"No, it's definitely bad...\""
    a "\"What day did the weather report say would be the official start of summer? The fifth?\""
    mc 1 u sigh "\"Who cares? I just know that it's really hot.\""
    "Aki shrugs, packing what looks to be a filled lunch box into his bag."
    mc 1 u "\"By the way, do you plan on coming by the festival after school?\""
    "He pauses, musing the question for a few seconds with an overly dramatic look on his face that just screams \"I'm thinking\"."
    a "\"I'm not sure. I don't really want to miss much practice.\""
    mc 1 u considerate "\"The festival only lasts four days. And you didn't go a single day last year.\""
    a 1 u sigh "\"There's not much of interest to me in the first place.\""
    mc 1 u sigh "\"Hey, a lot of people worked really hard to make it happen, you know.\""
    a 1 u smile "\"Yeah, and if any of those people were here I'd apologize for being insensitive, but since none of them are, I'll just finish packing for school.\""
    mc 1 u sigh2 "\"{size=-4}Little brat...{/size}\""
    show a 1 u at fdis
    "Aki rolls his eyes at the sight of my unhappy grumbling."
    "I swear, he used to be so cute..."
    a "\"By the way, Shoichi-nii told me your class is doing a Chinese diner. Do you plan on sticking around to help any this year?\""
    mc 1 u smile "\"Nope. You already know how I roll. I like to enj-\""
    a "\"Yeah, you like to be lazy, I know.\""
    play sound "music/stab.ogg"
    mc 1 u wince "\"Wha...\"" with hpunch
    "That's just plain rude."
    a 1 u worried2 "\"Try to check up on Shoichi-nii if you can, okay?\""
    if schoolfestival == "shoichi":
        mc 1 u worried "\"I don't need you to tell me that. That's already in my list of priorities...\""
        a 1 u smile "\"I didn't even know you had one of those. Or is priority number one to \"make a list of priorities\"?\""
        mc 1 u sigh "\"You're really asking to be slapped at this point.\""
        "Aki cheekily shows me his tongue, closing his school bag and propping it behind his back."
        a "\"I'm gonna get going now. You should try not to be late either. Tell Shoichi-nii I said hi and have fun.\""
        show a 1 u smile at offscreenright with moveoridis
        play sound "music/slidingdoor.ogg"
        "The sound of the door closing echoes down the hall."
        mc 1 u sigh3 "\"...\""
    elif schoolfestival == "keisuke":
        mc 1 u wince "\"I know that already.\""
        "Shoichi's team participated in the Interhigh's national qualifiers over the weekends."
        "While they didn't do badly, reaching the finals with ease..."
        "They got crushed by the opposing team there."
        "It always felt like no matter how hard they tried, the gap between those two teams kept widening every year."
        "This time it was plainly obvious. Barely able to score, their defense was just blasted away by the other team."
        "In the end, they lost in straight sets. Not once did they go over fifteen points in a set."
        "It felt like they were just missing more offensive potential..."
        a "\"Come on, don't look like that. Shoichi-nii's already going to be really upset, we don't need you down in the dumps too.\""
        mc 1 u considerate "\"Ahahaha, I guess you're right...\""
        a 1 u "\"Oh, and by the way, tell Keisuke-san he took my earbuds by accident the last time he was here please.\""
        mc 1 u curious "\"Wait, Kei-kun did?\""
        "Aki nods, closing his bag and holding it behind his shoulder."
        a 1 u sigh2 "\"Yeah, I think he just put it in his bag and forgot about it. Either way, I went looking for it yesterday and didn't find it.\""
        mc 1 u "\"Are you sure you didn't just lose it.\""
        a 1 u "\"Positive. Anyway, I'm leaving now. Have fun at the festival!\""
        show a 1 u at offscreenright with moveoridis
        play sound "music/slidingdoor.ogg"
        "The sound of the door closing echoes down the hall."
        mc 1 u talk "\"I should probably message Kei-kun about it before I forget...\""
    elif schoolfestival == "jun":
        mc 1 u confused "\"Check up on Shoichi? Why?\""
        "Aki's shoulders slump and he facepalms, looking astonished."
        a 1 u sigh2 "\"Come on, I already knew you forgot over the weekend but you can't be this clueless can you?\""
        mc 1 u think "\"I... don't know what you mean.\""
        a 1 u worried "\"Shoichi-nii's competition was this weekend. You're the only one who didn't show up.\""
        stop music2
        mc 1 u "\"...\""
        a "\"...\""
        play music3 "music/BGM/Punchline - Org.ogg" fadein 5.0
        mc 1 u dismay "\"{size=+4}Huuuuuuuuh?!{/size}\"" with hpunch
        a 1 u sigh2 "\"Now you remember...\""
        "Aki rubs his forehead, sighing."
        "He looks so disappointed that it hurts."
        mc 1 u dismay "\"N-n-n-no way. I-I can't have forgotten about that.\""
        a "\"You did. Even Jun-san showed up on Saturday although he said he was busy on Sunday and couldn't come. I didn't give you much flak over it cause I found out when you guys got home that he had a competition too.\""
        a 1 u "\"Still, you could have at least showed up on Saturday if you weren't gonna be there Sunday.\""
        mc 1 u wince "\"W-why didn't you tell me on Saturday?! If you'd reminded me I would have showed.\""
        a 1 u annoyed "\"What am I, your personal calendar? You're almost an adult, you should learn to handle your obligations by yourself.\""
        mc 1 u pout "\"But this was important, you should have reminded me!\""
        a 1 u "\"You woke up really late. I thought you'd head over there right after that so I went first. Then when you didn't show up... well, there wasn't much I could have done.\""
        mc 1 u worried "\"What about calling me? I have a phone, you know.\""
        "Aki shrugged, closing his bag and putting it over his shoulder."
        a "\"It's not like you ever have your phone anyway. Besides, are you really gonna keep trying to pin the responsibility on me?\""
        mc 1 u sigh3 "\"I can't believe no one called me...\""
        a 1 u sigh "\"I can't believe you didn't show. See, we can go on circles like this all day.\""
        stop music3 fadeout 2.5
        play music2 "music/BGM/On My Way.ogg" fadein 5.0
        mc 1 u worried "\"Is Shoichi really mad?\""
        a 1 u worried "\"He was... disappointed. Although right now I guess he's just depressed. They lost pretty handily at the finals.\""
        mc 1 u worried "\"I'll try talking to him once I get to school.\""
        a 1 u wry "\"Thanks. Oh, and tell Jun-san I said hi.\""
        mc 1 u "\"Why Jun in specific?\""
        "He shrugged again, stopping by the hallway leading to the front door."
        a 1 u "\"I dunno. You two are together often and are really close. I thought it'd be appropriate. Anyway, see ya.\""
        show a 1 u at offscreenright with moveoridis
        play sound "music/slidingdoor.ogg"
        "The sound of the door closing echoes down the hall."
        mc 1 u talk "\"Talk to Jun, huh...\""
        "Come to think of it, didn't Aki say something about thinking the two of us were a couple yesterday?"
        "..."
        "Ugh, thinking about this just makes my head hurt."
    mom 1 s smile "\"Ah, [povFirstName]. Good morning.\""
    "I hear a familiar voice calling out to me from the stairs."
    show mom 1 s smile at fdis, five with dissolve
    "When I turn to look, I see my mom dressed in her usual work attire, fiddling with her bag by the stairs."
    mc 1 u "\"That's new. You're usually long gone by the time I wake up.\""
    mom "\"My hours got changed a little bit. We got a few new hires in the office so I don't need to be pulling overtime every day.\""
    mc 1 u considerate "\"Knowing you, you're probably super bitter about it.\""
    "Mom puckers her lips with a \"hmph\", her brow furrowing deeply."
    mom "\"So what if I like my work? It's much better than staying at home and being bored.\""
    mc 1 u "\"Thanks, Mom. I love you too.\""
    mom "\"You know that's not what I meant. My God, where did I put my keys?\""
    mc 1 u considerate "\"You mean the ones right here on top of the kitchen island?\""
    "I grab at a pair of keys I noticed as soon as I walked downstairs, spinning them around on my thumb for effect."
    mom "\"Oh, that's right. I left them there after I had dinner, I forgot.\""
    mc 1 u "\"What did you think of it by the way? It wasn't much but I tried to change the spice mix I usually use a little.\""
    mom "\"It tasted a little milder than usual, but, as always, it was delicious.\""
    mc 1 u smile "\"Heh. Thanks.{nw}"
    show mc 1 u at offscreenleft
    extend " Will you drop by the school festival for a bit this week? You do have free time apparently.\""
    mom "\"I'll try but I might just end up working on some stuff once I get home.\""
    play sound "music/disappointment.ogg"
    "Seriously, you're too much of a workaholic. It's okay to relax every now and again you know."
    mom "\"By the way, have you wished your father a good day yet?\""
    stop music2 fadeout 2.5
    "As soon as she says those words, I freeze."
    mc 1 u worried "\"Mom...\""
    "She slowly shakes her head sideways, sighing."
    mom "\"You kids never pay him any attention. He's going to get really lonely you know...\""
    "She walks up to a small wooden shrine we have in the corner of the living room."
    "Aki and I keep the door to it closed all the time because we just... don't like looking at it."
    "Because of it, hardly anyone who comes here ever notices. Half the time, even I forget that it's there."
    "Mom delicately opens the doors, revealing a few small pottery ornaments, an incense burner and, right at the center of the whole thing, a single framed picture of my dad."
    "Because dad was never much one for pictures, the only good picture Mom could find of him was from back when he was in high school too."
    "It just... creeps me out to see him looking so young."
    mom "\"You know, your father probably misses you boys very much. It wouldn't kill you to pay your respects every now and again.\""
    "Reaching inside her handbag, she grabs a lighter and uses it to light a stick of incense, placing it inside the burner."
    "She kneels in front of the shrine, putting both of her hands together in prayer."
    "I watch the whole thing from the corner of my eye, my throat suddenly feeling like it has something stuck in it."
    "No matter how much I try, I just can't bring myself to watch it."
    "To me, it just feels wrong."
    "Like clinging to a past that won't ever come back instead of moving forward."
    "I'm sure it must be even weirder for Aki. He never even got to meet the man after all."
    mom "\"{size=-4}Have a good day, Ken.{/size}\""
    "Still, as far as I know, she follows this same routine every day."
    "Before leaving the house and before going to bed. Day by day, always doing the same."
    "My mind refuses to accept such a routine. I feel like if I were to start doing something like that, I'd just remain stuck in place."
    "Mom gets up, fixing the hem of her skirt and walking to the door."
    mom "\"I'll try to be home when you boys get back. If I can, I'll make dinner too. I can't have you doing everything around the house all the time.\""
    mc 1 u considerate "\"It's alright, you don't have to worry about that. You work really hard after all.\""
    "She smiles, walking up to me and cupping my cheek with her left hand."
    mom "\"You're really sweet, [povFirstName], but I'm your mother. I'm the one who's supposed to be taking care of you, not the other way around.\""
    mc 1 u avoidb "\"S-sheesh, you don't have to fuss over every little thing.\""
    mom "\"I love you too. Have a good day with the festival, okay? Oh, and if you see Shoichi-kun and Hitoka-chan, tell them I said hi.\""
    mc 1 u considerate "\"Will do.\""
    play sound "music/slidingdoor.ogg"
    show mom 1 s smile at offscreenright with moveoridis
    "..."
    "I walk up to the shrine Mom was praying to, making sure to put out the incense so it doesn't burn anything."
    mc 1 u avoid "\"... You're not really here are you, old man?\""
    "As is to be expected, the picture cannot respond."
    "Sighing, I close the door again, shutting it back inside."
    play music2 "music/BGM/Hanging Out.ogg" fadein 5.0
    scene SGate with fade
    play music "music/crowd01.ogg" fadein 5.0
    "Just getting near to the school gates, I can already hear a lot of activity in the area."
    "Lots of students arrived early in the morning to finish setting things up so all would be ready before the official start time."
    "Which of course just makes it so they create an \"unofficial\" start time."
    "I wasn't all that interested in waking up early so I decided to come a little bit later in the morning."
    "By getting there later in the day, there is more movement going around and more events have been prepared."
    "Lots of different booths have been set-up across the school grounds. Some of them are just games, others try to show part of our school curriculum in a way that might attract attention."
    "Science experiments, diagrams, there are all kinds of set-ups fighting for attention."
    "But the most popular end up being the foods. The smell of all kinds of foods wafts around the campus grounds and tons of people gravitate around those stands."
    "I have to admit, part of me is really interested in going around sampling the foods right away but I know I should probably hold on for a while."
    "But I know the first day is the best time to go sampling around the different displays, trying to see everything they have to offer."
    "The reason for that is quite simple. In our school, the first day of the cultural festival is always closed for students and staff only."
    "That gives students the chance to do a little test run before opening to the public, as well as just giving people some time to prepare for the larger influx that would soon follow."
    "It's also the only reason why people who would usually be very busy can find themselves free."
    "Like..."
    show s 1 u smile at fdis, five with dissolve
    if schoolfestival != "shoichi":
        $ [povPetName] = [povFirstName]
    s "\"Hey, [povPetName], good morning!\""
    mc 1 u smile "\"Hey there. Looks like I'm not the only one sauntering around the school grounds early in the morning.\""
    s 1 u "\"Sauntering? Did you fall asleep on top of a dictionary or something?\""
    mc 1 u sigh "\"Are you going to get on my case just because I used an unusual word?\""
    s 1 u smile "\"Hmm... I'm considering it.\""
    mc 1 u "\"Did you run into anyone else yet?\""
    s "\"Last I checked, Urushihara was trying to organize his class' haunted house. I ran into Saya-chan a bit earlier but we just greeted each other in passing. She seemed a bit busy.\""
    mc 1 u wince "\"Oh no. Do you think our plans to walk around the festival together as a group won't pan out?\""
    s 1 u think "\"I think it's a bit too early to tell. It's not even 9AM yet.\""
    mc 1 u wince "\"Fair enough, I guess.\""
    show s 1 u at fdis
    mc 1 u worried "\"...\""
    s "\"...\""
    mc 1 u wince "\"...\""
    s "\"Is something the matter?\""
    mc 1 u shock "\"O-oh. N-no, everything's fine.\""
    s "\"You sure? You don't seem fine.\""
    "..."
    "I eye Shoichi up and down, trying to get a feel for how he's feeling right now."
    "Even though I expected him to be super down, he's acting incredibly normal."
    "He's so casual right now that it's actually scaring me a little."
    mc 1 u worried "\"Uhm... Shoichi... are you okay?\""
    s 1 u think "\"Huh? Why wouldn't I be?\""
    mc 1 u worried "\"I mean... t-there was the competition yesterday and all...\""
    if schoolfestival == "jun":
        s 1 u "\"You mean the one you missed?\""
        play sound "music/stab.ogg"
        "Guh..." with hpunch
        "Shoichi's words dig straight to the point, not wasting any breath with idle chatter."
        mc 1 u worried "\"I'm... sorry I... I shouldn't have forgotten.\""
        s 1 u smile "\"It's fine. You worry too much.\""
        mc 1 u worried "\"Y-you're not mad?\""
        s 1 u think "\"Hmmm... how should I put it... I guess I was a little bit... surprised, I guess? You've showed up to all my competitions since we first became friends so it caught me a bit by surprise.\""
        s 1 u smile "\"But then again, you've always been an airhead so something like this was bound to happen.\""
        mc 1 u wince "\"H-hey. I am not an airhead!\""
        s 1 u "\"Oh? So should I assume the alternative of you just not caring and skipping because you couldn't be bothered?\""
        mc 1 u worried "\"... Okay, I'm an airhead.\""
        s 1 u smile "\"Hehe.\""
        mc 1 u worried "\"Are... are you sure you're okay?\""
        s "\"Yeah, I'm fine.{nw}"
        show s 1 u think at fdis
        extend " I mean, losing is definitely a chore but it isn't that big of a deal. It's just a high school club.\""
        "..."
        "Hearing those words just grosses me out in all sorts of ways."
        "I... I don't like it. I don't like it at all."
        s 1 u "\"You don't look really happy to hear it.\""
        mc 1 u considerate "\"N-no, I'm fine. I'm totally fine.\""
        "... The last thing I need right now is for you to be worrying about me."
        s 1 u smile "\"By the way, how was it? Jun's competition that is.\""
        mc 1 u shock "\"Wait, what? You knew about it?!\""
        s 1 u considerate "\"Not at first. Aki messaged me last night to tell me why you didn't show up. At least as far as Sunday is concerned.\""
        s 1 u smile "\"He was super worried about smoothing things over for you. It was kinda cute.\""
        "You really do some unnecessary things sometimes, Aki..."
        mc 1 u considerate "\"It was... good. Jun got first place, it was great to watch...\""
        s 1 u "\"Really? You don't sound too happy.\""
        mc 1 u worried "\"Sorry, I kinda have a lot on my mind...\""
        s 1 u smile "\"That's fine. By the way, if you head over to your classroom, tell Jun I congratulated him on his victory, okay?\""
        mc 1 u considerate "\"Will do.\""
        "Why do I get the feeling I'm being turned into some kind of errand boy?"
    elif schoolfestival == "keisuke":
        s 1 u "\"Yeah, there was. What about it?\""
        mc 1 u wince "\"I'm just... I don't know, a bit worried about you? You acted like it was no big deal yesterday and you continue to act like you don't even care.\""
        s 1 u smile "\"That's because it isn't a big deal. It's just a high school club. This is hardly the kind of thing I'll carry for the rest of my life.\""
        mc 1 u worried "\"But... aren't you upset you won't get to play with your team anymore?\""
        s 1 u "\"Well, sure, that {i}is{/i} kinda crappy but it's not really something to be down in the dumps about. It just is.\""
        mc 1 u talk "\"Man, you're really nonchalant over this whole thing.\""
        s 1 u sigh "\"Of course I am. The only thing that really annoys me is everyone assuming I {i}must{/i} be absolutely heartbroken over it. It's just a minor frustration, people really need to chill.\""
        mc 1 u confused "\"Everyone?\""
        s 1 u "\"Yeah. Both Urushihara and Saya-chan stopped me when we ran into each other today to ask if I was okay, yada yada yada. I'm pretty sure Jun will do the same too.\""
        mc 1 u considerate "\"Ahh... I didn't know that. Sorry.\""
        s 1 u smile "\"It's fine by me. It just means I have good friends.{nw}"
        show s 1 u think at fdis
        extend " Even if they're a little annoying sometimes.\""
        show s 1 u smile at fdis
        mc 1 u worried "\"So... you really are okay?\""
        s "\"I really am okay.\""
        mc 1 u "\"You promise?\""
        s 1 u considerate "\"Now I have to promise? Jeez, you really are insistent.{nw}"
        show s 1 u smile at fdis
        extend " I promise I'm okay.\""
        mc 1 u worried "\"... Alright.\""
        s 1 u happy "\"You should probably get going now though. I still have some loose ends I have to tie up before I'm free for the day. Hopefully no one has to cancel.\""
        mc 1 u smile "\"Alright. I'll see you later, Shoichi.\""
        s 1 u smile "\"You bet.\""
    elif schoolfestival == "shoichi":
        s 1 u "\"Yeah, there was. What about it?\""
        "His neutral, composed reaction is such a far cry from what I saw yesterday that I choke for a second trying to come up with a response."
        mc 1 u wince "\"You're... you're acting so nonchalant about it.\""
        s "\"I guess?\""
        "..."
        mc 1 u worried "\"Okay, Shoichi, I know you might think acting like nothing's wrong will keep me from worrying but it's just making me worry even more.\""
        s 1 u considerate "\"Don't be like that. I'm fine. I've... had some time to process.\""
        mc 1 u "\"Really? Cause your voice doesn't make it sound like you're fine.\""
        "One thing I've learned about Shoichi over the years is that whenever he's very upset, his voice tends to get really quiet and soft."
        "It doesn't happen very often. To date I can count how many times I've seen it on my fingers."
        "The last one I remember was when the news of his parents divorcing first came out."
        "Even though he was all smiles and acting like nothing was wrong, he was still very quiet and meek."
        "You might have become very good at shouldering your burdens over the years but even you can't act totally fine when something this huge happens."
        s 1 u worried "\"Come on, [povPetName], it's not a big deal.\""
        mc 1 u worried "\"... Look, I'll give you a pass because we're out in the open but once the two of us are alone I want to talk about this.\""
        s 1 u considerate "\"There's nothing to talk ab-\""
        mc 1 u "\"We'll talk and that's that.\""
        s 1 u worried "\"Man, you can be really pushy sometimes.\""
        mc 1 u considerate "\"Only because I care.\""
        s 1 u wry "\"Heh, I guess. Anyway, I should probably get going. There are still some things I need to do before I can really consider myself free.\""
        mc 1 u smile "\"Alright. I'll see you later, Shoichi.\""
        s 1 u smile "\"You bet.\""
    scene SCorridor with fade
    "Even inside the school hallways, the whole place is packed with students running down the halls in a rush."
    "It's kinda funny. I'm almost 100\% sure none of these people would be in such a rush if they were trying to get to something like a class they're late for."
    "Priorities, I guess?"
    show k 1 u at fdis, five with dissolve
    "As I'm going up the stairs to my floor, I see Kei-kun about to head downstairs."
    k 1 u smile "\"Ah, [povFirstName]-san, good morning.\""
    mc 1 u smile "\"Good morning.\""
    "He promptly greets me with a smile, stopping right in front of the staircase."
    "I finish climbing the last few steps so I can be level with him."
    k "\"Are you just arriving? I thought you would have gotten here earlier so you could spend as much time checking out the festival as possible.\""
    mc 1 u smile "\"Pfft, and miss the chance to sleep in? No way.\""
    k 2 u gentle "\"Haha. Fair enough.{nw}"
    show k 1 u smile at fdis
    extend " My class is kinda rushing trying to get everything set up properly. We found out that there's still too much light creeping in through the windows so they're trying to tape them off.\""
    mc 1 u "\"Isn't that going to be a huge hassle to remove later?\""
    k 1 u considerate "\"Probably? I'm trying not to think about it. The whole thing is already a chore to work on as is.\""
    mc 1 u "\"My condolences. By the way, are you still going to have free time later today for us all to get together?\""
    k 1 u smile "\"For sure. I told them I'd be ducking out today already. I already have people to cover for me.\""
    k 2 u think "\"The whole class is already much more excited about the concept of our venue than I am so there is no lack of volunteers.\""
    show k 1 u at fdis
    mc 1 u talk "\"People actually want to be working during the festival? That's kinda sad.\""
    k 1 u smile "\"I'm pretty sure the opposite of \"person that refuses to work and just gives more work to others\" is much, much sadder.\""
    mc 1 u considerate "\"Not at all subtle there.\""
    k "\"I wasn't trying to be.\""
    if schoolfestival == "keisuke":
        k 2 u gentle "\"By the way, [povFirstName], if you don't mind, let's hang out together during the festival once we both have free time.\""
        mc 1 u smile "\"Sure. I'd appreciate that.\""
        show k 1 u smile at fdis
        mc 1 u talk "\"Oh, I just remembered. Aki asked me to check with you if you'd somehow taken his earbuds with you the last time you were over at our place. He said he can't find it.\""
        k 1 u "\"Really? I'll have to check once I get home.\""
        mc 1 u confused "\"Can't you just go to your classroom and check your bag?\""
        k 1 u "\"Not really. It's not the same bag I had when I went to your place.\""
        mc 1 u confused "\"It's not?\""
        k 1 u smile "\"Nope. I keep five different bags separated for each day of the week with all the materials I'll need for classes that day.\""
        mc 1 u sigh "\"What? That's ridiculous. What do you do when you have the same subject multiple days a week?\""
        k "\"That's what I do to review everything I did. Once I get home, I take all my notes and I copy them to my other versions of that subject's notebooks.\""
        mc 1 u sigh3 "\"So you have multiple notebooks with the exact same notes so you can take them separately to class on different days?\""
        k 1 u calm "\"That's right. Isn't it a great idea?!\""
        "... It's definitely way over engineered, that's for sure."
        "I don't know about \"great\" though."
        "Although I'll refrain from saying anything. The last thing I need is to hurt his pride."
        "Besides, if it works for him then I guess it's not all bad."
        mc 1 u "\"Oh hey, changing the subject a bit but is everything prepared for the band to perform?\""
        k 1 u "\"Pretty much. They're all rehearsing the songs we'll perform and I'm making sure the organization will go smoothly.\""
        k 1 u smile "\"Of course, we still have some time until then. It's only on the last day anyway.\""
        mc 1 u "\"Try not to get too cozy with that time or else it'll sneak up on you before you notice it.\""
        k 1 u calm "\"Don't worry about it, I'm not the type to leave things for the last minute.\""
        mc 1 u smile "\"I believe you. I hope things go along great.\""
        k 1 u smile "\"If I have any say in the matter, they will.\""
        mc 1 u laugh "\"Too bad you're not going to be performing though, I wish I could see you sing again.\""
        k 1 u worried "\"I already told you, singing in public isn't my thing.\""
        play sound "music/tap.ogg"
        "I laugh, giving Kei-kun a few friendly taps on the shoulder."
        mc 1 u happy "\"I know that, you don't need to worry.\""
        k 2 u gentle "\"But... well, I wouldn't mind singing just for you sometime later.\""
        play sound "music/heartbeat.ogg"
        mc 1 u flustered "\"R-Really? I would love that.\""
        k 1 u smile "\"Heh, it's a date then. We'll hash out the specifics later. I have to run right now.\""
        mc 1 u happyb "\"O-okay! See ya.\""
        k 2 u gentle "\"Before I leave let me just warn you, your tail seems to be very excited, [povFirstName].\""
        "My body immediately freezes when I notice that fact."
        "I guess without my realizing, my tail had begun wagging rapidly."
        mc 1 u flustered "\"Ah...\""
        k 1 u smile "\"It's kinda cute. Anyway, bye bye.\""
        show k 1 u smile at offscreenright with moveoridis
        "Kei-kun passes by me and walks down the stairs, leaving me rooted on my spot with a red face."
        "Ugh... I want to bury my head somewhere secluded right now..."
        "Wait... he said... \"date\", right?"
        "He didn't mean like... {i}that{/i} kind of date, did he?"
        "Hah... why do I feel so happy thinking it might be that?"
        "I really wish my heart would slow down right about now..."
    else:
        show k 1 u at fdis
        mc 1 u talk "\"Any idea when I can swing by your class' display?\""
        k "\"Hmm... We'll probably be up and running in about an hour or so. Although, honestly, I don't see the appeal in doing a haunted house thing in the middle of the morning.\""
        mc 1 u smile "\"I'm pretty sure it'd still be fun.\""
        k 1 u worried "\"You and I have very different ideas of fun...\""
        mc 1 u happy "\"What's that? Could it be it scares you too much?\""
        k "\"...\""
        mc 1 u talk "\"Whoa, really? I wasn't expecting that.\""
        k 1 u annoyed "\"S-shut up. I'm not one for cheap thrills okay.\""
        mc 1 u smile "\"That's a very refined way to say you're chicken.\""
        k "\"Ugh. You can be so annoying sometimes.\""
        mc 1 u happy "\"Aww, thanks.\""
        k 1 u sigh2 "\"That wasn't a compliment.\""
        mc 1 u happy "\"Hehehe.\""
        k 1 u "\"Either way, I need to get going right now. Can't afford to start slacking right now.\""
        mc 1 u talk "\"Alright. Good luck.\""
        k "\"Thanks. I'll see you later.\""
        show k 1 u at offscreenright with moveoridis
        "Kei-kun passes by me and walks down the stairs. I turn to watch him go, lingering in my spot for a second before continuing to make my way up."
    play sound "music/slidingdoor.ogg"
    stop music fadeout 2.5
    scene SClass with fade
    "As soon as I walk into my class, I see all the walls have been decorated with strips of colored paper and with multiple paper lanterns dangling from the ceiling."
    "I know this place was decorated on Friday but I swear there are more lanterns here than there were when I last checked."
    "Still, as soon as the door was opened, an orange figure runs up to me excitedly."
    show j 1 ch gentle at fdis, five with dissolve
    j "\"[povFirstName]-san!\""
    "I've barely even had time to acclimate to my surroundings and he's already boisterously jumping around in front of me."
    mc 1 u smile "\"Hey there, Jun. You look pretty happy.\""
    j "\"I am! Look at me, I got my waiter uniform. Look! Isn't it cool?!\""
    "Jun spins around where he stands, trying to show off the whole thing to me."
    if schoolfestival == "jun":
        "He even lifts his tail when he turns his back to me, probably so he can give me a good view."
        "Unfortunately for me, all that does is pull my attention towards his... \"back\"."
        "I feel my cheeks suddenly becoming quite red and I look away.\""
    j 1 ch happy "\"Doesn't it look great on me?\""
    mc 1 u smile "\"Yes it does, Jun. You look very cute in that uniform.\""
    j 1 ch shock "\"Wha-{w=0.5}{nw}"
    show j 1 ch pout at fdis
    extend " Cute? I'm not cute. That's for girls.\""
    mc 1 u smile "\"I don't know what to tell you there, Jun. You're pretty cute.\""
    if schoolfestival == "jun":
        j 1 ch blush2 "\"I-I'm not.\""
        mc 1 u smile "\"Yeah you are. And you look pretty adorable when you blush.\""
        j "\"D-don't say things like that...\""
    else:
        j "\"Nuh-uh, I'm not!\""
        mc 1 u considerate "\"Alright alright, you're not. Settle down there. No need to get so fussy over it.\""
        j 1 ch wince "\"I'm not fussy!\""
        "Oh man, trying to keep a straight face after hearing that is really tough."
    mc 1 u smile "\"Anyway, you're all set to be a waiter huh?\""
    j 1 ch happy "\"Yes! It's gonna be a lot of fun!\""
    "I have no idea how going around serving people food is supposed to be fun but... hey, to each his own."
    "I look around the room, seeing a few of our classmates dressed in similar clothes to Jun."
    "For some reason, there are barely any waitresses here."
    "In fact, most of them are guys..."
    mc 1 u talk "\"What happened to the girls? It's looking like a real sausage party in here.\""
    j 1 ch watch "\"Sausage party?\""
    mc 1 u considerate "\"Oh... uhm, never mind.\""
    "Probably shouldn't use an expression like that around Jun."
    "I really don't need to taint him with that sort of thing."
    mc 1 u considerate "\"Anyway, what happened to the girls? It's mostly just guys around here.\""
    j 1 ch think "\"Oh, I actually asked Ayako-san about that. She said most girls refused to wear the chinese dress but that she said they all agreed anyway so the guys would too.\""
    "... So she basically used the promise of girls in chinese dresses as bait to get more waiters?"
    "That's really scummy..."
    mc 1 u "\"The improv kitchen is looking pretty good though. Although why is it all hidden behind panels?\""
    "The entire area that used to be the blackboard had been walled off with wooden bamboo panels that then got decorated with multiple Chinese symbols."
    "Dragons, lions, some letters."
    "Wait, is that the Chinese zodiac over there?"
    j 1 ch considerate "\"Apparently Gin-kun said he felt too shy about cooking with the guests being able to see him.\""
    mc 1 u worried "\"But... doesn't walling off the whole area mean that the heat from the burners will be trapped in there?\""
    j "\"Y-yeah... Jin-kun was complaining about that.\""
    "These guys are insane..."
    j 1 ch happy "\"Oh, but there are a few holes cut out on the counter so the waiters can pick the food up when it's ready.\""
    "Seriously, how the hell did you people have all these crazy ideas?"
    mc 1 u considerate "\"Hopefully there won't be any accidents...\""
    j 1 ch smile "\"You don't have to worry about the others, [povFirstName]-san. As the oldest one here, I'll make sure to look after them!\""
    "... You're the one most at risk of causing an accident."
    "Maybe I should talk to Gin and ask him to not let Jun handle any hot plates."
    "... Will they even serve cold plates?"
    ay "\"Jun-kun, we need your help here.\""
    "A voice calls Jun from amidst the mess of chairs and panels on the other end of the room."
    j 1 ch shock "\"Ah. I'm coming!\""
    j 1 ch smile "\"Sorry, [povFirstName]-san. We'll have to talk later.\""
    mc 1 u smile "\"It's alright. I'm gonna take a walk around the place. We'll meet up later.\""
    j 1 ch happy "\"Yeah. I can't wait!\""
    show j 1 ch smile at fdis, offscreenright with moveoridis
    "Jun scurries away and disappears into the kitchen area."
    "Smiling and shaking my head slightly, I make my way out the door to explore the festival a little more."
    stop music2 fadeout 2.5
    play music "music/crowd01.ogg" fadein 5.0
    scene SGate with fade
    show hours with dissolve
    $ renpy.pause (1.0)
    hide hours with dissolve
    "After I walked around for a bit on my own, I notice the time we agreed to meet was coming close to arriving."
    "Once I got to the agreed upon meeting place, I decided to stand around with my hands in my pockets and just watch the students passing by while I waited."
    "Even though there are probably a lot of students who decided they couldn't be bothered to show up today, the place still feels so much livelier than usual."
    "Somehow, even though I tend to hate crowds, watching all these students my own age walking around with their friends and having fun kinda makes me feel... I don't know, kinda at ease?"
    "It's a weird feeling."
    show sa 1 c happy at fdis, five with moveiledis
    sa "\"Osu!\""
    "Of course, my pleasant relaxed mood is soon interrupted by this troglodyte that I call my childhood friend, with her now commonplace loud greeting."
    mc 1 u smile "\"Hey, Saya-chan. You're here early.\""
    sa 1 c smile "\"So are you.\""
    mc 1 u happy "\"I guess that's true.{w=0.3}{nw}"
    show mc 1 u talk at offscreenleft
    extend " How come you're not wearing your uniform?\""
    show sa 1 c at fdis
    "Saya-chan looks down at herself, examining her own clothes front and back."
    "I think to myself why she would even need to do this given that she's the one who got dressed. She should know what the hell she is wearing."
    sa 1 c happy "\"I guess I just wanted to be comfy!\""
    mc 1 u fsmile "\"You guess?\""
    sa 1 c smile "\"Yeah!\""
    "..."
    play sound "music/disappointment.ogg"
    "You're way too simple-minded!"
    sa 1 c "\"Hey, [povFirstName]-kun, how have you been enjoying the festival so far?\""
    mc 1 u "\"It's pretty good. Although I think I prefer the one we had last year.\""
    sa 1 c think "\"Really? That one was kinda dull for me.\""
    show sa 1 c smile at fdis
    mc 1 u considerate "\"That's just because you got stuck behind a desk for most of it and couldn't go around exploring.\""
    sa 1 c laugh "\"Ah, you remembered!\""
    "It's not exactly a hard thing to remember after all."
    sa "\"Man, I'm really pumped right now!\""
    mc 1 u "\"Really? How come?\""
    sa "\"Well, first of all, there's the bonfire dance! I don't want to miss that.\""
    mc 1 u smile "\"Ironic that you would say that considering you've never been to it in the last two years.\""
    sa 1 c bored "\"Well, sure. But this year I actually have someone to dance with me so as per school tradition, I'll attend.\""
    mc 1 u "\"School tradition?\""
    sa 1 c smile "\"Yeah, don't you remember? They say that two people who dance together around the bonfire will be tied together forever.\""
    sa 1 c think "\"Although that's more of a platonic thing. Most of the people who do it are friends. There are a few couples that do it too.\""
    mc 1 u talk "\"I guarantee you most of these couples will have broken up before the year is over.\""
    sa 1 c laugh "\"Hahaha, probably.\""
    sa 1 c smile "\"But that's not all I'm excited about.\""
    if schoolfestival == "keisuke":
        sa 1 c happy "\"There's also Kei-kun's thing!\""
        mc 1 u "\"His what?\""
        sa 1 c "\"Hm? You mean you don't know?\""
        mc 1 u confused "\"Know what?\""
        sa 1 c talk "\"You know. Kei-kun's thing.\""
        mc 1 u worried "\"His... \"thing\"? Do you mean the band's show?\""
        sa 1 c confused "\"No, not that!{nw}"
        show sa 1 c think at fdis
        extend " Well... maybe a little bit that.\""
        sa 1 c "\"I mean his {i}other{/i} thing.\""
        "What's with the pronoun game here? Just say what you mean already, woman!"
        mc 1 u "\"Sorry, I have no idea.\""
        sa 1 c shock "\"Really? You guys have been spending so much time together, I'm surprised he didn't tell you!\""
        mc 1 u considerate "\"I can't really comment on it since I have no idea what you're talking about.\""
        sa 1 c think "\"...\""
        mc 1 u "\"Saya-chan?\""
        sa 1 c considerate "\"Hey, [povFirstName]-kun... do you promise not to tell Kei-kun that I told you?\""
        mc 1 u confused "\"If it's that important then wouldn't it be easier for you to just... not tell me?\""
        sa 1 c bored "\"No way. This is such a juicy gossip, I'm really excited to talk to someone about it and I figured you'd have been the first one to know.\""
        "Saya-chan, since when did you become such a gossip girl..."
        mc 1 u sigh3 "\"Fine, fine. Just get this over with.\""
        "She won't stop pestering me until I agree anyway."
        sa 1 c laugh "\"Yay! Okay, so get this...\""
        sa 1 c smile "\"Kei-kun said he's gonna ask the person he likes out during the festival.\""
        mc 1 u shock "\"... Ah.\""
        sa 1 c "\"That's it? \"Ah\"? Jeez, you could stand to be a bit more excited.\""
        "Kei-kun... has someone he likes?"
        "That's... news to me..."
        mc 1 u worried "\"I... see...\""
        sa 1 c talk "\"Are you okay, [povFirstName]-kun? You seem a little out of it. Did you stay up all night again?\""
        mc 1 u considerate "\"What? N-no, I'm fine.\""
        "That's... weird."
        "Why am I suddenly feeling so strange?"
        "The person he likes... I didn't know there was someone like that. He never told me."
        "I..."
    elif schoolfestival == "shoichi":
        sa 1 c smile "\"I ran into Hitoka-chan this morning and she told me something huge! Apparently she was on the phone with Shoichi after the competition and she heard something big!\""
        mc 1 u curious "\"Oh yeah? What is it?\""
        sa 1 c laugh "\"Shoichi apparently got scouted yesterday!\""
        mc 1 u "\"Ah. Is that it?\""
        show sa 1 c shock at fdis
        $ renpy.pause (1.0)
        sa 1 c pout "\"What do you mean \"is that it\"?\""
        mc 1 u sigh3 "\"This is hardly the first time he's gotten scouted. A bunch of teams have already tried to scout him before.\""
        sa 1 c think "\"Well, I guess that's true.\""
        sa 1 c laugh "\"But this time is different!\""
        mc 1 u "\"How so?\""
        sa 1 c smile "\"The scout that talked to him was from the Ekoda Panthers!\""
        mc 1 u shock "\"Wha-\""
        "The Ekoda Panthers?! They're the number 1 professional volleyball team in the country!"
        mc 1 u shock "\"Are you serious?! That's... that's huge!\""
        sa 1 c laugh "\"I know! Isn't it great?\""
        mc 1 u worried "\"I'm surprised Shoichi would even tell her. He usually just turns these offers down without saying a word.\""
        sa 1 c smile "\"She told me he was on the phone with her when the scout rang the doorbell.\""
        mc 1 u confused "\"He rang the doorbell? That's kinda weird. Usually they either contact you by e-mail or approach you after the competition.\""
        sa 1 c think "\"I mean... he did disappear yesterday after the match.\""
        mc 1 u considerate "\"I... guess that's true.\""
        "... Shit, I'm not supposed to be feeling bothered, but..."
        "I know Hitoka-chan is his sister but... she didn't even show up to watch the competition."
        "And he wasn't even reading my messages or answering my calls yesterday."
        "How come he was talking to her?"
        sa 1 c talk "\"Are you okay, [povFirstName]-kun? You seem a little out of it. Did you stay up all night again?\""
        mc 1 u considerate "\"What? N-no, I'm fine.\""
        sa 1 c think "\"Hmmm... I thought you'd be excited about this.\""
        mc 1 u wry "\"I want to be, but... We have no reason to believe he won't turn that offer down too.\""
        sa 1 c shock "\"What? But it's the Panthers. There's no way he'd turn an offer from them down!\""
        mc 1 u considerate "\"You'd be surprised...\""
        "Especially considering the conversation I had with him yesterday..."
        "I highly doubt he'd accept their offer just like that..."
    elif schoolfestival == "jun":
        sa 1 c happy "\"Did you hear the news about Jun-kun?\""
        mc 1 u "\"What news?\""
        sa 1 c smile "\"Well, apparently some kind of brand contacted the school principal today to talk about sponsoring our school's music club.\""
        mc 1 u shock "\"Whoa, that's pretty big. I wonder what brought that up.\""
        sa 1 c laugh "\"Apparently Jun-kun took part in a competition yesterday and won!\""
        mc 1 u smile "\"Oh? Yeah he did. How did you know?\""
        sa 1 c shock "\"Wha- So you knew?\""
        mc 1 u considerate "\"Kinda. I found out about it last week but Jun didn't want to tell anyone. I snuck in anyway to cheer for him.\""
        sa 1 c pout "\"I can't believe you didn't tell me!\""
        mc 1 u "\"If you'd showed up you would have missed Shoichi's competition just like I did.\""
        sa 1 c think "\"Oh... damn, you're right.\""
        mc 1 u considerate "\"It's not an idea I recommend.\""
        sa 1 c talk "\"Yeah, I can imagine. Shoichi was the one who told me about it. Then this morning I heard from Kyo-chan about the sponsorship.\""
        mc 1 u confused "\"How does {i}she{/i} know?\""
        sa 1 c "\"She's the principal's granddaughter remember?\""
        mc 1 u sigh "\"Yeah, but still, this isn't the kind of thing you share with your granddaughter.\""
        "Shouldn't this kinda thing be kept a bit more confidential?"
        sa 1 c "\"I don't see the big deal. He probably just remembered she goes to the same class as Jun-kun and decided to tell her about it.\""
        mc 1 u sigh3 "\"I still think that was a real lack of tact.\""
        sa 1 c "\"That's rich coming from the most tactless person I know.\""
        mc 1 u sigh "\"Hey!\""
        sa 1 c think "\"It's true.\""
        show sa 1 c smile at fdis
        "I grumble, kicking up a bit of dirt from the ground."
        "Saya stares at me as if the whole thing were very amusing to her."
    sa 1 c laugh "\"Ah, look. Here comes the boys!\""
    play music2 "music/BGM/Spring Classroom.ogg" fadein 5.0
    show sa 1 c smile at fdis, zeroh with move
    show j 1 ch sigh at fdis, threeh
    show k 1 u at fdis, sixh
    show s 1 u smile at fdis, ten
    with moveiridis
    "I look up on cue with her announcement, seeing the three of them walking out of the main building."
    "Shoichi smiles and waves once he realizes we see them."
    mc 1 u talk "\"This is surprising. Did you three meet up on the stairs or something?\""
    k 1 u "\"Not exactly. Urata and I met up inside but we decided to fetch Kobayashi first.\""
    show sa 1 c at fdis
    s 1 u happy "\"He looked like he was really overwhelmed trying to wait on tables. He was jumping from one place to the other in a hurry. It was really funny.\""
    "That's not exactly something you should be laughing about, you ass."
    "I look over at Jun who is still taking deep breaths, with beads of sweat rolling down his brow and mixing in with his fur."
    mc 1 u talk "\"Are you okay? You don't look so good.\""
    j 1 ch considerate "\"I'm fine. It's just... I didn't realize how hot it would get in the classroom once the burners were all on and we had a bunch of people inside.\""
    s 1 u smile "\"The place isn't even close to being packed though. Only half the tables were occupied. If this is too much for you then you're gonna suffer tomorrow.\""
    j 1 ch wince "\"D-don't say that...\""
    "Come to think of it, this whole thing might be hell for a guy that is afraid of crowds."
    play sound "music/disappointment.ogg"
    "Waiting tables might have been a bad idea, Jun..."
    j 1 ch considerate "\"[povFirstName]-san, you don't need to worry about me. I'm gonna be fine.\""
    mc 1 u shock "\"Wha- I didn't say anything.\""
    j 1 ch wry "\"It's written all over your face.\""
    show sa 1 c laugh at fdis
    s 1 u smile "\"Wow, he's right.\""
    sa "\"You look like a wrinkly old lady!\""
    show sa 1 c smile at fdis
    mc 1 u sigh "\"Watch it, floppy ears.\""
    k 1 u worried "\"W-what did I do?\""
    show sa 1 c at fdis
    mc 1 u sigh3 "\"Not you! The other floppy ears!\""
    sa "\"[povFirstName]-kun, calling someone floppy ears is a bit offensive you know.\""
    mc 1 u sigh "\"Like I care!\""
    j 1 ch pout "\"[povFirstName]-san, you shouldn't be mean to Keisuke-san!\""
    mc 1 u sigh3 "\"I already said I wasn't talking to Kei-kun.\""
    show k 1 u at fdis
    show s 1 u think at fdis
    show sa 1 c smile at fdis
    show j 1 ch watch at fdis
    s "\"I don't know about you guys but I really don't feel like standing around the entrance watching other people have fun.\""
    show s 1 u smile at fdis
    mc 1 u smile "\"Yeah, you're right. We should go have some fun.\""
    j 1 ch happy "\"I can't wait to see what the festival is like in here!\""
    "The five of us then start walking while we chat, taking quick looks at interesting booths in-between conversation."
    show j 1 ch watch at fdis
    sa "\"By the way, Jun-kun, what was your old school's festival like?\""
    j 1 ch considerate "\"It was much more sedate. The school didn't have all that many students to begin with. It's probably one of the reasons I'm so bad at dealing with crowds. It was always kinda lonely there.\""
    show k 1 u at fdis
    show s 1 u at fdis
    sa 1 c "\"So there wasn't anything you liked about the festival there?\""
    j 1 ch think "\"Something I liked? Hmm...{nw}"
    show j 1 ch gentle at fdis
    extend " Oh, I remember!{nw}"
    show j 1 ch smile at fdis
    extend " The fireworks display there was always pretty nice.\""
    show k 1 u smile at fdis
    show sa 1 c smile at fdis
    s 1 u smile "\"Fireworks, huh? So you're the type that likes those.\""
    j "\"Yes. I love them!\""
    mc 1 u considerate "\"Oh hey, guess I won't be the only one to enjoy them this year then.\""
    j 1 ch watch "\"The only one?\""
    mc 1 u sigh3 "\"These three aren't really fond of fireworks.\""
    show s 1 u considerate at fdis
    show sa 1 c at fdis
    k 1 u worried "\"Hey, that's a little unfair. I like them. They're very pretty. I just need to use earplugs because they hurt my ears.\""
    s "\"I have the same problem. My hearing is kinda sensitive so the fireworks really hurt. I prefer to be indoors when they happen.\""
    show s 1 u at fdis
    sa "\"They're pretty meh for me. Maybe it's because I'm colorblind?\""
    j 1 ch shock "\"Wha- You're colorblind?\""
    sa 1 c think "\"Oh. I didn't tell you?\""
    mc 1 u considerate "\"You rarely ever talk about yourself in the first place, Saya-chan.\""
    sa "\"Hmm... I guess that's true.\""
    j 1 ch wince "\"I... I'm sorry to hear.\""
    s "\"I really don't think being colorblind is why. Even with that, the fireworks should still be pretty.\""
    k 1 u smile "\"Not that you can attest that with certainty since you're not colorblind yourself.\""
    s 1 u considerate "\"I suppose that's true.\""
    show j 1 ch watch at fdis
    show s 1 u at fdis
    sa 1 c smile "\"You don't have to worry about it, Jun-kun. I don't think I'm missing something or anything like that. It doesn't bother me much.\""
    j "\"Mizoguchi-san...\""
    k 1 u smile "\"Oh, hey, they're selling game memorabilia here.\""
    j 1 ch shockb "\"Really, where?\""
    show sa 1 c considerate at fdis
    show s 1 u considerate at fdis
    show k 1 u uncomfortable at fdis
    "And just like that, Jun's attention is whisked away from what seemed to be an important topic because he was too excited about games."
    show j 1 ch watch at fdis
    show s 1 u smile at fdis
    show k 1 u smile at fdis
    sa 1 c "\"Hmm... I don't recognize any of these.\""
    mc 1 u "\"Are these all characters from obscure games or something?\""
    s "\"It would explain why they're so cheap.\""
    show s 1 u at fdis
    show k 1 u at fdis
    j 1 ch shockb "\"W-whoa! T-these are...\""
    show sins with dissolve
    "Jun points at a set of keychains hanging from the far wall."
    "They seem to be part of a collection since they're all hanging together like that."
    hide sins with dissolve
    s "\"Do you recognize them, Jun?\""
    j 1 ch happy "\"Yes! They're from an oldschool American RPG released about twenty years ago. I used to play it a lot a few years back. I probably finished five or six times.\""
    mc 1 u smile "\"Damn, that's a lot of times.\""
    s 1 u smile "\"What's the game about?\""
    j 1 ch smile "\"You play as a detective that gets killed and sent to the afterlife. Then you spend most of your time trying to keep your soul from being deleted while trying to find out how you died.\""
    sa 1 c complain "\"Damn, that's kinda morbid.\""
    k 1 u smile "\"It sounds like a lot of fun. What are the names of the characters?\""
    j 1 ch happyb "\"The wolf is the main character, Wolfstar. Then there's Rufus, Janus and Hugo.{nw}"
    show j 1 ch watch at fdis
    extend " The game has a few more main characters but I guess they don't have keychains of them here.\""
    show sa 1 c think at fdis
    s 1 u smile "\"I will admit, I like their designs.\""
    k "\"They do seem like they have a lot of personality.\""
    sa "\"A bunch of buff men? Not my thing.\""
    mc 1 u "\"How ironic that the only girl in the group is saying that.\""
    sa 1 c happy "\"If I'm supposed to carry a keychain around with me everywhere then I'd rather have a cute girl.\""
    mc 1 u sigh3 "\"You just enjoy being a contrarian don't you?\""
    sa 1 c think "\"Hmmm... Maybe a little.\""
    show sa 1 c at fdis
    j 1 ch smile "\"Excuse me, how much for these?\""
    "Jun fishes for his wallet inside his pants as he calls to the student in charge of the tent."
    "The guy or girl is sitting in the back of the booth, their back turned to us so I couldn't really see whether it's a guy or not."
    "Then they turned around and-"
    ry "\"Oh, it's Kobayashi.\""
    show j 1 ch shock at fdis
    show s 1 u at fdis
    mc 1 u shock "\"Ryoji-kun?!\""
    ry "\"You guys are here too? What's up?\""
    s "\"How come you've got a booth set up here? Shouldn't you be working at your class' display?\""
    "The bear shrugs, absent-mindedly tapping away at his phone in between sentences, his gaze never staying on us for too long."
    ry "\"It was boring so I asked for permission to set up my own booth. I bought some products I knew were worth more than they were selling for and decided to flip them. I've gotten some good money, so far.\""
    k "\"Looks like you have a pretty decent business sense.\""
    "He shrugs again, his eyes never even registering Kei-kun's presence due to being locked on his phone."
    ry "\"I've always been good at estimating value of stuff related to gaming, I guess.\""
    mc 1 u considerate "\"{size=-4}Well, you are a game addict after all.{/size}\""
    j 1 ch watch "\"Hey, Ryoji-kun, how much for the Sins & Paradise keychains?\""
    "Ryoji doesn't even look at Jun's hand to see where he's pointing. As soon as he hears the game's name, he immediately looks to the exact place on the wall that they were placed and picks them up.\""
    show sins with dissolve
    ry "\"These have been selling really well, even though the game is kinda old and not well known in Japan. I guess people just like the design. These four are the last ones I have.\""
    ry "\"They're ¥3500 each but I'll sell them to you for ¥12000 if you buy all four.\""
    hide sins with dissolve
    j 1 ch wince "\"Oooh... {size=-4}even for just one, that's kinda pricey for me...{/size}\""
    "Kei-kun, Shoichi and I look at each other, sharing our thoughts without having to exchange any words."
    "The three of us pull out our own wallets."
    mc 1 u smile "\"We'll take all four. Then it becomes a bit cheaper even for you, Jun.\""
    j 1 ch shock "\"Wha- Really?!\""
    show k 1 u smile at fdis
    s 1 u smile "\"You bet. Besides, I like their design so whichever one I get I'll be happy.\""
    k "\"Same here.\""
    j 1 ch happyb "\"O-okay! Thanks!\""
    "We pay Ryoji-kun and he hands us our keychains."
    mc 1 u "\"How do we decide who gets which?\""
    j 1 ch smile "\"Which one do you like the most, [povFirstName]-san?\""
    mc 1 u talk "\"Hmm... I guess it would be.\""
    menu:
        "I'll pick..."
        "Wolfstar, the Wolf":
            $ keychain = "wolfstar"
            mc 1 u smile "\"I guess I like Wolfstar the best. He's the protagonist, right? I really like his design. His clothes are pretty cool and he seems like a nice enough dude.\""
            k 1 u smile "\"You're judging whether a character is {i}nice{/i} by how they look in a chibi keychain?\""
            mc 1 u happy "\"Sure! That sounds like a totally reasonable thing to do, right?\""
            j 1 ch happy "\"Okay, then you can take Wolfstar. My favorite is Janus anyway.\""
            k 1 u smile "\"I guess I'll go for Hugo.\""
            s 1 u smile "\"The one I liked the most was Rufus so I'll go for him.\""
            show wolfstar with dissolve
            "I admire my new keychain, examining how good the color and molding of it is."
            "The metal back is also really smooth and has a brushed feel that I quite like."
            "Yep, these are pretty stylish."
            hide wolfstar with dissolve
        "Rufus, the Dog":
            $ keychain = "rufus"
            mc 1 u smile "\"Hmm... I really liked Rufus. His clothes are really stylish. He looks like he'd be the cool character of the bunch.\""
            j 1 ch happy "\"Hehe, he kind of is.\""
            show j 1 ch smile at fdis
            j "\"Okay, you can take Rufus. My favorite is Janus anyway.\""
            k 1 u smile "\"Sweet. Wolfstar was the one I liked the most. He's mine.\""
            s 1 u smile "\"I can take Hugo.\""
            show rufus with dissolve
            "I admire my new keychain, examining how good the color and molding of it is."
            "The metal back is also really smooth and has a brushed feel that I quite like."
            "Yep, these are pretty stylish."
            hide rufus with dissolve
        "Janus, the Kangaroo":
            $ keychain = "janus"
            mc 1 u smile "\"I like Janus. He looks really relaxed and chill.\""
            s 1 u smile "\"No argument here.\""
            j 1 ch think "\"Hmmm... I guess I'll take Rufus then.\""
            k 1 u smile "\"Sweet. Wolfstar was the one I liked the most. He's mine.\""
            s 1 u smile "\"I can take Hugo.\""
            show janus with dissolve
            "I admire my new keychain, examining how good the color and molding of it is."
            "The metal back is also really smooth and has a brushed feel that I quite like."
            "Yep, these are pretty stylish."
            hide janus with dissolve
        "Hugo, the Bull":
            $ keychain = "hugo"
            mc 1 u smile "\"I like Hugo. He looks like a really strong guy. That's always my kind of guy.\""
            j 1 ch happy "\"Yeah, he really is strong.\""
            j 1 ch smile "\"Okay, you can take Hugo. My favorite is Janus anyway.\""
            k 1 u smile "\"Sweet. Wolfstar was the one I liked the most. He's mine.\""
            s 1 u smile "\"The one I liked the most was Rufus so I'll go for him.\""
            show hugo with dissolve
            "I admire my new keychain, examining how good the color and molding of it is."
            "The metal back is also really smooth and has a brushed feel that I quite like."
            "Yep, these are pretty stylish."
            hide hugo with dissolve
    j 1 ch happy "\"Thanks a lot, Ryoji-kun. I love these!\""
    mc 1 u "\"Don't you want one, Saya?\""
    sa 1 c think "\"Nah. I'm not really fond of keychains anyway.\""
    ry "\"Thank you for your business.\""
    "Jun waves goodbye to Ryoji while we walk away."
    "While everyone else either put the keychain in their pocket or with their keys, Jun walks around staring at his the whole time."
    "He looks to be really pleased with it. It's kinda funny."
    "The rest of the day isn't very eventful."
    "We go around a few stalls eating together, we play a few games here and there."
    "There is barely any time for us to do anything as everyone's breaks quickly end."
    "This was the only time we could schedule for all five of us to go around together so it's kinda sad that it ended so soon."
    "As the other four leave to attend to their class' own events, I continue to roam around by myself until I get tired and decide to go back home."
    "I have to mentally prepare myself for tomorrow as the place is probably gonna be much more packed."
    stop music fadeout 2.5
    stop music2 fadeout 2.5
    stop music3 fadeout 2.5
    $ date = None
    if schoolfestival == "jun":
        jump Day18_Jun
    elif schoolfestival == "keisuke":
        jump Day19_Keisuke
    elif schoolfestival == "shoichi":
        jump Day20_Shoichi
